In [1]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# Step 1: Define the scope
scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]

# Step 2: Load credentials
creds = ServiceAccountCredentials.from_json_keyfile_name("ultra-sound-463216-c2-0e076e5f88fe.json", scope)

# Step 3: Authorize and connect
client = gspread.authorize(creds)

# Step 4: Open sheet by URL
sheet_url = "https://docs.google.com/spreadsheets/d/1VsFrUMKDOpCdVyuhaem3W_UXanAc7W1GW-_yZHS-0sQ/edit?gid=0#gid=0"
spreadsheet = client.open_by_url(sheet_url)

# Optional: Access specific sheet/tab
sheet = spreadsheet.worksheet("Active Projects")  # or spreadsheet.worksheet("SheetName")

# Example: Read data
data = sheet.get_all_records(head=4)

In [2]:
import pandas as pd

df = pd.DataFrame(data)

In [3]:
df

,Project,Developer,Name,Location,POINTS OF CONTACT,Lead Producer,Support Producer,Exec Relationship,Marketing,PR Manager,...,Windows,NSW1,NSW2,Mac,iOS,Android,Platform Exclusivity,Price Point,Launch Discount,Platform Notes
0,Lego,Lightbrick,Karsten Lund\nMads Prahm,Copenhagen,,Leanne,Naomi,Leanne,Becky,TBPR,...,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,none,$24.99,10%,Also releasing on PS4
1,Bounty Star,Dinogod,Ben Ruiz,"Phoenix, AZ",,Krystal,Matt D,Leanne,Narbeh,TBPR,...,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,Game Pass,$24.99,10%,
2,Morsels,Furcula,Toby Dixon,"Toronto, Canada",,Elias,,Hector,Nick,Jurge,...,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,none,$14.99,10%,
3,Wanderstop NSW,Ivy Road,Patrick McDermott,"Vancouver, BC",,Naomi,,,,,...,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,none,,,
4,People of Note,Iridium Studios,Jason Wishnov,Los Angeles,,Krystal,Elias,Hector,"Becky, Austin",TBPR,...,TRUE,FALSE,TRUE,FALSE,FALSE,FALSE,none,,,
5,to a T NSW2,Uvula,Keita Takahashi\nRyan Mohler,San Francisco,,Naomi,,,Unassigned,Unassigned,...,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,Game Pass,,,
6,Faraway,Little Eyes,Steph Thirion,Los Angeles,,Krystal,,Leanne,Austin,Jurge,...,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,none,$9.99,20%,
7,Mixtape,Beethoven & Dinosaur,Johnny Galvatron,"Melbourne, Australia",,Krystal,Matt D,Hector,Becky,Jules,...,TRUE,FALSE,FALSE,TRUE,TRUE,FALSE,Game Pass,$19.99,10%,
8,Storyteller,Ludomancy,Daniel Benmergui,"Buenos Aires, Argentina",,Leanne,Matt D,Hector,Unassigned,Unassigned,...,FALSE,TRUE,TRUE,FALSE,TRUE,TRUE,none,,,
9,D-Topia,Marumittu Games,Akira Mitsuhashi\nHiroco Shiino,"Kyoto, Japan",,Krystal,Leanne,Leanne,Becky,TBPR,...,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,none,,,
10,Snap & Grab,No Goblin,Dan Teasdale,Seattle,,Naomi,,,Austin,Jules,...,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,Game Pass,,,
11,Demi,Yarn Owl,Fabian Willis\nChristopher Hofmann,"Atlanta, GA\nAustin, TX",,Elias,,,Becky,TBPR,...,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,none,,,
12,"A Person, A Problem",A Million Flies,Ditto\nTom,Copenhagen,,Matt D,,Hector,Austin,Unassigned,...,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,none,,,
13,Forever Ago,Third Shift,Kai Brueckers\nFabian Denter,Germany,,Naomi,,,Narbeh,Unassigned,...,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,Game Pass,,,Third Shift considering Mac as a possible plat...
14,Decades,Solo Developer,Jess Mak,Toronto,,"Hector, Naomi",,Hector,Austin,Unassigned,...,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,Game Pass,,,
15,Battlesage,Tovenaar,Abdelkarim Houari\nAndreas Veeckman,Belgium,,Krystal,Leanne,Leanne,Narbeh,Unassigned,...,TRUE,FALSE,TRUE,FALSE,FALSE,FALSE,none,,,
16,Silent Hill: Townfall,Screen Burn,Jon McKellan\nRomana Ramzan,"Glasgow, Scotland",,Matt D,Leanne,Hector,Narbeh,Unassigned,...,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,Sony,,,
17,The Lost Wild,Great Ape Games,Nick Gregory\nTim Mehmet\nDavid Foster,"Brighton, UK",,Andrew,,Hector,Narbeh,Unassigned,...,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,Sony - 6 months,,,"Sony 6mo exclusive, xbox/nsw2 TBD"
18,Caretaker,Geometric Interactive,Jeppe Carlsen\nJakob Schmid,Copenhagen,,Krystal,Naomi,Hector,Narbeh,Unassigned,...,TRUE,FALSE,TRUE,FALSE,FALSE,FALSE,none,,,
19,Insomnia,Graceful Decay,Hanford Lemoore,"Henderson, NV",,Elias,,,Austin,Unassigned,...,TRUE,FALSE,TRUE,FALSE,FALSE,FALSE,none,,,
20,We Kill Monsters,Glass Revolver,Jacob Williams,Rhode Island,,Elias,Krystal,,Austin,Unassigned,...,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,none,,,
21,Revenant,Superbrothers,Craig Adams,Canada,,Elias,Krystal,,Narbeh,Unassigned,...,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,none,,,
22,Kafka,Int. Night,Charu Desodt\nCaroline Marchal,UK,,Naomi,,Leanne,Unassigned,Unassigned,...,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,none,,,
23,Mars Needs Whiskey,Cardboard Computer,Jake Elliot\nTomas Kemenczy\nBen Babbit,,,Matt D,Andrew,Hector,Becky,Unassigned,...,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,none,,,
24,Big Maze,Hollow Ponds,Ricky Haggett,"London, England",,"Hector, Naomi",,Hector,Austin,Unassigned,...,TRUE,FALSE,TRUE,FALSE,FALSE,FALSE,none,,,
25,BLK,BlueTwelve Studio,Swann Martin-Raget\nViv\nKoola,"Montpellier, France",,Leanne,Andrew,Hector,Becky,Unassigned,...,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,none,,,
26,Project Heron,Giant Sparrow,Ian Dallas,,,Naomi,Andrew,Hector,Austin,Unassigned,...,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,none,,,
27,Blue Star,Mobius,Masi Oka\nAlex Beachum,Los Angeles,,Elias,Jeb,Leanne,Narbeh,Unassigned,...,TRUE,FALSE,TRUE,FALSE,FALSE,FALSE,none,,,Mobius is open to having 24Bit support porting...
28,Ape Escape [project saru],Evening Star,Dave Padilla\nChristian Whitehead\nHunter Bridges,Los Angeles,,Matt D,Hector,Leanne,Unassigned,Unassigned,...,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,none,,,

In [4]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# Step 1: Define the scope
scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]

# Step 2: Load credentials
creds = ServiceAccountCredentials.from_json_keyfile_name("ultra-sound-463216-c2-0e076e5f88fe.json", scope)

# Step 3: Authorize and connect
client = gspread.authorize(creds)

# Step 4: Open sheet by URL
sheet_url = "https://docs.google.com/spreadsheets/d/1VsFrUMKDOpCdVyuhaem3W_UXanAc7W1GW-_yZHS-0sQ/edit?gid=0#gid=0"
spreadsheet = client.open_by_url(sheet_url)

# Optional: Access specific sheet/tab
sheet = spreadsheet.worksheet("Released Projects")  # or spreadsheet.worksheet("SheetName")

# Example: Read data
data2 = sheet.get_all_records(head=4)

In [5]:
import pandas as pd

df2 = pd.DataFrame(data2)

In [6]:
cancelled_idx = df2.query("Project =='Cancelled Games'").index[0]

In [7]:
df['status'] = 'active'
df2['status'] = 'released'

In [8]:
df2.loc[cancelled_idx:, 'status'] = 'cancelled'

In [9]:
df2 = df2.drop(cancelled_idx)

In [10]:
df2.head()

,Project,Developer,Name,Location,POC's,Lead Producer,Support Producer,Exec Relationship,Marketing Director,PR Manager,...,NSW1,NSW2,Mac,iOS,Android,Platform Exclusivity,Price Point,Launch Discount,Platform Notes,status
0,Wheel World,Messhof,Mark Essen\nKristy Norindr,Los Angeles,,Karla,Elias,,Narbeh,Jurge,...,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,Game Pass,$19.99,10%,released
1,Stray,BlueTwelve Studio,Swann Martin-Raget\nViv\nKoola,Montpellier,,SPx,"Leanne, Andrew",Hector,Unassigned,Unassigned,...,FALSE,TRUE,FALSE,FALSE,FALSE,Sony,,,,released
2,to a T,Uvula,Keita Takahashi\nRyan Mohler,San Francisco,,Jeb,Elias,,Unassigned,Jurge,...,FALSE,FALSE,FALSE,FALSE,FALSE,Game Pass,,,,released
3,Skin Deep,Blendo,Brendon Chung,"Culver City, CA",,Krystal,,,,Jurge,...,,,,,,,,,,released
4,Wanderstop,Ivy Road,Davey Wreden\nPatrick McDermott,"Vancouver, BC",,Karla,,,,Jules,...,FALSE,FALSE,FALSE,FALSE,FALSE,,,,,released

In [11]:
df2 = df2.drop(df2.query("Project ==''").index.values)

In [12]:
df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(r"\s+", "_", regex=True)   # spaces -> underscore
      .str.replace(r"[^0-9a-zA-Z_]", "", regex=True)  # optional: remove weird chars
      + "_pt"
)

In [13]:
df2.columns = (
    df2.columns
      .str.lower()
      .str.strip()
      .str.replace(r"\s+", "_", regex=True)   # spaces -> underscore
      .str.replace(r"[^0-9a-zA-Z_]", "", regex=True)  # optional: remove weird chars
      + "_pt"
)

In [14]:
df2 = df2.rename({"project_pt":"_id"}, axis=1)
df = df.rename({"project_pt":"_id"}, axis=1)

In [15]:
df2

,_id,developer_pt,name_pt,location_pt,pocs_pt,lead_producer_pt,support_producer_pt,exec_relationship_pt,marketing_director_pt,pr_manager_pt,...,nsw1_pt,nsw2_pt,mac_pt,ios_pt,android_pt,platform_exclusivity_pt,price_point_pt,launch_discount_pt,platform_notes_pt,status_pt
0,Wheel World,Messhof,Mark Essen\nKristy Norindr,Los Angeles,,Karla,Elias,,Narbeh,Jurge,...,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,Game Pass,$19.99,10%,released
1,Stray,BlueTwelve Studio,Swann Martin-Raget\nViv\nKoola,Montpellier,,SPx,"Leanne, Andrew",Hector,Unassigned,Unassigned,...,FALSE,TRUE,FALSE,FALSE,FALSE,Sony,,,,released
2,to a T,Uvula,Keita Takahashi\nRyan Mohler,San Francisco,,Jeb,Elias,,Unassigned,Jurge,...,FALSE,FALSE,FALSE,FALSE,FALSE,Game Pass,,,,released
3,Skin Deep,Blendo,Brendon Chung,"Culver City, CA",,Krystal,,,,Jurge,...,,,,,,,,,,released
4,Wanderstop,Ivy Road,Davey Wreden\nPatrick McDermott,"Vancouver, BC",,Karla,,,,Jules,...,FALSE,FALSE,FALSE,FALSE,FALSE,,,,,released
5,Sayonara Wild Hearts,Simogo,"Simon Flesser\nMagnus """"Gordon"""" Gardebäck",,,,,,,Jules,...,,,,,,,,,,released
6,Thirsty Suitors,Outerloop,Chandana Ekanayake,Seattle,,Leanne,,,,Unassigned,...,,,,,,,,,,released
7,Lushfoil,Matt Newell,Matt Newell,Japan,,Jeb,,,,Jules,...,,,,,,,,,,released
8,Neon White,Little Flag / Angel Matrix,Ben Esposito,,,,,,,,...,,,,,,,,,,released
9,Twelve Minutes,Solo Developer,Luis Antonio,,,,,,,,...,,,,,,,,,,released
10,Kentucky Route Zero,Cardboard Computer,Jake Elliot\nTomas Kemenczy\nBen Babbit,,,,,,,,...,,,,,,,,,,released
11,Outer Wilds,Mobius,Masi Oka\nAlex Beachum,,,,,,,,...,,,,,,,,,,released
12,Donut County,Ben Esposito,Ben Esposito,,,,,,,,...,,,,,,,,,,released
13,Gorogoa,Buried Signal,Jake Roberts,,,,,,,,...,,,,,,,,,,released
14,Ashen,A44,Simon Dasan,,,,,,,,...,,,,,,,,,,released
15,If Found,Dreamfeel,Llaura McGee,,,,,,,,...,,,,,,,,,,released
16,The Pathless,Giant Squid,Tina Kowalewski\nErica Ishijima Hsu,,,,,,,,...,,,,,,,,,,released
17,Last Stop,Variable State,Jonathan Burroughs,,,,,,,,...,,,,,,,,,,released
18,I am Dead,Hollow Ponds,Ricky Haggett,,,,,,,,...,,,,,,,,,,released
19,Solar Ash,Heart Machine,Alx Preston,,,,,,,,...,,,,,,,,,,released
20,Mundaun,Hidden Fields,Michel ziegler,,,,,,,,...,,,,,,,,,,released
21,A Memoir Blue,Cloisters,Shelley Chen,,,,,,,,...,,,,,,,,,,released
22,Hindsight,Team Hindsight,Joel McDonald,,,,,,,,...,,,,,,,,,,released
23,Maquette,Graceful Decay,Hanford Lemoore,,,,,,,,...,,,,,,,,,,released
24,Wattam,Uvula,Keita Takahashi\nRyan Mohler,,,,,,,,...,,,,,,,,,,released
25,What Remains of Edith Finch,Giant Sparrow,Ian Dallas,,,,,,,,...,,,,,,,,,,released
26,Telling Lies,Half Mermaid,Sam Barlow,,,,,,,,...,,,,,,,,,,released
27,Cocoon,Geometric,Jeppe Carlsen\nJakob Schmid,,,,,,,,...,,,,,,,,,,released
28,Open Roads,Open Roads Team,,,,,,,,,...,,,,,,,,,,released
29,Flock,Hollow Ponds,Ricky Haggett,"London, England",,,,,,,...,,,,,,,,,,released
30,Lorelei and the Laser Eyes,Simogo,"Simon Flesser\nMagnus """"Gordon"""" Gardebäck","Malmo, Sweden",,,,,,,...,,,,,,,,,,released
32,Little Devil Inside,Neostream,John Choi,,,,,,,Unassigned,...,,,,,,,,,,released
36,Big Hops,Luckshot,Chris Wade,"Austin, TX",,,,,,,...,,,,,,,,,,cancelled
37,Bog Bodies,Dreamfeel,Llaura McGee,Ireland,,,,,,,...,,,,,,,,,,cancelled
38,Doors,Half Mermaid,Sam Barlow\nNatalie Watson,New York,,Leanne,,,Unassigned,Unassigned,...,FALSE,FALSE,FALSE,FALSE,FALSE,none,,,,cancelled

In [16]:
df.head()

,_id,developer_pt,name_pt,location_pt,points_of_contact_pt,lead_producer_pt,support_producer_pt,exec_relationship_pt,marketing_pt,pr_manager_pt,...,nsw1_pt,nsw2_pt,mac_pt,ios_pt,android_pt,platform_exclusivity_pt,price_point_pt,launch_discount_pt,platform_notes_pt,status_pt
0,Lego,Lightbrick,Karsten Lund\nMads Prahm,Copenhagen,,Leanne,Naomi,Leanne,Becky,TBPR,...,TRUE,TRUE,FALSE,FALSE,FALSE,none,$24.99,10%,Also releasing on PS4,active
1,Bounty Star,Dinogod,Ben Ruiz,"Phoenix, AZ",,Krystal,Matt D,Leanne,Narbeh,TBPR,...,FALSE,FALSE,FALSE,FALSE,FALSE,Game Pass,$24.99,10%,,active
2,Morsels,Furcula,Toby Dixon,"Toronto, Canada",,Elias,,Hector,Nick,Jurge,...,TRUE,FALSE,FALSE,FALSE,FALSE,none,$14.99,10%,,active
3,Wanderstop NSW,Ivy Road,Patrick McDermott,"Vancouver, BC",,Naomi,,,,,...,TRUE,TRUE,FALSE,FALSE,FALSE,none,,,,active
4,People of Note,Iridium Studios,Jason Wishnov,Los Angeles,,Krystal,Elias,Hector,"Becky, Austin",TBPR,...,FALSE,TRUE,FALSE,FALSE,FALSE,none,,,,active

In [17]:
data = df.to_dict(orient='records')

In [18]:
released_data = df2.to_dict(orient='records')

In [19]:
stop

NameError: name 'stop' is not defined

In [20]:
## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [21]:
db = client['InDevelopment']

collection = db['AI_project_Tracker']

In [22]:
def batchify(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]

collection.delete_many({})

In [24]:
from pymongo import UpdateOne


#####
for batch in batchify(data, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 0, Inserted: 29, Modified: 0

In [25]:
from pymongo import UpdateOne


#####
for batch in batchify(released_data, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 0, Inserted: 35, Modified: 0

In [26]:
from datetime import datetime


datetime.today()

datetime.datetime(2025, 12, 9, 16, 46, 6, 337783)

In [27]:
client.close()