In [1]:
import warnings

warnings.filterwarnings("ignore")

# Source File

In [3]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# Step 1: Define the scope
scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]

# Step 2: Load credentials
creds = ServiceAccountCredentials.from_json_keyfile_name("ultra-sound-463216-c2-0e076e5f88fe.json", scope)

# Step 3: Authorize and connect
client = gspread.authorize(creds)

# Step 4: Open sheet by URL
sheet_url = "https://docs.google.com/spreadsheets/d/1rSBTlgMia3a9a0OdtZAlVwV0RdHz05ORs_dRIuHr6sI/edit?gid=0#gid=0"
spreadsheet = client.open_by_url(sheet_url)

# Optional: Access specific sheet/tab
sheet = spreadsheet.worksheet("projects")  # or spreadsheet.worksheet("SheetName")

# Example: Read data
data = sheet.get_all_records()

In [4]:
import pandas as pd

df = pd.DataFrame(data)

In [5]:
df.columns

Index(['sort_order', 'AP_ID', 'title', 'division', 'code', 'title_aliases',
       'imdb_id', 'tmdb_id', 'igdb_id', 'steam_id', 'dev_tracker_id',
       'indie_bi_product_name', 'iteration', 'status', 'created_by',
       'created_on', 'year', 'notes'],
      dtype='object')

In [6]:
alias_cols = ['imdb_id', 'tmdb_id', 'igdb_id',
       'steam_id', 'dev_tracker_id', 'indie_bi_product_name']

In [7]:
collection_cols = ['creative_status', 'BA_Metadata', 'deal_submissions',
       'development_tracker', 
             #      'ai_sales_data.units', 
                   'production_finance']

In [8]:
df["aliases"] = df[alias_cols].to_dict(orient="records")

In [9]:
df["required_collections"] = [collection_cols] * len(df)

In [10]:
df['AP_ID'] = df['AP_ID'].replace('', pd.NA)

In [11]:
df = df.dropna(subset="AP_ID")

In [12]:
df.iloc[0]['aliases']

{'imdb_id': '',
 'tmdb_id': '',
 'igdb_id': '',
 'steam_id': '',
 'dev_tracker_id': '20,000 Leagues Under the Sea_Animation_TV',
 'indie_bi_product_name': ''}

In [13]:
data = df[['AP_ID', 'title','title_aliases','aliases','status', 'created_by', 'created_on','notes','required_collections']]

In [14]:
docs_to_upload = data.to_dict(orient='records')

In [15]:
stop

NameError: name 'stop' is not defined

# Updating Core Mongo Registry

In [22]:
## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [23]:
db = client['InDevelopment']

collection = db['ap_id_registry']

collection.delete_many({})

In [24]:
def batchify(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]

In [25]:
from pymongo import UpdateOne


#####
for batch in batchify(docs_to_upload, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["AP_ID"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 167, Inserted: 0, Modified: 0

In [26]:
from datetime import datetime


datetime.today()

datetime.datetime(2025, 11, 18, 15, 57, 15, 348309)

In [27]:
stop

NameError: name 'stop' is not defined

# Checking Child ID Mapping

In [36]:
def validate_project(ap_id):
    missing = {}

    for col in collection_cols:
        count = db[col].count_documents({"ap_id": ap_id})
        if count == 0:
            missing[col] = "No records assigned"
    
    return missing

In [58]:
validate_project("F_2025_00055")

{'creative_status': 'No records assigned',
 'deal_submissions': 'No records assigned',
 'development_tracker': 'No records assigned',
 'production_finance': 'No records assigned'}

In [38]:
stop

NameError: name 'stop' is not defined

# Assigning Parent IDs to Children

In [48]:
def assign_project_id(collection_name, child_id, ap_id):
    db[collection_name].update_one(
        {"_id": child_id},
        {"$set": {"ap_id": ap_id}}
    )

In [49]:
data.iloc[0]['aliases']['dev_tracker_id']

'20,000 Leagues Under the Sea_Animation_TV'

In [50]:
data

,AP_ID,title,title_aliases,aliases,status,created_by,created_on,notes,required_collections
0,AN_2025_00001,"20,000 LEAGUES UNDER THE SEA",,"{'imdb_id': '', 'tmdb_id': '', 'igdb_id': '', ...",3. Internal Development,,10/27/2025,,"[creative_status, BA_Metadata, deal_submission..."
1,AN_2025_00002,ANTARCTICA,,"{'imdb_id': '', 'tmdb_id': '', 'igdb_id': '', ...",8. Library,,10/27/2025,,"[creative_status, BA_Metadata, deal_submission..."
2,AN_2025_00003,FOO,,"{'imdb_id': '', 'tmdb_id': '', 'igdb_id': '', ...",8. Library,,10/27/2025,,"[creative_status, BA_Metadata, deal_submission..."
3,AN_2025_00004,LIVING THE DREAM,,"{'imdb_id': '', 'tmdb_id': '', 'igdb_id': '', ...",7. Paused,,10/27/2025,,"[creative_status, BA_Metadata, deal_submission..."
4,AN_2025_00005,MOOMINS,,"{'imdb_id': '', 'tmdb_id': '', 'igdb_id': '', ...",6. Tracking,,10/27/2025,,"[creative_status, BA_Metadata, deal_submission..."
...,...,...,...,...,...,...,...,...,...
162,TV_2025_00065,UNT. ELVIS JASON HEHIR DOCUSERIES,,"{'imdb_id': '', 'tmdb_id': '', 'igdb_id': '', ...",8. Library,,10/27/2025,,"[creative_status, BA_Metadata, deal_submission..."
163,TV_2025_00066,"VOYEUR, THE",,"{'imdb_id': '', 'tmdb_id': '', 'igdb_id': '', ...",8. Library,,10/27/2025,,"[creative_status, BA_Metadata, deal_submission..."
164,TV_2025_00067,WE ARE LITTLE ZOMBIES,,"{'imdb_id': '', 'tmdb_id': '', 'igdb_id': '', ...",4. Pending Deal,,10/27/2025,,"[creative_status, BA_Metadata, deal_submission..."
165,TV_2025_00068,WHO IS MAUD DIXON,,"{'imdb_id': '', 'tmdb_id': '', 'igdb_id': '', ...",1. Post,,10/27/2025,,"[creative_status, BA_Metadata, deal_submission..."
166,TV_2025_00069,XEBULON,,"{'imdb_id': '', 'tmdb_id': '', 'igdb_id': '', ...",8. Library,,10/27/2025,,"[creative_status, BA_Metadata, deal_submission..."

In [51]:
pipeline = [
    {
        "$search": {
            "index": "default",
            "text": {
                "query": data.iloc[0]['title'],
                "path": "_id",
                "fuzzy": {
                    "maxEdits": 2,
                    "prefixLength": 2
                }
            }
        }
    },
    {"$limit": 10}
]

results = list(db["development_tracker"].aggregate(pipeline))

In [52]:
results[0]['_id']

'20,000 Leagues Under the Sea_Animation_TV'

In [53]:
dict_list = []

for _, row in data.iterrows():
    ap_id_title = row['aliases'].get('dev_tracker_id') or row['title']
    ap_id_uid   = row["AP_ID"]

    pipeline = [
        {
            "$search": {
                "index": "default",
                "text": {
                    "query": ap_id_title,
                    "path": "title",   # use the actual title field, NOT _id
                    "fuzzy": {
                        "maxEdits": 2,
                        "prefixLength": 2
                    }
                }
            }
        },
        {"$limit": 1}  # you only need the top result
    ]

    results = list(db["development_tracker"].aggregate(pipeline))

    if results:
        match_id = results[0]["_id"]
        dict_list.append({match_id: ap_id_uid})
    else:
        # optional: track failures
        dict_list.append({"NO_MATCH": ap_id_uid})

    print(ap_id_title)

20,000 Leagues Under the Sea_Animation_TV
Antarctica_Animation_Film
FOO (Animation)_Animation_Film
Living the Dream_Animation_TV
Moomins_Animation_Film
NARPS (Non-Associated Regular People)_Animation_TV
Nimona_Animation_Film
OUTER WILDS (TV)
Outlets_Animation_TV
Sapiens - Animation_Animation_TV
SAUSAGE PARTY (Film)
SAUSAGE PARTY (TV)
Some Assembly Required_Animation_Film
Mantooth_Animation_Film
he Trap_Animation_Film
COMA_Animation_Film
Witchfeld_Animation_TV
Twelve Minutes (Anim/TV)_Film
20TH CENTURY WOMEN
AMERICAN HUSTLE
American Jewel_Film
American Spartan_Film
Women Clothed by the Sun_Film
Unt Mr. Beast Fiction Project_Film
Belly of the Beast_Film
Unt Bennett Miller (fka Untitled Charlie Kaufman Project)_Film
BOMBSHELL
BOOKSMART
BRADY CORBET / MONA FASTVOLD PROJECT (UNT.)
Chef_Film
Cuban Missile Crisis_Film
DESTROYER
DETROIT
Untitled Dolly Parton_Film
Even the Losers/ Unt. Randy Lanier_Film
EVERYBODY WANTS SOME
Finding Gobi_Film
Five Hitmen_Film
FOXCATCHER
Grind_Film
HER
HUSTLERS
I LOVE BOOSTERS
IF BEALE STREET COULD TALK
INTO THE GLORY WHOLE
JAMES SWEENEY (UNT.)
JOY
KAJILLIONAIRE
KILLING THEM SOFTLY
LANDSCAPE WITH INVISIBLE HAND
LAWLESS
LEGEND OF GEORGIA MCBRIDE, THE
LOST WILD, THE
MISSING LINK
Monument Valley_Film
The New Man_Film
Unt Nicole Taylor_Film
NIGHTBITCH
Norco 80_Film
ON THE COUNT OF THREE
PHANTOM THREAD
PROFESSOR MARSTON AND THE WONDER WOMEN
SESAME STREET
SHE SAID
The Silent Patient - Plan B_Film
SOAPS
SORRY TO BOTHER YOU
SPRING BREAKERS
Syd_Film
THE BAD BATCH
THE GRANDMASTER
THE INVITE
THE MASTER
THE SISTERS BROTHERS
THIEF, THE
TWENTY FIVE SCENES
VICE
VISIT, THE
WHERE’D YOU GO BERNADETTE
WIENER-DOG
WOUNDS
ZERO DARK THIRTY
BATTLE OF TRAFALGAR
CALLIOPE
NOBODY’S BUSINESS
RED DEAD REDEMPTION
SHI YANG
STRAY (Film)
THE TRUNG SISTERS
APPROPRIATE
BABY REINDEER
CENTER STAGE
DEAR ENGLAND
FLEABAG
SIX THE MUSICAL
Case of the Existence of God_Theatre
THE MOTIVE IN THE QUE
THE WITCHES
ADVANTAGE
Alan Wake_TV
Aztec_TV
BACK
Badlands_TV
Biggest Little Farm_TV
Call Me Dad_TV
CARDBOARD DYNASTY
The Chosen One_TV
Control_TV
CURE FOR CANCER
Darkside of the Moon_TV
DEAD RINGERS
DEATH VALLEY
DEATH'S A BITCH
Dude Where's My Castle_TV
Edith Finch - Television_TV
Unt. Equestrian Series_TV
Everything I Never Told You_TV
Executive Protection_TV
Untitled Mallory Project_TV
FIGHTING
Unt. Game Doc Series_TV
Unt. Carlo Bernard/International Mercenaries_TV
Heartstring_TV
Hellraiser_Animation_Film
Hot Kid_TV
HOUSE OF LEAVES
I CAN’T RIGHT NOW
I LOVE THAT FOR YOU
Identical_TV
Unt. John Cho Jean Kyoung Frazier (if/come)_TV
KPOP
The Tour_TV
Made in Utah_TV
MINISTRY FOR THE FUTURE
MONSTERLAND
Unt Mr. Beast Fiction Project_TV
Murderland_TV
NEVERWOLD WAKE
Nomad Summer_TV
Operator_TV
The Original_TV
PAM & TOMMY
PARABLE OF THE SOWER
Planet of Exile_TV
PLAYDEAD (LIMBO AND INSIDE)
Red West_TV
S.T.A.G.S.
Seized_TV
Shot to Nothing_TV
Sia Martinez_TV
SKIMMER
SOUNDTRACK
SPORTS FAN SHOW (UNT. )
Strangers_TV
SWEETIE
THE BALLARD OF BUSTER SCRUGGS
THE CHANGELING (S1)
THE CHANGELING (S2)
THE DEAD THING
THE PLOT AGAINST AMERICA
THE STAIRCASE
THE TEACHER
UNT. ELVIS JASON HEHIR DOCUSERIES
VOYEUR, THE
WE ARE LITTLE ZOMBIES
Who is Maud Dixon_TV
Xebulon_TV

In [54]:
dict_list

[{'20,000 Leagues Under the Sea_Animation_TV': 'AN_2025_00001'},
 {'NO_MATCH': 'AN_2025_00002'},
 {'FOO (Animation)_Animation_Film': 'AN_2025_00003'},
 {'Living the Dream_Animation_TV': 'AN_2025_00004'},
 {'NO_MATCH': 'AN_2025_00005'},
 {'NARPS (Non-Associated Regular People)_Animation_TV': 'AN_2025_00006'},
 {'NO_MATCH': 'AN_2025_00007'},
 {'Donut County - Anim/TV_Animation_TV': 'AN_2025_00008'},
 {'NO_MATCH': 'AN_2025_00009'},
 {'Sapiens - Animation_Animation_TV': 'AN_2025_00010'},
 {'Exit Party_TV': 'AN_2025_00011'},
 {'Exit Party_TV': 'AN_2025_00012'},
 {'Some Assembly Required_Animation_Film': 'AN_2025_00013'},
 {'NO_MATCH': 'AN_2025_00014'},
 {'Her_Theatre': 'AN_2025_00015'},
 {'NO_MATCH': 'AN_2025_00016'},
 {'NO_MATCH': 'AN_2025_00017'},
 {'Twelve Minutes (Anim/TV)_Film': 'F_2025_00001'},
 {'Center Stage_Theatre': 'F_2025_00002'},
 {'American Spartan_Film': 'F_2025_00003'},
 {'American Spartan_Film': 'F_2025_00004'},
 {'American Spartan_Film': 'F_2025_00005'},
 {'Women Clothed by the Sun_Film': 'F_2025_00006'},
 {'Unt Mr. Beast Fiction Project_Film': 'F_2025_00007'},
 {'Belly of the Beast_Film': 'F_2025_00008'},
 {'Unt Bennett Miller (fka Untitled Charlie Kaufman Project)_Film': 'F_2025_00009'},
 {'NO_MATCH': 'F_2025_00010'},
 {'NO_MATCH': 'F_2025_00011'},
 {'Unt Mr. Beast Fiction Project_Film': 'F_2025_00012'},
 {'NO_MATCH': 'F_2025_00013'},
 {'Cuban Missile Crisis_Film': 'F_2025_00014'},
 {'NO_MATCH': 'F_2025_00015'},
 {'NO_MATCH': 'F_2025_00016'},
 {'Untitled Dolly Parton_Film': 'F_2025_00017'},
 {'Even the Losers/ Unt. Randy Lanier_Film': 'F_2025_00018'},
 {'Some Assembly Required_Animation_Film': 'F_2025_00019'},
 {'Finding Gobi_Film': 'F_2025_00020'},
 {'Five Hitmen_Film': 'F_2025_00021'},
 {'NO_MATCH': 'F_2025_00022'},
 {'NO_MATCH': 'F_2025_00023'},
 {'Her_Theatre': 'F_2025_00024'},
 {'NO_MATCH': 'F_2025_00025'},
 {'Everything I Never Told You_TV': 'F_2025_00026'},
 {'Belly of the Beast_Film': 'F_2025_00027'},
 {'The Trap_Animation_Film': 'F_2025_00028'},
 {'Unt James Sweeney_Film': 'F_2025_00029'},
 {'Unt. John Cho Jean Kyoung Frazier (if/come)_TV': 'F_2025_00030'},
 {'NO_MATCH': 'F_2025_00031'},
 {'The Trap_Animation_Film': 'F_2025_00032'},
 {'The Lost Wild - Film_Film': 'F_2025_00033'},
 {'NO_MATCH': 'F_2025_00034'},
 {'The Legend of Georgia McBride_Film': 'F_2025_00035'},
 {'The Lost Wild - Film_Film': 'F_2025_00036'},
 {'Cuban Missile Crisis_Film': 'F_2025_00037'},
 {'Monument Valley_Film': 'F_2025_00038'},
 {'The New Man_Film': 'F_2025_00039'},
 {'Unt Nicole Taylor_Film': 'F_2025_00040'},
 {'NO_MATCH': 'F_2025_00041'},
 {'Norco 80_Film': 'F_2025_00042'},
 {'Case of the Existence of God_Theatre': 'F_2025_00043'},
 {'NO_MATCH': 'F_2025_00044'},
 {'Women Clothed by the Sun_Film': 'F_2025_00045'},
 {'NO_MATCH': 'F_2025_00046'},
 {'Unt. Shi Yang_TV': 'F_2025_00047'},
 {'The Silent Patient - Plan B_Film': 'F_2025_00048'},
 {'NO_MATCH': 'F_2025_00049'},
 {'Shot to Nothing_TV': 'F_2025_00050'},
 {'NO_MATCH': 'F_2025_00051'},
 {'NO_MATCH': 'F_2025_00052'},
 {'The Trap_Animation_Film': 'F_2025_00053'},
 {'The Trap_Animation_Film': 'F_2025_00054'},
 {'Inside_TV': 'F_2025_00055'},
 {'The Trap_Animation_Film': 'F_2025_00056'},
 {'The Trap_Animation_Film': 'F_2025_00057'},
 {'The Trap_Animation_Film': 'F_2025_00058'},
 {'Five Hitmen_Film': 'F_2025_00059'},
 {'NO_MATCH': 'F_2025_00060'},
 {'The Visit_Film': 'F_2025_00061'},
 {'Everything I Never Told You_TV': 'F_2025_00062'},
 {'Unt. Game Doc Series_TV': 'F_2025_00063'},
 {'NO_MATCH': 'F_2025_00064'},
 {'Call Me Dad_TV': 'F_2025_00065'},
 {'Case of the Existence of God_Theatre': 'I_2025_00001'},
 {'Calliope_corporate': 'I_2025_00002'},
 {'NO_MATCH': 'I_2025_00003'},
 {'Red West_TV': 'I_2025_00004'},
 {'Unt. Shi Yang_TV': 'I_2025_00005'},
 {'Stray - Animation_Animation_Film': 'I_2025_00006'},
 {'The Trap_Animation_Film': 'I_2025_00007'},
 {'NO_MATCH': 'TH_2025_00001'},
 {'NO_MATCH': 'TH_2025_00002'},
 {'Center Stage_Theatre': 'TH_2025_00003'},
 {'England Expects (Film)_corporate': 'TH_2025_00004'},
 {'NO_MATCH': 'TH_2025_00005'},
 {'Sia Martinez_TV': 'TH_2025_00006'},
 {'Case of the Existence of God_Theatre': 'TH_2025_00007'},
 {'Made in Utah_TV': 'TH_2025_00008'},
 {'The Trap_Animation_Film': 'TH_2025_00009'},
 {'NO_MATCH': 'TV_2025_00001'},
 {'Alan Wake_TV': 'TV_2025_00002'},
 {'NO_MATCH': 'TV_2025_00003'},
 {'NO_MATCH': 'TV_2025_00004'},
 {'NO_MATCH': 'TV_2025_00005'},
 {'Biggest Little Farm_TV': 'TV_2025_00006'},
 {'Call Me Dad_TV': 'TV_2025_00007'},
 {'NO_MATCH': 'TV_2025_00008'},
 {'The Chosen One_TV': 'TV_2025_00009'},
 {'NO_MATCH': 'TV_2025_00010'},
 {'FOO (Animation)_Animation_Film': 'TV_2025_00011'},
 {'Darkside of the Moon_TV': 'TV_2025_00012'},
 {'Unt. Death Hoax_TV': 'TV_2025_00013'},
 {'Monument Valley_Film': 'TV_2025_00014'},
 {'Unt. Death Hoax_TV': 'TV_2025_00015'},
 {"Dude Where's My Castle_TV": 'TV_2025_00016'},
 {'Edith Finch - Television_TV': 'TV_2025_00017'},
 {'Unt. Equestrian Series_TV': 'TV_2025_00018'},
 {'Everything I Never Told You_TV': 'TV_2025_00019'},
 {'Executive Protection_TV': 'TV_2025_00020'},
 {'Untitled Mallory Project_TV': 'TV_2025_00021'},
 {'NO_MATCH': 'TV_2025_00022'},
 {'Unt. Game Doc Series_TV': 'TV_2025_00023'},
 {'Unt. Carlo Bernard/International Mercenaries_TV': 'TV_2025_00024'},
 {'NO_MATCH': 'TV_2025_00025'},
 {'NO_MATCH': 'TV_2025_00026'},
 {'Hot Kid_TV': 'TV_2025_00027'},
 {'Case of the Existence of God_Theatre': 'TV_2025_00028'},
 {'Everything I Never Told You_TV': 'TV_2025_00029'},
 {'Everything I Never Told You_TV': 'TV_2025_00030'},
 {'NO_MATCH': 'TV_2025_00031'},
 {'Unt. John Cho Jean Kyoung Frazier (if/come)_TV': 'TV_2025_00032'},
 {'NO_MATCH': 'TV_2025_00033'},
 {'The Trap_Animation_Film': 'TV_2025_00034'},
 {'Made in Utah_TV': 'TV_2025_00035'},
 {'FOO (Animation)_Animation_Film': 'TV_2025_00036'},
 {'NO_MATCH': 'TV_2025_00037'},
 {'Unt Mr. Beast Fiction Project_Film': 'TV_2025_00038'},
 {'NO_MATCH': 'TV_2025_00039'},
 {'Alan Wake_TV': 'TV_2025_00040'},
 {'Nomad Summer_TV': 'TV_2025_00041'},
 {'NO_MATCH': 'TV_2025_00042'},
 {'The Trap_Animation_Film': 'TV_2025_00043'},
 {'NO_MATCH': 'TV_2025_00044'},
 {'Case of the Existence of God_Theatre': 'TV_2025_00045'},
 {'Planet of Exile_TV': 'TV_2025_00046'},
 {'Inside_TV': 'TV_2025_00047'},
 {'Red West_TV': 'TV_2025_00048'},
 {'NO_MATCH': 'TV_2025_00049'},
 {'NO_MATCH': 'TV_2025_00050'},
 {'Shot to Nothing_TV': 'TV_2025_00051'},
 {'Sia Martinez_TV': 'TV_2025_00052'},
 {'NO_MATCH': 'TV_2025_00053'},
 {'NO_MATCH': 'TV_2025_00054'},
 {'Unt. Sports Fan Show_TV': 'TV_2025_00055'},
 {'NO_MATCH': 'TV_2025_00056'},
 {'NO_MATCH': 'TV_2025_00057'},
 {'Case of the Existence of God_Theatre': 'TV_2025_00058'},
 {'The Trap_Animation_Film': 'TV_2025_00059'},
 {'The Trap_Animation_Film': 'TV_2025_00060'},
 {'Unt. Death Hoax_TV': 'TV_2025_00061'},
 {'American Spartan_Film': 'TV_2025_00062'},
 {'The Trap_Animation_Film': 'TV_2025_00063'},
 {'The Trap_Animation_Film': 'TV_2025_00064'},
 {'Unt. Shi Yang_TV': 'TV_2025_00065'},
 {'The Voyeur_TV': 'TV_2025_00066'},
 {'Biggest Little Farm_TV': 'TV_2025_00067'},
 {'Who is Maud Dixon_TV': 'TV_2025_00068'},
 {'NO_MATCH': 'TV_2025_00069'}]

In [55]:
pipeline = [

    {"$project": {"_id": 1}},   # Only return IDs
]

results = list(db["development_tracker"].aggregate(pipeline))

unique_ids = {doc["_id"] for doc in results}

In [56]:
unique_ids

{'20,000 Leagues Under the Sea_Animation_TV',
 'Alan Wake_TV',
 'American Jewel_Film',
 'American Spartan_Film',
 'Antarctica_Animation_Film',
 'Aztec_TV',
 'Badlands_TV',
 'Belly of the Beast_Film',
 'Biggest Little Farm_TV',
 'Blankets_Film',
 'COMA_Animation_Film',
 'Call Me Dad_TV',
 'Calliope_corporate',
 'Case of the Existence of God_Theatre',
 'Center Stage_Theatre',
 'Chef_Film',
 'Conner (Literary Research)_Film',
 'Conner (Literary Research)_TV',
 'Control_TV',
 'Counterculture_corporate',
 'Cuban Missile Crisis_Film',
 'Cutter & Tats_TV',
 'Darkside of the Moon_TV',
 'Donut County - Anim/TV_Animation_TV',
 "Dude Where's My Castle_TV",
 'Edith Finch - Television_TV',
 'England Expects (Film)_corporate',
 'Eric Warren Singer_Film',
 'Even the Losers/ Unt. Randy Lanier_Film',
 'Everything I Never Told You_TV',
 'Executive Protection_TV',
 'Exit Party_TV',
 'FOO (Animation)_Animation_Film',
 'Finding Gobi_Film',
 'Five Hitmen_Film',
 'Grant & Sherman_TV',
 'Grant & Sherman_corporate',
 'Grind_Film',
 'Haiet_Animation_Film',
 'Heartstring_TV',
 'Hellraiser_Animation_Film',
 'Her_Theatre',
 'Hot Kid_TV',
 'Identical_TV',
 'Inside_TV',
 'Inter Alia (Broadway 2026)_Theatre',
 'Kill the Rabbit_TV',
 "Let's Boogey_Animation_Film",
 'Limbo (TV/FILM tbd)_TV',
 'Living the Dream_Animation_TV',
 'Made in Utah_TV',
 'Mantooth_Animation_Film',
 'Minds on Fire_Film',
 'Monument Valley_Film',
 'Moomins_Animation_Film',
 'Murderland_TV',
 'NARPS (Non-Associated Regular People)_Animation_TV',
 'Nick Weidenfeld_Animation_TV',
 'Nimona_Animation_Film',
 'Nomad Summer_TV',
 'Norco 80_Film',
 'Operator_TV',
 'Outlets_Animation_TV',
 'Planet of Exile_TV',
 'Red West_TV',
 'Sapiens - Animation_Animation_TV',
 'Seized_TV',
 'Shot to Nothing_TV',
 'Sia Martinez_TV',
 'Some Assembly Required_Animation_Film',
 'Stephen Feder fee_Film',
 'Strangers_TV',
 'Stray - Animation_Animation_Film',
 'Syd_Film',
 'Syd_TV',
 'The Chosen One_TV',
 'The Drifting Classroom_TV',
 'The Legend of Georgia McBride_Film',
 'The Lost Wild - Film_Film',
 'The New Man_Film',
 'The Original_TV',
 'The Silent Patient - Plan B_Film',
 'The Tour_TV',
 'The Trap_Animation_Film',
 'The Visit_Film',
 'The Voyeur_TV',
 'Twelve Minutes (Anim/TV)_Film',
 'Unt Bennett Miller (fka Untitled Charlie Kaufman Project)_Film',
 'Unt James Sweeney_Film',
 'Unt Mr. Beast Fiction Project_Film',
 'Unt Nicole Taylor_Film',
 'Unt. Carlo Bernard/International Mercenaries_TV',
 'Unt. Death Hoax_TV',
 'Unt. Equestrian Series_TV',
 'Unt. Game Doc Series_TV',
 'Unt. John Cho Jean Kyoung Frazier (if/come)_TV',
 'Unt. Shi Yang_TV',
 'Unt. Sports Fan Show_TV',
 'Untitled Dolly Parton_Film',
 'Untitled Lessovitz, Quesada, Zund_Film',
 'Untitled Mallory Project_TV',
 'Who is Maud Dixon_TV',
 'Witchfeld_Animation_TV',
 'Women Clothed by the Sun_Film',
 'Xebulon_TV'}

In [57]:
stop

NameError: name 'stop' is not defined

In [60]:
from pandas import json_normalize

aliases_df = json_normalize(data["aliases"])
data = data.join(aliases_df)

In [61]:
data

,AP_ID,title,title_aliases,aliases,status,created_by,created_on,notes,required_collections,imdb_id,tmdb_id,igdb_id,steam_id,dev_tracker_id,indie_bi_product_name
0,AN_2025_00001,"20,000 LEAGUES UNDER THE SEA",,"{'imdb_id': '', 'tmdb_id': '', 'igdb_id': '', ...",3. Internal Development,,10/27/2025,,"[creative_status, BA_Metadata, deal_submission...",,,,,"20,000 Leagues Under the Sea_Animation_TV",
1,AN_2025_00002,ANTARCTICA,,"{'imdb_id': '', 'tmdb_id': '', 'igdb_id': '', ...",8. Library,,10/27/2025,,"[creative_status, BA_Metadata, deal_submission...",,,,,Antarctica_Animation_Film,
2,AN_2025_00003,FOO,,"{'imdb_id': '', 'tmdb_id': '', 'igdb_id': '', ...",8. Library,,10/27/2025,,"[creative_status, BA_Metadata, deal_submission...",,,,,FOO (Animation)_Animation_Film,
3,AN_2025_00004,LIVING THE DREAM,,"{'imdb_id': '', 'tmdb_id': '', 'igdb_id': '', ...",7. Paused,,10/27/2025,,"[creative_status, BA_Metadata, deal_submission...",,,,,Living the Dream_Animation_TV,
4,AN_2025_00005,MOOMINS,,"{'imdb_id': '', 'tmdb_id': '', 'igdb_id': '', ...",6. Tracking,,10/27/2025,,"[creative_status, BA_Metadata, deal_submission...",,,,,Moomins_Animation_Film,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,TV_2025_00065,UNT. ELVIS JASON HEHIR DOCUSERIES,,"{'imdb_id': '', 'tmdb_id': '', 'igdb_id': '', ...",8. Library,,10/27/2025,,"[creative_status, BA_Metadata, deal_submission...",,,,,,
163,TV_2025_00066,"VOYEUR, THE",,"{'imdb_id': '', 'tmdb_id': '', 'igdb_id': '', ...",8. Library,,10/27/2025,,"[creative_status, BA_Metadata, deal_submission...",,,,,,
164,TV_2025_00067,WE ARE LITTLE ZOMBIES,,"{'imdb_id': '', 'tmdb_id': '', 'igdb_id': '', ...",4. Pending Deal,,10/27/2025,,"[creative_status, BA_Metadata, deal_submission...",,,,,,
165,TV_2025_00068,WHO IS MAUD DIXON,,"{'imdb_id': '', 'tmdb_id': '', 'igdb_id': '', ...",1. Post,,10/27/2025,,"[creative_status, BA_Metadata, deal_submission...",,,,,Who is Maud Dixon_TV,
166,TV_2025_00069,XEBULON,,"{'imdb_id': '', 'tmdb_id': '', 'igdb_id': '', ...",8. Library,,10/27/2025,,"[creative_status, BA_Metadata, deal_submission...",,,,,Xebulon_TV,

In [69]:
updater = data[['AP_ID', 'dev_tracker_id']]
updater['dev_tracker_id'] = updater['dev_tracker_id'].replace('', pd.NA)

updater = updater.dropna(subset='dev_tracker_id')

In [73]:
updater

             AP_ID                             dev_tracker_id
0    AN_2025_00001  20,000 Leagues Under the Sea_Animation_TV
1    AN_2025_00002                  Antarctica_Animation_Film
2    AN_2025_00003             FOO (Animation)_Animation_Film
3    AN_2025_00004              Living the Dream_Animation_TV
4    AN_2025_00005                     Moomins_Animation_Film
..             ...                                        ...
148  TV_2025_00051                         Shot to Nothing_TV
149  TV_2025_00052                            Sia Martinez_TV
153  TV_2025_00056                               Strangers_TV
165  TV_2025_00068                       Who is Maud Dixon_TV
166  TV_2025_00069                                 Xebulon_TV

[71 rows x 2 columns]

In [75]:
for _, row in updater.iterrows():
    assign_project_id("development_tracker", row['dev_tracker_id'], row['AP_ID'])

In [77]:
stop

NameError: name 'stop' is not defined

## for Metadata, I need to organize the metdata fields so there is always a Title and then do a fuzzy lookup periodically. That would capture BA and its many documents.

In [149]:
pipeline = [

    {"$project": {"project": 1, 'projectname':1, 'projecttitle':1}},   # Only return IDs
]

results = list(db["BA_Metadata"].aggregate(pipeline))

results

[{'_id': 'c2144680-0629-4b00-ac70-f3483f3ffb7c',
  'project': nan,
  'projectname': 'The People Upstairs',
  'projecttitle': nan},
 {'_id': '88061483-03d4-466d-8219-331af846ab60',
  'project': 'The Invite',
  'projectname': nan,
  'projecttitle': nan},
 {'_id': '298d7766-4ae2-4033-92a6-1cefe7d4d91d',
  'project': 'The Invite',
  'projectname': nan,
  'projecttitle': nan},
 {'_id': '708c8c19-544f-4854-848b-a01ad7cb60c1',
  'project': 'Sentimental (a/k/a "The People Upstairs")',
  'projectname': nan,
  'projecttitle': nan},
 {'_id': '9a14cf14-e6fd-4d6f-a1a3-df0c0cc03543',
  'project': 'The Invite',
  'projectname': nan,
  'projecttitle': nan},
 {'_id': '82bd62bc-7d69-41e2-8a99-2908afb32aff',
  'project': nan,
  'projectname': 'The Invite',
  'projecttitle': nan},
 {'_id': '0538614a-6d65-428a-a22a-4b94b9405afc',
  'project': nan,
  'projectname': 'JACK & NORMAN',
  'projecttitle': nan},
 {'_id': '761e7556-7228-4991-a468-e8cef9cc458b',
  'project': nan,
  'projectname': nan,
  'projecttitle': 'THE INVITE'}]

In [167]:
pipeline = [
    {
        "$search": {
            "index": "default",
            "text": {
                "query": 'Belly of the Beast',
                "path": ["project", "projectname"],   # correct and complete
                "fuzzy": {
                    "maxEdits": 2,
                    "prefixLength": 2
                }
            }
        }
    },
    {"$limit": 50}
]

results = list(db["BA_Metadata"].aggregate(pipeline))

In [169]:
ba_id_list  = [item["_id"] for item in results]
ba_id_list

['82bd62bc-7d69-41e2-8a99-2908afb32aff',
 'c2144680-0629-4b00-ac70-f3483f3ffb7c',
 '9a14cf14-e6fd-4d6f-a1a3-df0c0cc03543',
 '88061483-03d4-466d-8219-331af846ab60',
 '298d7766-4ae2-4033-92a6-1cefe7d4d91d',
 '708c8c19-544f-4854-848b-a01ad7cb60c1']

In [171]:
results

[{'_id': '82bd62bc-7d69-41e2-8a99-2908afb32aff',
  'box_canEdit': True,
  'box_id': '82bd62bc-7d69-41e2-8a99-2908afb32aff',
  'box_parent': 'file_2028748459100',
  'box_scope': 'enterprise_1353798051',
  'box_template': 'produceragreement',
  'box_type': 'produceragreement-6accbf86-1817-4d96-8266-c320db854a59',
  'box_typeVersion': 2,
  'box_version': 2,
  'compensation': 250000.0,
  'contingencyBudget': nan,
  'contingencyRemaining': nan,
  'contingencySpendToDate': nan,
  'control': 'Company shall have the sole authority to regulate all activities on set.',
  'credit': 'One individual "Produced by" credit for Producer in a size and style of type no less favorable than 100% of the size of credit accorded any other non-cast individual rendering services in connection with the Picture',
  'deliverables': 'services as are customarily rendered by producers of first-class feature-length theatrical motion pictures in the motion picture industry in accordance with the reasonable directions, requests, rules and regulations of Company in connection therewith, whether the same involve matters of artistic taste and judgment.',
  'department': nan,
  'dept': nan,
  'etag': nan,
  'extensions': nan,
  'file_id': 2028748459100,
  'file_version': {'id': nan},
  'finalDraftCompensation': nan,
  'finalDraftPeriodWeeks': nan,
  'firstDraftCompensation1': nan,
  'firstDraftPeriodWeeks': nan,
  'grossBudget': nan,
  'initialoption': nan,
  'initialoptionstartdate': nan,
  'keydates': 'Dated as of April 9, 2025 but effective as of August 20, 2021\nStart Date: no more than eight (8) weeks prior to the start of principal photography\nTerm: ending on the completion of principal photography of the Picture',
  'name': nan,
  'netBudget': nan,
  'optionalPolishCompensation': nan,
  'optionalPolishPeriodWeeks': nan,
  'optionalRewriteCompensation': nan,
  'optionalRewritePeriodWeeks': nan,
  'optionstatus': nan,
  'parties': 'Permut Presentations, Inc. (Lender) for the services of David Permut (Producer) and Invite Productions, Inc. (Company)',
  'postweeksactualfinish': nan,
  'postweeksactualstart': nan,
  'postweeksscheduledfinish': nan,
  'postweeksscheduledstart': nan,
  'project': nan,
  'projectname': 'The Invite',
  'purchaseprice': nan,
  'readingPeriodPeriodWeeks': nan,
  'remainingSpend': nan,
  'rightsholder': nan,
  'sequence_id': nan,
  'sha1': nan,
  'shootdateactualfinish': nan,
  'shootdateactualstart': nan,
  'shootdatescheduledfinish': nan,
  'shootdatescheduledstart': nan,
  'spendToDate': nan,
  'type': nan,
  'updated_time': datetime.datetime(2025, 10, 31, 10, 13, 42, 993000),
  'periodending': nan,
  'projecttitle': nan,
  'ap_id': 'F_2025_00055'},
 {'_id': 'c2144680-0629-4b00-ac70-f3483f3ffb7c',
  'box_canEdit': True,
  'box_id': 'c2144680-0629-4b00-ac70-f3483f3ffb7c',
  'box_parent': 'file_2019247038893',
  'box_scope': 'enterprise_1353798051',
  'box_template': 'writeragreement',
  'box_type': 'writeragreement-a8b6033d-a3f7-493e-bfe5-594336630afb',
  'box_typeVersion': 0,
  'box_version': 2,
  'compensation': nan,
  'contingencyBudget': nan,
  'contingencyRemaining': nan,
  'contingencySpendToDate': nan,
  'control': nan,
  'credit': nan,
  'deliverables': nan,
  'department': 'film',
  'dept': nan,
  'etag': nan,
  'extensions': nan,
  'file_id': 2019247038893,
  'file_version': {'id': nan},
  'finalDraftCompensation': 100000.0,
  'finalDraftPeriodWeeks': 8.0,
  'firstDraftCompensation1': 150000.0,
  'firstDraftPeriodWeeks': 12.0,
  'grossBudget': nan,
  'initialoption': nan,
  'initialoptionstartdate': nan,
  'keydates': nan,
  'name': nan,
  'netBudget': nan,
  'optionalPolishCompensation': 35000.0,
  'optionalPolishPeriodWeeks': 4.0,
  'optionalRewriteCompensation': 50000.0,
  'optionalRewritePeriodWeeks': 6.0,
  'optionstatus': nan,
  'parties': nan,
  'postweeksactualfinish': nan,
  'postweeksactualstart': nan,
  'postweeksscheduledfinish': nan,
  'postweeksscheduledstart': nan,
  'project': nan,
  'projectname': 'The People Upstairs',
  'purchaseprice': nan,
  'readingPeriodPeriodWeeks': 4.0,
  'remainingSpend': nan,
  'rightsholder': nan,
  'sequence_id': nan,
  'sha1': nan,
  'shootdateactualfinish': nan,
  'shootdateactualstart': nan,
  'shootdatescheduledfinish': nan,
  'shootdatescheduledstart': nan,
  'spendToDate': nan,
  'type': nan,
  'updated_time': datetime.datetime(2025, 10, 31, 10, 13, 42, 993000),
  'periodending': nan,
  'projecttitle': nan,
  'ap_id': 'F_2025_00055'},
 {'_id': '9a14cf14-e6fd-4d6f-a1a3-df0c0cc03543',
  'box_canEdit': True,
  'box_id': '9a14cf14-e6fd-4d6f-a1a3-df0c0cc03543',
  'box_parent': 'file_2028748447100',
  'box_scope': 'enterprise_1353798051',
  'box_template': 'performersagreement',
  'box_type': 'performersagreement-a1dd1d83-25d4-4ec0-b566-8d7179971f83',
  'box_typeVersion': 2,
  'box_version': 1,
  'compensation': 250000.0,
  'contingencyBudget': nan,
  'contingencyRemaining': nan,
  'contingencySpendToDate': nan,
  'control': 'Company has decision-making authority over creative, financial, or operational aspects of the project.',
  'credit': 'Provided that Performer appears recognizably in the Picture as released in the Role, Performer shall be accorded credit on screen, in the main titles (whether such main titles appear at the beginning or end of the Picture), on a shared card with the other three (3) lead cast members only, listed by order of appearance, above or before the title of the Picture in such main titles, in an average size no less favorable than the average size of credit accorded to any other principal cast members receiving main title credit.',
  'deliverables': 'acting services in the theatrical motion picture currently entitled "The Invite"',
  'department': nan,
  'dept': nan,
  'etag': nan,
  'extensions': nan,
  'file_id': 2028748447100,
  'file_version': {'id': nan},
  'finalDraftCompensation': nan,
  'finalDraftPeriodWeeks': nan,
  'firstDraftCompensation1': nan,
  'firstDraftPeriodWeeks': nan,
  'grossBudget': nan,
  'initialoption': nan,
  'initialoptionstartdate': nan,
  'keydates': 'February 17, 2025, April 14, 2025, April 16, 2025, April 21, 2025, May 21, 2025',
  'name': nan,
  'netBudget': nan,
  'optionalPolishCompensation': nan,
  'optionalPolishPeriodWeeks': nan,
  'optionalRewriteCompensation': nan,
  'optionalRewritePeriodWeeks': nan,
  'optionstatus': nan,
  'parties': 'Invite Productions, Inc. and KETCHUP CHIP, INC. for the services of Seth Rogen',
  'postweeksactualfinish': nan,
  'postweeksactualstart': nan,
  'postweeksscheduledfinish': nan,
  'postweeksscheduledstart': nan,
  'project': 'The Invite',
  'projectname': nan,
  'purchaseprice': nan,
  'readingPeriodPeriodWeeks': nan,
  'remainingSpend': nan,
  'rightsholder': nan,
  'sequence_id': nan,
  'sha1': nan,
  'shootdateactualfinish': nan,
  'shootdateactualstart': nan,
  'shootdatescheduledfinish': nan,
  'shootdatescheduledstart': nan,
  'spendToDate': nan,
  'type': nan,
  'updated_time': datetime.datetime(2025, 10, 31, 10, 13, 42, 993000),
  'periodending': nan,
  'projecttitle': nan,
  'ap_id': 'F_2025_00055'},
 {'_id': '88061483-03d4-466d-8219-331af846ab60',
  'box_canEdit': True,
  'box_id': '88061483-03d4-466d-8219-331af846ab60',
  'box_parent': 'file_2019255635647',
  'box_scope': 'enterprise_1353798051',
  'box_template': 'directorsagreement',
  'box_type': 'directorsagreement-94fd2a9e-15cf-4b57-91df-d471ae0174e8',
  'box_typeVersion': 2,
  'box_version': 1,
  'compensation': 425000.0,
  'contingencyBudget': nan,
  'contingencyRemaining': nan,
  'contingencySpendToDate': nan,
  'control': "Company and Director shall mutually approve all material creative elements of the Picture, provided that Company's decision shall control in the event of a dispute",
  'credit': 'Director shall receive credit as the director of the Picture, in substantially the form "Directed by Olivia Wilde", and Director shall also receive possessory credit in substantially the form: "A Film by Olivia Wilde"',
  'deliverables': 'direct a full-length motion picture currently entitled "The Invite"',
  'department': nan,
  'dept': nan,
  'etag': nan,
  'extensions': nan,
  'file_id': 2019255635647,
  'file_version': {'id': nan},
  'finalDraftCompensation': nan,
  'finalDraftPeriodWeeks': nan,
  'firstDraftCompensation1': nan,
  'firstDraftPeriodWeeks': nan,
  'grossBudget': nan,
  'initialoption': nan,
  'initialoptionstartdate': nan,
  'keydates': 'February 10, 2025 (Agreement Date), March 28, 2025 (pre-approved budget date), March 11, 2025 (pre-approved schedules date)',
  'name': nan,
  'netBudget': nan,
  'optionalPolishCompensation': nan,
  'optionalPolishPeriodWeeks': nan,
  'optionalRewriteCompensation': nan,
  'optionalRewritePeriodWeeks': nan,
  'optionstatus': nan,
  'parties': 'Invite Productions, Inc. and The Wilde Company for the services of Olivia Wilde',
  'postweeksactualfinish': nan,
  'postweeksactualstart': nan,
  'postweeksscheduledfinish': nan,
  'postweeksscheduledstart': nan,
  'project': 'The Invite',
  'projectname': nan,
  'purchaseprice': nan,
  'readingPeriodPeriodWeeks': nan,
  'remainingSpend': nan,
  'rightsholder': nan,
  'sequence_id': nan,
  'sha1': nan,
  'shootdateactualfinish': nan,
  'shootdateactualstart': nan,
  'shootdatescheduledfinish': nan,
  'shootdatescheduledstart': nan,
  'spendToDate': nan,
  'type': nan,
  'updated_time': datetime.datetime(2025, 10, 31, 10, 13, 42, 993000),
  'periodending': nan,
  'projecttitle': nan,
  'ap_id': 'F_2025_00055'},
 {'_id': '298d7766-4ae2-4033-92a6-1cefe7d4d91d',
  'box_canEdit': True,
  'box_id': '298d7766-4ae2-4033-92a6-1cefe7d4d91d',
  'box_parent': 'file_2019256737318',
  'box_scope': 'enterprise_1353798051',
  'box_template': 'performersagreement',
  'box_type': 'performersagreement-a1dd1d83-25d4-4ec0-b566-8d7179971f83',
  'box_typeVersion': 2,
  'box_version': 0,
  'compensation': 40135.0,
  'contingencyBudget': nan,
  'contingencyRemaining': nan,
  'contingencySpendToDate': nan,
  'control': "Company shall render Performer's services in accordance with the reasonable directions, requests, rules and regulations of Company in connection therewith, whether the same involves matters of artistic taste and judgment.",
  'credit': 'Provided that Performer appears recognizably in the Picture as released in the Role, Performer shall be accorded credit and Company shall have the right to accord Performer credit in accordance with the terms and provisions of this Paragraph 4.',
  'deliverables': 'acting services in the theatrical motion picture currently entitled "The Invite"',
  'department': nan,
  'dept': nan,
  'etag': nan,
  'extensions': nan,
  'file_id': 2019256737318,
  'file_version': {'id': nan},
  'finalDraftCompensation': nan,
  'finalDraftPeriodWeeks': nan,
  'firstDraftCompensation1': nan,
  'firstDraftPeriodWeeks': nan,
  'grossBudget': nan,
  'initialoption': nan,
  'initialoptionstartdate': nan,
  'keydates': 'February 17, 2025, April 7, 2025, April 21, 2025',
  'name': nan,
  'netBudget': nan,
  'optionalPolishCompensation': nan,
  'optionalPolishPeriodWeeks': nan,
  'optionalRewriteCompensation': nan,
  'optionalRewritePeriodWeeks': nan,
  'optionstatus': nan,
  'parties': 'Invite Productions, Inc. and The Wilde Company for the services of Olivia Wilde',
  'postweeksactualfinish': nan,
  'postweeksactualstart': nan,
  'postweeksscheduledfinish': nan,
  'postweeksscheduledstart': nan,
  'project': 'The Invite',
  'projectname': nan,
  'purchaseprice': nan,
  'readingPeriodPeriodWeeks': nan,
  'remainingSpend': nan,
  'rightsholder': nan,
  'sequence_id': nan,
  'sha1': nan,
  'shootdateactualfinish': nan,
  'shootdateactualstart': nan,
  'shootdatescheduledfinish': nan,
  'shootdatescheduledstart': nan,
  'spendToDate': nan,
  'type': nan,
  'updated_time': datetime.datetime(2025, 10, 31, 10, 13, 42, 993000),
  'periodending': nan,
  'projecttitle': nan,
  'ap_id': 'F_2025_00055'},
 {'_id': '708c8c19-544f-4854-848b-a01ad7cb60c1',
  'box_canEdit': True,
  'box_id': '708c8c19-544f-4854-848b-a01ad7cb60c1',
  'box_parent': 'file_2016001857515',
  'box_scope': 'enterprise_1353798051',
  'box_template': 'optionsmetadata',
  'box_type': 'optionsmetadata-2e7c9f5c-8b51-469f-984a-50383e9f3d9a',
  'box_typeVersion': 2,
  'box_version': 1,
  'compensation': nan,
  'contingencyBudget': nan,
  'contingencyRemaining': nan,
  'contingencySpendToDate': nan,
  'control': nan,
  'credit': nan,
  'deliverables': nan,
  'department': nan,
  'dept': 'film',
  'etag': nan,
  'extensions': 'an additional eighteen (18) month period',
  'file_id': 2016001857515,
  'file_version': {'id': nan},
  'finalDraftCompensation': nan,
  'finalDraftPeriodWeeks': nan,
  'firstDraftCompensation1': nan,
  'firstDraftPeriodWeeks': nan,
  'grossBudget': nan,
  'initialoption': 'Twenty Thousand Dollars ($20,000)',
  'initialoptionstartdate': 'October 21, 2021',
  'keydates': nan,
  'name': nan,
  'netBudget': nan,
  'optionalPolishCompensation': nan,
  'optionalPolishPeriodWeeks': nan,
  'optionalRewriteCompensation': nan,
  'optionalRewritePeriodWeeks': nan,
  'optionstatus': 'Option',
  'parties': nan,
  'postweeksactualfinish': nan,
  'postweeksactualstart': nan,
  'postweeksscheduledfinish': nan,
  'postweeksscheduledstart': nan,
  'project': 'Sentimental (a/k/a "The People Upstairs")',
  'projectname': nan,
  'purchaseprice': 200000.0,
  'readingPeriodPeriodWeeks': nan,
  'remainingSpend': nan,
  'rightsholder': 'Castelao Pictures, SLU',
  'sequence_id': nan,
  'sha1': nan,
  'shootdateactualfinish': nan,
  'shootdateactualstart': nan,
  'shootdatescheduledfinish': nan,
  'shootdatescheduledstart': nan,
  'spendToDate': nan,
  'type': 'motion picture',
  'updated_time': datetime.datetime(2025, 10, 31, 10, 13, 42, 993000),
  'periodending': nan,
  'projecttitle': nan,
  'ap_id': 'F_2025_00055'}]

In [161]:
for id in ba_id_list:
    assign_project_id("BA_Metadata", id, 'F_2025_00008')