In [1]:
## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [2]:
db = client['InDevelopment']

collection = db['box_metadata']

In [3]:
docs = collection.find({
    'templates.writeragreement': {
        '$exists': True
    }
}
)

In [4]:
import pandas as pd

df = pd.DataFrame(docs)

df.head(2).to_clipboard()

In [5]:
client.close()

In [6]:
df.head(10)

,_id,canonical,filename,hub_id,templates,updated_time,summary
0,2119975951128,"{'owner': 'BA', 'division': 'Film', 'hub_id': ...",02a. INVITE - Writing Agreement - FE.pdf,828769775,"{'folderMeta': {'owner': 'BA', 'division': 'Fi...",2026-03-03 10:24:58.138,- Engagement & deliverables: West 150 Producti...
1,2052613323635,"{'owner': 'BA', 'division': 'Film', 'hub_id': ...",American Jewel_Writer Agmt (J. Tolentino)_v2cl...,857713278,"{'folderMeta': {'owner': 'BA', 'division': 'Fi...",2026-03-03 10:24:58.138,"- Parties, date and scope: Memorandum dated Oc..."
2,2052622240787,"{'owner': 'BA', 'division': 'Film', 'hub_id': ...",CustomOfTheCountry_WR2_Tolentino_FE.pdf,857713278,"{'folderMeta': {'owner': 'BA', 'division': 'Fi...",2026-03-03 10:24:58.138,"- Agreement between STORYBUILDERS, LLC and wri..."

In [7]:
options_df = pd.json_normalize(df["templates"].apply(lambda t: t.get("writeragreement", {})))
options_df = options_df.dropna(subset='hub_id')

In [8]:
data = df.join(options_df, how="left", lsuffix="_df")
data = data.drop("hub_id_df", axis=1)

In [9]:
data

,_id,canonical,filename,templates,updated_time,summary,projectname,guaranteedStepsAndFees,optionalStepsAndFees,credit,contingentComp,creditbasedBonus,deliveryAndTiming,writerNames,expensesAndTravel,hub_id
0,2119975951128,"{'owner': 'BA', 'division': 'Film', 'hub_id': ...",02a. INVITE - Writing Agreement - FE.pdf,"{'folderMeta': {'owner': 'BA', 'division': 'Fi...",2026-03-03 10:24:58.138,- Engagement & deliverables: West 150 Producti...,The People Upstairs,"For the First Draft and Final Draft, the total...","Optional Rewrite: $50,000 (50% on commencement...","Governed by WGA Basic Agreement. Form, placeme...",Producer's Share of Net Proceeds: If Sole Scre...,"Sole Credit Bonus: 2.5% of the ""Ingoing Direct...","First Draft: 12 weeks writing, 4 weeks reading...",Will McCormack & Rashida Jones,If required to render services >50 miles from ...,828769775
1,2052613323635,"{'owner': 'BA', 'division': 'Film', 'hub_id': ...",American Jewel_Writer Agmt (J. Tolentino)_v2cl...,"{'folderMeta': {'owner': 'BA', 'division': 'Fi...",2026-03-03 10:24:58.138,"- Parties, date and scope: Memorandum dated Oc...",American Jewel,"Rewrite: $52,544.65",NaN,,NaN,,Writing Period: 8 weeks,Jia Tolentino,,857713278
2,2052622240787,"{'owner': 'BA', 'division': 'Film', 'hub_id': ...",CustomOfTheCountry_WR2_Tolentino_FE.pdf,"{'folderMeta': {'owner': 'BA', 'division': 'Fi...",2026-03-03 10:24:58.138,"- Agreement between STORYBUILDERS, LLC and wri...",Custom of the Country (American Jewel),"First Draft ($200,000)","Rewrite ($100,000), 2nd Rewrite ($75,000), Pol...",Determined by WGA,NaN,"Sole Credit: $550,000 less all writing fees pa...","First draft: Writing: 12 weeks, Reading: 4 wee...",Jia Tolentino,NaN,857713278

In [10]:
data.columns = (
    data.columns
      .str.lower()
      .str.strip()
      .str.replace(r"\s+", "_", regex=True)   # spaces -> underscore
      .str.replace(r"[^0-9a-zA-Z_]", "", regex=True)  # optional: remove weird chars
      + "_box_wt"
)

In [11]:
data

,_id_box_wt,canonical_box_wt,filename_box_wt,templates_box_wt,updated_time_box_wt,summary_box_wt,projectname_box_wt,guaranteedstepsandfees_box_wt,optionalstepsandfees_box_wt,credit_box_wt,contingentcomp_box_wt,creditbasedbonus_box_wt,deliveryandtiming_box_wt,writernames_box_wt,expensesandtravel_box_wt,hub_id_box_wt
0,2119975951128,"{'owner': 'BA', 'division': 'Film', 'hub_id': ...",02a. INVITE - Writing Agreement - FE.pdf,"{'folderMeta': {'owner': 'BA', 'division': 'Fi...",2026-03-03 10:24:58.138,- Engagement & deliverables: West 150 Producti...,The People Upstairs,"For the First Draft and Final Draft, the total...","Optional Rewrite: $50,000 (50% on commencement...","Governed by WGA Basic Agreement. Form, placeme...",Producer's Share of Net Proceeds: If Sole Scre...,"Sole Credit Bonus: 2.5% of the ""Ingoing Direct...","First Draft: 12 weeks writing, 4 weeks reading...",Will McCormack & Rashida Jones,If required to render services >50 miles from ...,828769775
1,2052613323635,"{'owner': 'BA', 'division': 'Film', 'hub_id': ...",American Jewel_Writer Agmt (J. Tolentino)_v2cl...,"{'folderMeta': {'owner': 'BA', 'division': 'Fi...",2026-03-03 10:24:58.138,"- Parties, date and scope: Memorandum dated Oc...",American Jewel,"Rewrite: $52,544.65",NaN,,NaN,,Writing Period: 8 weeks,Jia Tolentino,,857713278
2,2052622240787,"{'owner': 'BA', 'division': 'Film', 'hub_id': ...",CustomOfTheCountry_WR2_Tolentino_FE.pdf,"{'folderMeta': {'owner': 'BA', 'division': 'Fi...",2026-03-03 10:24:58.138,"- Agreement between STORYBUILDERS, LLC and wri...",Custom of the Country (American Jewel),"First Draft ($200,000)","Rewrite ($100,000), 2nd Rewrite ($75,000), Pol...",Determined by WGA,NaN,"Sole Credit: $550,000 less all writing fees pa...","First draft: Writing: 12 weeks, Reading: 4 wee...",Jia Tolentino,NaN,857713278

In [12]:
data.columns

Index(['_id_box_wt', 'canonical_box_wt', 'filename_box_wt', 'templates_box_wt',
       'updated_time_box_wt', 'summary_box_wt', 'projectname_box_wt',
       'guaranteedstepsandfees_box_wt', 'optionalstepsandfees_box_wt',
       'credit_box_wt', 'contingentcomp_box_wt', 'creditbasedbonus_box_wt',
       'deliveryandtiming_box_wt', 'writernames_box_wt',
       'expensesandtravel_box_wt', 'hub_id_box_wt'],
      dtype='object')

In [13]:
export_data_cols = ['_id_box_wt',  'filename_box_wt',
      'summary_box_wt', 'projectname_box_wt',
       'guaranteedstepsandfees_box_wt', 'optionalstepsandfees_box_wt',
       'credit_box_wt', 'contingentcomp_box_wt', 'creditbasedbonus_box_wt',
       'deliveryandtiming_box_wt', 'writernames_box_wt',
       'expensesandtravel_box_wt', 'hub_id_box_wt']

In [14]:
data_export= data[export_data_cols]


data_export['updated_time_box_ot']

In [15]:
stop

NameError: name 'stop' is not defined

In [22]:
data_export = data_export.fillna("")

In [23]:
data_export = data_export.set_index("_id_box_wt")
data_export = data_export.reset_index()

In [24]:
data_export_final = [data_export.columns.tolist()] + data_export.values.tolist()

In [25]:
data_export_final

[['_id_box_wt',
  'filename_box_wt',
  'summary_box_wt',
  'projectname_box_wt',
  'guaranteedstepsandfees_box_wt',
  'optionalstepsandfees_box_wt',
  'credit_box_wt',
  'contingentcomp_box_wt',
  'creditbasedbonus_box_wt',
  'deliveryandtiming_box_wt',
  'writernames_box_wt',
  'expensesandtravel_box_wt',
  'hub_id_box_wt'],
 ['2119975951128',
  '02a. INVITE - Writing Agreement - FE.pdf',
  '- Engagement & deliverables: West 150 Productions engaged Will McCormack and Rashida Jones (through their lenders) to write an English-language screenplay based on the Spanish film Sentimental — guaranteed deliverables are a First Draft and a Final Draft, with two company options (one rewrite, one polish); detailed delivery schedules, reading periods and availability/deferral rules apply.\n\n- Compensation & contingent pay: Fixed fee total $250,000 (First Draft $150,000; Final Draft $100,000) with optional rewrite ($50,000) and polish ($35,000); payments split 50/50 to each lender. Additional contingent compensation includes credit bonuses (sole/shared screenplay credit), various backend/net-proceeds or premium-streamer buyouts, and sequel/remake/TV royalty schedules, subject to credit and production conditions.\n\n- Rights, control & protections: Company receives exclusive, perpetual ownership of all materials as work-made-for-hire and broad exploitation rights; credit governed by the WGA; Company controls changes, publicity, insurance, indemnities, suspension/termination (including force majeure and disability), assignment rules, and other standard legal and warranty provisions.',
  'The People Upstairs',
  'For the First Draft and Final Draft, the total sum of Two Hundred Fifty Thousand Dollars ($250,000). Payable as: $150,000 for First Draft (50% upon commencement, 50% upon delivery) and $100,000 for Final Draft (50% upon commencement, 50% upon delivery).',
  'Optional Rewrite: $50,000 (50% on commencement, 50% upon delivery). Optional Polish: $35,000 (50% on commencement, 50% upon delivery).',
  'Governed by WGA Basic Agreement. Form, placement, size, duration, and other matters determined by Company in its sole discretion, subject to WGA Agreement. Company to contractually obligate domestic distributor and use reasonable efforts for other licensees/assignees to comply.',
  'Producer\'s Share of Net Proceeds: If Sole Screenplay Credit, 7.5% of 100% of "Producer\'s Share of Net Proceeds" (no less than 50% of "Adjusted Gross Proceeds"). If Shared Screenplay Credit, 3.5% of 100% of "Producer\'s Share of Net Proceeds".\nMajor or Mini-Major Studio / Major Independent: If Sole Screenplay Credit, 7.5% of 100% of "Net Proceeds". If Shared Screenplay Credit, 3.5% of 100% of "Net Proceeds".\nPremium Streaming Platform (Streamer Buyout for Sole Screenplay Credit, half for Shared Screenplay Credit):\n- Budget $10,000,000 and under: $35,000\n- Budget $10,000,001 - $15,000,000: $50,000\n- Budget $15,000,001 - $20,000,000: $75,000\n- Budget $20,000,001 - $30,000,000: $100,000\n- Budget $30,000,001 and higher: $150,000',
  'Sole Credit Bonus: 2.5% of the "Ingoing Direct Budget" of the Picture, with a floor of $250,000 and a ceiling of $500,000. Ceiling increases based on budget: $20M budget -> $600,000; $30M -> $700,000; $40M -> $800,000; $50M -> $900,000; $60M -> $1,000,000. Shared Credit Bonus: One-half of the applicable Sole Credit Bonus.',
  "First Draft: 12 weeks writing, 4 weeks reading. Final Draft: 8 weeks writing, 4 weeks reading. Optional Rewrite: 6 weeks writing, 3 weeks reading. Optional Polish: 4 weeks writing. Writer's services are exclusive during writing periods and non-exclusive during reading periods. Company may defer services for up to 12 months, tolled for prior commitments.",
  'Will McCormack & Rashida Jones',
  'If required to render services >50 miles from residence: business-class round-trip air transportation, exclusive ground transportation (if applicable), first-class accommodations, and WGA per diems. If 14+ consecutive days at Location, business-class round-trip air transportation for one companion (if-used basis). If Location is not a major city, full-size fully insured rental car and reimbursement for parking/gas.',
  '828769775'],
 ['2052613323635',
  'American Jewel_Writer Agmt (J. Tolentino)_v2cln_JT.pdf',
  '- Parties, date and scope: Memorandum dated October 10, 2025 between Freddie Sportello, LLC (Company) and My Large Adult LLC (Lender) for the writing services of Jia Tolentino (Writer) to produce a rewrite of material based on Edith Wharton’s "Custom of the Country" for the motion picture titled "AMERICAN JEWEL."\n\n- Compensation and delivery: Guaranteed fee of $52,544.65 payable in two installments (half on start, half on delivery); an 8-week writing period (time is of the essence); deliveries must follow Company’s Script Formatting Policy and be made to Company designees at a specified West Hollywood address.\n\n- Rights, obligations and dispute rules: Writer’s work is assigned to Company as work-for-hire (with broad ownership/assignment, warranties including no AI use, confidentiality, publicity controls, indemnities, WGA-governed credit and fringe obligations), with disputes resolved by binding arbitration in Los Angeles (JAMS) and limited remedies for Writer/Lender.',
  'American Jewel ',
  'Rewrite: $52,544.65',
  '',
  '',
  '',
  '',
  'Writing Period: 8 weeks ',
  'Jia Tolentino ',
  '',
  '857713278'],
 ['2052622240787',
  'CustomOfTheCountry_WR2_Tolentino_FE.pdf',
  '- Agreement between STORYBUILDERS, LLC and writer Jia Tolentino (dated May 15, 2020) engaging Tolentino to adapt Edith Wharton’s novel "Custom of the Country" into a feature screenplay, replacing a prior writer agreement and incorporating exhibits (Writer’s Certificate, Annotation Guide, Standard Terms and Rider).\n\n- Compensation, delivery and credit: guaranteed $200,000 for the First Draft (paid half on commencement, half on delivery); optional rewrite/polish steps with additional fees ($100k, $75k, $50k) if exercised; writing and reading periods (First Draft: 12-week write / 4-week read; shorter periods for rewrites/polish); major credit bonus structure (up to $550,000 sole credit pro rata) and various passive/sequel/remake/TV payments described.\n\n- Rights, warranties and protections: Tolentino’s work is treated as work-made-for-hire with Company owning all rights worldwide in perpetuity (broad assignment and exploitation rights); standard warranties, indemnities, confidentiality, dispute resolution by binding arbitration in Los Angeles under California law, Guild compliance, and Rider modifications to several Standard Terms.',
  'Custom of the Country (American Jewel) ',
  'First Draft ($200,000)',
  'Rewrite ($100,000), 2nd Rewrite ($75,000), Polish ($50,000)',
  'Determined by WGA ',
  '',
  'Sole Credit: $550,000 less all writing fees paid; Shared Credit: 50% of sole credit bonus ',
  'First draft: Writing: 12 weeks, Reading: 4 weeks; Optional Rewrite: Writing period: 8 Weeks, Reading period: 4 weeks; 2nd Optional Rewrite: Writing Period: 6 weeks, Reading Period: 4 weeks; Optional Polish: Writing period 3 weeks ',
  'Jia Tolentino ',
  '',
  '857713278']]

In [26]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# Step 1: Define the scope
scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]

# Step 2: Load credentials
creds = ServiceAccountCredentials.from_json_keyfile_name("ultra-sound-463216-c2-0e076e5f88fe.json", scope)

# Step 3: Authorize and connect
client = gspread.authorize(creds)

# Step 4: Open sheet by URL
sheet_url = "https://docs.google.com/spreadsheets/d/1PaAQEAJcTupLNgvTLaawyWPKOfIrUFAQf-WiUnZMbxY/edit?gid=25505532#gid=25505532"
spreadsheet = client.open_by_url(sheet_url)

# Optional: Access specific sheet/tab
sheet = spreadsheet.worksheet("box_writers_metadata")  # or spreadsheet.worksheet("SheetName")

In [27]:
# Example: Read data
sheet.clear()

{'spreadsheetId': '1PaAQEAJcTupLNgvTLaawyWPKOfIrUFAQf-WiUnZMbxY',
 'clearedRange': 'box_writers_metadata!A1:Z1000'}

In [28]:
sheet.update(data_export_final)

{'spreadsheetId': '1PaAQEAJcTupLNgvTLaawyWPKOfIrUFAQf-WiUnZMbxY',
 'updatedRange': 'box_writers_metadata!A1:M4',
 'updatedRows': 4,
 'updatedColumns': 13,
 'updatedCells': 52}