In [1]:
## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [2]:
db = client['InDevelopment']

collection = db['box_metadata']

In [3]:
docs = collection.find({
    'templates.optionsmetadata': {
        '$exists': True
    }
}
)

In [4]:
import pandas as pd

df = pd.DataFrame(docs)

In [5]:
df.head(2).to_clipboard()

In [6]:
client.close()

In [7]:
df.head(10)

,_id,canonical,filename,hub_id,templates,updated_time,summary
0,2119884021444,"{'owner': 'BA', 'division': 'Film', 'hub_id': ...",Even the Losers_Option Purchase Agmt (Survival...,857711298,"{'folderMeta': {'owner': 'BA', 'division': 'Fi...",2026-03-04 06:35:03.187,"- Company pays $40,000 option (15 months) with..."
1,2119977662134,"{'owner': 'BA', 'division': 'Film', 'hub_id': ...",Invite.Option Purchase Agreement.Side Letter_F...,828769775,"{'folderMeta': {'owner': 'BA', 'division': 'Fi...",2026-03-04 06:35:03.187,"- On option exercise Owner receives $215,623.3..."

In [8]:
options_df = pd.json_normalize(df["templates"].apply(lambda t: t.get("optionsmetadata", {})))
options_df = options_df.dropna(subset='hub_id')
options_df

,dept,dealspecificnotes,initialoptionstartdate,initialoption,extensions,currentoptiontermexpirationdate,rightsholder,currentstatus,optionstatus,project,purchaseprice,type,hub_id
0,Film,"The Initial Option Payment of $40,000 shall be...",2023-12-15,"Forty Thousand US Dollars ($40,000)","First Extension Period: 12 months for $30,000....",15 months after satisfaction of Conditions Pre...,Lanier Management LLC; Checkered Flag Media LLC,Agreement completed,Option exercised,Survival of the Fastest,350000.0,OPTION/PURCHASE AGREEMENT,857711298
1,NaN,"Side Letter dated April 2, 2025, modifying the...",2022-07-08,NaN,NaN,NaN,"Castelao Pictures, SLU",Active,exercised,The Invite,215623.3,Option/Purchase Agreement,828769775

In [9]:
data = df.join(options_df, how="left", lsuffix="_df")
data = data.drop("hub_id_df", axis=1)

In [10]:
data

,_id,canonical,filename,templates,updated_time,summary,dept,dealspecificnotes,initialoptionstartdate,initialoption,extensions,currentoptiontermexpirationdate,rightsholder,currentstatus,optionstatus,project,purchaseprice,type,hub_id
0,2119884021444,"{'owner': 'BA', 'division': 'Film', 'hub_id': ...",Even the Losers_Option Purchase Agmt (Survival...,"{'folderMeta': {'owner': 'BA', 'division': 'Fi...",2026-03-04 06:35:03.187,"- Company pays $40,000 option (15 months) with...",Film,"The Initial Option Payment of $40,000 shall be...",2023-12-15,"Forty Thousand US Dollars ($40,000)","First Extension Period: 12 months for $30,000....",15 months after satisfaction of Conditions Pre...,Lanier Management LLC; Checkered Flag Media LLC,Agreement completed,Option exercised,Survival of the Fastest,350000.0,OPTION/PURCHASE AGREEMENT,857711298
1,2119977662134,"{'owner': 'BA', 'division': 'Film', 'hub_id': ...",Invite.Option Purchase Agreement.Side Letter_F...,"{'folderMeta': {'owner': 'BA', 'division': 'Fi...",2026-03-04 06:35:03.187,"- On option exercise Owner receives $215,623.3...",NaN,"Side Letter dated April 2, 2025, modifying the...",2022-07-08,NaN,NaN,NaN,"Castelao Pictures, SLU",Active,exercised,The Invite,215623.3,Option/Purchase Agreement,828769775

In [11]:
data.columns = (
    data.columns
      .str.lower()
      .str.strip()
      .str.replace(r"\s+", "_", regex=True)   # spaces -> underscore
      .str.replace(r"[^0-9a-zA-Z_]", "", regex=True)  # optional: remove weird chars
      + "_box_ot"
)

In [12]:
data

,_id_box_ot,canonical_box_ot,filename_box_ot,templates_box_ot,updated_time_box_ot,summary_box_ot,dept_box_ot,dealspecificnotes_box_ot,initialoptionstartdate_box_ot,initialoption_box_ot,extensions_box_ot,currentoptiontermexpirationdate_box_ot,rightsholder_box_ot,currentstatus_box_ot,optionstatus_box_ot,project_box_ot,purchaseprice_box_ot,type_box_ot,hub_id_box_ot
0,2119884021444,"{'owner': 'BA', 'division': 'Film', 'hub_id': ...",Even the Losers_Option Purchase Agmt (Survival...,"{'folderMeta': {'owner': 'BA', 'division': 'Fi...",2026-03-04 06:35:03.187,"- Company pays $40,000 option (15 months) with...",Film,"The Initial Option Payment of $40,000 shall be...",2023-12-15,"Forty Thousand US Dollars ($40,000)","First Extension Period: 12 months for $30,000....",15 months after satisfaction of Conditions Pre...,Lanier Management LLC; Checkered Flag Media LLC,Agreement completed,Option exercised,Survival of the Fastest,350000.0,OPTION/PURCHASE AGREEMENT,857711298
1,2119977662134,"{'owner': 'BA', 'division': 'Film', 'hub_id': ...",Invite.Option Purchase Agreement.Side Letter_F...,"{'folderMeta': {'owner': 'BA', 'division': 'Fi...",2026-03-04 06:35:03.187,"- On option exercise Owner receives $215,623.3...",NaN,"Side Letter dated April 2, 2025, modifying the...",2022-07-08,NaN,NaN,NaN,"Castelao Pictures, SLU",Active,exercised,The Invite,215623.3,Option/Purchase Agreement,828769775

In [13]:
data.columns

Index(['_id_box_ot', 'canonical_box_ot', 'filename_box_ot', 'templates_box_ot',
       'updated_time_box_ot', 'summary_box_ot', 'dept_box_ot',
       'dealspecificnotes_box_ot', 'initialoptionstartdate_box_ot',
       'initialoption_box_ot', 'extensions_box_ot',
       'currentoptiontermexpirationdate_box_ot', 'rightsholder_box_ot',
       'currentstatus_box_ot', 'optionstatus_box_ot', 'project_box_ot',
       'purchaseprice_box_ot', 'type_box_ot', 'hub_id_box_ot'],
      dtype='object')

In [14]:
export_data_cols = ['_id_box_ot',  'filename_box_ot', 
      # 'updated_time_box_ot', 
                    'hub_id_box_ot', 
                    'summary_box_ot',
       'project_box_ot', 'dealspecificnotes_box_ot',
       'initialoptionstartdate_box_ot', 'rightsholder_box_ot',
       'currentstatus_box_ot', 'optionstatus_box_ot', 'purchaseprice_box_ot',
       'type_box_ot']

In [15]:
data_export= data[export_data_cols]


data_export['updated_time_box_ot']

In [16]:
stop

NameError: name 'stop' is not defined

In [18]:
data_export = data_export.fillna("")

In [19]:
data_export = data_export.set_index("_id_box_ot")
data_export = data_export.reset_index()

In [20]:
data_export_final = [data_export.columns.tolist()] + data_export.values.tolist()

In [21]:
data_export_final

[['_id_box_ot',
  'filename_box_ot',
  'hub_id_box_ot',
  'summary_box_ot',
  'project_box_ot',
  'dealspecificnotes_box_ot',
  'initialoptionstartdate_box_ot',
  'rightsholder_box_ot',
  'currentstatus_box_ot',
  'optionstatus_box_ot',
  'purchaseprice_box_ot',
  'type_box_ot'],
 ['2119884021444',
  'Even the Losers_Option Purchase Agmt (Survival of the Fastest)_FE (5.15.24).pdf',
  '857711298',
  '- Company pays $40,000 option (15 months) with optional extensions ($30,000 and $35,000) to secure exclusive rights.  \n- Purchase price varies: theatrical 3% of net budget ($350k–$650k), MOW $125k–$250k, plus 5% net receipts participation.  \n- Company obtains perpetual worldwide rights, producer/consulting fees (e.g., $110k producer, $35k consulting), credits, indemnities and strict confidentiality.',
  'Survival of the Fastest',
  'The Initial Option Payment of $40,000 shall be deemed an advance against, and shall be deductible from, the Purchase Price. The Purchase Price Floor is $350,000 and the Purchase Price Ceiling is $650,000 for a Theatrical Film. If the Picture is an MOW for a Tier 1 Buyer, the Purchase Price is $250,000; for a Tier 2 Buyer, $125,000. If the Picture is a Mini-Series or Episodic Series for a Tier 1 Buyer, the Purchase Price is $150,000; for a Tier 2 Buyer, $112,500.',
  '2023-12-15',
  'Lanier Management LLC; Checkered Flag Media LLC',
  'Agreement completed',
  'Option exercised',
  350000.0,
  'OPTION/PURCHASE AGREEMENT'],
 ['2119977662134',
  'Invite.Option Purchase Agreement.Side Letter_FullyX.pdf',
  '828769775',
  "- On option exercise Owner receives $215,623.30 (2% of $11,781,165 minus initial option payment).  \n- Owner receives backend equal to 2% of Producer's Share of AGP, including any more favorable Producer’s Share definitions.  \n- Exhibit A deducts specific costs, repays financing and equity (plus 20% premium, 10% overhead), then splits AGP 50/50.",
  'The Invite',
  'Side Letter dated April 2, 2025, modifying the original Option/Purchase Agreement. The purchase price is 2% of the "In-Going Direct Budget" ($11,781,165) less the Initial Option Payment. Owner is entitled to 2% of 100% of Producer\'s Share of AGP.',
  '2022-07-08',
  'Castelao Pictures, SLU',
  'Active',
  'exercised',
  215623.3,
  'Option/Purchase Agreement']]

In [22]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# Step 1: Define the scope
scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]

# Step 2: Load credentials
creds = ServiceAccountCredentials.from_json_keyfile_name("ultra-sound-463216-c2-0e076e5f88fe.json", scope)

# Step 3: Authorize and connect
client = gspread.authorize(creds)

# Step 4: Open sheet by URL
sheet_url = "https://docs.google.com/spreadsheets/d/1PaAQEAJcTupLNgvTLaawyWPKOfIrUFAQf-WiUnZMbxY/edit?gid=25505532#gid=25505532"
spreadsheet = client.open_by_url(sheet_url)

# Optional: Access specific sheet/tab
sheet = spreadsheet.worksheet("box_options_metadata")  # or spreadsheet.worksheet("SheetName")

In [23]:
# Example: Read data
sheet.clear()

{'spreadsheetId': '1PaAQEAJcTupLNgvTLaawyWPKOfIrUFAQf-WiUnZMbxY',
 'clearedRange': 'box_options_metadata!A1:Z1000'}

In [24]:
sheet.update(data_export_final)

{'spreadsheetId': '1PaAQEAJcTupLNgvTLaawyWPKOfIrUFAQf-WiUnZMbxY',
 'updatedRange': 'box_options_metadata!A1:L3',
 'updatedRows': 3,
 'updatedColumns': 12,
 'updatedCells': 36}