In [1]:
import os
from dotenv import load_dotenv
import requests

# Load from cred.env
load_dotenv("/Users/dougs/Documents/GitHub/BOX-API-Testing/cred.env")
client_id = os.getenv("client_id")
client_secret = os.getenv("client_secret")
DEV_TOKEN = ""
redirect_uri = 'http://localhost/'
enterprise_id = os.getenv("box_eid")
user_id = '45979511044' #doug UID

In [2]:
enterprise_id

'1353798051'

In [3]:
# if using enterprise_id, app needs to be added as a service account


url = "https://api.box.com/oauth2/token"
data = {
    "grant_type": "client_credentials",
    "client_id": client_id,
    "client_secret": client_secret,
    "box_subject_type": "user",  # could also be 'enterprise'
    "box_subject_id": user_id # could be enterprise_id
}

resp = requests.post(url, data=data)
resp.raise_for_status()
token_data = resp.json()

access_token = token_data["access_token"]
print("Access Token:", access_token)

Access Token: BOV4J7Ld5Ekru73Ue1m5JU2lX0EmkG7L

In [4]:
import requests

url = "https://api.box.com/2.0/hubs"

headers = {
    "Authorization": f"Bearer {access_token}",
    "Content-Type": "application/json",
    "Box-Version": "2025.0",   # important for hubs
}



resp = requests.get(url, headers=headers)
hub_data = resp.json()
print(resp.raise_for_status())

None

In [5]:
url = "https://api.box.com/2.0/users/me"
resp = requests.get(url, headers=headers)
print(resp.json())

{'type': 'user', 'id': '45979511044', 'name': 'Doug Sack', 'login': 'dougs@annapurna.com', 'created_at': '2025-10-14T13:19:55-07:00', 'modified_at': '2026-03-09T10:41:40-07:00', 'language': 'en', 'timezone': 'America/Los_Angeles', 'space_amount': 10737418240, 'space_used': 6556797473, 'max_upload_size': 536870912000, 'status': 'active', 'job_title': '', 'phone': '', 'address': '', 'avatar_url': 'https://annapurna.app.box.com/api/avatar/large/45979511044', 'notification_email': None}

In [6]:
hub_data

{'entries': [{'id': '814974530',
   'type': 'hubs',
   'title': 'Foo (Animation)',
   'description': 'AP_ID: 814974530',
   'created_at': '2026-01-27T21:04:08.000Z',
   'updated_at': '2026-03-04T14:34:04.000Z',
   'created_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'updated_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'view_count': 76,
   'is_ai_enabled': True,
   'is_collaboration_restricted_to_enterprise': True,
   'can_non_owners_invite': True,
   'can_shared_link_be_created': True,
   'can_public_shared_link_be_created': False,
   'copy_hub_access': 'all'},
  {'id': '828769775',
   'type': 'hubs',
   'title': 'The Invite (Film)',
   'description': 'AP_ID: 828769775',
   'created_at': '2026-02-03T19:20:19.000Z',
   'updated_at': '2026-02-18T16:39:45.000Z',
   'created_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'updated_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'view_count': 109,
   'is_ai_enabled': True,
   'is_collaboration_restricted_to_enterprise': True,
   'can_non_owners_invite': True,
   'can_shared_link_be_created': True,
   'can_public_shared_link_be_created': False,
   'copy_hub_access': 'all'},
  {'id': '857708672',
   'type': 'hubs',
   'title': 'Control (TV)',
   'description': 'AP_ID: 857708672',
   'created_at': '2026-02-17T20:13:58.000Z',
   'updated_at': '2026-02-18T16:38:50.000Z',
   'created_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'updated_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'view_count': 14,
   'is_ai_enabled': True,
   'is_collaboration_restricted_to_enterprise': True,
   'can_non_owners_invite': True,
   'can_shared_link_be_created': True,
   'can_public_shared_link_be_created': False,
   'copy_hub_access': 'all'},
  {'id': '857711298',
   'type': 'hubs',
   'title': 'Even The Losers (Film)',
   'description': 'AP_ID: 857711298',
   'created_at': '2026-02-17T20:14:24.000Z',
   'updated_at': '2026-03-03T23:12:57.000Z',
   'created_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'updated_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'view_count': 33,
   'is_ai_enabled': True,
   'is_collaboration_restricted_to_enterprise': True,
   'can_non_owners_invite': True,
   'can_shared_link_be_created': True,
   'can_public_shared_link_be_created': False,
   'copy_hub_access': 'all'},
  {'id': '857713278',
   'type': 'hubs',
   'title': 'American Jewel (Film)',
   'description': 'AP_ID: 857713278',
   'created_at': '2026-02-17T20:14:41.000Z',
   'updated_at': '2026-02-23T17:12:12.000Z',
   'created_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'updated_by': {'id': '18649155298',
    'type': 'user',
    'name': 'Skye Caruso',
    'login': 'skyec@annapurna.com'},
   'view_count': 39,
   'is_ai_enabled': True,
   'is_collaboration_restricted_to_enterprise': True,
   'can_non_owners_invite': True,
   'can_shared_link_be_created': True,
   'can_public_shared_link_be_created': False,
   'copy_hub_access': 'all'},
  {'id': '881999892',
   'type': 'hubs',
   'title': 'CALL ME DAD (TV)',
   'description': 'AP_ID: 881999892',
   'created_at': '2026-02-26T23:15:54.000Z',
   'updated_at': '2026-02-26T23:16:39.000Z',
   'created_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'updated_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'view_count': 7,
   'is_ai_enabled': True,
   'is_collaboration_restricted_to_enterprise': True,
   'can_non_owners_invite': True,
   'can_shared_link_be_created': True,
   'can_public_shared_link_be_created': False,
   'copy_hub_access': 'all'},
  {'id': '896370380',
   'type': 'hubs',
   'title': 'TEMPLATE PROJECT HUB',
   'description': '',
   'created_at': '2026-03-05T17:33:48.000Z',
   'updated_at': '2026-03-05T17:38:38.000Z',
   'created_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'updated_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'view_count': 8,
   'is_ai_enabled': True,
   'is_collaboration_restricted_to_enterprise': True,
   'can_non_owners_invite': True,
   'can_shared_link_be_created': True,
   'can_public_shared_link_be_created': False,
   'copy_hub_access': 'all'},
  {'id': '905490123',
   'type': 'hubs',
   'title': 'Alan Wake',
   'description': 'test description',
   'created_at': '2026-03-09T19:53:29.000Z',
   'updated_at': '2026-03-09T19:53:29.000Z',
   'created_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'updated_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'view_count': 0,
   'is_ai_enabled': True,
   'is_collaboration_restricted_to_enterprise': True,
   'can_non_owners_invite': True,
   'can_shared_link_be_created': True,
   'can_public_shared_link_be_created': False,
   'copy_hub_access': 'all'},
  {'id': '905492817',
   'type': 'hubs',
   'title': 'Murderland',
   'description': 'test description',
   'created_at': '2026-03-09T19:53:30.000Z',
   'updated_at': '2026-03-09T19:53:30.000Z',
   'created_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'updated_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'view_count': 0,
   'is_ai_enabled': True,
   'is_collaboration_restricted_to_enterprise': True,
   'can_non_owners_invite': True,
   'can_shared_link_be_created': True,
   'can_public_shared_link_be_created': False,
   'copy_hub_access': 'all'},
  {'id': '905495981',
   'type': 'hubs',
   'title': 'Shot for Nothing',
   'description': 'test description',
   'created_at': '2026-03-09T19:53:32.000Z',
   'updated_at': '2026-03-09T19:53:32.000Z',
   'created_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'updated_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'view_count': 0,
   'is_ai_enabled': True,
   'is_collaboration_restricted_to_enterprise': True,
   'can_non_owners_invite': True,
   'can_shared_link_be_created': True,
   'can_public_shared_link_be_created': False,
   'copy_hub_access': 'all'},
  {'id': '905497535',
   'type': 'hubs',
   'title': 'American Spartan',
   'description': 'test description',
   'created_at': '2026-03-09T19:53:33.000Z',
   'updated_at': '2026-03-09T19:53:33.000Z',
   'created_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'updated_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'view_count': 0,
   'is_ai_enabled': True,
   'is_collaboration_restricted_to_enterprise': True,
   'can_non_owners_invite': True,
   'can_shared_link_be_created': True,
   'can_public_shared_link_be_created': False,
   'copy_hub_access': 'all'},
  {'id': '905500587',
   'type': 'hubs',
   'title': 'Soaps',
   'description': 'test description',
   'created_at': '2026-03-09T19:53:34.000Z',
   'updated_at': '2026-03-09T19:53:34.000Z',
   'created_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'updated_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'view_count': 0,
   'is_ai_enabled': True,
   'is_collaboration_restricted_to_enterprise': True,
   'can_non_owners_invite': True,
   'can_shared_link_be_created': True,
   'can_public_shared_link_be_created': False,
   'copy_hub_access': 'all'},
  {'id': '905502854',
   'type': 'hubs',
   'title': 'Ann Lee',
   'description': 'test description',
   'created_at': '2026-03-09T19:53:36.000Z',
   'updated_at': '2026-03-09T19:53:36.000Z',
   'created_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'updated_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'view_count': 0,
   'is_ai_enabled': True,
   'is_collaboration_restricted_to_enterprise': True,
   'can_non_owners_invite': True,
   'can_shared_link_be_created': True,
   'can_public_shared_link_be_created': False,
   'copy_hub_access': 'all'},
  {'id': '905504919',
   'type': 'hubs',
   'title': 'Grind',
   'description': 'test description',
   'created_at': '2026-03-09T19:53:37.000Z',
   'updated_at': '2026-03-09T19:53:37.000Z',
   'created_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'updated_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'view_count': 0,
   'is_ai_enabled': True,
   'is_collaboration_restricted_to_enterprise': True,
   'can_non_owners_invite': True,
   'can_shared_link_be_created': True,
   'can_public_shared_link_be_created': False,
   'copy_hub_access': 'all'},
  {'id': '905507328',
   'type': 'hubs',
   'title': 'Silent Patient',
   'description': 'test description',
   'created_at': '2026-03-09T19:53:38.000Z',
   'updated_at': '2026-03-09T19:53:38.000Z',
   'created_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'updated_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'view_count': 2,
   'is_ai_enabled': True,
   'is_collaboration_restricted_to_enterprise': True,
   'can_non_owners_invite': True,
   'can_shared_link_be_created': True,
   'can_public_shared_link_be_created': False,
   'copy_hub_access': 'all'},
  {'id': '905509963',
   'type': 'hubs',
   'title': 'Norco 80',
   'description': 'test description',
   'created_at': '2026-03-09T19:53:39.000Z',
   'updated_at': '2026-03-09T19:53:39.000Z',
   'created_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'updated_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'view_count': 0,
   'is_ai_enabled': True,
   'is_collaboration_restricted_to_enterprise': True,
   'can_non_owners_invite': True,
   'can_shared_link_be_created': True,
   'can_public_shared_link_be_created': False,
   'copy_hub_access': 'all'},
  {'id': '905512660',
   'type': 'hubs',
   'title': 'Nicole Taylor',
   'description': 'test description',
   'created_at': '2026-03-09T19:53:40.000Z',
   'updated_at': '2026-03-09T19:53:40.000Z',
   'created_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'updated_by': {'id': '45979511044',
    'type': 'user',
    'name': 'Doug Sack',
    'login': 'dougs@annapurna.com'},
   'view_count': 1,
   'is_ai_enabled': True,
   'is_collaboration_restricted_to_enterprise': True,
   'can_non_owners_invite': True,
   'can_shared_link_be_created': True,
   'can_public_shared_link_be_created': False,
   'copy_hub_access': 'all'}],
 'next_marker': None,
 'limit': 30}

In [7]:
hub_list = [x['id'] for x in hub_data['entries'] if x['title']=='Foo (Animation)']
hub_list = [x['id'] for x in hub_data['entries']]

hub_list[0]

'814974530'

In [8]:
hub_list

['814974530',
 '828769775',
 '857708672',
 '857711298',
 '857713278',
 '881999892',
 '896370380',
 '905490123',
 '905492817',
 '905495981',
 '905497535',
 '905500587',
 '905502854',
 '905504919',
 '905507328',
 '905509963',
 '905512660']

In [9]:
import requests

file_dict = {}
folder_list = []
hub_file_dict = {}

for hub in hub_list:
    url = "https://api.box.com/2.0/hub_items"

    headers = {
        "Authorization": f"Bearer {access_token}",
        "Box-Version": "2025.0",   # required for hubs
    }
    
    params = {
        "hub_id": hub,
        "limit": 1000
    }
    
    resp = requests.get(url, headers=headers, params=params)
    resp.raise_for_status()
    
    data = resp.json()
    
    for item in data["entries"]:
        #print(item["type"], item["id"], item["name"])
        if item['type'] =='file':
            file_dict[item["id"]] = item["name"]
            hub_file_dict[item["id"]] = hub
        if item['type'] =='folder':
            folder_list.append(item["id"])

In [10]:
file_dict

{'2041161844567': 'Chris Wedge Deal .xlsx',
 '2041164284871': 'Wedge deal memo Execution.docx',
 '2041165418316': 'FOO Budget_9-11-23 SW.pdf',
 '2052695099974': 'Foo Rewrite 1-12-23_CINESITE.pdf',
 '2153822749844': 'Foo_Cost Report_02.28.26.pdf',
 '2044693703611': 'The Invite_One Liner_Final Actualized_06_02_2025.pdf',
 '2044695313708': 'TI WE 102525 CR.pdf',
 '2044700014987': 'THE INVITE_FNL BUDGET_2025-04-16_20 DYS LA-2 DYS SF_1.pdf',
 '2119974483634': '01a. INVITE - Original Picture Option Purchase - FE.pdf',
 '2119975951128': '02a. INVITE - Writing Agreement - FE.pdf',
 '2119976975079': 'Invite.Olivia_Wilde.Performer_Agreement.execution_FullyX.pdf',
 '2119977220029': 'The Invite_Script_Production Draft_4.29.25 FINAL.pdf',
 '2119977403111': 'Edward_Norton_-_The_Invite_-_Performer_Agreement.FE.pdf',
 '2119977630419': 'The Invite_Uniform Counter for U.S. Distribution Deal.docx',
 '2119977662134': 'Invite.Option Purchase Agreement.Side Letter_FullyX.pdf',
 '2119978724721': 'Invite.Director_Agreement.Olivia_Wilde.execution_FullyX.pdf',
 '2119980865905': 'Invite.Saul_Germaine.Producer_Agreement.execution_FE.pdf',
 '2119983778968': 'Performer_Agreement_-_THE_INVITE_FullyX copy.pdf',
 '2119984237503': 'Invite.Seth Rogen.Performer Agreement_FullyX.pdf',
 '2119987295165': 'Invite.Producer Agreement.FilmNation.2nd.red_JT.doc',
 '2119987573634': 'The Invite_Producer Agmt (D. Permut)_FullyX.pdf',
 '2122991245901': 'THE INVITE - 1.29.26.pdf',
 '2123701194432': 'Invite+GL Memo.gsheet',
 '2123716103309': 'Invite_Comps.gsheet',
 '2123718925623': 'The Invite_Sales Model_$11.5M Net_SplitRights.pdf',
 '2124989574120': 'The Invite_Prelim Calendar_1-31-25.pdf',
 '2124993381364': 'THE INVITE_GL BUDGET TOPSHEET.pdf',
 '2052454427437': 'DEAL REQUEST : CONTROL : Pilot and Back Up Script for Eric Heisserer and Craig Zobel .pdf',
 '2052457545572': 'Control - Craig Zobel - co-story + pilot directing - EP services - 10.9.25 proposed terms.pdf',
 '2052462100258': 'DEAL REQUEST : CONTROL : Pilot and Back Up Script for Eric Heisserer and Craig Zobel .pdf',
 '2052462754937': 'Control - Eric Heisserer - co-story + pilot writing + EP services - 10.9.25 proposed terms.pdf',
 '2131714842889': 'CONTROL - Eric Heisserer -  Script Commitment Proposal 2.11.26.docx',
 '2119879353140': 'Even The Losers - Producer Deal Memo + Cert + Ex AGR + Rider - v9red_JT.pdf',
 '2119884021444': 'Even the Losers_Option Purchase Agmt (Survival of the Fastest)_FE (5.15.24).pdf',
 '2119887403146': 'Even the Losers - Writer Agmt (Singer)_v8 (FullyX).pdf',
 '2041170894718': 'AMERICAN JEWEL_YSF_6.18.2025.pdf',
 '2052597952702': 'AMERICAN JEWEL - Chernin - Producer COE_v2.1red_JT.docx',
 '2052601820798': '*DEAL REQUEST - AMERICAN JEWEL - Yngvild Sve Flikke (Director) & Rachel Sennott (Talent) - 6.3.25.pdf',
 '2052607194571': 'American Jewel_Screenplay_10-24[91].pdf',
 '2052608272404': 'American Jewel 06.16.25 BA TS.pdf',
 '2052610144637': 'CustomOfTheCountry_WR_SennottFlikke.jk - FE.pdf',
 '2052613323635': 'American Jewel_Writer Agmt (J. Tolentino)_v2cln_JT.pdf',
 '2052622240787': 'CustomOfTheCountry_WR2_Tolentino_FE.pdf',
 '2119689359544': 'AMERICAN JEWEL_010826.mmbx.pdf'}

In [11]:
hub_file_dict

{'2041161844567': '814974530',
 '2041164284871': '814974530',
 '2041165418316': '814974530',
 '2052695099974': '814974530',
 '2153822749844': '814974530',
 '2044693703611': '828769775',
 '2044695313708': '828769775',
 '2044700014987': '828769775',
 '2119974483634': '828769775',
 '2119975951128': '828769775',
 '2119976975079': '828769775',
 '2119977220029': '828769775',
 '2119977403111': '828769775',
 '2119977630419': '828769775',
 '2119977662134': '828769775',
 '2119978724721': '828769775',
 '2119980865905': '828769775',
 '2119983778968': '828769775',
 '2119984237503': '828769775',
 '2119987295165': '828769775',
 '2119987573634': '828769775',
 '2122991245901': '828769775',
 '2123701194432': '828769775',
 '2123716103309': '828769775',
 '2123718925623': '828769775',
 '2124989574120': '828769775',
 '2124993381364': '828769775',
 '2052454427437': '857708672',
 '2052457545572': '857708672',
 '2052462100258': '857708672',
 '2052462754937': '857708672',
 '2131714842889': '857708672',
 '2119879353140': '857711298',
 '2119884021444': '857711298',
 '2119887403146': '857711298',
 '2041170894718': '857713278',
 '2052597952702': '857713278',
 '2052601820798': '857713278',
 '2052607194571': '857713278',
 '2052608272404': '857713278',
 '2052610144637': '857713278',
 '2052613323635': '857713278',
 '2052622240787': '857713278',
 '2119689359544': '857713278'}

import requests

url = "https://api.box.com/2.0/hub_items"

headers = {
    "Authorization": f"Bearer {access_token}",
    "Box-Version": "2025.0",   # required for hubs
}

params = {
    "hub_id": hub_list[0],
    "limit": 1000
}

resp = requests.get(url, headers=headers, params=params)
resp.raise_for_status()

data = resp.json()
file_dict = {}
folder_list = []
for item in data["entries"]:
    #print(item["type"], item["id"], item["name"])
    if item['type'] =='file':
        file_dict[item["id"]] = item["name"]
    if item['type'] =='folder':
        folder_list.append(item["id"])

client.hubs.create_hub_v2025_r0(title="test_API", description='TEST TEST')

In [12]:
file_dict

{'2041161844567': 'Chris Wedge Deal .xlsx',
 '2041164284871': 'Wedge deal memo Execution.docx',
 '2041165418316': 'FOO Budget_9-11-23 SW.pdf',
 '2052695099974': 'Foo Rewrite 1-12-23_CINESITE.pdf',
 '2153822749844': 'Foo_Cost Report_02.28.26.pdf',
 '2044693703611': 'The Invite_One Liner_Final Actualized_06_02_2025.pdf',
 '2044695313708': 'TI WE 102525 CR.pdf',
 '2044700014987': 'THE INVITE_FNL BUDGET_2025-04-16_20 DYS LA-2 DYS SF_1.pdf',
 '2119974483634': '01a. INVITE - Original Picture Option Purchase - FE.pdf',
 '2119975951128': '02a. INVITE - Writing Agreement - FE.pdf',
 '2119976975079': 'Invite.Olivia_Wilde.Performer_Agreement.execution_FullyX.pdf',
 '2119977220029': 'The Invite_Script_Production Draft_4.29.25 FINAL.pdf',
 '2119977403111': 'Edward_Norton_-_The_Invite_-_Performer_Agreement.FE.pdf',
 '2119977630419': 'The Invite_Uniform Counter for U.S. Distribution Deal.docx',
 '2119977662134': 'Invite.Option Purchase Agreement.Side Letter_FullyX.pdf',
 '2119978724721': 'Invite.Director_Agreement.Olivia_Wilde.execution_FullyX.pdf',
 '2119980865905': 'Invite.Saul_Germaine.Producer_Agreement.execution_FE.pdf',
 '2119983778968': 'Performer_Agreement_-_THE_INVITE_FullyX copy.pdf',
 '2119984237503': 'Invite.Seth Rogen.Performer Agreement_FullyX.pdf',
 '2119987295165': 'Invite.Producer Agreement.FilmNation.2nd.red_JT.doc',
 '2119987573634': 'The Invite_Producer Agmt (D. Permut)_FullyX.pdf',
 '2122991245901': 'THE INVITE - 1.29.26.pdf',
 '2123701194432': 'Invite+GL Memo.gsheet',
 '2123716103309': 'Invite_Comps.gsheet',
 '2123718925623': 'The Invite_Sales Model_$11.5M Net_SplitRights.pdf',
 '2124989574120': 'The Invite_Prelim Calendar_1-31-25.pdf',
 '2124993381364': 'THE INVITE_GL BUDGET TOPSHEET.pdf',
 '2052454427437': 'DEAL REQUEST : CONTROL : Pilot and Back Up Script for Eric Heisserer and Craig Zobel .pdf',
 '2052457545572': 'Control - Craig Zobel - co-story + pilot directing - EP services - 10.9.25 proposed terms.pdf',
 '2052462100258': 'DEAL REQUEST : CONTROL : Pilot and Back Up Script for Eric Heisserer and Craig Zobel .pdf',
 '2052462754937': 'Control - Eric Heisserer - co-story + pilot writing + EP services - 10.9.25 proposed terms.pdf',
 '2131714842889': 'CONTROL - Eric Heisserer -  Script Commitment Proposal 2.11.26.docx',
 '2119879353140': 'Even The Losers - Producer Deal Memo + Cert + Ex AGR + Rider - v9red_JT.pdf',
 '2119884021444': 'Even the Losers_Option Purchase Agmt (Survival of the Fastest)_FE (5.15.24).pdf',
 '2119887403146': 'Even the Losers - Writer Agmt (Singer)_v8 (FullyX).pdf',
 '2041170894718': 'AMERICAN JEWEL_YSF_6.18.2025.pdf',
 '2052597952702': 'AMERICAN JEWEL - Chernin - Producer COE_v2.1red_JT.docx',
 '2052601820798': '*DEAL REQUEST - AMERICAN JEWEL - Yngvild Sve Flikke (Director) & Rachel Sennott (Talent) - 6.3.25.pdf',
 '2052607194571': 'American Jewel_Screenplay_10-24[91].pdf',
 '2052608272404': 'American Jewel 06.16.25 BA TS.pdf',
 '2052610144637': 'CustomOfTheCountry_WR_SennottFlikke.jk - FE.pdf',
 '2052613323635': 'American Jewel_Writer Agmt (J. Tolentino)_v2cln_JT.pdf',
 '2052622240787': 'CustomOfTheCountry_WR2_Tolentino_FE.pdf',
 '2119689359544': 'AMERICAN JEWEL_010826.mmbx.pdf'}

In [13]:
folder_list

['352234141292',
 '363631088428',
 '352172473734',
 '352175420537',
 '352185733623',
 '350249581731']

In [14]:

for folder in folder_list:

    resp = requests.get(f"https://api.box.com/2.0/folders/{folder}/items", headers=headers)
    resp.raise_for_status()
    folder_data = resp.json()
    
    for file in folder_data['entries']:
    
        file_id = file['id']
        file_dict[file_id] = file['name']

In [15]:
file_dict

{'2041161844567': 'Chris Wedge Deal .xlsx',
 '2041164284871': 'Wedge deal memo Execution.docx',
 '2041165418316': 'FOO Budget_9-11-23 SW.pdf',
 '2052695099974': 'Foo Rewrite 1-12-23_CINESITE.pdf',
 '2153822749844': 'Foo_Cost Report_02.28.26.pdf',
 '2044693703611': 'The Invite_One Liner_Final Actualized_06_02_2025.pdf',
 '2044695313708': 'TI WE 102525 CR.pdf',
 '2044700014987': 'THE INVITE_FNL BUDGET_2025-04-16_20 DYS LA-2 DYS SF_1.pdf',
 '2119974483634': '01a. INVITE - Original Picture Option Purchase - FE.pdf',
 '2119975951128': '02a. INVITE - Writing Agreement - FE.pdf',
 '2119976975079': 'Invite.Olivia_Wilde.Performer_Agreement.execution_FullyX.pdf',
 '2119977220029': 'The Invite_Script_Production Draft_4.29.25 FINAL.pdf',
 '2119977403111': 'Edward_Norton_-_The_Invite_-_Performer_Agreement.FE.pdf',
 '2119977630419': 'The Invite_Uniform Counter for U.S. Distribution Deal.docx',
 '2119977662134': 'Invite.Option Purchase Agreement.Side Letter_FullyX.pdf',
 '2119978724721': 'Invite.Director_Agreement.Olivia_Wilde.execution_FullyX.pdf',
 '2119980865905': 'Invite.Saul_Germaine.Producer_Agreement.execution_FE.pdf',
 '2119983778968': 'Performer_Agreement_-_THE_INVITE_FullyX copy.pdf',
 '2119984237503': 'Invite.Seth Rogen.Performer Agreement_FullyX.pdf',
 '2119987295165': 'Invite.Producer Agreement.FilmNation.2nd.red_JT.doc',
 '2119987573634': 'The Invite_Producer Agmt (D. Permut)_FullyX.pdf',
 '2122991245901': 'THE INVITE - 1.29.26.pdf',
 '2123701194432': 'Invite+GL Memo.gsheet',
 '2123716103309': 'Invite_Comps.gsheet',
 '2123718925623': 'The Invite_Sales Model_$11.5M Net_SplitRights.pdf',
 '2124989574120': 'The Invite_Prelim Calendar_1-31-25.pdf',
 '2124993381364': 'THE INVITE_GL BUDGET TOPSHEET.pdf',
 '2052454427437': 'DEAL REQUEST : CONTROL : Pilot and Back Up Script for Eric Heisserer and Craig Zobel .pdf',
 '2052457545572': 'Control - Craig Zobel - co-story + pilot directing - EP services - 10.9.25 proposed terms.pdf',
 '2052462100258': 'DEAL REQUEST : CONTROL : Pilot and Back Up Script for Eric Heisserer and Craig Zobel .pdf',
 '2052462754937': 'Control - Eric Heisserer - co-story + pilot writing + EP services - 10.9.25 proposed terms.pdf',
 '2131714842889': 'CONTROL - Eric Heisserer -  Script Commitment Proposal 2.11.26.docx',
 '2119879353140': 'Even The Losers - Producer Deal Memo + Cert + Ex AGR + Rider - v9red_JT.pdf',
 '2119884021444': 'Even the Losers_Option Purchase Agmt (Survival of the Fastest)_FE (5.15.24).pdf',
 '2119887403146': 'Even the Losers - Writer Agmt (Singer)_v8 (FullyX).pdf',
 '2041170894718': 'AMERICAN JEWEL_YSF_6.18.2025.pdf',
 '2052597952702': 'AMERICAN JEWEL - Chernin - Producer COE_v2.1red_JT.docx',
 '2052601820798': '*DEAL REQUEST - AMERICAN JEWEL - Yngvild Sve Flikke (Director) & Rachel Sennott (Talent) - 6.3.25.pdf',
 '2052607194571': 'American Jewel_Screenplay_10-24[91].pdf',
 '2052608272404': 'American Jewel 06.16.25 BA TS.pdf',
 '2052610144637': 'CustomOfTheCountry_WR_SennottFlikke.jk - FE.pdf',
 '2052613323635': 'American Jewel_Writer Agmt (J. Tolentino)_v2cln_JT.pdf',
 '2052622240787': 'CustomOfTheCountry_WR2_Tolentino_FE.pdf',
 '2119689359544': 'AMERICAN JEWEL_010826.mmbx.pdf',
 '352233779067': 'ATL and HODs',
 '352233951807': 'Brad Copeland',
 '352229589179': 'Budget and Schedule',
 '352232939619': 'Chris Wedge',
 '352230890138': 'Consultants',
 '352230913663': 'COT',
 '352231821402': 'Crew',
 '352234849393': 'Disney Option\uf022Purchase',
 '352233189082': 'Exb. B and Stipulation Arbitration for Writers and credit\uf028',
 '352232469262': 'Executory Obligations information chart',
 '352230992943': 'FLYWHEEL',
 '352230971565': 'Foo Approved Template - Deal Memo 1.4.23',
 '352231339017': 'FooFlim Corp Docs',
 '352230554197': 'Guilds',
 '352229371022': 'Insurance',
 '352235051510': 'Lease',
 '352231244560': 'Michael McBride (DNEG Assistant Editor)',
 '352233356980': "NDA's and COE's",
 '352234770361': 'Production Accounting and Budget build - Laurel Elmendorf',
 '352230803747': 'Production Design',
 '352231684216': 'Raymond Persi (Head of Story)',
 '352229840623': 'Rob Baird',
 '352233510345': 'Scripts',
 '352228870903': 'Vendor\uf022Equipment\uf022Location\uf022Rentals',
 '2140668131244': '*FOO - Reels Development_ - Greenlight_Memo - Executed (June 2025).pdf',
 '2119693110070': 'INVOICE Raymond Persi FOO Week 7.pdf',
 '2129699409297': 'Invite.Atrium.MLA.FE.pdf',
 '2119977244696': 'Invite.Bir.Turkey.DA.FE.pdf',
 '2119973601084': 'Invite.GER.Exh.FE.pdf',
 '2119978566577': 'Invite.Longride.Japan.DA (FE).pdf',
 '2119977518170': 'Invite.Monolith.Poland.DA (FullyX).pdf',
 '2119973140709': 'Invite.Shaw.Singapore.DA (FullyX) - date added.pdf',
 '2119980152827': 'Invite.Sun.Spain+Portugal+LatAm+So_Africa+DA (FullyX).pdf',
 '2139686543879': 'Invite.Tobis.Germany+Austria.DA.FE.pdf',
 '2119972064851': 'Invite.Tobis.Germany.Company Guarantee.FE.pdf',
 '2133179442957': 'Invite.Vertical.EE.DA.FE.pdf',
 '2119978165879': 'Invite.VVS.Canada+ANZ.DA.FE.pdf',
 '352174336418': 'Development Plan',
 '352175581728': 'Long Form',
 '352174743707': 'Term Sheet',
 '2052397698343': 'rmd_ControlAlanWake_OptionPurchase_v1.0.fkks 9 6 24.docx',
 '2052397288070': 'rmd_ControlAlanWake_OptionPurchase_v1.1.cc REDLINE 10 15 24.docx',
 '2052394318827': 'rmd_ControlAlanWake_OptionPurchase_v1.2.fkks REDLINE 10 18 24.docx',
 '2052395370375': 'rmd_ControlAlanWake_OptionPurchase_v1.2.fkks REDLINE 10 18 24.pdf',
 '2052396189270': 'rmd_ControlAlanWake_OptionPurchase_v1.3.cc REDLINE 10 23 24.docx',
 '2052397903063': 'rmd_ControlAlanWake_OptionPurchase_v1.4.cc 10 23 24.docx',
 '2052401835808': 'rmd_ControlAlanWake_OptionPurchase_v1.4.cc REDLINE 10 23 24.docx',
 '2052397670365': 'rmd_ControlAlanWake_OptionPurchase_v2.0.rmd 1 29 25.docx',
 '2052396642837': 'rmd_ControlAlanWake_OptionPurchase_v2.0.rmd REDLINE 1 29 25.docx',
 '2052391100669': 'rmd_ControlAlanWake_OptionPurchase_v3.0.jm 2 18 25.docx',
 '2052394197401': 'rmd_ControlAlanWake_OptionPurchase_v3.1.wk 2 26 25.docx',
 '2052397657890': 'rmd_ControlAlanWake_OptionPurchase_v3.10.jm REDLINE 5 19 25 (JM Comments 7.1.25).docx',
 '2052390375931': 'rmd_ControlAlanWake_OptionPurchase_v3.10.jm REDLINE 5 19 25.docx',
 '2052396513130': 'rmd_ControlAlanWake_OptionPurchase_v3.2.jm 2 28 25.docx',
 '2052396748295': 'rmd_ControlAlanWake_OptionPurchase_v3.3.jm 3 7 25.docx',
 '2052393709446': 'rmd_ControlAlanWake_OptionPurchase_v3.4.jm 3 21 25.docx',
 '2052396015997': 'rmd_ControlAlanWake_OptionPurchase_v3.5.jm 3 26 25.docx',
 '2052393445867': 'rmd_ControlAlanWake_OptionPurchase_v3.6.jm 3 31 25.docx',
 '2052391782412': 'rmd_ControlAlanWake_OptionPurchase_v3.6.jm REDLINE 3 31 25.docx',
 '2052391987084': 'rmd_ControlAlanWake_OptionPurchase_v3.7.wk REDLINE 4 1 25.docx',
 '2052396952668': 'rmd_ControlAlanWake_OptionPurchase_v3.8.jm 4 1 25.docx',
 '2052390954650': 'rmd_ControlAlanWake_OptionPurchase_v3.8.jm REDLINE 4 1 25.docx',
 '2052396654309': 'rmd_ControlAlanWake_OptionPurchase_v3.9.wk REDLINE 5 8 25.docx',
 '2052400533040': 'rmd_ControlAlanWake_OptionPurchase_v4.0.rmd 10 6 25.docx',
 '2052400763539': 'rmd_ControlAlanWake_OptionPurchase_v4.0.rmd REDLINE 10 6 25.docx',
 '2052398566882': 'rmd_ControlAlanWake_OptionPurchase_v5.0.jm 10 20 25.docx',
 '2052396107913': 'rmd_ControlAlanWake_OptionPurchase_v5.1.jm 11 6 25.docx',
 '2119691793586': 'rmd_ControlAlanWake_OptionPurchase_v6.0.wk REDLINE 1 29 26.docx',
 '2119689796223': 'rmd_ControlAlanWake_OptionPurchase_v6.1.jm REDLINE 1 29 26.docx',
 '2119690830702': 'rmd_ControlAlanWake_OptionPurchase_v6.2.wk REDLINE 1 29 26.docx',
 '2119688762008': 'rmd_ControlAlanWake_OptionPurchase_v6.3.wk REDLINE 1 29 26.docx',
 '2119684058382': 'rmd_ControlAlanWake_OptionPurchase_v6.4.jm REDLINE 1 30 26.docx',
 '2119684379308': 'rmd_ControlAlanWake_OptionPurchase_v6.5.wk REDLINE 1 30 26.docx',
 '2124310771055': 'rmd_ControlAlanWake_OptionPurchase_v6.5.wk REDLINE 1 30 26.pdf',
 '352187195508': 'Craig Zobel Pilot Director',
 '352185719254': 'Eric Heisserer WEP',
 '365410571067': 'Jason Altman NWEP',
 '2052457914555': 'EH + CZ Calc Notes 9.9.25.xlsx',
 '2052462176428': 'Heisserer + Zobel AS Notes 9.9.25.docx',
 '2052452939340': 'KB Internal Email - Deal Offers 9.10.25.pdf',
 '2052455252761': 'SHORTCUT TO AP GAMES FOLDER - Remedy (Control 2 and Alan Wake) alias',
 '2130724808803': 'SHORTCUT TO Remedy (Control 2 and Alan Wake) alias',
 '2044549657716': 'AmericanJewel_Lookbook[2].pdf'}

file_dict.items()

file_dict.items()

In [16]:
data_list = []

for file_id, file_name in file_dict.items():
    url = f"https://api.box.com/2.0/files/{file_id}/metadata/"
    resp = requests.get(url, headers=headers)

    if resp.status_code == 404:
        continue  # no metadata — normal case

    if not resp.ok:
        print(f"Error {resp.status_code} on file {file_id}")
        continue

    data = resp.json()

    for entry in data.get("entries", []):
        entry["file_id"] = file_id
        data_list.append(entry)

In [17]:
import pandas as pd
df = pd.json_normalize(data_list)

In [18]:
data_list

[{'$id': 'dd5f29c1-6750-411b-b596-31f48e2658f8',
  '$version': 0,
  '$type': 'folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47',
  '$parent': 'file_2041161844567',
  '$typeVersion': 4,
  '$template': 'folderMeta',
  '$scope': 'enterprise_1353798051',
  'owner': 'Physical Production',
  '$canEdit': True,
  'file_id': '2041161844567'},
 {'$id': '918c9c06-68dc-4668-b161-e0b451c4b17e',
  '$version': 0,
  '$type': 'folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47',
  '$parent': 'file_2041164284871',
  '$typeVersion': 4,
  '$template': 'folderMeta',
  '$scope': 'enterprise_1353798051',
  'owner': 'Physical Production',
  '$canEdit': True,
  'file_id': '2041164284871'},
 {'$id': '61414bf4-12a8-47cb-8e81-694bfba04557',
  '$version': 0,
  '$type': 'budgetCrits-7c7ef05b-156a-4754-80bf-188a4601c37b',
  '$parent': 'file_2041165418316',
  '$typeVersion': 3,
  '$template': 'budgetCrits',
  '$scope': 'enterprise_1353798051',
  'totalBelowTheLine': 78651659,
  'grossBudgetTotal': 93975032,
  'storyRights': 3800000,
  'extraProducer': 817308,
  'subtotalCast': 388320,
  'screenwriters': 1400000,
  'music': 2492000,
  'totalAboveTheLine': 12073373,
  'lineProducer': 545192,
  'directingFee': 3269231,
  'developmentCosts': 875000,
  'miscDirectingFringes': 817308,
  'production': 71922659,
  'netBudgetTotal': 73035032,
  'atlTravelLiving': 695390,
  'miscProducing': 340625,
  'other': 1835000,
  'postProduction': 4894000,
  '$canEdit': True,
  'file_id': '2041165418316'},
 {'$id': '64bc127c-0fad-43d9-a8d3-504f600cf4c6',
  '$version': 0,
  '$type': 'folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47',
  '$parent': 'file_2041165418316',
  '$typeVersion': 4,
  '$template': 'folderMeta',
  '$scope': 'enterprise_1353798051',
  'owner': 'Physical Production',
  '$canEdit': True,
  'file_id': '2041165418316'},
 {'$id': '40ed6711-ac79-47d9-9089-5f7962fb306b',
  '$version': 0,
  '$type': 'folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47',
  '$parent': 'file_2052695099974',
  '$typeVersion': 4,
  '$template': 'folderMeta',
  '$scope': 'enterprise_1353798051',
  'owner': 'BA',
  'division': 'Animation',
  '$canEdit': True,
  'file_id': '2052695099974'},
 {'$id': 'e558be86-3a68-419c-b8be-8d6c9bc4baaa',
  '$version': 0,
  '$type': 'productionfinance-7510a1e2-4007-4fe9-a5ec-d72de14e3483',
  '$parent': 'file_2153822749844',
  '$typeVersion': 14,
  '$template': 'productionfinance',
  '$scope': 'enterprise_1353798051',
  'contingencySpendToDate': 428249,
  'periodending': '2026-02-28',
  'netBudget': 5875012,
  'spendToDate': 2535384,
  'grossBudget': 5875012,
  'remainingSpend': 95600,
  'contingencyBudget': 428249,
  'projecttitle': 'FOO',
  '$canEdit': True,
  'file_id': '2153822749844'},
 {'$id': '9822d02f-2187-40a6-9422-18bab0d7deb3',
  '$version': 0,
  '$type': 'folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47',
  '$parent': 'file_2044693703611',
  '$typeVersion': 4,
  '$template': 'folderMeta',
  '$scope': 'enterprise_1353798051',
  'owner': 'Physical Production',
  '$canEdit': True,
  'file_id': '2044693703611'},
 {'$id': '1e415024-11ab-4688-8dc7-af05cdec1b7a',
  '$version': 0,
  '$type': 'physicalProductionSchedule-7204a635-80b7-4dbe-bbe7-04525aa39fb9',
  '$parent': 'file_2044693703611',
  '$typeVersion': 1,
  '$template': 'physicalProductionSchedule',
  '$scope': 'enterprise_1353798051',
  'productionStart': '2025-04-21T00:00:00.000Z',
  'productionLocation': 'Los Angeles, CA / San Francisco, CA',
  'projectname': 'THE INVITE',
  'productionShootDays': 23,
  'productionWrap': '2025-05-21T00:00:00.000Z',
  'scheduleDate': '2025-06-02T00:00:00.000Z',
  '$canEdit': True,
  'file_id': '2044693703611'},
 {'$id': '73ac8ad4-5b89-41f3-9f43-226714e0fc56',
  '$version': 0,
  '$type': 'folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47',
  '$parent': 'file_2044695313708',
  '$typeVersion': 4,
  '$template': 'folderMeta',
  '$scope': 'enterprise_1353798051',
  'owner': 'Physical Production',
  '$canEdit': True,
  'file_id': '2044695313708'},
 {'$id': 'f2cfb501-c6a3-44b6-9a3d-3ca76383fdb5',
  '$version': 0,
  '$type': 'productionfinance-7510a1e2-4007-4fe9-a5ec-d72de14e3483',
  '$parent': 'file_2044695313708',
  '$typeVersion': 14,
  '$template': 'productionfinance',
  '$scope': 'enterprise_1353798051',
  'contingencySpendToDate': 83594,
  'periodending': '2025-10-25',
  'netBudget': 11715332,
  'contingencyRemaining': 716406,
  'shootdateactualstart': '2025-04-21',
  'spendToDate': 11737151,
  'postweeksscheduledfinish': '2025-11-07',
  'postweeksactualstart': '2025-06-02',
  'grossBudget': 13657732,
  'postweeksscheduledstart': '2025-05-26',
  'remainingSpend': 680656,
  'shootdateactualfinish': '2025-05-21',
  'contingencyBudget': 800000,
  'shootdatescheduledstart': '2025-04-21',
  'postweeksactualfinish': '2025-12-13',
  'projecttitle': 'THE INVITE',
  'shootdatescheduledfinish': '2025-05-21',
  '$canEdit': True,
  'file_id': '2044695313708'},
 {'$id': 'a8c5b14c-a197-42de-8831-5bd7ba6f996d',
  '$version': 0,
  '$type': 'folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47',
  '$parent': 'file_2044700014987',
  '$typeVersion': 4,
  '$template': 'folderMeta',
  '$scope': 'enterprise_1353798051',
  'owner': 'Physical Production',
  '$canEdit': True,
  'file_id': '2044700014987'},
 {'$id': 'dba665a9-dc41-40b9-90de-c6cde90aaed6',
  '$version': 1,
  '$type': 'baRightsAgreement-64f5613a-4dee-48ce-8457-e1240f1c2c0d',
  '$parent': 'file_2119974483634',
  '$typeVersion': 2,
  '$template': 'baRightsAgreement',
  '$scope': 'enterprise_1353798051',
  'optionExtensionTermAndFees': 'Purchaser has the option to extend the Initial Option Period for an additional eighteen (18) month period (the "Extension Option Period") by written notice on or before the expiration date of the Initial Option Period and an additional payment of Twenty Thousand Dollars ($20,000) to Owner (the "Extension Option Payment") within ten (10) business days thereafter. The Extension Option Payment shall be non-applicable against the "Purchase Price".',
  'optionStatus': 'Initial Option',
  'purchasePrice': 200000,
  'rightsHolder': 'Castelao Pictures, SLU (operating as "Filmax")',
  'optionNotes': "The Option Period shall be deemed automatically suspended, and thus extended, for (i) the entire duration of any third party claim which arises from a breach or alleged breach of Owner's representations, warranties or agreements hereunder, and/or (ii) the length of any industry wide labor dispute or force majeure event which interrupts, hinders or prevents Purchaser from development or pre-production activities in connection with any production intended to be based upon the Property. In the event that the Option Period would otherwise expire on a Saturday, Sunday or national holiday, said period shall be extended without notice until the end of the next following business day.",
  'commencementDate': '2021-10-21T00:00:00.000Z',
  'currentOptionTermsAndFees': 'Twenty Thousand Dollars ($20,000) payable within ten (10) business days of full execution and satisfaction of Conditions Precedent. This sum is fully applicable against, and reduces, the Purchase Price. The Initial Option Period is eighteen (18) months.',
  'optionExpiration': '2024-01-21T00:00:00.000Z',
  '$canEdit': True,
  'file_id': '2119974483634'},
 {'$id': 'a93d8687-5bcc-4efe-a59a-3b5509b88eb0',
  '$version': 0,
  '$type': 'folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47',
  '$parent': 'file_2119974483634',
  '$typeVersion': 4,
  '$template': 'folderMeta',
  '$scope': 'enterprise_1353798051',
  'owner': 'BA',
  'division': 'Film',
  '$canEdit': True,
  'file_id': '2119974483634'},
 {'$id': 'b32cff46-5a66-4810-9408-63bee0a21da6',
  '$version': 0,
  '$type': 'folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47',
  '$parent': 'file_2119975951128',
  '$typeVersion': 4,
  '$template': 'folderMeta',
  '$scope': 'enterprise_1353798051',
  'owner': 'BA',
  'division': 'Film',
  '$canEdit': True,
  'file_id': '2119975951128'},
 {'$id': '805e888e-a8a5-4731-bc66-a9355421f065',
  '$version': 2,
  '$type': 'writeragreement-a8b6033d-a3f7-493e-bfe5-594336630afb',
  '$parent': 'file_2119975951128',
  '$typeVersion': 11,
  '$template': 'writeragreement',
  '$scope': 'enterprise_1353798051',
  'guaranteedStepsAndFees': 'For the First Draft and Final Draft, the total sum of Two Hundred Fifty Thousand Dollars ($250,000). Payable as: $150,000 for First Draft (50% upon commencement, 50% upon delivery) and $100,000 for Final Draft (50% upon commencement, 50% upon delivery).',
  'optionalStepsAndFees': 'Optional Rewrite: $50,000 (50% on commencement, 50% upon delivery). Optional Polish: $35,000 (50% on commencement, 50% upon delivery).',
  'credit': 'Governed by WGA Basic Agreement. Form, placement, size, duration, and other matters determined by Company in its sole discretion, subject to WGA Agreement. Company to contractually obligate domestic distributor and use reasonable efforts for other licensees/assignees to comply.',
  'projectname': 'The People Upstairs',
  'totalCompensation': 1000000,
  'contingentComp': 'Producer\'s Share of Net Proceeds: If Sole Screenplay Credit, 7.5% of 100% of "Producer\'s Share of Net Proceeds" (no less than 50% of "Adjusted Gross Proceeds"). If Shared Screenplay Credit, 3.5% of 100% of "Producer\'s Share of Net Proceeds".\nMajor or Mini-Major Studio / Major Independent: If Sole Screenplay Credit, 7.5% of 100% of "Net Proceeds". If Shared Screenplay Credit, 3.5% of 100% of "Net Proceeds".\nPremium Streaming Platform (Streamer Buyout for Sole Screenplay Credit, half for Shared Screenplay Credit):\n- Budget $10,000,000 and under: $35,000\n- Budget $10,000,001 - $15,000,000: $50,000\n- Budget $15,000,001 - $20,000,000: $75,000\n- Budget $20,000,001 - $30,000,000: $100,000\n- Budget $30,000,001 and higher: $150,000',
  'creditbasedBonus': 'Sole Credit Bonus: 2.5% of the "Ingoing Direct Budget" of the Picture, with a floor of $250,000 and a ceiling of $500,000. Ceiling increases based on budget: $20M budget -> $600,000; $30M -> $700,000; $40M -> $800,000; $50M -> $900,000; $60M -> $1,000,000. Shared Credit Bonus: One-half of the applicable Sole Credit Bonus.',
  'deliveryAndTiming': "First Draft: 12 weeks writing, 4 weeks reading. Final Draft: 8 weeks writing, 4 weeks reading. Optional Rewrite: 6 weeks writing, 3 weeks reading. Optional Polish: 4 weeks writing. Writer's services are exclusive during writing periods and non-exclusive during reading periods. Company may defer services for up to 12 months, tolled for prior commitments.",
  'writerNames': 'Will McCormack & Rashida Jones',
  'expensesAndTravel': 'If required to render services >50 miles from residence: business-class round-trip air transportation, exclusive ground transportation (if applicable), first-class accommodations, and WGA per diems. If 14+ consecutive days at Location, business-class round-trip air transportation for one companion (if-used basis). If Location is not a major city, full-size fully insured rental car and reimbursement for parking/gas.',
  'commencementDate': '2021-12-17T00:00:00.000Z',
  '$canEdit': True,
  'file_id': '2119975951128'},
 {'$id': '6f2525b0-67cc-4208-9e9b-f1f35a53897f',
  '$version': 0,
  '$type': 'folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47',
  '$parent': 'file_2119976975079',
  '$typeVersion': 4,
  '$template': 'folderMeta',
  '$scope': 'enterprise_1353798051',
  'owner': 'BA',
  'division': 'Film',
  '$canEdit': True,
  'file_id': '2119976975079'},
 {'$id': '348692ee-3581-4cdd-a643-66adfedd972a',
  '$version': 1,
  '$type': 'performersagreement-a1dd1d83-25d4-4ec0-b566-8d7179971f83',
  '$parent': 'file_2119976975079',
  '$typeVersion': 10,
  '$template': 'performersagreement',
  '$scope': 'enterprise_1353798051',
  'compensation': 40135,
  'project': 'The Invite',
  'parties': 'Olivia Wilde (Performer) and The Wilde Company (Lender)',
  'perks': "Performer shall receive: one (1) first-class round-trip air transportation to distant locations; exclusive first-class ground transportation with an approved driver; first-class accommodations subject to Performer's reasonable approval; a single star trailer with customary first-class amenities for exclusive use (favored nations with all cast members and director); a private exclusive dressing room at the Los Angeles set location; an approved assistant for the entire Production Period or reimbursement for personal assistant; a non-accountable, non-reducible per diem of $100 per day (favored nations).",
  'contingentcompawards': 75000,
  'contingentcompshareagp': 7.5415,
  'credit': "Performer shall be accorded credit on screen, in the main titles (whether such main titles appear at the beginning or end of the Picture), on a shared card with the other three (3) lead cast members only, listed by order of appearance, above or before the title of the Picture in such main titles, in an average size no less favorable than the average size of credit accorded to any other principal cast members receiving main title credit. Performer shall also be accorded credit in the billing block of all paid advertising issued by or under the authority of Company or a distributor, whenever and wherever a billing block is used, in the same position as Performer's on-screen credit, above or before the title of the Picture in the billing block, in a size no less favorable than (i) 100% of the title of Picture in the billing block; (ii) 20% of the artwork title; or (iii) 100% the size of billing block credit accorded to any other individual receiving billing block credit therein, whichever is larger.",
  '$canEdit': True,
  'file_id': '2119976975079'},
 {'$id': '6d255cd4-4730-4e9c-b029-80e8176386db',
  '$version': 0,
  '$type': 'folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47',
  '$parent': 'file_2119977220029',
  '$typeVersion': 4,
  '$template': 'folderMeta',
  '$scope': 'enterprise_1353798051',
  'owner': 'BA',
  'division': 'Film',
  '$canEdit': True,
  'file_id': '2119977220029'},
 {'$id': 'ef4a02d3-d802-4c2b-aee7-d720c09e26a7',
  '$version': 0,
  '$type': 'productionScripts-ad5ce484-73ba-4fcd-8cb0-e7f691e3279f',
  '$parent': 'file_2119977220029',
  '$typeVersion': 0,
  '$template': 'productionScripts',
  '$scope': 'enterprise_1353798051',
  'pages': 108,
  'projectname': 'The Invite',
  'draftStep': 'Production Draft / Final Step ',
  'draftDate': '2025-04-29T00:00:00.000Z',
  'draftDeliveryDate': '2025-04-29T00:00:00.000Z',
  '$canEdit': True,
  'file_id': '2119977220029'},
 {'$id': 'faab53d6-f4cc-4374-9b9f-b615a0e8824a',
  '$version': 0,
  '$type': 'folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47',
  '$parent': 'file_2119977403111',
  '$typeVersion': 4,
  '$template': 'folderMeta',
  '$scope': 'enterprise_1353798051',
  'owner': 'BA',
  'division': 'Film',
  '$canEdit': True,
  'file_id': '2119977403111'},
 {'$id': '6f76dbaf-2238-4c33-b22a-562b24c71585',
  '$version': 1,
  '$type': 'performersagreement-a1dd1d83-25d4-4ec0-b566-8d7179971f83',
  '$parent': 'file_2119977403111',
  '$typeVersion': 10,
  '$template': 'performersagreement',
  '$scope': 'enterprise_1353798051',
  'compensation': 250000,
  'project': 'The Invite',
  'parties': 'Edward Norton and 10th Street Ventures Inc.',
  'perks': "One (1) first-class (if-used, if-available, otherwise best available class) round-trip air transportation between Los Angeles and the distant location, with VIP greeters at each arriving and departing airport. Exclusive first-class ground transportation with an approved driver to and from airports and between accommodations and set. First-class accommodations subject to Performer's reasonable approval. A single star trailer with customary first-class amenities for exclusive use, on a favored nations basis with all cast members and the director. During principal photography in Los Angeles, a private exclusive dressing room at the set location, substantially similar to other cast members and director, with amenities on a favored nations basis. Exclusive use of an approved assistant (PA and/or local hire) during the Production Period, or reimbursement of personal assistant up to the cost of a production-provided assistant. A non-accountable, non-reducible per diem of One Hundred Dollars ($100) per day. A non-accountable transportation and expenses stipend of Fifteen Thousand Dollars ($15,000) payable fifty percent (50%) upon commencement and fifty percent (50%) upon completion of the Production Period.",
  'contingentcompawards': 75000,
  'contingentcompshareagp': 7.5415,
  'credit': 'On screen, in the main titles, on a shared card with the other three (3) lead cast members only, listed by order of appearance, above or before the title of the Picture, in an average size no less favorable than the average size of credit accorded to any other principal cast members receiving main title credit. In the billing block of all paid advertising, whenever and wherever a billing block is used, in the same position as Performer\'s on-screen credit, above or before the title of the Picture in the billing block, in a size no less favorable than (i) 100% of the title of Picture in the billing block; (ii) 20% of the artwork title; or (iii) 100% the size of billing block credit accorded to any other individual receiving billing block credit therein, whichever is larger. If any other cast member is accorded credit above or as part of the "artwork title", Performer shall also be accorded credit above or as part of the artwork title in the same position as Performer\'s credit on screen, in a size no less favorable than any other cast member therein. If the name of any individual is mentioned in radio advertisements and/or the audio portion of television advertisements and/or theatrical/internet trailers, then Performer\'s name shall also be mentioned, listed by order of appearance.',
  '$canEdit': True,
  'file_id': '2119977403111'},
 {'$id': '4dd9e48e-2c1d-4d2f-9100-90798a436f26',
  '$version': 0,
  '$type': 'baDistributionAgreement-438cc0c3-f4e4-4b0b-985b-667cc9b46edf',
  '$parent': 'file_2119977630419',
  '$typeVersion': 0,
  '$template': 'baDistributionAgreement',
  '$scope': 'enterprise_1353798051',
  'projectname': 'The Invite',
  'compensationFees': 17.5,
  'screenCommitment': 1000,
  'term': '15 years + 5 if unrecouped',
  'territoryTerritories': 'THE UNITED STATES OF AMERICA and its respective territories and possessions',
  'company': 'U.S. Distributor',
  '$canEdit': True,
  'file_id': '2119977630419'},
 {'$id': '81188e42-cd56-4055-911a-95f3c492878d',
  '$version': 0,
  '$type': 'baSalesAgreement-048b59c0-1fe1-4b25-8951-77b503180816',
  '$parent': 'file_2119977630419',
  '$typeVersion': 0,
  '$template': 'baSalesAgreement',
  '$scope': 'enterprise_1353798051',
  '$canEdit': True,
  'file_id': '2119977630419'},
 {'$id': '30b9fcd9-de6f-481c-b0b9-25a928dae592',
  '$version': 0,
  '$type': 'folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47',
  '$parent': 'file_2119977630419',
  '$typeVersion': 4,
  '$template': 'folderMeta',
  '$scope': 'enterprise_1353798051',
  'owner': 'BA',
  'division': 'Film',
  '$canEdit': True,
  'file_id': '2119977630419'},
 {'$id': 'a711e394-3768-42d1-8151-8f581ae2be46',
  '$version': 0,
  '$type': 'folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47',
  '$parent': 'file_2119977662134',
  '$typeVersion': 4,
  '$template': 'folderMeta',
  '$scope': 'enterprise_1353798051',
  'owner': 'BA',
  'division': 'Film',
  '$canEdit': True,
  'file_id': '2119977662134'},
 {'$id': '3052b7ce-369c-4a58-b88b-c76b2276579c',
  '$version': 1,
  '$type': 'optionsmetadata-2e7c9f5c-8b51-469f-984a-50383e9f3d9a',
  '$parent': 'file_2119977662134',
  '$typeVersion': 10,
  '$template': 'optionsmetadata',
  '$scope': 'enterprise_1353798051',
  'dealspecificnotes': 'Side Letter dated April 2, 2025, modifying the original Option/Purchase Agreement. The purchase price is 2% of the "In-Going Direct Budget" ($11,781,165) less the Initial Option Payment. Owner is entitled to 2% of 100% of Producer\'s Share of AGP.',

In [19]:
df

,$id,$version,$type,$parent,$typeVersion,$template,$scope,owner,$canEdit,file_id,...,greenlightMemoDate,dept,optionexpirationdate,initialoption,extensions,currentoptiontermexpirationdate,budgetLocation,budgetDate,miscWritingFringes,visualEffects
0,dd5f29c1-6750-411b-b596-31f48e2658f8,0,folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47,file_2041161844567,4,folderMeta,enterprise_1353798051,Physical Production,True,2041161844567,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,918c9c06-68dc-4668-b161-e0b451c4b17e,0,folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47,file_2041164284871,4,folderMeta,enterprise_1353798051,Physical Production,True,2041164284871,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,61414bf4-12a8-47cb-8e81-694bfba04557,0,budgetCrits-7c7ef05b-156a-4754-80bf-188a4601c37b,file_2041165418316,3,budgetCrits,enterprise_1353798051,NaN,True,2041165418316,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,64bc127c-0fad-43d9-a8d3-504f600cf4c6,0,folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47,file_2041165418316,4,folderMeta,enterprise_1353798051,Physical Production,True,2041165418316,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,40ed6711-ac79-47d9-9089-5f7962fb306b,0,folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47,file_2052695099974,4,folderMeta,enterprise_1353798051,BA,True,2052695099974,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,19877d14-f8f3-4647-97ad-ca0cec672564,0,folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47,file_2052462176428,4,folderMeta,enterprise_1353798051,BA,True,2052462176428,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,698e20f8-c1a5-4767-96b6-420f3ee4de9b,0,folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47,file_2052452939340,4,folderMeta,enterprise_1353798051,BA,True,2052452939340,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,ced20ee4-d364-420c-95bb-864c99700759,0,folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47,file_2052455252761,4,folderMeta,enterprise_1353798051,BA,True,2052455252761,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,c061716e-4959-4850-96d0-3443e88ac7c5,0,folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47,file_2130724808803,4,folderMeta,enterprise_1353798051,BA,True,2130724808803,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,feae2f48-32ab-4e49-9968-f7dbe42309f3,0,folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47,file_2044549657716,4,folderMeta,enterprise_1353798051,Physical Production,True,2044549657716,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

file_dict

In [20]:
df.columns = df.columns.str.replace('$', 'box_', regex=False)

df['file_id'] = df['file_id'].astype("int")

In [21]:
df = df.set_index('box_id')
#df

In [22]:
df['filename'] = df['file_id'].map(file_dict)

In [23]:
from datetime import datetime
df['updated_time'] = datetime.today()

In [24]:
df['hub_id'] = df['file_id'].map(hub_file_dict)

In [25]:
data = df.copy()

In [26]:
data.to_csv("flattened.csv")

In [27]:
file_id_list  = data['file_id'].to_list()
data

,box_version,box_type,box_parent,box_typeVersion,box_template,box_scope,owner,box_canEdit,file_id,totalBelowTheLine,...,initialoption,extensions,currentoptiontermexpirationdate,budgetLocation,budgetDate,miscWritingFringes,visualEffects,filename,updated_time,hub_id
box_id,,,,,,,,,,,,,,,,,,,,,
dd5f29c1-6750-411b-b596-31f48e2658f8,0,folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47,file_2041161844567,4,folderMeta,enterprise_1353798051,Physical Production,True,2041161844567,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Chris Wedge Deal .xlsx,2026-03-09 13:34:36.836164,814974530
918c9c06-68dc-4668-b161-e0b451c4b17e,0,folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47,file_2041164284871,4,folderMeta,enterprise_1353798051,Physical Production,True,2041164284871,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wedge deal memo Execution.docx,2026-03-09 13:34:36.836164,814974530
61414bf4-12a8-47cb-8e81-694bfba04557,0,budgetCrits-7c7ef05b-156a-4754-80bf-188a4601c37b,file_2041165418316,3,budgetCrits,enterprise_1353798051,NaN,True,2041165418316,78651659.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FOO Budget_9-11-23 SW.pdf,2026-03-09 13:34:36.836164,814974530
64bc127c-0fad-43d9-a8d3-504f600cf4c6,0,folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47,file_2041165418316,4,folderMeta,enterprise_1353798051,Physical Production,True,2041165418316,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FOO Budget_9-11-23 SW.pdf,2026-03-09 13:34:36.836164,814974530
40ed6711-ac79-47d9-9089-5f7962fb306b,0,folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47,file_2052695099974,4,folderMeta,enterprise_1353798051,BA,True,2052695099974,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Foo Rewrite 1-12-23_CINESITE.pdf,2026-03-09 13:34:36.836164,814974530
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19877d14-f8f3-4647-97ad-ca0cec672564,0,folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47,file_2052462176428,4,folderMeta,enterprise_1353798051,BA,True,2052462176428,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Heisserer + Zobel AS Notes 9.9.25.docx,2026-03-09 13:34:36.836164,NaN
698e20f8-c1a5-4767-96b6-420f3ee4de9b,0,folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47,file_2052452939340,4,folderMeta,enterprise_1353798051,BA,True,2052452939340,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KB Internal Email - Deal Offers 9.10.25.pdf,2026-03-09 13:34:36.836164,NaN
ced20ee4-d364-420c-95bb-864c99700759,0,folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47,file_2052455252761,4,folderMeta,enterprise_1353798051,BA,True,2052455252761,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SHORTCUT TO AP GAMES FOLDER - Remedy (Control ...,2026-03-09 13:34:36.836164,NaN
c061716e-4959-4850-96d0-3443e88ac7c5,0,folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47,file_2130724808803,4,folderMeta,enterprise_1353798051,BA,True,2130724808803,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SHORTCUT TO Remedy (Control 2 and Alan Wake) a...,2026-03-09 13:34:36.836164,NaN
feae2f48-32ab-4e49-9968-f7dbe42309f3,0,folderMeta-adee8e8b-d9d5-4adc-a4d6-3e4323a57b47,file_2044549657716,4,folderMeta,enterprise_1353798051,Physical Production,True,2044549657716,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AmericanJewel_Lookbook[2].pdf,2026-03-09 13:34:36.836164,NaN

In [28]:
system_cols = {
    "_id", "file_id", "filename", "updated_time",
    "box_template", "box_version", "box_type",
    "box_parent", "box_typeVersion", "box_scope",
    "box_canEdit", "box_id",
}

final_data = {}

# (optional) base fields come from "any row" for that file_id
base_cols = ["filename", "updated_time", 'hub_id']

# precompute base info per file_id
base = (
    df.sort_values("updated_time")
      .groupby("file_id", dropna=False)[base_cols]
      .last()
      .to_dict(orient="index")
)

for template, tdf in df.groupby("box_template", dropna=False):
    # candidate template fields = everything except system cols
    template_fields = [c for c in tdf.columns if c not in system_cols]

    # drop columns where ALL rows are NaN for this template
    keep_fields = [c for c in template_fields if not tdf[c].isna().all()]

    # iterate rows for this template
    for _, row in tdf.iterrows():
        fid = row["file_id"]

        if fid not in final_data:
            final_data[fid] = {
                "_id": fid,
                **base.get(fid, {}),
                "templates": {},
                "canonical": {},
            }

        # per-row: drop nulls
        template_data = {c: row[c] for c in keep_fields if pd.notna(row[c])}

        # only add if there’s anything to store
        if template_data:
            final_data[fid]["templates"][template] = template_data
            # update canonical
            for k, v in template_data.items():
                if k not in final_data[fid]["canonical"]:
                    final_data[fid]["canonical"][k] = v

In [29]:
pd.DataFrame(final_data)

,2119977630419,2122991245901,2129699409297,2119977244696,2119973601084,2119978566577,2119977518170,2119973140709,2119980152827,2119972064851,...,2119684058382,2119684379308,2124310771055,2052457914555,2052462176428,2052452939340,2052455252761,2130724808803,2044549657716,2153822749844
_id,2119977630419,2122991245901,2129699409297,2119977244696,2119973601084,2119978566577,2119977518170,2119973140709,2119980152827,2119972064851,...,2119684058382,2119684379308,2124310771055,2052457914555,2052462176428,2052452939340,2052455252761,2130724808803,2044549657716,2153822749844
filename,The Invite_Uniform Counter for U.S. Distributi...,THE INVITE - 1.29.26.pdf,Invite.Atrium.MLA.FE.pdf,Invite.Bir.Turkey.DA.FE.pdf,Invite.GER.Exh.FE.pdf,Invite.Longride.Japan.DA (FE).pdf,Invite.Monolith.Poland.DA (FullyX).pdf,Invite.Shaw.Singapore.DA (FullyX) - date added...,Invite.Sun.Spain+Portugal+LatAm+So_Africa+DA (...,Invite.Tobis.Germany.Company Guarantee.FE.pdf,...,rmd_ControlAlanWake_OptionPurchase_v6.4.jm RED...,rmd_ControlAlanWake_OptionPurchase_v6.5.wk RED...,rmd_ControlAlanWake_OptionPurchase_v6.5.wk RED...,EH + CZ Calc Notes 9.9.25.xlsx,Heisserer + Zobel AS Notes 9.9.25.docx,KB Internal Email - Deal Offers 9.10.25.pdf,SHORTCUT TO AP GAMES FOLDER - Remedy (Control ...,SHORTCUT TO Remedy (Control 2 and Alan Wake) a...,AmericanJewel_Lookbook[2].pdf,Foo_Cost Report_02.28.26.pdf
updated_time,2026-03-09 13:34:36.836164,2026-03-09 13:34:36.836164,2026-03-09 13:34:36.836164,2026-03-09 13:34:36.836164,2026-03-09 13:34:36.836164,2026-03-09 13:34:36.836164,2026-03-09 13:34:36.836164,2026-03-09 13:34:36.836164,2026-03-09 13:34:36.836164,2026-03-09 13:34:36.836164,...,2026-03-09 13:34:36.836164,2026-03-09 13:34:36.836164,2026-03-09 13:34:36.836164,2026-03-09 13:34:36.836164,2026-03-09 13:34:36.836164,2026-03-09 13:34:36.836164,2026-03-09 13:34:36.836164,2026-03-09 13:34:36.836164,2026-03-09 13:34:36.836164,2026-03-09 13:34:36.836164
hub_id,828769775,828769775,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,814974530
templates,{'baDistributionAgreement': {'projectname': 'T...,{'baDistributionAgreement': {'projectname': 'T...,{'baDistributionAgreement': {'term': 'The Term...,{'baDistributionAgreement': {'projectname': 'T...,{'baDistributionAgreement': {'projectname': 'T...,{'baDistributionAgreement': {'projectname': 'T...,{'baDistributionAgreement': {'projectname': 'T...,{'baDistributionAgreement': {'projectname': 'T...,{'baDistributionAgreement': {'projectname': 'T...,{'baDistributionAgreement': {'projectname': 'T...,...,"{'folderMeta': {'owner': 'BA', 'division': 'In...","{'folderMeta': {'owner': 'BA', 'division': 'In...","{'folderMeta': {'owner': 'BA', 'division': 'In...","{'folderMeta': {'owner': 'BA', 'division': 'TV'}}","{'folderMeta': {'owner': 'BA', 'division': 'TV'}}","{'folderMeta': {'owner': 'BA', 'division': 'TV'}}","{'folderMeta': {'owner': 'BA', 'division': 'TV'}}","{'folderMeta': {'owner': 'BA', 'division': 'In...",{'folderMeta': {'owner': 'Physical Production'}},{'productionfinance': {'contingencySpendToDate...
canonical,"{'projectname': 'The Invite', 'compensationFee...","{'projectname': 'The Invite', 'compensationFee...",{'term': 'The Term of this Agreement shall com...,"{'projectname': 'THE INVITE.', 'compensationFe...","{'projectname': 'THE INVITE', 'compensationFee...","{'projectname': 'THE INVITE', 'compensationFee...","{'projectname': 'THE INVITE.', 'compensationFe...","{'projectname': 'THE INVITE', 'compensationFee...","{'projectname': 'THE INVITE', 'compensationFee...","{'projectname': 'THE INVITE', 'term': 'the ent...",...,"{'owner': 'BA', 'division': 'Interactive'}","{'owner': 'BA', 'division': 'Interactive'}","{'owner': 'BA', 'division': 'Interactive'}","{'owner': 'BA', 'division': 'TV'}","{'owner': 'BA', 'division': 'TV'}","{'owner': 'BA', 'division': 'TV'}","{'owner': 'BA', 'division': 'TV'}","{'owner': 'BA', 'division': 'Interactive'}",{'owner': 'Physical Production'},"{'contingencySpendToDate': 428249.0, 'perioden..."

In [30]:
import pandas as pd

for d in final_data.values():
    if isinstance(d.get("updated_time"), pd.Timestamp):
        d["updated_time"] = d["updated_time"].to_pydatetime()

In [31]:
docs = list(final_data.values())  # <- IMPORTANT
docs

[{'_id': '2119977630419',
  'filename': 'The Invite_Uniform Counter for U.S. Distribution Deal.docx',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': '828769775',
  'templates': {'baDistributionAgreement': {'projectname': 'The Invite',
    'compensationFees': 17.5,
    'screenCommitment': 1000.0,
    'term': '15 years + 5 if unrecouped',
    'territoryTerritories': 'THE UNITED STATES OF AMERICA and its respective territories and possessions',
    'company': 'U.S. Distributor',
    'hub_id': '828769775'},
   'baSalesAgreement': {'hub_id': '828769775'},
   'folderMeta': {'owner': 'BA', 'division': 'Film', 'hub_id': '828769775'}},
  'canonical': {'projectname': 'The Invite',
   'compensationFees': 17.5,
   'screenCommitment': 1000.0,
   'term': '15 years + 5 if unrecouped',
   'territoryTerritories': 'THE UNITED STATES OF AMERICA and its respective territories and possessions',
   'company': 'U.S. Distributor',
   'hub_id': '828769775',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2122991245901',
  'filename': 'THE INVITE - 1.29.26.pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': '828769775',
  'templates': {'baDistributionAgreement': {'projectname': 'The Invite',
    'compensationFees': 9577000.0,
    'territoryTerritories': 'Worldwide',
    'company': 'FilmNation Entertainment',
    'hub_id': '828769775'},
   'baSalesAgreement': {'projectname': 'The Invite',
    'compensationFees': 9577000.0,
    'hub_id': '828769775'},
   'folderMeta': {'owner': 'BA', 'division': 'Film', 'hub_id': '828769775'}},
  'canonical': {'projectname': 'The Invite',
   'compensationFees': 9577000.0,
   'territoryTerritories': 'Worldwide',
   'company': 'FilmNation Entertainment',
   'hub_id': '828769775',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2129699409297',
  'filename': 'Invite.Atrium.MLA.FE.pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': None,
  'templates': {'baDistributionAgreement': {'term': 'The Term of this Agreement shall commence on the date of execution of the first Distribution Agreement and shall expire for each country of the Territory on the date which is one (1) year later or until the applicable Distribution Agreements under this Agreement have expired, whichever is the later.',
    'company': 'Atrium Productions Kft.'},
   'folderMeta': {'owner': 'BA', 'division': 'Film'}},
  'canonical': {'term': 'The Term of this Agreement shall commence on the date of execution of the first Distribution Agreement and shall expire for each country of the Territory on the date which is one (1) year later or until the applicable Distribution Agreements under this Agreement have expired, whichever is the later.',
   'company': 'Atrium Productions Kft.',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2119977244696',
  'filename': 'Invite.Bir.Turkey.DA.FE.pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': None,
  'templates': {'baDistributionAgreement': {'projectname': 'THE INVITE.',
    'compensationFees': 25000.0,
    'term': 'ten (10) years',
    'territoryTerritories': 'TURKEY',
    'company': 'YENI BIR FILM LTD'},
   'folderMeta': {'owner': 'BA', 'division': 'Film'}},
  'canonical': {'projectname': 'THE INVITE.',
   'compensationFees': 25000.0,
   'term': 'ten (10) years',
   'territoryTerritories': 'TURKEY',
   'company': 'YENI BIR FILM LTD',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2119973601084',
  'filename': 'Invite.GER.Exh.FE.pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': None,
  'templates': {'baDistributionAgreement': {'projectname': 'THE INVITE',
    'compensationFees': 1790000.0,
    'term': "shall commence on the date set forth above and continue for twenty (20) years following the earlier of (i) Licensee's Distributor's initial release of the Picture in the Territory (it being agreed that marketing and promotion [including test screenings and screenings at festivals] of the Picture shall not be considered as a release of the Picture) or (ii) four (4) months following Licensee's Distributor's Technical Acceptance of the Initial Materials. Notwithstanding the foregoing, in the event the Minimum Guarantee and/or the Recoupable Distribution Expenses are not recouped by the date that the Term would otherwise expire, and provided that Licensee's Distributor provides Licensor with an accounting evidencing that the Minimum Guarantee and/or the Recoupable Distribution Expenses has not been recouped during the last six (6) months of the original Term, the Term shall be automatically extended for an additional period which shall last until one (1) year from the date the Term was originally set to expire.",
    'territoryTerritories': 'Exclusive Territory: Germany and Austria\nNon-Exclusive Territory: Alto Adige, Liechtenstein, Luxembourg, Switzerland',
    'company': 'GEM Entertainment Kft.'},
   'folderMeta': {'owner': 'BA', 'division': 'Film'}},
  'canonical': {'projectname': 'THE INVITE',
   'compensationFees': 1790000.0,
   'term': "shall commence on the date set forth above and continue for twenty (20) years following the earlier of (i) Licensee's Distributor's initial release of the Picture in the Territory (it being agreed that marketing and promotion [including test screenings and screenings at festivals] of the Picture shall not be considered as a release of the Picture) or (ii) four (4) months following Licensee's Distributor's Technical Acceptance of the Initial Materials. Notwithstanding the foregoing, in the event the Minimum Guarantee and/or the Recoupable Distribution Expenses are not recouped by the date that the Term would otherwise expire, and provided that Licensee's Distributor provides Licensor with an accounting evidencing that the Minimum Guarantee and/or the Recoupable Distribution Expenses has not been recouped during the last six (6) months of the original Term, the Term shall be automatically extended for an additional period which shall last until one (1) year from the date the Term was originally set to expire.",
   'territoryTerritories': 'Exclusive Territory: Germany and Austria\nNon-Exclusive Territory: Alto Adige, Liechtenstein, Luxembourg, Switzerland',
   'company': 'GEM Entertainment Kft.',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2119978566577',
  'filename': 'Invite.Longride.Japan.DA (FE).pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': None,
  'templates': {'baDistributionAgreement': {'projectname': 'THE INVITE',
    'compensationFees': 75000.0,
    'term': 'For all rights licensed herein, the term ("Term") shall commence on the date set forth above, and continue for ten (10) years following the date of Licensor\'s written notice ("Notice of Delivery") to Distributor that Licensor is ready to make "Initial Delivery" (as defined below) of the "Initial Materials" (as defined below). Notwithstanding the foregoing, in the event the Minimum Guarantee is not recouped by the date that the Term would otherwise expire...the Term shall be extended for an additional period (*Extended Term") which shall last until the earlier of the date that Distributor has recouped the Minimum Guarantee and three (3) years from the date the term was originally set to expire.',
    'territoryTerritories': 'JAPAN',
    'company': 'LONGRIDE INC.'},
   'folderMeta': {'owner': 'BA', 'division': 'Film'}},
  'canonical': {'projectname': 'THE INVITE',
   'compensationFees': 75000.0,
   'term': 'For all rights licensed herein, the term ("Term") shall commence on the date set forth above, and continue for ten (10) years following the date of Licensor\'s written notice ("Notice of Delivery") to Distributor that Licensor is ready to make "Initial Delivery" (as defined below) of the "Initial Materials" (as defined below). Notwithstanding the foregoing, in the event the Minimum Guarantee is not recouped by the date that the Term would otherwise expire...the Term shall be extended for an additional period (*Extended Term") which shall last until the earlier of the date that Distributor has recouped the Minimum Guarantee and three (3) years from the date the term was originally set to expire.',
   'territoryTerritories': 'JAPAN',
   'company': 'LONGRIDE INC.',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2119977518170',
  'filename': 'Invite.Monolith.Poland.DA (FullyX).pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': None,
  'templates': {'baDistributionAgreement': {'projectname': 'THE INVITE.',
    'compensationFees': 350000.0,
    'term': 'For all rights licensed herein, the Term shall commence on the date set forth above, and continue for seventeen (17) years following the date of the the Availability Date (as defined below). Notwithstanding the foregoing, in the event the Minimum Guarantee is not recouped by the date that the Term would otherwise expire, and provided that Distributor provides Licensor with an accounting evidencing that the Minimum Guarantee has not been recouped during the thirty (30) day period immediately prior to the date the Term would otherwise expire, the Term shall be extended for an additional period ("Extended Term") which shall last until three (3) years from the date the term was originally set to expire.',
    'territoryTerritories': 'POLAND and MONGOLIA.',
    'company': 'MONOLITH INTERNATIONAL LTD.'},
   'folderMeta': {'owner': 'BA', 'division': 'Film'}},
  'canonical': {'projectname': 'THE INVITE.',
   'compensationFees': 350000.0,
   'term': 'For all rights licensed herein, the Term shall commence on the date set forth above, and continue for seventeen (17) years following the date of the the Availability Date (as defined below). Notwithstanding the foregoing, in the event the Minimum Guarantee is not recouped by the date that the Term would otherwise expire, and provided that Distributor provides Licensor with an accounting evidencing that the Minimum Guarantee has not been recouped during the thirty (30) day period immediately prior to the date the Term would otherwise expire, the Term shall be extended for an additional period ("Extended Term") which shall last until three (3) years from the date the term was originally set to expire.',
   'territoryTerritories': 'POLAND and MONGOLIA.',
   'company': 'MONOLITH INTERNATIONAL LTD.',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2119973140709',
  'filename': 'Invite.Shaw.Singapore.DA (FullyX) - date added.pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': None,
  'templates': {'baDistributionAgreement': {'projectname': 'THE INVITE',
    'compensationFees': 7000.0,
    'term': 'seven (7) years following the date of Licensor\'s written notice ("Notice of Delivery")',
    'territoryTerritories': 'SINGAPORE and MYANMAR',
    'company': 'SHAW RENTERS (SINGAPORE) PTE LIMITED'},
   'folderMeta': {'owner': 'BA', 'division': 'Film'}},
  'canonical': {'projectname': 'THE INVITE',
   'compensationFees': 7000.0,
   'term': 'seven (7) years following the date of Licensor\'s written notice ("Notice of Delivery")',
   'territoryTerritories': 'SINGAPORE and MYANMAR',
   'company': 'SHAW RENTERS (SINGAPORE) PTE LIMITED',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2119980152827',
  'filename': 'Invite.Sun.Spain+Portugal+LatAm+So_Africa+DA (FullyX).pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': None,
  'templates': {'baDistributionAgreement': {'projectname': 'THE INVITE',
    'compensationFees': 1500000.0,
    'term': 'For all rights licensed herein, the term ("Term") shall commence on the date set forth above, and continue for twenty (20) years following the date of Licensor\'s written notice ("Notice of Delivery") to Distributor that Licensor is ready to make "Initial Delivery" (as defined below) of the "Initial Materials" (as defined below).',
    'territoryTerritories': 'the Spanish Territory, the Portuguese Territory, the LatAm Territory, and the South African Territory',
    'company': 'SUN DISTRIBUTION GROUP S.A.'},
   'folderMeta': {'owner': 'BA', 'division': 'Film'}},
  'canonical': {'projectname': 'THE INVITE',
   'compensationFees': 1500000.0,
   'term': 'For all rights licensed herein, the term ("Term") shall commence on the date set forth above, and continue for twenty (20) years following the date of Licensor\'s written notice ("Notice of Delivery") to Distributor that Licensor is ready to make "Initial Delivery" (as defined below) of the "Initial Materials" (as defined below).',
   'territoryTerritories': 'the Spanish Territory, the Portuguese Territory, the LatAm Territory, and the South African Territory',
   'company': 'SUN DISTRIBUTION GROUP S.A.',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2119972064851',
  'filename': 'Invite.Tobis.Germany.Company Guarantee.FE.pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': None,
  'templates': {'baDistributionAgreement': {'projectname': 'THE INVITE',
    'term': 'the entire Term of the Picture pursuant to the Agreement',
    'territoryTerritories': 'the Territory as defined in the Agreement',
    'company': 'Tobis Film GmbH'},
   'folderMeta': {'owner': 'BA', 'division': 'Film'}},
  'canonical': {'projectname': 'THE INVITE',
   'term': 'the entire Term of the Picture pursuant to the Agreement',
   'territoryTerritories': 'the Territory as defined in the Agreement',
   'company': 'Tobis Film GmbH',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2119978165879',
  'filename': 'Invite.VVS.Canada+ANZ.DA.FE.pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': None,
  'templates': {'baDistributionAgreement': {'projectname': 'THE INVITE',
    'compensationFees': 1300000.0,
    'term': 'For all rights licensed herein, the term ("Term") shall commence on the date set forth above, and continue for fifteen (15) years following the date of Licensor\'s written notice ("Notice of Delivery") to Distributor that Licensor is ready to make "Delivery" (as defined below) of "Bonded Materials" (as defined below). Notwithstanding the foregoing, in the event the Minimum Guarantee is not recouped by the date that the Term would otherwise expire, and provided that Distributor provides Licensor with an accounting evidencing that the Minimum Guarantee has not been recouped during the thirty (30) day period immediately prior to the date the Term would otherwise expire, the Term shall be extended for an additional period ("Extended Term") which shall last until the earlier of (i) the date that Distributor has recouped the Minimum Guarantee and three (3) years from the date the term was originally set to expire.',
    'territoryTerritories': 'CANADA, AUSTRALIA and NEW ZEALAND (including, subject to Paragraph 3(e) below, Papua/New Guinea, New Britain, New Ireland, Admiralty Islands, Solomon Islands (including Bougainville), Vanuatu, Christmas Islands, Ashmore & Cartier Islands, Ocean Island, Nauru, Australian Antarctica, Cocos (Keeling) Islands, Coral Sea Islands, Heard and MacDonald Islands, and solely for the English language New Caledonia; and New Zealand, including Cook Islands, Fijian Islands, Samoan Islands, Tonga, Rarotonga, Norfolk Island, Kiribati (formerly Gilbert Islands), Tuvalu (formerly Ellice Islands), Niue, Phoenix Islands and The Tokelau Islands)',
    'company': 'VVS FILMS'},
   'folderMeta': {'owner': 'BA', 'division': 'Film'}},
  'canonical': {'projectname': 'THE INVITE',
   'compensationFees': 1300000.0,
   'term': 'For all rights licensed herein, the term ("Term") shall commence on the date set forth above, and continue for fifteen (15) years following the date of Licensor\'s written notice ("Notice of Delivery") to Distributor that Licensor is ready to make "Delivery" (as defined below) of "Bonded Materials" (as defined below). Notwithstanding the foregoing, in the event the Minimum Guarantee is not recouped by the date that the Term would otherwise expire, and provided that Distributor provides Licensor with an accounting evidencing that the Minimum Guarantee has not been recouped during the thirty (30) day period immediately prior to the date the Term would otherwise expire, the Term shall be extended for an additional period ("Extended Term") which shall last until the earlier of (i) the date that Distributor has recouped the Minimum Guarantee and three (3) years from the date the term was originally set to expire.',
   'territoryTerritories': 'CANADA, AUSTRALIA and NEW ZEALAND (including, subject to Paragraph 3(e) below, Papua/New Guinea, New Britain, New Ireland, Admiralty Islands, Solomon Islands (including Bougainville), Vanuatu, Christmas Islands, Ashmore & Cartier Islands, Ocean Island, Nauru, Australian Antarctica, Cocos (Keeling) Islands, Coral Sea Islands, Heard and MacDonald Islands, and solely for the English language New Caledonia; and New Zealand, including Cook Islands, Fijian Islands, Samoan Islands, Tonga, Rarotonga, Norfolk Island, Kiribati (formerly Gilbert Islands), Tuvalu (formerly Ellice Islands), Niue, Phoenix Islands and The Tokelau Islands)',
   'company': 'VVS FILMS',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2119974483634',
  'filename': '01a. INVITE - Original Picture Option Purchase - FE.pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': '828769775',
  'templates': {'baRightsAgreement': {'optionExtensionTermAndFees': 'Purchaser has the option to extend the Initial Option Period for an additional eighteen (18) month period (the "Extension Option Period") by written notice on or before the expiration date of the Initial Option Period and an additional payment of Twenty Thousand Dollars ($20,000) to Owner (the "Extension Option Payment") within ten (10) business days thereafter. The Extension Option Payment shall be non-applicable against the "Purchase Price".',
    'optionStatus': 'Initial Option',
    'purchasePrice': 200000.0,
    'rightsHolder': 'Castelao Pictures, SLU (operating as "Filmax")',
    'optionNotes': "The Option Period shall be deemed automatically suspended, and thus extended, for (i) the entire duration of any third party claim which arises from a breach or alleged breach of Owner's representations, warranties or agreements hereunder, and/or (ii) the length of any industry wide labor dispute or force majeure event which interrupts, hinders or prevents Purchaser from development or pre-production activities in connection with any production intended to be based upon the Property. In the event that the Option Period would otherwise expire on a Saturday, Sunday or national holiday, said period shall be extended without notice until the end of the next following business day.",
    'commencementDate': '2021-10-21T00:00:00.000Z',
    'currentOptionTermsAndFees': 'Twenty Thousand Dollars ($20,000) payable within ten (10) business days of full execution and satisfaction of Conditions Precedent. This sum is fully applicable against, and reduces, the Purchase Price. The Initial Option Period is eighteen (18) months.',
    'optionExpiration': '2024-01-21T00:00:00.000Z',
    'hub_id': '828769775'},
   'folderMeta': {'owner': 'BA', 'division': 'Film', 'hub_id': '828769775'}},
  'canonical': {'optionExtensionTermAndFees': 'Purchaser has the option to extend the Initial Option Period for an additional eighteen (18) month period (the "Extension Option Period") by written notice on or before the expiration date of the Initial Option Period and an additional payment of Twenty Thousand Dollars ($20,000) to Owner (the "Extension Option Payment") within ten (10) business days thereafter. The Extension Option Payment shall be non-applicable against the "Purchase Price".',
   'optionStatus': 'Initial Option',
   'purchasePrice': 200000.0,

In [32]:
file_id_list

['2041161844567',
 '2041164284871',
 '2041165418316',
 '2041165418316',
 '2052695099974',
 '2153822749844',
 '2044693703611',
 '2044693703611',
 '2044695313708',
 '2044695313708',
 '2044700014987',
 '2119974483634',
 '2119974483634',
 '2119975951128',
 '2119975951128',
 '2119976975079',
 '2119976975079',
 '2119977220029',
 '2119977220029',
 '2119977403111',
 '2119977403111',
 '2119977630419',
 '2119977630419',
 '2119977630419',
 '2119977662134',
 '2119977662134',
 '2119978724721',
 '2119978724721',
 '2119978724721',
 '2119980865905',
 '2119980865905',
 '2119983778968',
 '2119983778968',
 '2119984237503',
 '2119984237503',
 '2119987295165',
 '2119987295165',
 '2119987573634',
 '2119987573634',
 '2122991245901',
 '2122991245901',
 '2122991245901',
 '2123701194432',
 '2052454427437',
 '2052457545572',
 '2052462100258',
 '2052462754937',
 '2131714842889',
 '2119879353140',
 '2119879353140',
 '2119884021444',
 '2119884021444',
 '2119887403146',
 '2119887403146',
 '2041170894718',
 '2041170894718',
 '2052597952702',
 '2052601820798',
 '2052607194571',
 '2052607194571',
 '2052608272404',
 '2052608272404',
 '2052610144637',
 '2052613323635',
 '2052613323635',
 '2052622240787',
 '2052622240787',
 '2119689359544',
 '2119689359544',
 '2119689359544',
 '2140668131244',
 '2119693110070',
 '2129699409297',
 '2129699409297',
 '2119977244696',
 '2119977244696',
 '2119973601084',
 '2119973601084',
 '2119978566577',
 '2119978566577',
 '2119977518170',
 '2119977518170',
 '2119973140709',
 '2119973140709',
 '2119980152827',
 '2119980152827',
 '2139686543879',
 '2119972064851',
 '2119972064851',
 '2133179442957',
 '2119978165879',
 '2119978165879',
 '2052397698343',
 '2052397288070',
 '2052394318827',
 '2052395370375',
 '2052396189270',
 '2052397903063',
 '2052401835808',
 '2052397670365',
 '2052396642837',
 '2052391100669',
 '2052394197401',
 '2052397657890',
 '2052390375931',
 '2052396513130',
 '2052396748295',
 '2052393709446',
 '2052396015997',
 '2052393445867',
 '2052391782412',
 '2052391987084',
 '2052396952668',
 '2052390954650',
 '2052396654309',
 '2052400533040',
 '2052400763539',
 '2052398566882',
 '2052396107913',
 '2119691793586',
 '2119689796223',
 '2119690830702',
 '2119688762008',
 '2119684058382',
 '2119684379308',
 '2124310771055',
 '2052457914555',
 '2052462176428',
 '2052452939340',
 '2052455252761',
 '2130724808803',
 '2044549657716']

for doc in docs:
    doc_id = doc.get("_id")
    doc["summary"] = summary_dict.get(doc_id)

In [33]:
docs

[{'_id': '2119977630419',
  'filename': 'The Invite_Uniform Counter for U.S. Distribution Deal.docx',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': '828769775',
  'templates': {'baDistributionAgreement': {'projectname': 'The Invite',
    'compensationFees': 17.5,
    'screenCommitment': 1000.0,
    'term': '15 years + 5 if unrecouped',
    'territoryTerritories': 'THE UNITED STATES OF AMERICA and its respective territories and possessions',
    'company': 'U.S. Distributor',
    'hub_id': '828769775'},
   'baSalesAgreement': {'hub_id': '828769775'},
   'folderMeta': {'owner': 'BA', 'division': 'Film', 'hub_id': '828769775'}},
  'canonical': {'projectname': 'The Invite',
   'compensationFees': 17.5,
   'screenCommitment': 1000.0,
   'term': '15 years + 5 if unrecouped',
   'territoryTerritories': 'THE UNITED STATES OF AMERICA and its respective territories and possessions',
   'company': 'U.S. Distributor',
   'hub_id': '828769775',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2122991245901',
  'filename': 'THE INVITE - 1.29.26.pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': '828769775',
  'templates': {'baDistributionAgreement': {'projectname': 'The Invite',
    'compensationFees': 9577000.0,
    'territoryTerritories': 'Worldwide',
    'company': 'FilmNation Entertainment',
    'hub_id': '828769775'},
   'baSalesAgreement': {'projectname': 'The Invite',
    'compensationFees': 9577000.0,
    'hub_id': '828769775'},
   'folderMeta': {'owner': 'BA', 'division': 'Film', 'hub_id': '828769775'}},
  'canonical': {'projectname': 'The Invite',
   'compensationFees': 9577000.0,
   'territoryTerritories': 'Worldwide',
   'company': 'FilmNation Entertainment',
   'hub_id': '828769775',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2129699409297',
  'filename': 'Invite.Atrium.MLA.FE.pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': None,
  'templates': {'baDistributionAgreement': {'term': 'The Term of this Agreement shall commence on the date of execution of the first Distribution Agreement and shall expire for each country of the Territory on the date which is one (1) year later or until the applicable Distribution Agreements under this Agreement have expired, whichever is the later.',
    'company': 'Atrium Productions Kft.'},
   'folderMeta': {'owner': 'BA', 'division': 'Film'}},
  'canonical': {'term': 'The Term of this Agreement shall commence on the date of execution of the first Distribution Agreement and shall expire for each country of the Territory on the date which is one (1) year later or until the applicable Distribution Agreements under this Agreement have expired, whichever is the later.',
   'company': 'Atrium Productions Kft.',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2119977244696',
  'filename': 'Invite.Bir.Turkey.DA.FE.pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': None,
  'templates': {'baDistributionAgreement': {'projectname': 'THE INVITE.',
    'compensationFees': 25000.0,
    'term': 'ten (10) years',
    'territoryTerritories': 'TURKEY',
    'company': 'YENI BIR FILM LTD'},
   'folderMeta': {'owner': 'BA', 'division': 'Film'}},
  'canonical': {'projectname': 'THE INVITE.',
   'compensationFees': 25000.0,
   'term': 'ten (10) years',
   'territoryTerritories': 'TURKEY',
   'company': 'YENI BIR FILM LTD',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2119973601084',
  'filename': 'Invite.GER.Exh.FE.pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': None,
  'templates': {'baDistributionAgreement': {'projectname': 'THE INVITE',
    'compensationFees': 1790000.0,
    'term': "shall commence on the date set forth above and continue for twenty (20) years following the earlier of (i) Licensee's Distributor's initial release of the Picture in the Territory (it being agreed that marketing and promotion [including test screenings and screenings at festivals] of the Picture shall not be considered as a release of the Picture) or (ii) four (4) months following Licensee's Distributor's Technical Acceptance of the Initial Materials. Notwithstanding the foregoing, in the event the Minimum Guarantee and/or the Recoupable Distribution Expenses are not recouped by the date that the Term would otherwise expire, and provided that Licensee's Distributor provides Licensor with an accounting evidencing that the Minimum Guarantee and/or the Recoupable Distribution Expenses has not been recouped during the last six (6) months of the original Term, the Term shall be automatically extended for an additional period which shall last until one (1) year from the date the Term was originally set to expire.",
    'territoryTerritories': 'Exclusive Territory: Germany and Austria\nNon-Exclusive Territory: Alto Adige, Liechtenstein, Luxembourg, Switzerland',
    'company': 'GEM Entertainment Kft.'},
   'folderMeta': {'owner': 'BA', 'division': 'Film'}},
  'canonical': {'projectname': 'THE INVITE',
   'compensationFees': 1790000.0,
   'term': "shall commence on the date set forth above and continue for twenty (20) years following the earlier of (i) Licensee's Distributor's initial release of the Picture in the Territory (it being agreed that marketing and promotion [including test screenings and screenings at festivals] of the Picture shall not be considered as a release of the Picture) or (ii) four (4) months following Licensee's Distributor's Technical Acceptance of the Initial Materials. Notwithstanding the foregoing, in the event the Minimum Guarantee and/or the Recoupable Distribution Expenses are not recouped by the date that the Term would otherwise expire, and provided that Licensee's Distributor provides Licensor with an accounting evidencing that the Minimum Guarantee and/or the Recoupable Distribution Expenses has not been recouped during the last six (6) months of the original Term, the Term shall be automatically extended for an additional period which shall last until one (1) year from the date the Term was originally set to expire.",
   'territoryTerritories': 'Exclusive Territory: Germany and Austria\nNon-Exclusive Territory: Alto Adige, Liechtenstein, Luxembourg, Switzerland',
   'company': 'GEM Entertainment Kft.',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2119978566577',
  'filename': 'Invite.Longride.Japan.DA (FE).pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': None,
  'templates': {'baDistributionAgreement': {'projectname': 'THE INVITE',
    'compensationFees': 75000.0,
    'term': 'For all rights licensed herein, the term ("Term") shall commence on the date set forth above, and continue for ten (10) years following the date of Licensor\'s written notice ("Notice of Delivery") to Distributor that Licensor is ready to make "Initial Delivery" (as defined below) of the "Initial Materials" (as defined below). Notwithstanding the foregoing, in the event the Minimum Guarantee is not recouped by the date that the Term would otherwise expire...the Term shall be extended for an additional period (*Extended Term") which shall last until the earlier of the date that Distributor has recouped the Minimum Guarantee and three (3) years from the date the term was originally set to expire.',
    'territoryTerritories': 'JAPAN',
    'company': 'LONGRIDE INC.'},
   'folderMeta': {'owner': 'BA', 'division': 'Film'}},
  'canonical': {'projectname': 'THE INVITE',
   'compensationFees': 75000.0,
   'term': 'For all rights licensed herein, the term ("Term") shall commence on the date set forth above, and continue for ten (10) years following the date of Licensor\'s written notice ("Notice of Delivery") to Distributor that Licensor is ready to make "Initial Delivery" (as defined below) of the "Initial Materials" (as defined below). Notwithstanding the foregoing, in the event the Minimum Guarantee is not recouped by the date that the Term would otherwise expire...the Term shall be extended for an additional period (*Extended Term") which shall last until the earlier of the date that Distributor has recouped the Minimum Guarantee and three (3) years from the date the term was originally set to expire.',
   'territoryTerritories': 'JAPAN',
   'company': 'LONGRIDE INC.',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2119977518170',
  'filename': 'Invite.Monolith.Poland.DA (FullyX).pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': None,
  'templates': {'baDistributionAgreement': {'projectname': 'THE INVITE.',
    'compensationFees': 350000.0,
    'term': 'For all rights licensed herein, the Term shall commence on the date set forth above, and continue for seventeen (17) years following the date of the the Availability Date (as defined below). Notwithstanding the foregoing, in the event the Minimum Guarantee is not recouped by the date that the Term would otherwise expire, and provided that Distributor provides Licensor with an accounting evidencing that the Minimum Guarantee has not been recouped during the thirty (30) day period immediately prior to the date the Term would otherwise expire, the Term shall be extended for an additional period ("Extended Term") which shall last until three (3) years from the date the term was originally set to expire.',
    'territoryTerritories': 'POLAND and MONGOLIA.',
    'company': 'MONOLITH INTERNATIONAL LTD.'},
   'folderMeta': {'owner': 'BA', 'division': 'Film'}},
  'canonical': {'projectname': 'THE INVITE.',
   'compensationFees': 350000.0,
   'term': 'For all rights licensed herein, the Term shall commence on the date set forth above, and continue for seventeen (17) years following the date of the the Availability Date (as defined below). Notwithstanding the foregoing, in the event the Minimum Guarantee is not recouped by the date that the Term would otherwise expire, and provided that Distributor provides Licensor with an accounting evidencing that the Minimum Guarantee has not been recouped during the thirty (30) day period immediately prior to the date the Term would otherwise expire, the Term shall be extended for an additional period ("Extended Term") which shall last until three (3) years from the date the term was originally set to expire.',
   'territoryTerritories': 'POLAND and MONGOLIA.',
   'company': 'MONOLITH INTERNATIONAL LTD.',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2119973140709',
  'filename': 'Invite.Shaw.Singapore.DA (FullyX) - date added.pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': None,
  'templates': {'baDistributionAgreement': {'projectname': 'THE INVITE',
    'compensationFees': 7000.0,
    'term': 'seven (7) years following the date of Licensor\'s written notice ("Notice of Delivery")',
    'territoryTerritories': 'SINGAPORE and MYANMAR',
    'company': 'SHAW RENTERS (SINGAPORE) PTE LIMITED'},
   'folderMeta': {'owner': 'BA', 'division': 'Film'}},
  'canonical': {'projectname': 'THE INVITE',
   'compensationFees': 7000.0,
   'term': 'seven (7) years following the date of Licensor\'s written notice ("Notice of Delivery")',
   'territoryTerritories': 'SINGAPORE and MYANMAR',
   'company': 'SHAW RENTERS (SINGAPORE) PTE LIMITED',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2119980152827',
  'filename': 'Invite.Sun.Spain+Portugal+LatAm+So_Africa+DA (FullyX).pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': None,
  'templates': {'baDistributionAgreement': {'projectname': 'THE INVITE',
    'compensationFees': 1500000.0,
    'term': 'For all rights licensed herein, the term ("Term") shall commence on the date set forth above, and continue for twenty (20) years following the date of Licensor\'s written notice ("Notice of Delivery") to Distributor that Licensor is ready to make "Initial Delivery" (as defined below) of the "Initial Materials" (as defined below).',
    'territoryTerritories': 'the Spanish Territory, the Portuguese Territory, the LatAm Territory, and the South African Territory',
    'company': 'SUN DISTRIBUTION GROUP S.A.'},
   'folderMeta': {'owner': 'BA', 'division': 'Film'}},
  'canonical': {'projectname': 'THE INVITE',
   'compensationFees': 1500000.0,
   'term': 'For all rights licensed herein, the term ("Term") shall commence on the date set forth above, and continue for twenty (20) years following the date of Licensor\'s written notice ("Notice of Delivery") to Distributor that Licensor is ready to make "Initial Delivery" (as defined below) of the "Initial Materials" (as defined below).',
   'territoryTerritories': 'the Spanish Territory, the Portuguese Territory, the LatAm Territory, and the South African Territory',
   'company': 'SUN DISTRIBUTION GROUP S.A.',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2119972064851',
  'filename': 'Invite.Tobis.Germany.Company Guarantee.FE.pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': None,
  'templates': {'baDistributionAgreement': {'projectname': 'THE INVITE',
    'term': 'the entire Term of the Picture pursuant to the Agreement',
    'territoryTerritories': 'the Territory as defined in the Agreement',
    'company': 'Tobis Film GmbH'},
   'folderMeta': {'owner': 'BA', 'division': 'Film'}},
  'canonical': {'projectname': 'THE INVITE',
   'term': 'the entire Term of the Picture pursuant to the Agreement',
   'territoryTerritories': 'the Territory as defined in the Agreement',
   'company': 'Tobis Film GmbH',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2119978165879',
  'filename': 'Invite.VVS.Canada+ANZ.DA.FE.pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': None,
  'templates': {'baDistributionAgreement': {'projectname': 'THE INVITE',
    'compensationFees': 1300000.0,
    'term': 'For all rights licensed herein, the term ("Term") shall commence on the date set forth above, and continue for fifteen (15) years following the date of Licensor\'s written notice ("Notice of Delivery") to Distributor that Licensor is ready to make "Delivery" (as defined below) of "Bonded Materials" (as defined below). Notwithstanding the foregoing, in the event the Minimum Guarantee is not recouped by the date that the Term would otherwise expire, and provided that Distributor provides Licensor with an accounting evidencing that the Minimum Guarantee has not been recouped during the thirty (30) day period immediately prior to the date the Term would otherwise expire, the Term shall be extended for an additional period ("Extended Term") which shall last until the earlier of (i) the date that Distributor has recouped the Minimum Guarantee and three (3) years from the date the term was originally set to expire.',
    'territoryTerritories': 'CANADA, AUSTRALIA and NEW ZEALAND (including, subject to Paragraph 3(e) below, Papua/New Guinea, New Britain, New Ireland, Admiralty Islands, Solomon Islands (including Bougainville), Vanuatu, Christmas Islands, Ashmore & Cartier Islands, Ocean Island, Nauru, Australian Antarctica, Cocos (Keeling) Islands, Coral Sea Islands, Heard and MacDonald Islands, and solely for the English language New Caledonia; and New Zealand, including Cook Islands, Fijian Islands, Samoan Islands, Tonga, Rarotonga, Norfolk Island, Kiribati (formerly Gilbert Islands), Tuvalu (formerly Ellice Islands), Niue, Phoenix Islands and The Tokelau Islands)',
    'company': 'VVS FILMS'},
   'folderMeta': {'owner': 'BA', 'division': 'Film'}},
  'canonical': {'projectname': 'THE INVITE',
   'compensationFees': 1300000.0,
   'term': 'For all rights licensed herein, the term ("Term") shall commence on the date set forth above, and continue for fifteen (15) years following the date of Licensor\'s written notice ("Notice of Delivery") to Distributor that Licensor is ready to make "Delivery" (as defined below) of "Bonded Materials" (as defined below). Notwithstanding the foregoing, in the event the Minimum Guarantee is not recouped by the date that the Term would otherwise expire, and provided that Distributor provides Licensor with an accounting evidencing that the Minimum Guarantee has not been recouped during the thirty (30) day period immediately prior to the date the Term would otherwise expire, the Term shall be extended for an additional period ("Extended Term") which shall last until the earlier of (i) the date that Distributor has recouped the Minimum Guarantee and three (3) years from the date the term was originally set to expire.',
   'territoryTerritories': 'CANADA, AUSTRALIA and NEW ZEALAND (including, subject to Paragraph 3(e) below, Papua/New Guinea, New Britain, New Ireland, Admiralty Islands, Solomon Islands (including Bougainville), Vanuatu, Christmas Islands, Ashmore & Cartier Islands, Ocean Island, Nauru, Australian Antarctica, Cocos (Keeling) Islands, Coral Sea Islands, Heard and MacDonald Islands, and solely for the English language New Caledonia; and New Zealand, including Cook Islands, Fijian Islands, Samoan Islands, Tonga, Rarotonga, Norfolk Island, Kiribati (formerly Gilbert Islands), Tuvalu (formerly Ellice Islands), Niue, Phoenix Islands and The Tokelau Islands)',
   'company': 'VVS FILMS',
   'owner': 'BA',
   'division': 'Film'}},
 {'_id': '2119974483634',
  'filename': '01a. INVITE - Original Picture Option Purchase - FE.pdf',
  'updated_time': datetime.datetime(2026, 3, 9, 13, 34, 36, 836164),
  'hub_id': '828769775',
  'templates': {'baRightsAgreement': {'optionExtensionTermAndFees': 'Purchaser has the option to extend the Initial Option Period for an additional eighteen (18) month period (the "Extension Option Period") by written notice on or before the expiration date of the Initial Option Period and an additional payment of Twenty Thousand Dollars ($20,000) to Owner (the "Extension Option Payment") within ten (10) business days thereafter. The Extension Option Payment shall be non-applicable against the "Purchase Price".',
    'optionStatus': 'Initial Option',
    'purchasePrice': 200000.0,
    'rightsHolder': 'Castelao Pictures, SLU (operating as "Filmax")',
    'optionNotes': "The Option Period shall be deemed automatically suspended, and thus extended, for (i) the entire duration of any third party claim which arises from a breach or alleged breach of Owner's representations, warranties or agreements hereunder, and/or (ii) the length of any industry wide labor dispute or force majeure event which interrupts, hinders or prevents Purchaser from development or pre-production activities in connection with any production intended to be based upon the Property. In the event that the Option Period would otherwise expire on a Saturday, Sunday or national holiday, said period shall be extended without notice until the end of the next following business day.",
    'commencementDate': '2021-10-21T00:00:00.000Z',
    'currentOptionTermsAndFees': 'Twenty Thousand Dollars ($20,000) payable within ten (10) business days of full execution and satisfaction of Conditions Precedent. This sum is fully applicable against, and reduces, the Purchase Price. The Initial Option Period is eighteen (18) months.',
    'optionExpiration': '2024-01-21T00:00:00.000Z',
    'hub_id': '828769775'},
   'folderMeta': {'owner': 'BA', 'division': 'Film', 'hub_id': '828769775'}},
  'canonical': {'optionExtensionTermAndFees': 'Purchaser has the option to extend the Initial Option Period for an additional eighteen (18) month period (the "Extension Option Period") by written notice on or before the expiration date of the Initial Option Period and an additional payment of Twenty Thousand Dollars ($20,000) to Owner (the "Extension Option Payment") within ten (10) business days thereafter. The Extension Option Payment shall be non-applicable against the "Purchase Price".',
   'optionStatus': 'Initial Option',
   'purchasePrice': 200000.0,

In [34]:
TO MONGO

SyntaxError: invalid syntax (1712733337.py, line 1)

In [35]:
from pymongo import UpdateOne

## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [36]:
db = client['InDevelopment']
collection = db['box_metadata']

collection.delete_many({})

In [37]:

ops = [
    UpdateOne({"_id": d["_id"]}, {"$set": d}, upsert=True)
    for d in docs
]

result = collection.bulk_write(ops, ordered=False)
print("matched:", result.matched_count, "upserted:", len(result.upserted_ids))

matched: 93 upserted: 0

In [38]:
SUMMARY

NameError: name 'SUMMARY' is not defined

In [48]:
docs = collection.find({
    '$or': [
        {
            'summary': {
                '$exists': False
            }
        }, {
            'summary': ''
        }
    ]
})

In [49]:
id_list = pd.DataFrame(docs)

id_list = id_list['_id'].to_list() if len(id_list) >0 else []
id_list

['2052455252761', '2130724808803']

In [50]:
prompt = """
            Provide an executive summary of this document using exactly 3 bullet points.
            Prioritize key financial terms, obligations, and outcomes.
            Write in plain, direct language for fast scanning.
            Limit each bullet to one sentence (max 20 words).
            Do not include filler or ask follow-up questions.
"""

In [51]:
prompt.strip()

'Provide an executive summary of this document using exactly 3 bullet points.\n            Prioritize key financial terms, obligations, and outcomes.\n            Write in plain, direct language for fast scanning.\n            Limit each bullet to one sentence (max 20 words).\n            Do not include filler or ask follow-up questions.'

In [52]:
summary_dict = {}

for file in id_list:
    url = "https://api.box.com/2.0/ai/ask"

    payload = {
        "mode": "single_item_qa",
        "items": [{"id": f"{file}", "type": "file"}],
        "prompt": prompt.strip()
    }
    headers = {
        "Authorization": f"Bearer {access_token}",
        "Content-Type": "application/json",
        "Box-Version": "2024.0",   # important for hubs
    }
    
    r = requests.post(url, headers=headers, json=payload, timeout=60)
    
    print("status:", r.status_code)
    #print("text:", r.text)
    
    # If it's JSON, pretty print it
    try:
        summary = r.json()['answer']
        summary_dict[file] = summary
    except Exception:
        pass

status: 400
status: 400

In [53]:
summary_dict

{}

In [54]:
stop

NameError: name 'stop' is not defined

In [55]:
from pymongo import UpdateOne

ops = [
    UpdateOne(
        {"_id": _id},
        {"$set": {"summary": summary}},
        upsert=True
    )
    for _id, summary in summary_dict.items()
]

result = collection.bulk_write(ops, ordered=False)

print(
    "matched:", result.matched_count,
    "upserted:", len(result.upserted_ids)
)

InvalidOperation: No operations to execute

In [ ]:
client.close()