In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_excel("development_tracker/APH Development Tracker - 12.05.25.xlsx", sheet_name='ALL SUMMARY')

In [3]:
df

,Annapurna,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,Development Report by Project by Department,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"As of December 5, 2025",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,Inception To Date,Year To Date,Inception To Date,Year To Date,ITD TOTAL SPEND,NaN,NaN,...,Remaining,NaN,NaN,ITD w Commitments,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Status,2023-12-31 00:00:00,2024-12-31 00:00:00,2024-12-31 00:00:00,2025-12-05 00:00:00,2025-12-05 00:00:00,Q4 2025,Q1 2026,...,NaN,NaN,check,2025-12-31 00:00:00,NaN,Changes from Prior,NaN,SUMMARY,NaN,DATE ADDED
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,Total Theatre,NaN,NaN,0,0,0,8593.17,8593.17,NaN,NaN,...,220000,NaN,NaN,448593.17,NaN,NaN,NaN,NaN,NaN,NaN
139,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,All Depts,NaN,NaN,5028531.94,4130666.79,8497754.13,6648269.04,15146023.17,1118250.58,5137201.405333,...,16541233.432,1363088.75,0,33812145.152,NaN,NaN,NaN,NaN,NaN,NaN
141,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
col_names = df.iloc[3].dropna()
col_dates = df.iloc[4].dropna()

In [5]:
col_actuals = df.iloc[5].dropna()

In [6]:
col_filter = ['Unnamed: 1','Unnamed: 2'] + list(set(col_names.index.to_list() + col_actuals.index.to_list()))

df.index[df['Annapurna'] == 'Total Film (Closed Deals)']

In [7]:
start_index = df.index[df['Annapurna'] == 'Film'][0]+1
stop_index = df.index[df['Annapurna'] == 'Total Film (Closed + Capitalized Deals)'][0]-1

In [8]:
start_index_consult = df.index[df['Annapurna'] == 'Total Film (Closed + Capitalized Deals)'][0]+2
stop_index_consult = df.index[df['Annapurna'] == 'Total Film (Closed + Capitalized + Expensed Deals)'][0]-1

In [9]:
start_index_pending = df.index[df['Annapurna'] == 'Total Film (Closed + Capitalized + Expensed Deals)'][0]+2
stop_index_pending = df.index[df['Annapurna'] == 'Total Film (Closed + Capitalized + Expensed Deals + Pending)'][0]-1

In [10]:
start_index_TV = df.index[df['Annapurna'] == 'TV'][0]+1
stop_index_TV = df.index[df['Annapurna'] == 'Total TV (Closed + Capitalized Deals)'][0]-1

In [11]:
start_index_consult_TV = df.index[df['Annapurna'] == 'Total TV (Closed + Capitalized Deals)'][0]+2
stop_index_consult_TV = df.index[df['Annapurna'] == 'Total TV (Closed + Capitalized + Expensed Deals)'][0]-1

In [12]:
start_index_pending_TV = df.index[df['Annapurna'] == 'Total TV (Closed + Capitalized + Expensed Deals)'][0]+2
stop_index_pending_TV = df.index[df['Annapurna'] == 'Total TV (Closed + Capitalized + Expensed Deals + Pending)'][0]-1

In [13]:
start_index_corporate = df.index[df['Annapurna'] == 'Corporate'][0]+1
stop_index_corporate = df.index[df['Annapurna'] == ' Total Corporate'][0]-1

In [14]:
start_index_ani_film = df.index[df['Annapurna'] == 'Animation (Film)'][0]+1
stop_index_ani_film = df.index[df['Annapurna'] == 'Total Animation (Film)'][0]-1

In [15]:
start_index_ani_tv = df.index[df['Annapurna'] == 'Animation (TV)'][0]+1
stop_index_ani_tv = df.index[df['Annapurna'] == 'Total Animation (TV)'][0]-1

In [16]:
start_index_theatre = df.index[df['Annapurna'] == 'Theatre'][0]+1
stop_index_theatre = df.index[df['Annapurna'] == 'Total Theatre'][0]-1

In [17]:
data = df[start_index:stop_index]
data['division'] = "Film"
data_pending = df[start_index_pending:stop_index_pending]
data_pending['division'] = "Film"

data_tv = df[start_index_TV:stop_index_TV]
data_tv['division'] = "TV"

data_pending_TV = df[start_index_pending_TV:stop_index_pending_TV]
data_pending_TV['division'] = "TV"

data_corp = df[start_index_corporate:stop_index_corporate]
data_corp['division'] = "corporate"

data_ani_film = df[start_index_ani_film:stop_index_ani_film]
data_ani_film['division'] = "Animation_Film"

data_ani_TV= df[start_index_ani_tv:stop_index_ani_tv]
data_ani_TV['division'] = "Animation_TV"

data_ani_Theatre= df[start_index_theatre:stop_index_theatre]
data_ani_Theatre['division'] = "Theatre"


data_film_consult= df[start_index_consult:stop_index_consult]
data_film_consult['division'] = "Film"

data_tv_consult = df[start_index_consult_TV:stop_index_consult_TV]
data_tv_consult['division'] = "TV"

In [18]:
data = data.reset_index()
data['_id'] = data['Unnamed: 1'] + "_" + data['division'].astype(str)#  + "_" + data['index'].astype(str)

data_pending = data_pending.reset_index()
data_pending['_id'] = data_pending['Unnamed: 1']+ "_" + data_pending['division'].astype(str)#   + "_" + data_pending['index'].astype(str)

data_tv = data_tv.reset_index()
data_tv['_id'] = data_tv['Unnamed: 1']+ "_" + data_tv['division'].astype(str)#   + "_" + data_tv['index'].astype(str)

data_pending_TV = data_pending_TV.reset_index()
data_pending_TV['_id'] = data_pending_TV['Unnamed: 1']+ "_" + data_pending_TV['division'].astype(str)#   + "_" + data_pending_TV['index'].astype(str)

data_corp = data_corp.reset_index()
data_corp['_id'] = data_corp['Unnamed: 1']+ "_" + data_corp['division'].astype(str)#   + "_" + data_corp['index'].astype(str)

data_ani_film = data_ani_film.reset_index()
data_ani_film['_id'] = data_ani_film['Unnamed: 1']+ "_" + data_ani_film['division'].astype(str)#   + "_" + data_ani_film['index'].astype(str)

data_ani_TV = data_ani_TV.reset_index()
data_ani_TV['_id'] = data_ani_TV['Unnamed: 1']+ "_" + data_ani_TV['division'].astype(str)#   + "_" + data_ani_TV['index'].astype(str)

data_ani_Theatre = data_ani_Theatre.reset_index()
data_ani_Theatre['_id'] = data_ani_Theatre['Unnamed: 1']+ "_" + data_ani_Theatre['division'].astype(str)#   + "_" + data_ani_Theatre['index'].astype(str)


data_film_consult = data_film_consult.reset_index()
data_film_consult['_id'] = data_film_consult['Unnamed: 1']+ "_" + data_film_consult['division'].astype(str)#   + "_" + data_ani_film['index'].astype(str)

data_tv_consult = data_tv_consult.reset_index()
data_tv_consult['_id'] = data_tv_consult['Unnamed: 1']+ "_" + data_tv_consult['division'].astype(str)#   + "_" + data_ani_film['index'].astype(str)

In [19]:
pd.set_option('display.max_columns', None)  # show all columns

data

,index,Annapurna,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,division,_id
0,7,NaN,Even the Losers/ Unt. Randy Lanier,closed deals/active,NaN,NaN,0,2089738.5,2089738.5,0,1513125,500000,500000,0,1250000,3013125,750000,0,5852863.5,NaN,NaN,NaN,script fee $4M; dev fee $1M; $30k option exten...,NaN,NaN,Film,Even the Losers/ Unt. Randy Lanier_Film
1,8,NaN,The Silent Patient - Plan B,closed deals/active,621510.95,1175887.1,1797398.05,143372.5,1940770.55,46593.75,46593.75,0,0,0,0,31062.5,62125,0,2033958.05,NaN,NaN,NaN,polish and optional polish $100K; reflects the...,NaN,NaN,Film,The Silent Patient - Plan B_Film
2,9,NaN,Unt Nicole Taylor,closed deals/active,0,3395,3395,279562.5,282957.5,0,327468.75,142500,30000,0,0,439968.75,60000,0,782926.25,NaN,NaN,NaN,script fee $600K + fringe; optional polish $60K,NaN,NaN,Film,Unt Nicole Taylor_Film
3,10,NaN,American Spartan,closed deals/active,NaN,NaN,0,0,0,187125,187125,249500,0,0,0,623750,NaN,0,623750,NaN,NaN,NaN,$500K first draft + first rewrite,NaN,NaN,Film,American Spartan_Film
4,11,NaN,Unt James Sweeney,closed deals/active,NaN,NaN,0,9940,9940,178733.625,178733.625,76600.125,76600.125,0,48457.5,510667.5,48457.5,0,569065,NaN,NaN,NaN,script fee $411K + fringe; optional polish $39K,NaN,NaN,Film,Unt James Sweeney_Film
5,12,NaN,Cuban Missile Crisis,closed deals/active,NaN,NaN,0,187925,187925,0,126225,49900,49900,0,140000,226025,140000,0,553950,NaN,NaN,NaN,option $40K; script $330K + fringe; $85K optio...,NaN,NaN,Film,Cuban Missile Crisis_Film
6,13,NaN,Unt Bennett Miller (fka Untitled Charlie Kaufm...,closed deals/active,0,463944.9,463944.9,-374781.25,89163.65,0,0,0,0,0,454687.5,454687.5,NaN,0,543851.15,NaN,NaN,NaN,delivery of first draft $375K + fringe; $20K r...,NaN,NaN,Film,Unt Bennett Miller (fka Untitled Charlie Kaufm...
7,14,NaN,Five Hitmen,closed deals/active,0,56192.5,56192.5,200065.23,256257.73,93868.75,37275,37275,0,0,102506.25,168418.75,102506.25,0,527182.73,NaN,NaN,NaN,option $10K; remaining script fee $195K + frin...,NaN,NaN,Film,Five Hitmen_Film
8,15,NaN,Untitled Dolly Parton,closed deals/active,0,0,0,5300,5300,0,124750,124750,187125,0,0,436625,NaN,0,441925,NaN,NaN,NaN,script fee $350K + fringe (pending writing deal),NaN,NaN,Film,Untitled Dolly Parton_Film
9,16,NaN,Finding Gobi,closed deals/active,0,15462.5,15462.5,18130,33592.5,0,124250,124250,62125,62125,0,372750,NaN,0,406342.5,NaN,NaN,NaN,script fee $300K + fringe (pending writing deal),NaN,NaN,Film,Finding Gobi_Film
10,17,NaN,Syd,closed deals/active,0,0,0,223650,223650,0,74550,0,0,0,0,74550,NaN,0,298200,NaN,NaN,NaN,script fee $300K + fringe,NaN,NaN,Film,Syd_Film
11,18,NaN,Norco 80,closed deals/active,0,0,0,0,0,167306.255,67500,0,0,0,0,234806.255,NaN,0,234806.255,NaN,NaN,NaN,script $450K + fringe - will be split 50% with...,NaN,NaN,Film,Norco 80_Film
12,19,NaN,Twelve Minutes (Anim/TV),closed deals/active,97049.73,10502.54,107552.27,19.39,107571.66,0,82833.333333,41416.666667,82833.333333,103541.666667,NaN,310625,NaN,0,418196.66,NaN,NaN,NaN,script fee $250K,NaN,NaN,Film,Twelve Minutes (Anim/TV)_Film
13,20,NaN,American Jewel,closed deals/active,NaN,NaN,NaN,32993.48,32993.48,0,101272.32,0,0,0,NaN,101272.32,NaN,0,134265.8,NaN,NaN,NaN,script rewrite $53K; EP deal $75K,NaN,NaN,Film,American Jewel_Film
14,21,NaN,"Untitled Lessovitz, Quesada, Zund",closed deals/active,80040.06,0,80040.06,0,80040.06,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,80040.06,NaN,NaN,NaN,NaN,NaN,NaN,Film,"Untitled Lessovitz, Quesada, Zund_Film"
15,22,NaN,Chef,closed deals/active,0,1885,1885,2420,4305,0,63332.95525,0,0,0,0,63332.95525,NaN,0,67637.95525,NaN,NaN,NaN,WGA scale + 15% $50K + fringe,NaN,NaN,Film,Chef_Film
16,23,NaN,The Lost Wild - Film,closed deals/active,NaN,NaN,0,1100,1100,0,0,0,0,0,0,0,NaN,0,1100,NaN,NaN,NaN,NaN,NaN,NaN,Film,The Lost Wild - Film_Film

In [20]:
combined_data = pd.concat([data,data_pending,data_tv,data_pending_TV,data_corp,data_ani_film,data_ani_TV,data_ani_Theatre, data_film_consult, data_tv_consult])

In [21]:
combined_data['Unnamed: 1'].unique()

array(['Even the Losers/ Unt. Randy Lanier',
       'The Silent Patient - Plan B', 'Unt Nicole Taylor',
       'American Spartan', 'Unt James Sweeney', 'Cuban Missile Crisis',
       'Unt Bennett Miller (fka Untitled Charlie Kaufman Project)',
       'Five Hitmen', 'Untitled Dolly Parton', 'Finding Gobi', 'Syd',
       'Norco 80', 'Twelve Minutes (Anim/TV)', 'American Jewel',
       'Untitled Lessovitz, Quesada, Zund', 'Chef',
       'The Lost Wild - Film', 'Eric Warren Singer', 'Grind',
       'The Legend of Georgia McBride', 'Blankets', 'Belly of the Beast',
       'The Visit', 'Women Clothed by the Sun', 'The New Man',
       'Unt Mr. Beast Fiction Project', 'Monument Valley',
       'Minds on Fire', 'Control', 'Who is Maud Dixon', 'The Original',
       'Hot Kid', 'Planet of Exile', 'Call Me Dad', 'The Voyeur',
       'Unt. Carlo Bernard/International Mercenaries', 'Operator',
       'The Tour', 'The Chosen One', 'Identical', 'Seized',
       'Made in Utah', 'Untitled Mallory Project', 'Strangers',
       'Darkside of the Moon', 'Unt. Death Hoax', 'Alan Wake',
       'Unt. Shi Yang', 'Unt. Equestrian Series', 'Heartstring',
       'Nomad Summer', 'Unt. Sports Fan Show', 'Biggest Little Farm',
       'Unt. Game Doc Series', 'Executive Protection',
       'Unt. John Cho Jean Kyoung Frazier (if/come)',
       'Limbo (TV/FILM tbd)', 'Inside', 'Exit Party', 'Shot to Nothing',
       'Murderland', 'Cutter & Tats', 'Kill the Rabbit',
       'The Drifting Classroom', 'Gravity Let Me Go',
       "Dude Where's My Castle", 'Sia Martinez', 'Calliope',
       'Grant & Sherman', 'England Expects (Film)', 'Mantooth',
       'Stray - Animation', 'Moomins', 'Haiet', 'COMA', 'Antarctica',
       'Hellraiser', 'Nimona', 'FOO (Animation)', "Let's Boogey",
       'Some Assembly Required', 'The Trap', 'Nick Weidenfeld',
       'Sapiens - Animation', 'Witchfeld', 'Living the Dream',
       'NARPS (Non-Associated Regular People)', 'Outlets',
       '20,000 Leagues Under the Sea', 'Donut County - Anim/TV',
       'Center Stage', 'Her', 'Inter Alia (Broadway 2026)',
       'Case of the Existence of God', 'Stephen Feder fee',
       'Conner (Literary Research)'], dtype=object)

In [22]:
col_names = col_names.to_dict()
col_dates = col_dates.to_dict()
col_actuals = col_actuals.to_dict()

col_names['Unnamed: 16'] = "Remaining - Optional"
col_names['Unnamed: 15'] = "Remaining - Committed"

In [23]:
col_actuals

{'Unnamed: 3': 'Actual',
 'Unnamed: 4': 'Actual',
 'Unnamed: 5': 'Actual',
 'Unnamed: 6': 'Actual',
 'Unnamed: 7': 'Actual',
 'Unnamed: 14': 'Committed ',
 'Unnamed: 15': 'Optional',
 'Unnamed: 17': 'Actual + Committed + Optional'}

In [24]:
col_dates

{'Unnamed: 2': 'Status',
 'Unnamed: 3': datetime.datetime(2023, 12, 31, 0, 0),
 'Unnamed: 4': datetime.datetime(2024, 12, 31, 0, 0),
 'Unnamed: 5': datetime.datetime(2024, 12, 31, 0, 0),
 'Unnamed: 6': datetime.datetime(2025, 12, 5, 0, 0),
 'Unnamed: 7': datetime.datetime(2025, 12, 5, 0, 0),
 'Unnamed: 8': 'Q4 2025',
 'Unnamed: 9': 'Q1 2026',
 'Unnamed: 10': 'Q2 2026',
 'Unnamed: 11': 'Q3 2026',
 'Unnamed: 12': 'Q4 2026',
 'Unnamed: 13': 'post 2026',
 'Unnamed: 16': 'check',
 'Unnamed: 17': datetime.datetime(2025, 12, 31, 0, 0),
 'Unnamed: 19': 'Changes from Prior',
 'Unnamed: 21': 'SUMMARY',
 'Unnamed: 23': 'DATE ADDED'}

In [25]:
column_dict = col_actuals
column_dict.update(col_dates)

In [26]:
common_keys = set(col_names) & set(col_dates) & set(col_actuals)
column_dict_2 = {
    k: f"{col_names.get(k, '')} | {col_dates.get(k, '').strftime("%Y")}"
    for k in common_keys
}

In [27]:
column_dict_2

{'Unnamed: 17': 'ITD w Commitments | 2025',
 'Unnamed: 6': 'Year To Date | 2025',
 'Unnamed: 4': 'Year To Date | 2024',
 'Unnamed: 7': 'ITD TOTAL SPEND | 2025',
 'Unnamed: 3': 'Inception To Date | 2023',
 'Unnamed: 5': 'Inception To Date | 2024'}

In [28]:
column_dict.update(column_dict_2)

In [29]:
column_dict

{'Unnamed: 3': 'Inception To Date | 2023',
 'Unnamed: 4': 'Year To Date | 2024',
 'Unnamed: 5': 'Inception To Date | 2024',
 'Unnamed: 6': 'Year To Date | 2025',
 'Unnamed: 7': 'ITD TOTAL SPEND | 2025',
 'Unnamed: 14': 'Committed ',
 'Unnamed: 15': 'Optional',
 'Unnamed: 17': 'ITD w Commitments | 2025',
 'Unnamed: 2': 'Status',
 'Unnamed: 8': 'Q4 2025',
 'Unnamed: 9': 'Q1 2026',
 'Unnamed: 10': 'Q2 2026',
 'Unnamed: 11': 'Q3 2026',
 'Unnamed: 12': 'Q4 2026',
 'Unnamed: 13': 'post 2026',
 'Unnamed: 16': 'check',
 'Unnamed: 19': 'Changes from Prior',
 'Unnamed: 21': 'SUMMARY',
 'Unnamed: 23': 'DATE ADDED'}

In [30]:
combined_data.head()

,index,Annapurna,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,division,_id
0,7,NaN,Even the Losers/ Unt. Randy Lanier,closed deals/active,NaN,NaN,0,2089738.5,2089738.5,0,1513125,500000,500000,0,1250000,3013125,750000,0,5852863.5,NaN,NaN,NaN,script fee $4M; dev fee $1M; $30k option exten...,NaN,NaN,Film,Even the Losers/ Unt. Randy Lanier_Film
1,8,NaN,The Silent Patient - Plan B,closed deals/active,621510.95,1175887.1,1797398.05,143372.5,1940770.55,46593.75,46593.75,0,0,0,0,31062.5,62125,0,2033958.05,NaN,NaN,NaN,polish and optional polish $100K; reflects the...,NaN,NaN,Film,The Silent Patient - Plan B_Film
2,9,NaN,Unt Nicole Taylor,closed deals/active,0,3395,3395,279562.5,282957.5,0,327468.75,142500,30000,0,0,439968.75,60000,0,782926.25,NaN,NaN,NaN,script fee $600K + fringe; optional polish $60K,NaN,NaN,Film,Unt Nicole Taylor_Film
3,10,NaN,American Spartan,closed deals/active,NaN,NaN,0,0,0,187125,187125,249500,0,0,0,623750,NaN,0,623750,NaN,NaN,NaN,$500K first draft + first rewrite,NaN,NaN,Film,American Spartan_Film
4,11,NaN,Unt James Sweeney,closed deals/active,NaN,NaN,0,9940,9940,178733.625,178733.625,76600.125,76600.125,0,48457.5,510667.5,48457.5,0,569065,NaN,NaN,NaN,script fee $411K + fringe; optional polish $39K,NaN,NaN,Film,Unt James Sweeney_Film

In [31]:
stop

NameError: name 'stop' is not defined

In [32]:
column_dict['Unnamed: 1'] = "Title"
#column_dict['Unnamed: 16'] = "Remaining - Optional"
#column_dict['Unnamed: 15'] = "Remaining - Committed"

In [33]:

combined_data = combined_data.rename(column_dict, axis=1)
#data = data.rename(col_names, axis=1)

In [34]:
clean_cols = [col for col in combined_data.columns if "unnamed" not in col.lower() and col != "Annapurna"]

In [35]:
final_data = combined_data[clean_cols]

In [36]:
final_data

,index,Title,Status,Inception To Date | 2023,Year To Date | 2024,Inception To Date | 2024,Year To Date | 2025,ITD TOTAL SPEND | 2025,Q4 2025,Q1 2026,Q2 2026,Q3 2026,Q4 2026,post 2026,Committed,Optional,check,ITD w Commitments | 2025,Changes from Prior,SUMMARY,DATE ADDED,division,_id
0,7,Even the Losers/ Unt. Randy Lanier,closed deals/active,NaN,NaN,0,2089738.5,2089738.5,0,1513125,500000,500000,0,1250000,3013125,750000,0,5852863.5,NaN,script fee $4M; dev fee $1M; $30k option exten...,NaN,Film,Even the Losers/ Unt. Randy Lanier_Film
1,8,The Silent Patient - Plan B,closed deals/active,621510.95,1175887.1,1797398.05,143372.5,1940770.55,46593.75,46593.75,0,0,0,0,31062.5,62125,0,2033958.05,NaN,polish and optional polish $100K; reflects the...,NaN,Film,The Silent Patient - Plan B_Film
2,9,Unt Nicole Taylor,closed deals/active,0,3395,3395,279562.5,282957.5,0,327468.75,142500,30000,0,0,439968.75,60000,0,782926.25,NaN,script fee $600K + fringe; optional polish $60K,NaN,Film,Unt Nicole Taylor_Film
3,10,American Spartan,closed deals/active,NaN,NaN,0,0,0,187125,187125,249500,0,0,0,623750,NaN,0,623750,NaN,$500K first draft + first rewrite,NaN,Film,American Spartan_Film
4,11,Unt James Sweeney,closed deals/active,NaN,NaN,0,9940,9940,178733.625,178733.625,76600.125,76600.125,0,48457.5,510667.5,48457.5,0,569065,NaN,script fee $411K + fringe; optional polish $39K,NaN,Film,Unt James Sweeney_Film
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,135,Inter Alia (Broadway 2026),pending,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,Theatre,Inter Alia (Broadway 2026)_Theatre
3,136,Case of the Existence of God,inactive,0,0,0,8593.17,8593.17,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,8593.17,NaN,NaN,NaN,Theatre,Case of the Existence of God_Theatre
0,27,Stephen Feder fee,closed deals/active,0,176824.8,176824.8,391392.76,568217.56,35581,35581,0,0,0,NaN,71162,NaN,0,639379.56,NaN,5 months of fee $178K,NaN,Film,Stephen Feder fee_Film
1,28,Conner (Literary Research),closed deals/active,153450,34800,188250,31900,220150,2900,8700,8700,8700,8700,0,37700,NaN,0,257850,NaN,15 months @ $2.9K/mo,NaN,Film,Conner (Literary Research)_Film
0,72,Conner (Literary Research),closed deals/active,153450,34800,188250,31900,220150,2900,8700,8700,8700,8700,0,37700,NaN,0,257850,NaN,15 months @ $2.9K/mo,NaN,TV,Conner (Literary Research)_TV

In [37]:
from datetime import datetime
final_data['update_date'] = datetime.today()

In [38]:
type_dict = {'Title':'string', 
             'Status':'string', 
             'Inception To Date | 2023':'float',
             'Year To Date | 2024':'float', 
             'Inception To Date | 2024':'float',
             'Year To Date | 2025':'float', 
             'ITD TOTAL SPEND | 2025':'float',
             'Committed ':'float', 
             'Optional':'float',
             'ITD w Commitments | 2025':'float', 
             'Changes from Prior':'string',
             'SUMMARY':'string'
            }

In [39]:
final_data = final_data.astype(type_dict)

In [40]:
final_data['Committed '].sum()/1_000_000

16.541233432

In [41]:
final_data['ITD w Commitments | 2025'].sum()/1_000_000

33.812145152

In [42]:
final_data['Optional'].sum()/1_000_000

1.36308875

In [43]:
final_data['ITD TOTAL SPEND | 2025'].sum()/1_000_000

15.146023170000001

In [44]:
final_data['Changes from Prior'] = final_data['Changes from Prior'].fillna("")
final_data['SUMMARY'] = final_data['SUMMARY'].fillna("")
final_data['Status'] = final_data['Status'].fillna("")

In [45]:
final_data.query("division =='Film'")

,index,Title,Status,Inception To Date | 2023,Year To Date | 2024,Inception To Date | 2024,Year To Date | 2025,ITD TOTAL SPEND | 2025,Q4 2025,Q1 2026,Q2 2026,Q3 2026,Q4 2026,post 2026,Committed,Optional,check,ITD w Commitments | 2025,Changes from Prior,SUMMARY,DATE ADDED,division,_id,update_date
0,7,Even the Losers/ Unt. Randy Lanier,closed deals/active,NaN,NaN,0.00,2089738.50,2089738.50,0,1513125,500000,500000,0,1250000,3.013125e+06,750000.00,0,5.852864e+06,,script fee $4M; dev fee $1M; $30k option exten...,NaN,Film,Even the Losers/ Unt. Randy Lanier_Film,2025-12-10 06:09:21.519864
1,8,The Silent Patient - Plan B,closed deals/active,621510.95,1175887.10,1797398.05,143372.50,1940770.55,46593.75,46593.75,0,0,0,0,3.106250e+04,62125.00,0,2.033958e+06,,polish and optional polish $100K; reflects the...,NaN,Film,The Silent Patient - Plan B_Film,2025-12-10 06:09:21.519864
2,9,Unt Nicole Taylor,closed deals/active,0.00,3395.00,3395.00,279562.50,282957.50,0,327468.75,142500,30000,0,0,4.399688e+05,60000.00,0,7.829262e+05,,script fee $600K + fringe; optional polish $60K,NaN,Film,Unt Nicole Taylor_Film,2025-12-10 06:09:21.519864
3,10,American Spartan,closed deals/active,NaN,NaN,0.00,0.00,0.00,187125,187125,249500,0,0,0,6.237500e+05,NaN,0,6.237500e+05,,$500K first draft + first rewrite,NaN,Film,American Spartan_Film,2025-12-10 06:09:21.519864
4,11,Unt James Sweeney,closed deals/active,NaN,NaN,0.00,9940.00,9940.00,178733.625,178733.625,76600.125,76600.125,0,48457.5,5.106675e+05,48457.50,0,5.690650e+05,,script fee $411K + fringe; optional polish $39K,NaN,Film,Unt James Sweeney_Film,2025-12-10 06:09:21.519864
5,12,Cuban Missile Crisis,closed deals/active,NaN,NaN,0.00,187925.00,187925.00,0,126225,49900,49900,0,140000,2.260250e+05,140000.00,0,5.539500e+05,,option $40K; script $330K + fringe; $85K optio...,NaN,Film,Cuban Missile Crisis_Film,2025-12-10 06:09:21.519864
6,13,Unt Bennett Miller (fka Untitled Charlie Kaufm...,closed deals/active,0.00,463944.90,463944.90,-374781.25,89163.65,0,0,0,0,0,454687.5,4.546875e+05,NaN,0,5.438512e+05,,delivery of first draft $375K + fringe; $20K r...,NaN,Film,Unt Bennett Miller (fka Untitled Charlie Kaufm...,2025-12-10 06:09:21.519864
7,14,Five Hitmen,closed deals/active,0.00,56192.50,56192.50,200065.23,256257.73,93868.75,37275,37275,0,0,102506.25,1.684188e+05,102506.25,0,5.271827e+05,,option $10K; remaining script fee $195K + frin...,NaN,Film,Five Hitmen_Film,2025-12-10 06:09:21.519864
8,15,Untitled Dolly Parton,closed deals/active,0.00,0.00,0.00,5300.00,5300.00,0,124750,124750,187125,0,0,4.366250e+05,NaN,0,4.419250e+05,,script fee $350K + fringe (pending writing deal),NaN,Film,Untitled Dolly Parton_Film,2025-12-10 06:09:21.519864
9,16,Finding Gobi,closed deals/active,0.00,15462.50,15462.50,18130.00,33592.50,0,124250,124250,62125,62125,0,3.727500e+05,NaN,0,4.063425e+05,,script fee $300K + fringe (pending writing deal),NaN,Film,Finding Gobi_Film,2025-12-10 06:09:21.519864
10,17,Syd,closed deals/active,0.00,0.00,0.00,223650.00,223650.00,0,74550,0,0,0,0,7.455000e+04,NaN,0,2.982000e+05,,script fee $300K + fringe,NaN,Film,Syd_Film,2025-12-10 06:09:21.519864
11,18,Norco 80,closed deals/active,0.00,0.00,0.00,0.00,0.00,167306.255,67500,0,0,0,0,2.348063e+05,NaN,0,2.348063e+05,,script $450K + fringe - will be split 50% with...,NaN,Film,Norco 80_Film,2025-12-10 06:09:21.519864
12,19,Twelve Minutes (Anim/TV),closed deals/active,97049.73,10502.54,107552.27,19.39,107571.66,0,82833.333333,41416.666667,82833.333333,103541.666667,NaN,3.106250e+05,NaN,0,4.181967e+05,,script fee $250K,NaN,Film,Twelve Minutes (Anim/TV)_Film,2025-12-10 06:09:21.519864
13,20,American Jewel,closed deals/active,NaN,NaN,NaN,32993.48,32993.48,0,101272.32,0,0,0,NaN,1.012723e+05,NaN,0,1.342658e+05,,script rewrite $53K; EP deal $75K,NaN,Film,American Jewel_Film,2025-12-10 06:09:21.519864
14,21,"Untitled Lessovitz, Quesada, Zund",closed deals/active,80040.06,0.00,80040.06,0.00,80040.06,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,0,8.004006e+04,,,NaN,Film,"Untitled Lessovitz, Quesada, Zund_Film",2025-12-10 06:09:21.519864
15,22,Chef,closed deals/active,0.00,1885.00,1885.00,2420.00,4305.00,0,63332.95525,0,0,0,0,6.333296e+04,NaN,0,6.763796e+04,,WGA scale + 15% $50K + fringe,NaN,Film,Chef_Film,2025-12-10 06:09:21.519864
16,23,The Lost Wild - Film,closed deals/active,NaN,NaN,0.00,1100.00,1100.00,0,0,0,0,0,0,0.000000e+00,NaN,0,1.100000e+03,,,NaN,Film,The Lost Wild - Film_Film,2025-12-10 06:09:21.519864
0,32,Eric Warren Singer,pending,NaN,NaN,0.00,0.00,0.00,NaN,NaN,4500000,NaN,NaN,NaN,4.500000e+06,NaN,0,4.500000e+06,,script deal $4.5M,NaN,Film,Eric Warren Singer_Film,2025-12-10 06:09:21.519864
1,33,Grind,pending,NaN,NaN,0.00,0.00,0.00,202275,202275,134850,134850,0,0,6.742500e+05,NaN,0,6.742500e+05,,script fee $600K + fringe,NaN,Film,Grind_Film,2025-12-10 06:09:21.519864
2,34,The Legend of Georgia McBride,pending,0.00,0.00,0.00,0.00,0.00,0,0,62375,62375,62375,62375,2.495000e+05,NaN,0,2.495000e+05,,script fee $200K + fringe,NaN,Film,The Legend of Georgia McBride_Film,2025-12-10 06:09:21.519864
3,35,Blankets,pending,NaN,NaN,NaN,NaN,NaN,NaN,10000,75000,62500,62500,NaN,2.100000e+05,NaN,0,2.100000e+05,,script fee $200K and option $10K,NaN,Film,Blankets_Film,2025-12-10 06:09:21.519864
4,36,Belly of the Beast,pending,NaN,NaN,0.00,55104.86,55104.86,0,139233.38,0,0,0,0,6.423338e+04,75000.00,0,1.943382e+05,,"option fee 37K; optional polish 75K, 32K budge...",NaN,Film,Belly of the Beast_Film,2025-12-10 06:09:21.519864
5,37,The Visit,pending,0.00,0.00,0.00,268.17,268.17,0,52000,0,0,0,0,5.200000e+04,NaN,0,5.226817e+04,,option $50K; $2K travel,NaN,Film,The Visit_Film,2025-12-10 06:09:21.519864
6,38,Women Clothed by the Sun,pending,NaN,NaN,0.00,30638.73,30638.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.063873e+04,,,NaN,Film,Women Clothed by the Sun_Film,2025-12-10 06:09:21.519864
7,39,The New Man,pending,0.00,1522.50,1522.50,0.00,1522.50,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,0,1.522500e+03,,,NaN,Film,The New Man_Film,2025-12-10 06:09:21.519864
8,40,Unt Mr. Beast Fiction Project,pending,NaN,NaN,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,0,0.000000e+00,,,NaN,Film,Unt Mr. Beast Fiction Project_Film,2025-12-10 06:09:21.519864
9,41,Monument Valley,pending,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.000000e+00,,,NaN,Film,Monument Valley_Film,2025-12-10 06:09:21.519864
10,42,Minds on Fire,pending,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,,,2025-10-14 00:00:00,Film,Minds on Fire_Film,2025-12-10 06:09:21.519864
0,27,Stephen Feder fee,closed deals/active,0.00,176824.80,176824.80,391392.76,568217.56,35581,35581,0,0,0,NaN,7.116200e+04,NaN,0,6.393796e+05,,5 months of fee $178K,NaN,Film,Stephen Feder fee_Film,2025-12-10 06:09:21.519864
1,28,Conner (Literary Research),closed deals/active,153450.00,34800.00,188250.00,31900.00,220150.00,2900,8700,8700,8700,8700,0,3.770000e+04,NaN,0,2.578500e+05,,15 months @ $2.9K/mo,NaN,Film,Conner (Literary Research)_Film,2025-12-10 06:09:21.519864

In [46]:
from datetime import datetime

doc_list = []

for _, row in final_data.iterrows():
    #changes_val = row['changes']
    #changes_val = str(changes_val) if pd.notna(changes_val) else ""

    new_update = {
        'update_date': row['update_date'],
        'Status': row['Status'],
        'title': row['Title'],
        'ITD_2023': row['Inception To Date | 2023'],
        'ITD_2024': row['Inception To Date | 2024'],
        'ITD_2025': row['ITD TOTAL SPEND | 2025'],
        '2024_spend': row['Year To Date | 2024'],
        '2025_spend': row['Year To Date | 2025'],
        'Remaining_Committed': row['Committed '],
        'Remaining_Optional': row['Optional'],
        'Total_Cost_with_Committments': row['ITD w Commitments | 2025'],
        'Changes':row['Changes from Prior'],
        "Summary":row['SUMMARY']
    }

    doc = {
        '_id': row['_id'],
        #'date_added':row['DATE ADDED'],
        'title': row['Title'],
        'division': row['division'].lower(),
        'Status': row['Status'],
        'update_date': row['update_date'],
        'Total_Cost_with_Committments': new_update['Total_Cost_with_Committments'],
        'ITD_2025': new_update['ITD_2025'],
        'Remaining_Committed': new_update['Remaining_Committed'],
        'Remaining_Optional': new_update['Remaining_Optional'],
        'Changes': new_update['Changes'],
        # This will *append* to the history on upsert
        '$push': {'updates': new_update}
    }

    doc_list.append(doc)

In [47]:
## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [48]:
db = client['InDevelopment']

collection = db['development_tracker']

In [49]:
len(doc_list)

98

In [50]:
doc_list

[{'_id': 'Even the Losers/ Unt. Randy Lanier_Film',
  'title': 'Even the Losers/ Unt. Randy Lanier',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 5852863.5,
  'ITD_2025': 2089738.5,
  'Remaining_Committed': 3013125.0,
  'Remaining_Optional': 750000.0,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'closed deals/active',
    'title': 'Even the Losers/ Unt. Randy Lanier',
    'ITD_2023': nan,
    'ITD_2024': 0.0,
    'ITD_2025': 2089738.5,
    '2024_spend': nan,
    '2025_spend': 2089738.5,
    'Remaining_Committed': 3013125.0,
    'Remaining_Optional': 750000.0,
    'Total_Cost_with_Committments': 5852863.5,
    'Changes': '',
    'Summary': 'script fee $4M; dev fee $1M; $30k option extension; $13K consulting fee; $750K optional rewrite and polish'}}},
 {'_id': 'The Silent Patient - Plan B_Film',
  'title': 'The Silent Patient - Plan B',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 2033958.05,
  'ITD_2025': 1940770.55,
  'Remaining_Committed': 31062.5,
  'Remaining_Optional': 62125.0,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'closed deals/active',
    'title': 'The Silent Patient - Plan B',
    'ITD_2023': 621510.95,
    'ITD_2024': 1797398.05,
    'ITD_2025': 1940770.55,
    '2024_spend': 1175887.1,
    '2025_spend': 143372.5,
    'Remaining_Committed': 31062.5,
    'Remaining_Optional': 62125.0,
    'Total_Cost_with_Committments': 2033958.05,
    'Changes': '',
    'Summary': 'polish and optional polish $100K; reflects the $925K option purchase'}}},
 {'_id': 'Unt Nicole Taylor_Film',
  'title': 'Unt Nicole Taylor',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 782926.25,
  'ITD_2025': 282957.5,
  'Remaining_Committed': 439968.75,
  'Remaining_Optional': 60000.0,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'closed deals/active',
    'title': 'Unt Nicole Taylor',
    'ITD_2023': 0.0,
    'ITD_2024': 3395.0,
    'ITD_2025': 282957.5,
    '2024_spend': 3395.0,
    '2025_spend': 279562.5,
    'Remaining_Committed': 439968.75,
    'Remaining_Optional': 60000.0,
    'Total_Cost_with_Committments': 782926.25,
    'Changes': '',
    'Summary': 'script fee $600K + fringe; optional polish $60K'}}},
 {'_id': 'American Spartan_Film',
  'title': 'American Spartan',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 623750.0,
  'ITD_2025': 0.0,
  'Remaining_Committed': 623750.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'closed deals/active',
    'title': 'American Spartan',
    'ITD_2023': nan,
    'ITD_2024': 0.0,
    'ITD_2025': 0.0,
    '2024_spend': nan,
    '2025_spend': 0.0,
    'Remaining_Committed': 623750.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 623750.0,
    'Changes': '',
    'Summary': '$500K first draft + first rewrite'}}},
 {'_id': 'Unt James Sweeney_Film',
  'title': 'Unt James Sweeney',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 569065.0,
  'ITD_2025': 9940.0,
  'Remaining_Committed': 510667.5,
  'Remaining_Optional': 48457.5,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'closed deals/active',
    'title': 'Unt James Sweeney',
    'ITD_2023': nan,
    'ITD_2024': 0.0,
    'ITD_2025': 9940.0,
    '2024_spend': nan,
    '2025_spend': 9940.0,
    'Remaining_Committed': 510667.5,
    'Remaining_Optional': 48457.5,
    'Total_Cost_with_Committments': 569065.0,
    'Changes': '',
    'Summary': 'script fee $411K + fringe; optional polish $39K'}}},
 {'_id': 'Cuban Missile Crisis_Film',
  'title': 'Cuban Missile Crisis',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 553950.0,
  'ITD_2025': 187925.0,
  'Remaining_Committed': 226025.0,
  'Remaining_Optional': 140000.0,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'closed deals/active',
    'title': 'Cuban Missile Crisis',
    'ITD_2023': nan,
    'ITD_2024': 0.0,
    'ITD_2025': 187925.0,
    '2024_spend': nan,
    '2025_spend': 187925.0,
    'Remaining_Committed': 226025.0,
    'Remaining_Optional': 140000.0,
    'Total_Cost_with_Committments': 553950.0,
    'Changes': '',
    'Summary': 'option $40K; script $330K + fringe; $85K optional rewrite; $55K optional polish'}}},
 {'_id': 'Unt Bennett Miller (fka Untitled Charlie Kaufman Project)_Film',
  'title': 'Unt Bennett Miller (fka Untitled Charlie Kaufman Project)',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 543851.15,
  'ITD_2025': 89163.65000000002,
  'Remaining_Committed': 454687.5,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'closed deals/active',
    'title': 'Unt Bennett Miller (fka Untitled Charlie Kaufman Project)',
    'ITD_2023': 0.0,
    'ITD_2024': 463944.9,
    'ITD_2025': 89163.65000000002,
    '2024_spend': 463944.9,
    '2025_spend': -374781.25,
    'Remaining_Committed': 454687.5,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 543851.15,
    'Changes': '',
    'Summary': 'delivery of first draft $375K + fringe; $20K research (pending writing deal) '}}},
 {'_id': 'Five Hitmen_Film',
  'title': 'Five Hitmen',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 527182.73,
  'ITD_2025': 256257.72999999998,
  'Remaining_Committed': 168418.75,
  'Remaining_Optional': 102506.25,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'closed deals/active',
    'title': 'Five Hitmen',
    'ITD_2023': 0.0,
    'ITD_2024': 56192.5,
    'ITD_2025': 256257.72999999998,
    '2024_spend': 56192.5,
    '2025_spend': 200065.22999999998,
    'Remaining_Committed': 168418.75,
    'Remaining_Optional': 102506.25,
    'Total_Cost_with_Committments': 527182.73,
    'Changes': '',
    'Summary': 'option $10K; remaining script fee $195K + fringe; optional rewrite and polish $82.5K'}}},
 {'_id': 'Untitled Dolly Parton_Film',
  'title': 'Untitled Dolly Parton',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 441925.0,
  'ITD_2025': 5300.0,
  'Remaining_Committed': 436625.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'closed deals/active',
    'title': 'Untitled Dolly Parton',
    'ITD_2023': 0.0,
    'ITD_2024': 0.0,
    'ITD_2025': 5300.0,
    '2024_spend': 0.0,
    '2025_spend': 5300.0,
    'Remaining_Committed': 436625.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 441925.0,
    'Changes': '',
    'Summary': 'script fee $350K + fringe (pending writing deal)'}}},
 {'_id': 'Finding Gobi_Film',
  'title': 'Finding Gobi',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 406342.5,
  'ITD_2025': 33592.5,
  'Remaining_Committed': 372750.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'closed deals/active',
    'title': 'Finding Gobi',
    'ITD_2023': 0.0,
    'ITD_2024': 15462.5,
    'ITD_2025': 33592.5,
    '2024_spend': 15462.5,
    '2025_spend': 18130.0,
    'Remaining_Committed': 372750.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 406342.5,
    'Changes': '',
    'Summary': 'script fee $300K + fringe (pending writing deal)'}}},
 {'_id': 'Syd_Film',
  'title': 'Syd',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 298200.0,
  'ITD_2025': 223650.0,
  'Remaining_Committed': 74550.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'closed deals/active',
    'title': 'Syd',
    'ITD_2023': 0.0,
    'ITD_2024': 0.0,
    'ITD_2025': 223650.0,
    '2024_spend': 0.0,
    '2025_spend': 223650.0,
    'Remaining_Committed': 74550.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 298200.0,
    'Changes': '',
    'Summary': 'script fee $300K + fringe'}}},
 {'_id': 'Norco 80_Film',
  'title': 'Norco 80',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 234806.255,
  'ITD_2025': 0.0,
  'Remaining_Committed': 234806.255,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'closed deals/active',
    'title': 'Norco 80',
    'ITD_2023': 0.0,
    'ITD_2024': 0.0,
    'ITD_2025': 0.0,
    '2024_spend': 0.0,
    '2025_spend': 0.0,
    'Remaining_Committed': 234806.255,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 234806.255,
    'Changes': '',
    'Summary': 'script $450K + fringe - will be split 50% with Fifth Season'}}},
 {'_id': 'Twelve Minutes (Anim/TV)_Film',
  'title': 'Twelve Minutes (Anim/TV)',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 418196.66,
  'ITD_2025': 107571.65999999999,
  'Remaining_Committed': 310625.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'closed deals/active',
    'title': 'Twelve Minutes (Anim/TV)',
    'ITD_2023': 97049.73,
    'ITD_2024': 107552.26999999999,
    'ITD_2025': 107571.65999999999,
    '2024_spend': 10502.54,
    '2025_spend': 19.39,
    'Remaining_Committed': 310625.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 418196.66,
    'Changes': '',
    'Summary': 'script fee $250K'}}},
 {'_id': 'American Jewel_Film',
  'title': 'American Jewel',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 134265.80000000002,
  'ITD_2025': 32993.48,
  'Remaining_Committed': 101272.32,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'closed deals/active',
    'title': 'American Jewel',
    'ITD_2023': nan,
    'ITD_2024': nan,
    'ITD_2025': 32993.48,
    '2024_spend': nan,
    '2025_spend': 32993.48,
    'Remaining_Committed': 101272.32,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 134265.80000000002,
    'Changes': '',
    'Summary': 'script rewrite $53K; EP deal $75K'}}},
 {'_id': 'Untitled Lessovitz, Quesada, Zund_Film',
  'title': 'Untitled Lessovitz, Quesada, Zund',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 80040.06,
  'ITD_2025': 80040.06,
  'Remaining_Committed': 0.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'closed deals/active',
    'title': 'Untitled Lessovitz, Quesada, Zund',
    'ITD_2023': 80040.06,
    'ITD_2024': 80040.06,
    'ITD_2025': 80040.06,
    '2024_spend': 0.0,
    '2025_spend': 0.0,
    'Remaining_Committed': 0.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 80040.06,
    'Changes': '',
    'Summary': ''}}},
 {'_id': 'Chef_Film',
  'title': 'Chef',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 67637.95525,
  'ITD_2025': 4305.0,
  'Remaining_Committed': 63332.95524999999,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'closed deals/active',
    'title': 'Chef',
    'ITD_2023': 0.0,
    'ITD_2024': 1885.0,
    'ITD_2025': 4305.0,
    '2024_spend': 1885.0,
    '2025_spend': 2420.0,
    'Remaining_Committed': 63332.95524999999,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 67637.95525,
    'Changes': '',
    'Summary': 'WGA scale + 15% $50K + fringe'}}},
 {'_id': 'The Lost Wild - Film_Film',
  'title': 'The Lost Wild - Film',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 1100.0,
  'ITD_2025': 1100.0,
  'Remaining_Committed': 0.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'closed deals/active',
    'title': 'The Lost Wild - Film',
    'ITD_2023': nan,
    'ITD_2024': 0.0,
    'ITD_2025': 1100.0,
    '2024_spend': nan,
    '2025_spend': 1100.0,
    'Remaining_Committed': 0.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 1100.0,
    'Changes': '',
    'Summary': ''}}},
 {'_id': 'Eric Warren Singer_Film',
  'title': 'Eric Warren Singer',
  'division': 'film',
  'Status': 'pending',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 4500000.0,
  'ITD_2025': 0.0,
  'Remaining_Committed': 4500000.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'pending',
    'title': 'Eric Warren Singer',
    'ITD_2023': nan,
    'ITD_2024': 0.0,
    'ITD_2025': 0.0,
    '2024_spend': nan,
    '2025_spend': 0.0,
    'Remaining_Committed': 4500000.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 4500000.0,
    'Changes': '',
    'Summary': 'script deal $4.5M'}}},
 {'_id': 'Grind_Film',
  'title': 'Grind',
  'division': 'film',
  'Status': 'pending',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 674250.0,
  'ITD_2025': 0.0,
  'Remaining_Committed': 674250.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'pending',
    'title': 'Grind',
    'ITD_2023': nan,
    'ITD_2024': 0.0,
    'ITD_2025': 0.0,
    '2024_spend': nan,
    '2025_spend': 0.0,
    'Remaining_Committed': 674250.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 674250.0,
    'Changes': '',
    'Summary': 'script fee $600K + fringe'}}},
 {'_id': 'The Legend of Georgia McBride_Film',
  'title': 'The Legend of Georgia McBride',
  'division': 'film',
  'Status': 'pending',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 249500.0,
  'ITD_2025': 0.0,
  'Remaining_Committed': 249500.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'pending',
    'title': 'The Legend of Georgia McBride',
    'ITD_2023': 0.0,
    'ITD_2024': 0.0,
    'ITD_2025': 0.0,
    '2024_spend': 0.0,
    '2025_spend': 0.0,
    'Remaining_Committed': 249500.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 249500.0,
    'Changes': '',
    'Summary': 'script fee $200K + fringe'}}},
 {'_id': 'Blankets_Film',
  'title': 'Blankets',
  'division': 'film',
  'Status': 'pending',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 210000.0,
  'ITD_2025': nan,
  'Remaining_Committed': 210000.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'pending',
    'title': 'Blankets',
    'ITD_2023': nan,
    'ITD_2024': nan,
    'ITD_2025': nan,
    '2024_spend': nan,
    '2025_spend': nan,
    'Remaining_Committed': 210000.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 210000.0,
    'Changes': '',
    'Summary': 'script fee $200K and option $10K'}}},
 {'_id': 'Belly of the Beast_Film',
  'title': 'Belly of the Beast',
  'division': 'film',
  'Status': 'pending',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 194338.24,
  'ITD_2025': 55104.86,
  'Remaining_Committed': 64233.380000000005,
  'Remaining_Optional': 75000.0,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'pending',
    'title': 'Belly of the Beast',
    'ITD_2023': nan,
    'ITD_2024': 0.0,
    'ITD_2025': 55104.86,
    '2024_spend': nan,
    '2025_spend': 55104.86,
    'Remaining_Committed': 64233.380000000005,
    'Remaining_Optional': 75000.0,
    'Total_Cost_with_Committments': 194338.24,
    'Changes': '',
    'Summary': 'option fee 37K; optional polish 75K, 32K budgeting and scouting'}}},
 {'_id': 'The Visit_Film',
  'title': 'The Visit',
  'division': 'film',
  'Status': 'pending',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 52268.17,
  'ITD_2025': 268.17,
  'Remaining_Committed': 52000.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'pending',
    'title': 'The Visit',
    'ITD_2023': 0.0,
    'ITD_2024': 0.0,
    'ITD_2025': 268.17,
    '2024_spend': 0.0,
    '2025_spend': 268.17,
    'Remaining_Committed': 52000.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 52268.17,
    'Changes': '',
    'Summary': 'option $50K; $2K travel'}}},
 {'_id': 'Women Clothed by the Sun_Film',
  'title': 'Women Clothed by the Sun',
  'division': 'film',
  'Status': 'pending',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 30638.73,
  'ITD_2025': 30638.73,
  'Remaining_Committed': nan,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'pending',
    'title': 'Women Clothed by the Sun',
    'ITD_2023': nan,
    'ITD_2024': 0.0,
    'ITD_2025': 30638.73,
    '2024_spend': nan,
    '2025_spend': 30638.73,
    'Remaining_Committed': nan,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 30638.73,
    'Changes': '',
    'Summary': ''}}},
 {'_id': 'The New Man_Film',
  'title': 'The New Man',
  'division': 'film',
  'Status': 'pending',
  'update_date': Timestamp('2025-12-10 06:09:21.519864'),
  'Total_Cost_with_Committments': 1522.5,
  'ITD_2025': 1522.5,
  'Remaining_Committed': 0.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2025-12-10 06:09:21.519864'),
    'Status': 'pending',
    'title': 'The New Man',
    'ITD_2023': 0.0,
    'ITD_2024': 1522.5,
    'ITD_2025': 1522.5,
    '2024_spend': 1522.5,
    '2025_spend': 0.0,
    'Remaining_Committed': 0.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 1522.5,
    'Changes': '',
    'Summary': ''}}},
 {'_id': 'Unt Mr. Beast Fiction Project_Film',

In [51]:
stop

NameError: name 'stop' is not defined

collection.delete_many({})

In [52]:
from pymongo import UpdateOne

operations = []

for doc in doc_list:
    # Split update payloads
    base_fields = {
        'title': doc['title'],
        'division': doc['division'],
        'status':doc['Status'],
        'update_date': doc['update_date'],
        'Total_Cost_with_Committments': doc['Total_Cost_with_Committments'],
        'ITD_2025': doc['ITD_2025'],
        'Remaining_Committed': doc['Remaining_Committed'],
        'Remaining_Optional': doc['Remaining_Optional'],
    }

    new_update = doc['$push']['updates']  # from your earlier construction

    operations.append(
        UpdateOne(
            {"_id": doc["_id"]},
            {
                "$set": base_fields,
                "$push": {"updates": new_update}
            },
            upsert=True
        )
    )

result = collection.bulk_write(operations)
print(f"Matched: {result.matched_count}, Upserted: {len(result.upserted_ids)}, Modified: {result.modified_count}")

Matched: 97, Upserted: 1, Modified: 97

In [53]:
docs = collection.find({})

In [54]:
df = pd.DataFrame(docs)

In [55]:
df.sort_values(by='Total_Cost_with_Committments',ascending=False)

,_id,ITD_2025,Remaining_Committed,Remaining_Optional,Total_Cost_with_Committments,division,status,title,update_date,updates,ap_id
0,Even the Losers/ Unt. Randy Lanier_Film,2089738.50,3013125.0,750000.0,5852863.50,film,closed deals/active,Even the Losers/ Unt. Randy Lanier,2025-12-10 06:09:21.519,"[{'update_date': 2025-10-31 10:35:01.546000, '...",F_2025_00018
18,Eric Warren Singer_Film,0.00,4500000.0,NaN,4500000.00,film,pending,Eric Warren Singer,2025-12-10 06:09:21.519,"[{'update_date': 2025-10-31 10:35:01.546000, '...",NaN
78,Mantooth_Animation_Film,2296780.64,120000.0,NaN,2416780.64,animation_film,,Mantooth,2025-12-10 06:09:21.519,"[{'update_date': 2025-10-31 10:35:01.546000, '...",AN_2025_00014
1,The Silent Patient - Plan B_Film,1940770.55,31062.5,62125.0,2033958.05,film,closed deals/active,The Silent Patient - Plan B,2025-12-10 06:09:21.519,"[{'update_date': 2025-10-31 10:35:01.546000, '...",F_2025_00048
82,Moomins_Animation_Film,527887.81,285250.0,NaN,1056887.81,animation_film,,Moomins,2025-12-10 06:09:21.519,"[{'update_date': 2025-10-31 10:35:01.546000, '...",AN_2025_00005
...,...,...,...,...,...,...,...,...,...,...,...
60,Unt. Equestrian Series_TV,0.00,0.0,NaN,0.00,tv,closed deals/active,Unt. Equestrian Series,2025-12-10 06:09:21.519,"[{'update_date': 2025-10-31 10:35:01.546000, '...",TV_2025_00018
76,Kill the Rabbit_TV,0.00,NaN,NaN,0.00,tv,pending,Kill the Rabbit,2025-12-10 06:09:21.519,"[{'update_date': 2025-10-31 10:35:01.546000, '...",NaN
70,Exit Party_TV,0.00,NaN,NaN,0.00,tv,pending,Exit Party,2025-12-10 06:09:21.519,"[{'update_date': 2025-10-31 10:35:01.546000, '...",NaN
41,Syd_TV,-288733.88,0.0,NaN,-288733.88,tv,inactive,Syd,2025-12-10 06:09:21.519,"[{'update_date': 2025-10-31 10:35:01.546000, '...",NaN
105,Gravity Let Me Go_TV,0.00,65400.0,NaN,NaN,tv,pending,Gravity Let Me Go,2025-12-10 06:09:21.519,"[{'update_date': 2025-12-10 06:09:21.519000, '...",NaN

In [56]:
client.close()

In [57]:
df.groupby('division')['Total_Cost_with_Committments'].sum()/1_000_000

division
animation_film     6.137974
animation_tv       1.185744
corporate          1.053055
film              20.379808
theatre            0.448593
tv                 6.277826
Name: Total_Cost_with_Committments, dtype: float64

In [58]:
df.query("division =='corporate'")

,_id,ITD_2025,Remaining_Committed,Remaining_Optional,Total_Cost_with_Committments,division,status,title,update_date,updates,ap_id
77,England Expects (Film)_corporate,46154.00,NaN,NaN,46154.00,corporate,pending,England Expects (Film),2025-12-10 06:09:21.519,"[{'update_date': 2025-10-31 10:35:01.546000, '...",NaN
79,Counterculture_corporate,921893.26,NaN,NaN,921893.26,corporate,closed deals/active,Counterculture,2025-11-10 05:40:42.156,"[{'update_date': 2025-10-31 10:35:01.546000, '...",NaN
80,Calliope_corporate,41107.97,33900.0,NaN,75007.97,corporate,closed deals/active,Calliope,2025-12-10 06:09:21.519,"[{'update_date': 2025-10-31 10:35:01.546000, '...",NaN
103,Grant & Sherman_corporate,10000.00,0.0,NaN,10000.00,corporate,closed deals/active,Grant & Sherman,2025-12-10 06:09:21.519,"[{'update_date': 2025-11-10 05:34:58.644000, '...",NaN