In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_excel("development_tracker/APH Development Tracker - 02.20.26.xlsx", sheet_name='ALL SUMMARY')

In [3]:
df.query("Annapurna =='International TV'")

,Annapurna,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
89,International TV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
col_names = df.iloc[3].dropna()
col_dates = df.iloc[4].dropna()

In [5]:
col_actuals = df.iloc[5].dropna()

In [6]:
col_filter = ['Unnamed: 1','Unnamed: 2'] + list(set(col_names.index.to_list() + col_actuals.index.to_list()))

df.index[df['Annapurna'] == 'Total Film (Closed Deals)']

In [7]:
start_index = df.index[df['Annapurna'] == 'Film'][0]+1
stop_index = df.index[df['Annapurna'] == 'Total Film (Closed + Capitalized Deals)'][0]-1

In [8]:
start_index_consult = df.index[df['Annapurna'] == 'Total Film (Closed + Capitalized Deals)'][0]+2
stop_index_consult = df.index[df['Annapurna'] == 'Total Film (Closed + Capitalized + Expensed Deals)'][0]-1

In [9]:
start_index_pending = df.index[df['Annapurna'] == 'Total Film (Closed + Capitalized + Expensed Deals)'][0]+2
stop_index_pending = df.index[df['Annapurna'] == 'Total Film (Closed + Capitalized + Expensed Deals + Pending)'][0]-1

In [10]:
start_index_TV = df.index[df['Annapurna'] == 'TV'][0]+1
stop_index_TV = df.index[df['Annapurna'] == 'Total TV (Closed + Capitalized Deals)'][0]-1

In [11]:
start_index_ITV = df.index[df['Annapurna'] == 'International TV'][0]+1
stop_index_ITV = df.index[df['Annapurna'] == 'Total International TV '][0]-1

In [12]:
start_index_consult_TV = df.index[df['Annapurna'] == 'Total TV (Closed + Capitalized Deals)'][0]+2
stop_index_consult_TV = df.index[df['Annapurna'] == 'Total TV (Closed + Capitalized + Expensed Deals)'][0]-1

In [13]:
start_index_pending_TV = df.index[df['Annapurna'] == 'Total TV (Closed + Capitalized + Expensed Deals)'][0]+2
stop_index_pending_TV = df.index[df['Annapurna'] == 'Total TV (Closed + Capitalized + Expensed Deals + Pending)'][0]-1

In [14]:
start_index_corporate = df.index[df['Annapurna'] == 'Corporate'][0]+1
stop_index_corporate = df.index[df['Annapurna'] == ' Total Corporate'][0]-1

In [15]:
start_index_ani_film = df.index[df['Annapurna'] == 'Animation (Film)'][0]+1
stop_index_ani_film = df.index[df['Annapurna'] == 'Total Animation (Film)'][0]-1

In [16]:
start_index_ani_tv = df.index[df['Annapurna'] == 'Animation (TV)'][0]+1
stop_index_ani_tv = df.index[df['Annapurna'] == 'Total Animation (TV)'][0]-1

In [17]:
start_index_theatre = df.index[df['Annapurna'] == 'Theatre'][0]+1
stop_index_theatre = df.index[df['Annapurna'] == 'Total Theatre'][0]-1

In [18]:
data = df[start_index:stop_index]
data['division'] = "Film"
data_pending = df[start_index_pending:stop_index_pending]
data_pending['division'] = "Film"

data_tv = df[start_index_TV:stop_index_TV]
data_tv['division'] = "TV"

data_pending_TV = df[start_index_pending_TV:stop_index_pending_TV]
data_pending_TV['division'] = "TV"

data_pending_ITV = df[start_index_ITV:stop_index_ITV]
data_pending_ITV['division'] = "Intl_TV"

data_corp = df[start_index_corporate:stop_index_corporate]
data_corp['division'] = "corporate"

data_ani_film = df[start_index_ani_film:stop_index_ani_film]
data_ani_film['division'] = "Animation_Film"

data_ani_TV= df[start_index_ani_tv:stop_index_ani_tv]
data_ani_TV['division'] = "Animation_TV"

data_ani_Theatre= df[start_index_theatre:stop_index_theatre]
data_ani_Theatre['division'] = "Theatre"


data_film_consult= df[start_index_consult:stop_index_consult]
data_film_consult['division'] = "Film"

data_tv_consult = df[start_index_consult_TV:stop_index_consult_TV]
data_tv_consult['division'] = "TV"

In [19]:
data_pending_ITV

,Annapurna,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,division
90,NaN,This Immaculate Body (fka Heartstring),pending,0,3584.29,3584.29,0,3584.29,0,3584.29,...,NaN,0,90709.29,NaN,NaN,NaN,option $25K; script fee $50K,NaN,NaN,Intl_TV
91,NaN,Killingbeck,pending,NaN,NaN,0,0,0,0,0,...,NaN,0,4450,NaN,NaN,NaN,$3.3K rewrite; $1k UK counsel,NaN,NaN,Intl_TV
92,NaN,This Perfect Day,pending,NaN,NaN,NaN,NaN,0,NaN,0,...,NaN,0,0,NaN,added,NaN,NaN,NaN,2026-02-19 00:00:00,Intl_TV
93,NaN,A Lie for a Life,pending,NaN,NaN,NaN,NaN,0,NaN,0,...,NaN,0,0,NaN,added,NaN,NaN,NaN,NaN,Intl_TV

In [20]:
data = data.reset_index()
data['_id'] = data['Unnamed: 1'] + "_" + data['division'].astype(str)#  + "_" + data['index'].astype(str)

data_pending = data_pending.reset_index()
data_pending['_id'] = data_pending['Unnamed: 1']+ "_" + data_pending['division'].astype(str)#   + "_" + data_pending['index'].astype(str)

data_tv = data_tv.reset_index()
data_tv['_id'] = data_tv['Unnamed: 1']+ "_" + data_tv['division'].astype(str)#   + "_" + data_tv['index'].astype(str)

data_pending_TV = data_pending_TV.reset_index()
data_pending_TV['_id'] = data_pending_TV['Unnamed: 1']+ "_" + data_pending_TV['division'].astype(str)#   + "_" + data_pending_TV['index'].astype(str)

data_pending_ITV = data_pending_ITV.reset_index()
data_pending_ITV['_id'] = data_pending_ITV['Unnamed: 1']+ "_" + data_pending_ITV['division'].astype(str)#   + "_" + data_pending_TV['index'].astype(str)


data_corp = data_corp.reset_index()
data_corp['_id'] = data_corp['Unnamed: 1']+ "_" + data_corp['division'].astype(str)#   + "_" + data_corp['index'].astype(str)

data_ani_film = data_ani_film.reset_index()
data_ani_film['_id'] = data_ani_film['Unnamed: 1']+ "_" + data_ani_film['division'].astype(str)#   + "_" + data_ani_film['index'].astype(str)

data_ani_TV = data_ani_TV.reset_index()
data_ani_TV['_id'] = data_ani_TV['Unnamed: 1']+ "_" + data_ani_TV['division'].astype(str)#   + "_" + data_ani_TV['index'].astype(str)

data_ani_Theatre = data_ani_Theatre.reset_index()
data_ani_Theatre['_id'] = data_ani_Theatre['Unnamed: 1']+ "_" + data_ani_Theatre['division'].astype(str)#   + "_" + data_ani_Theatre['index'].astype(str)


data_film_consult = data_film_consult.reset_index()
data_film_consult['_id'] = data_film_consult['Unnamed: 1']+ "_" + data_film_consult['division'].astype(str)#   + "_" + data_ani_film['index'].astype(str)

data_tv_consult = data_tv_consult.reset_index()
data_tv_consult['_id'] = data_tv_consult['Unnamed: 1']+ "_" + data_tv_consult['division'].astype(str)#   + "_" + data_ani_film['index'].astype(str)

In [21]:
pd.set_option('display.max_columns', None)  # show all columns

data

,index,Annapurna,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,division,_id
0,7,NaN,Even the Losers/ Unt. Randy Lanier,closed deals/active,NaN,NaN,0,2094378.5,2094378.5,0,2094378.5,0,263125,0,0,500000,0,0,500000,0,0,0,0,1250000,1763125,750000,0,4607503.5,NaN,NaN,NaN,script fee $4M; dev fee $1M; $30k option exten...,NaN,NaN,Film,Even the Losers/ Unt. Randy Lanier_Film
1,8,NaN,The Silent Patient - Plan B,closed deals/active,621510.95,1175887.1,1797398.05,190153.75,1987551.8,15593.75,2003145.55,0,15531.25,0,31062.5,0,0,0,0,0,0,0,0,0,31062.5,15531.25,0,2049739.3,NaN,NaN,NaN,polish and optional polish $100K; reflects the...,NaN,NaN,Film,The Silent Patient - Plan B_Film
2,9,NaN,Unt Nicole Taylor,closed deals/active,0,3395,3395,279562.5,282957.5,0,282957.5,0,0,0,0,0,187125,0,140343.75,0,0,142500,30000,0,439968.75,60000,0,782926.25,NaN,NaN,NaN,script fee $600K + fringe; optional polish $60K,NaN,NaN,Film,Unt Nicole Taylor_Film
3,10,NaN,American Spartan,closed deals/active,NaN,NaN,0,0,0,0,0,0,187125,187125,0,124750,0,124750,0,0,0,0,0,0,623750,NaN,0,623750,NaN,NaN,NaN,$500K first draft + first rewrite,NaN,NaN,Film,American Spartan_Film
4,11,NaN,Unt James Sweeney,closed deals/active,NaN,NaN,0,190318.63,190318.63,0,190318.63,0,178733.625,0,76600.125,0,0,76600.125,0,0,0,0,0,48457.5,331933.875,48457.5,0,570710.005,NaN,NaN,NaN,script fee $411K + fringe; optional polish $39K,NaN,NaN,Film,Unt James Sweeney_Film
5,12,NaN,Cuban Missile Crisis,closed deals/active,NaN,NaN,0,187925,187925,0,187925,0,126225,0,0,49900,0,0,0,49900,0,0,0,140000,226025,140000,0,553950,NaN,NaN,NaN,option $40K; script $330K + fringe; $85K optio...,NaN,NaN,Film,Cuban Missile Crisis_Film
6,13,NaN,Unt Bennett Miller (fka Untitled Charlie Kaufm...,closed deals/active,0,463944.9,463944.9,-374781.25,89163.65,0,89163.65,0,0,0,0,0,0,0,0,0,0,0,0,454687.5,454687.5,NaN,0,543851.15,NaN,NaN,NaN,delivery of first draft $375K + fringe; $20K r...,NaN,NaN,Film,Unt Bennett Miller (fka Untitled Charlie Kaufm...
7,14,NaN,Five Hitmen,closed deals/active,0,56192.5,56192.5,288582.51,344775.01,0,344775.01,0,37275,0,0,37275,0,0,0,0,0,0,0,102506.25,74550,102506.25,0,521831.26,NaN,NaN,NaN,option $10K; remaining script fee $195K + frin...,NaN,NaN,Film,Five Hitmen_Film
8,15,NaN,Untitled Dolly Parton,closed deals/active,0,0,0,5300,5300,0,5300,0,0,0,124750,0,0,124750,0,0,0,187125,0,0,436625,NaN,0,441925,NaN,NaN,NaN,script fee $350K + fringe (pending writing deal),NaN,NaN,Film,Untitled Dolly Parton_Film
9,16,NaN,Twelve Minutes (Anim/TV),closed deals/active,97049.73,10502.54,107552.27,234.39,107786.66,0,107786.66,0,18083.333333,0,8083.333333,41416.666667,33333.333333,41416.666667,33333.333333,41416.666667,0,41416.666667,62125,0,320625,NaN,0,428411.66,NaN,NaN,NaN,script fee $250K + fringe; Option $10K,NaN,NaN,Film,Twelve Minutes (Anim/TV)_Film
10,17,NaN,Finding Gobi,closed deals/active,0,15462.5,15462.5,18130,33592.5,0,33592.5,0,0,124250,0,124250,0,0,62125,0,0,0,62125,0,372750,NaN,0,406342.5,NaN,NaN,NaN,script fee $300K + fringe (pending writing deal),NaN,NaN,Film,Finding Gobi_Film
11,18,NaN,Syd,closed deals/active,0,0,0,260925,260925,0,260925,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,260925,NaN,NaN,NaN,script fee $300K + fringe,NaN,NaN,Film,Syd_Film
12,19,NaN,Norco 80,closed deals/active,0,0,0,202306.26,202306.26,0,202306.26,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,0,0,NaN,0,202306.26,NaN,NaN,NaN,script $450K + fringe - will be split 50% with...,NaN,NaN,Film,Norco 80_Film
13,20,NaN,American Jewel,closed deals/active,NaN,NaN,NaN,32993.48,32993.48,0,32993.48,0,101272.32,0,0,0,0,0,0,0,0,0,0,0,101272.32,NaN,0,134265.8,NaN,NaN,NaN,script rewrite $53K; EP deal $75K,NaN,NaN,Film,American Jewel_Film
14,21,NaN,"Untitled Lessovitz, Quesada, Zund",closed deals/active,80040.06,0,80040.06,0,80040.06,0,80040.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,80040.06,NaN,NaN,NaN,NaN,NaN,NaN,Film,"Untitled Lessovitz, Quesada, Zund_Film"
15,22,NaN,Chef,closed deals/active,0,1885,1885,2420,4305,0,4305,0,63332.95525,0,0,0,0,0,0,0,0,0,0,0,63332.95525,NaN,0,67637.95525,NaN,NaN,NaN,WGA scale + 15% $50K + fringe,NaN,NaN,Film,Chef_Film
16,23,NaN,The Lost Wild - Film,closed deals/active,NaN,NaN,0,1100,1100,0,1100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1100,NaN,NaN,NaN,NaN,NaN,NaN,Film,The Lost Wild - Film_Film

In [22]:
combined_data = pd.concat([data,data_pending,data_tv,data_pending_TV,data_pending_ITV,data_corp,data_ani_film,data_ani_TV,data_ani_Theatre, data_film_consult, data_tv_consult])

In [23]:
combined_data['Unnamed: 1'].unique()

array(['Even the Losers/ Unt. Randy Lanier',
       'The Silent Patient - Plan B', 'Unt Nicole Taylor',
       'American Spartan', 'Unt James Sweeney', 'Cuban Missile Crisis',
       'Unt Bennett Miller (fka Untitled Charlie Kaufman Project)',
       'Five Hitmen', 'Untitled Dolly Parton', 'Twelve Minutes (Anim/TV)',
       'Finding Gobi', 'Syd', 'Norco 80', 'American Jewel',
       'Untitled Lessovitz, Quesada, Zund', 'Chef',
       'The Lost Wild - Film', 'Eric Warren Singer', 'Grind',
       'The Legend of Georgia McBride', 'Blankets', 'Belly of the Beast',
       'The Visit', 'Women Clothed by the Sun', 'Unt Soap Opera Doc',
       'Unt Brady Corbett Project', 'Monument Valley', 'Minds on Fire',
       'Control', 'Who is Maud Dixon', 'Murderland', 'The Original',
       'Hot Kid', 'Planet of Exile', 'Call Me Dad', 'The Voyeur',
       'Unt. Carlo Bernard/International Mercenaries', 'Operator',
       'The Tour', 'The Chosen One', 'Nomad Summer', 'Identical',
       'Seized', 'Made in Utah', 'Untitled Mallory Project', 'Strangers',
       'Darkside of the Moon', 'Unt. Death Hoax', 'Alan Wake',
       'Unt. Shi Yang', 'Unt. Equestrian Series', 'Shot to Nothing',
       'The Drifting Classroom', 'Unt. Sports Fan Show',
       'Unt. Game Doc Series',
       'Unt. John Cho Jean Kyoung Frazier (if/come)',
       'Executive Protection', 'Limbo (TV/FILM tbd)', 'Inside',
       'Cutter & Tats', 'This Immaculate Body (fka Heartstring)',
       'Killingbeck', 'This Perfect Day', 'A Lie for a Life', 'Calliope',
       'Grant & Sherman', 'England Expects (Film)', 'Stray - Animation',
       'Mantooth', 'Moomins', 'Some Assembly Required', 'COMA',
       'FOO (Animation)', 'To be billed back', 'Antarctica', 'The Trap',
       'Nimona', "Let's Boogey", 'Sapiens - Animation', 'Nick Weidenfeld',
       'Living the Dream', '20,000 Leagues Under the Sea',
       'NARPS (Non-Associated Regular People)', 'Witchfeld', 'Outlets',
       'Center Stage', 'Her', 'Inter Alia (Broadway 2026)',
       'Stephen Feder fee', 'Conner (Literary Research)'], dtype=object)

In [24]:
col_names = col_names.to_dict()
col_dates = col_dates.to_dict()
col_actuals = col_actuals.to_dict()

col_names['Unnamed: 16'] = "Remaining - Optional"
col_names['Unnamed: 15'] = "Remaining - Committed"

In [25]:
col_actuals

{'Unnamed: 3': 'Actual',
 'Unnamed: 4': 'Actual',
 'Unnamed: 5': 'Actual',
 'Unnamed: 6': 'Actual',
 'Unnamed: 7': 'Actual',
 'Unnamed: 9': 'Actual',
 'Unnamed: 23': 'Committed ',
 'Unnamed: 24': 'Optional',
 'Unnamed: 26': 'Actual + Committed + Optional'}

In [26]:
col_dates

{'Unnamed: 2': 'Status',
 'Unnamed: 3': datetime.datetime(2023, 12, 31, 0, 0),
 'Unnamed: 4': datetime.datetime(2024, 12, 31, 0, 0),
 'Unnamed: 5': datetime.datetime(2024, 12, 31, 0, 0),
 'Unnamed: 6': datetime.datetime(2025, 12, 31, 0, 0),
 'Unnamed: 7': datetime.datetime(2025, 12, 31, 0, 0),
 'Unnamed: 8': datetime.datetime(2026, 2, 20, 0, 0),
 'Unnamed: 9': datetime.datetime(2026, 2, 20, 0, 0),
 'Unnamed: 10': datetime.datetime(2026, 1, 31, 0, 0),
 'Unnamed: 11': datetime.datetime(2026, 2, 28, 0, 0),
 'Unnamed: 12': datetime.datetime(2026, 3, 31, 0, 0),
 'Unnamed: 13': datetime.datetime(2026, 4, 30, 0, 0),
 'Unnamed: 14': datetime.datetime(2026, 5, 31, 0, 0),
 'Unnamed: 15': datetime.datetime(2026, 6, 30, 0, 0),
 'Unnamed: 16': datetime.datetime(2026, 7, 31, 0, 0),
 'Unnamed: 17': datetime.datetime(2026, 8, 31, 0, 0),
 'Unnamed: 18': datetime.datetime(2026, 9, 30, 0, 0),
 'Unnamed: 19': datetime.datetime(2026, 10, 31, 0, 0),
 'Unnamed: 20': datetime.datetime(2026, 11, 30, 0, 0),
 'Unnamed: 21': datetime.datetime(2026, 12, 31, 0, 0),
 'Unnamed: 22': 'post 2026',
 'Unnamed: 25': 'check',
 'Unnamed: 26': datetime.datetime(2026, 12, 31, 0, 0),
 'Unnamed: 28': 'Changes from Prior',
 'Unnamed: 30': 'SUMMARY',
 'Unnamed: 32': 'DATE ADDED'}

In [27]:
column_dict = col_actuals
column_dict.update(col_dates)

In [28]:
common_keys = set(col_names) & set(col_dates) & set(col_actuals)
column_dict_2 = {
    k: f"{col_names.get(k, '')} | {col_dates.get(k, '').strftime("%Y")}"
    for k in common_keys
}

In [29]:
column_dict_2

{'Unnamed: 7': 'ITD TOTAL SPEND | 2025',
 'Unnamed: 8': 'Year To Date | 2026',
 'Unnamed: 9': 'ITD TOTAL SPEND | 2026',
 'Unnamed: 3': 'Inception To Date | 2023',
 'Unnamed: 4': 'Year To Date | 2024',
 'Unnamed: 6': 'Year To Date | 2025',
 'Unnamed: 26': 'ITD w Commitments | 2026',
 'Unnamed: 5': 'Inception To Date | 2024'}

In [30]:
column_dict.update(column_dict_2)

In [31]:
column_dict

{'Unnamed: 3': 'Inception To Date | 2023',
 'Unnamed: 4': 'Year To Date | 2024',
 'Unnamed: 5': 'Inception To Date | 2024',
 'Unnamed: 6': 'Year To Date | 2025',
 'Unnamed: 7': 'ITD TOTAL SPEND | 2025',
 'Unnamed: 9': 'ITD TOTAL SPEND | 2026',
 'Unnamed: 23': 'Committed ',
 'Unnamed: 24': 'Optional',
 'Unnamed: 26': 'ITD w Commitments | 2026',
 'Unnamed: 2': 'Status',
 'Unnamed: 8': 'Year To Date | 2026',
 'Unnamed: 10': datetime.datetime(2026, 1, 31, 0, 0),
 'Unnamed: 11': datetime.datetime(2026, 2, 28, 0, 0),
 'Unnamed: 12': datetime.datetime(2026, 3, 31, 0, 0),
 'Unnamed: 13': datetime.datetime(2026, 4, 30, 0, 0),
 'Unnamed: 14': datetime.datetime(2026, 5, 31, 0, 0),
 'Unnamed: 15': datetime.datetime(2026, 6, 30, 0, 0),
 'Unnamed: 16': datetime.datetime(2026, 7, 31, 0, 0),
 'Unnamed: 17': datetime.datetime(2026, 8, 31, 0, 0),
 'Unnamed: 18': datetime.datetime(2026, 9, 30, 0, 0),
 'Unnamed: 19': datetime.datetime(2026, 10, 31, 0, 0),
 'Unnamed: 20': datetime.datetime(2026, 11, 30, 0, 0),
 'Unnamed: 21': datetime.datetime(2026, 12, 31, 0, 0),
 'Unnamed: 22': 'post 2026',
 'Unnamed: 25': 'check',
 'Unnamed: 28': 'Changes from Prior',
 'Unnamed: 30': 'SUMMARY',
 'Unnamed: 32': 'DATE ADDED'}

In [32]:
combined_data.head()

,index,Annapurna,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,division,_id
0,7,NaN,Even the Losers/ Unt. Randy Lanier,closed deals/active,NaN,NaN,0,2094378.5,2094378.5,0,2094378.5,0,263125,0,0,500000,0,0,500000,0,0,0,0,1250000,1763125,750000,0,4607503.5,NaN,NaN,NaN,script fee $4M; dev fee $1M; $30k option exten...,NaN,NaN,Film,Even the Losers/ Unt. Randy Lanier_Film
1,8,NaN,The Silent Patient - Plan B,closed deals/active,621510.95,1175887.1,1797398.05,190153.75,1987551.8,15593.75,2003145.55,0,15531.25,0,31062.5,0,0,0,0,0,0,0,0,0,31062.5,15531.25,0,2049739.3,NaN,NaN,NaN,polish and optional polish $100K; reflects the...,NaN,NaN,Film,The Silent Patient - Plan B_Film
2,9,NaN,Unt Nicole Taylor,closed deals/active,0,3395,3395,279562.5,282957.5,0,282957.5,0,0,0,0,0,187125,0,140343.75,0,0,142500,30000,0,439968.75,60000,0,782926.25,NaN,NaN,NaN,script fee $600K + fringe; optional polish $60K,NaN,NaN,Film,Unt Nicole Taylor_Film
3,10,NaN,American Spartan,closed deals/active,NaN,NaN,0,0,0,0,0,0,187125,187125,0,124750,0,124750,0,0,0,0,0,0,623750,NaN,0,623750,NaN,NaN,NaN,$500K first draft + first rewrite,NaN,NaN,Film,American Spartan_Film
4,11,NaN,Unt James Sweeney,closed deals/active,NaN,NaN,0,190318.63,190318.63,0,190318.63,0,178733.625,0,76600.125,0,0,76600.125,0,0,0,0,0,48457.5,331933.875,48457.5,0,570710.005,NaN,NaN,NaN,script fee $411K + fringe; optional polish $39K,NaN,NaN,Film,Unt James Sweeney_Film

In [33]:
stop

NameError: name 'stop' is not defined

In [34]:
column_dict['Unnamed: 1'] = "Title"
#column_dict['Unnamed: 16'] = "Remaining - Optional"
#column_dict['Unnamed: 15'] = "Remaining - Committed"

In [35]:

combined_data = combined_data.rename(column_dict, axis=1)
#data = data.rename(col_names, axis=1)

In [36]:
combined_data

,index,Annapurna,Title,Status,Inception To Date | 2023,Year To Date | 2024,Inception To Date | 2024,Year To Date | 2025,ITD TOTAL SPEND | 2025,Year To Date | 2026,ITD TOTAL SPEND | 2026,2026-01-31 00:00:00,2026-02-28 00:00:00,2026-03-31 00:00:00,2026-04-30 00:00:00,2026-05-31 00:00:00,2026-06-30 00:00:00,2026-07-31 00:00:00,2026-08-31 00:00:00,2026-09-30 00:00:00,2026-10-31 00:00:00,2026-11-30 00:00:00,2026-12-31 00:00:00,post 2026,Committed,Optional,check,ITD w Commitments | 2026,Unnamed: 27,Changes from Prior,Unnamed: 29,SUMMARY,Unnamed: 31,DATE ADDED,division,_id
0,7,NaN,Even the Losers/ Unt. Randy Lanier,closed deals/active,NaN,NaN,0,2094378.5,2094378.5,0,2094378.5,0,263125,0,0,500000,0,0,500000,0,0,0,0,1250000,1763125,750000,0,4607503.5,NaN,NaN,NaN,script fee $4M; dev fee $1M; $30k option exten...,NaN,NaN,Film,Even the Losers/ Unt. Randy Lanier_Film
1,8,NaN,The Silent Patient - Plan B,closed deals/active,621510.95,1175887.1,1797398.05,190153.75,1987551.8,15593.75,2003145.55,0,15531.25,0,31062.5,0,0,0,0,0,0,0,0,0,31062.5,15531.25,0,2049739.3,NaN,NaN,NaN,polish and optional polish $100K; reflects the...,NaN,NaN,Film,The Silent Patient - Plan B_Film
2,9,NaN,Unt Nicole Taylor,closed deals/active,0,3395,3395,279562.5,282957.5,0,282957.5,0,0,0,0,0,187125,0,140343.75,0,0,142500,30000,0,439968.75,60000,0,782926.25,NaN,NaN,NaN,script fee $600K + fringe; optional polish $60K,NaN,NaN,Film,Unt Nicole Taylor_Film
3,10,NaN,American Spartan,closed deals/active,NaN,NaN,0,0,0,0,0,0,187125,187125,0,124750,0,124750,0,0,0,0,0,0,623750,NaN,0,623750,NaN,NaN,NaN,$500K first draft + first rewrite,NaN,NaN,Film,American Spartan_Film
4,11,NaN,Unt James Sweeney,closed deals/active,NaN,NaN,0,190318.63,190318.63,0,190318.63,0,178733.625,0,76600.125,0,0,76600.125,0,0,0,0,0,48457.5,331933.875,48457.5,0,570710.005,NaN,NaN,NaN,script fee $411K + fringe; optional polish $39K,NaN,NaN,Film,Unt James Sweeney_Film
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,132,NaN,Her,pending,NaN,NaN,0,0,0,NaN,0,NaN,NaN,25000,NaN,NaN,25000,NaN,NaN,0,NaN,NaN,0,NaN,50000,NaN,0,100000,NaN,NaN,NaN,dev fee $50K,NaN,NaN,Theatre,Her_Theatre
2,133,NaN,Inter Alia (Broadway 2026),pending,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,Theatre,Inter Alia (Broadway 2026)_Theatre
0,27,NaN,Stephen Feder fee,closed deals/active,0,176824.8,176824.8,426973.76,603798.56,0,603798.56,0,35581,35581,0,0,0,0,0,0,0,0,0,0,71162,NaN,0,674960.56,NaN,NaN,NaN,3 months fee,NaN,NaN,Film,Stephen Feder fee_Film
1,28,NaN,Conner (Literary Research),closed deals/active,153450,34800,188250,34800,223050,2900,225950,0,2900,2900,2900,2900,2900,2900,2900,2900,2900,2900,2900,0,31900,NaN,0,257850,NaN,NaN,NaN,$2.9K/mo,NaN,NaN,Film,Conner (Literary Research)_Film
0,73,NaN,Conner (Literary Research),closed deals/active,153450,34800,188250,34800,223050,5800,228850,0,2900,2900,2900,2900,2900,2900,2900,2900,2900,2900,2900,0,31900,NaN,0,260750,NaN,NaN,NaN,$2.9K/mo,NaN,NaN,TV,Conner (Literary Research)_TV

In [37]:
print(combined_data.columns)
print([type(col) for col in combined_data.columns])

Index([                   'index',                'Annapurna',
                          'Title',                   'Status',
       'Inception To Date | 2023',      'Year To Date | 2024',
       'Inception To Date | 2024',      'Year To Date | 2025',
         'ITD TOTAL SPEND | 2025',      'Year To Date | 2026',
         'ITD TOTAL SPEND | 2026',        2026-01-31 00:00:00,
              2026-02-28 00:00:00,        2026-03-31 00:00:00,
              2026-04-30 00:00:00,        2026-05-31 00:00:00,
              2026-06-30 00:00:00,        2026-07-31 00:00:00,
              2026-08-31 00:00:00,        2026-09-30 00:00:00,
              2026-10-31 00:00:00,        2026-11-30 00:00:00,
              2026-12-31 00:00:00,                'post 2026',
                     'Committed ',                 'Optional',
                          'check', 'ITD w Commitments | 2026',
                    'Unnamed: 27',       'Changes from Prior',
                    'Unnamed: 29',                  'SUMMARY',
                    'Unnamed: 31',               'DATE ADDED',
                       'division',                      '_id'],
      dtype='object')
[<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'datetime.datetime'>, <class 'datetime.datetime'>, <class 'datetime.datetime'>, <class 'datetime.datetime'>, <class 'datetime.datetime'>, <class 'datetime.datetime'>, <class 'datetime.datetime'>, <class 'datetime.datetime'>, <class 'datetime.datetime'>, <class 'datetime.datetime'>, <class 'datetime.datetime'>, <class 'datetime.datetime'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]

In [38]:
import datetime
import pandas as pd

combined_data.columns = [
    col.strftime("%Y-%m-%d") if isinstance(col, (pd.Timestamp, datetime.datetime)) else str(col)
    for col in combined_data.columns
]

In [39]:
clean_cols = [col for col in combined_data.columns if "unnamed" not in col.lower() and col != "Annapurna"]

In [40]:
final_data = combined_data[clean_cols]

In [41]:
final_data

,index,Title,Status,Inception To Date | 2023,Year To Date | 2024,Inception To Date | 2024,Year To Date | 2025,ITD TOTAL SPEND | 2025,Year To Date | 2026,ITD TOTAL SPEND | 2026,2026-01-31,2026-02-28,2026-03-31,2026-04-30,2026-05-31,2026-06-30,2026-07-31,2026-08-31,2026-09-30,2026-10-31,2026-11-30,2026-12-31,post 2026,Committed,Optional,check,ITD w Commitments | 2026,Changes from Prior,SUMMARY,DATE ADDED,division,_id
0,7,Even the Losers/ Unt. Randy Lanier,closed deals/active,NaN,NaN,0,2094378.5,2094378.5,0,2094378.5,0,263125,0,0,500000,0,0,500000,0,0,0,0,1250000,1763125,750000,0,4607503.5,NaN,script fee $4M; dev fee $1M; $30k option exten...,NaN,Film,Even the Losers/ Unt. Randy Lanier_Film
1,8,The Silent Patient - Plan B,closed deals/active,621510.95,1175887.1,1797398.05,190153.75,1987551.8,15593.75,2003145.55,0,15531.25,0,31062.5,0,0,0,0,0,0,0,0,0,31062.5,15531.25,0,2049739.3,NaN,polish and optional polish $100K; reflects the...,NaN,Film,The Silent Patient - Plan B_Film
2,9,Unt Nicole Taylor,closed deals/active,0,3395,3395,279562.5,282957.5,0,282957.5,0,0,0,0,0,187125,0,140343.75,0,0,142500,30000,0,439968.75,60000,0,782926.25,NaN,script fee $600K + fringe; optional polish $60K,NaN,Film,Unt Nicole Taylor_Film
3,10,American Spartan,closed deals/active,NaN,NaN,0,0,0,0,0,0,187125,187125,0,124750,0,124750,0,0,0,0,0,0,623750,NaN,0,623750,NaN,$500K first draft + first rewrite,NaN,Film,American Spartan_Film
4,11,Unt James Sweeney,closed deals/active,NaN,NaN,0,190318.63,190318.63,0,190318.63,0,178733.625,0,76600.125,0,0,76600.125,0,0,0,0,0,48457.5,331933.875,48457.5,0,570710.005,NaN,script fee $411K + fringe; optional polish $39K,NaN,Film,Unt James Sweeney_Film
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,132,Her,pending,NaN,NaN,0,0,0,NaN,0,NaN,NaN,25000,NaN,NaN,25000,NaN,NaN,0,NaN,NaN,0,NaN,50000,NaN,0,100000,NaN,dev fee $50K,NaN,Theatre,Her_Theatre
2,133,Inter Alia (Broadway 2026),pending,NaN,NaN,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,Theatre,Inter Alia (Broadway 2026)_Theatre
0,27,Stephen Feder fee,closed deals/active,0,176824.8,176824.8,426973.76,603798.56,0,603798.56,0,35581,35581,0,0,0,0,0,0,0,0,0,0,71162,NaN,0,674960.56,NaN,3 months fee,NaN,Film,Stephen Feder fee_Film
1,28,Conner (Literary Research),closed deals/active,153450,34800,188250,34800,223050,2900,225950,0,2900,2900,2900,2900,2900,2900,2900,2900,2900,2900,2900,0,31900,NaN,0,257850,NaN,$2.9K/mo,NaN,Film,Conner (Literary Research)_Film
0,73,Conner (Literary Research),closed deals/active,153450,34800,188250,34800,223050,5800,228850,0,2900,2900,2900,2900,2900,2900,2900,2900,2900,2900,2900,0,31900,NaN,0,260750,NaN,$2.9K/mo,NaN,TV,Conner (Literary Research)_TV

In [42]:
from datetime import datetime
final_data['update_date'] = datetime.today()

In [43]:
final_data.columns

Index(['index', 'Title', 'Status', 'Inception To Date | 2023',
       'Year To Date | 2024', 'Inception To Date | 2024',
       'Year To Date | 2025', 'ITD TOTAL SPEND | 2025', 'Year To Date | 2026',
       'ITD TOTAL SPEND | 2026', '2026-01-31', '2026-02-28', '2026-03-31',
       '2026-04-30', '2026-05-31', '2026-06-30', '2026-07-31', '2026-08-31',
       '2026-09-30', '2026-10-31', '2026-11-30', '2026-12-31', 'post 2026',
       'Committed ', 'Optional', 'check', 'ITD w Commitments | 2026',
       'Changes from Prior', 'SUMMARY', 'DATE ADDED', 'division', '_id',
       'update_date'],
      dtype='object')

In [44]:
type_dict = {'Title':'string', 
             'Status':'string', 
             'Inception To Date | 2023':'float',
             'Year To Date | 2024':'float', 
             'Inception To Date | 2024':'float',
             'Year To Date | 2025':'float', 
             'ITD TOTAL SPEND | 2025':'float',
            'Year To Date | 2026':'float',
             'ITD TOTAL SPEND | 2026': 'float',
             'ITD w Commitments | 2026':'float', 
             '2026-01-31':'float', 
             '2026-02-28':'float', 
         #    'Q1 2026':'float',
             '2026-04-30':'float', 
             '2026-05-31':'float', 
            # 'Q2 2026':'float', 
             '2026-07-31':'float', 
             '2026-08-31':'float',
          #   'Q3 2026':'float', 
             '2026-10-31':'float', 
             '2026-11-30':'float', 
           #  'Q4 2026':'float', 
             'post 2026':'float',
             'Committed ':'float', 
             'Optional':'float',
             'Changes from Prior':'string',
             'SUMMARY':'string'
            }

In [45]:
final_data = final_data.astype(type_dict)

In [46]:
final_data['Committed '].sum()/1_000_000

17.078743322

In [47]:
final_data['ITD w Commitments | 2026'].sum()/1_000_000

34.892568452000006

In [48]:
final_data['Optional'].sum()/1_000_000

1.295662

In [49]:
final_data['ITD TOTAL SPEND | 2026'].sum()

16412718.88

In [50]:
final_data.division.unique()

array(['Film', 'TV', 'Intl_TV', 'corporate', 'Animation_Film',
       'Animation_TV', 'Theatre'], dtype=object)

In [51]:
final_data.groupby('division')['ITD TOTAL SPEND | 2026'].sum()

division
Animation_Film    5166126.13
Animation_TV       734137.86
Film              7065663.12
Intl_TV              3584.29
TV                3342628.84
Theatre                 0.00
corporate          100578.64
Name: ITD TOTAL SPEND | 2026, dtype: float64

In [52]:
final_data['Changes from Prior'] = final_data['Changes from Prior'].fillna("")
final_data['SUMMARY'] = final_data['SUMMARY'].fillna("")
final_data['Status'] = final_data['Status'].fillna("")

In [53]:
final_data.query("division =='Film'")

,index,Title,Status,Inception To Date | 2023,Year To Date | 2024,Inception To Date | 2024,Year To Date | 2025,ITD TOTAL SPEND | 2025,Year To Date | 2026,ITD TOTAL SPEND | 2026,2026-01-31,2026-02-28,2026-03-31,2026-04-30,2026-05-31,2026-06-30,2026-07-31,2026-08-31,2026-09-30,2026-10-31,2026-11-30,2026-12-31,post 2026,Committed,Optional,check,ITD w Commitments | 2026,Changes from Prior,SUMMARY,DATE ADDED,division,_id,update_date
0,7,Even the Losers/ Unt. Randy Lanier,closed deals/active,NaN,NaN,0.00,2094378.50,2094378.50,0.00,2094378.50,0.0,263125.000000,0,0.000000,500000.000000,0,0.000000,500000.000000,0,0.0,0.000000,0,1250000.00,1.763125e+06,750000.00,0,4.607504e+06,,script fee $4M; dev fee $1M; $30k option exten...,NaN,Film,Even the Losers/ Unt. Randy Lanier_Film,2026-02-23 10:52:16.567168
1,8,The Silent Patient - Plan B,closed deals/active,621510.95,1175887.10,1797398.05,190153.75,1987551.80,15593.75,2003145.55,0.0,15531.250000,0,31062.500000,0.000000,0,0.000000,0.000000,0,0.0,0.000000,0,0.00,3.106250e+04,15531.25,0,2.049739e+06,,polish and optional polish $100K; reflects the...,NaN,Film,The Silent Patient - Plan B_Film,2026-02-23 10:52:16.567168
2,9,Unt Nicole Taylor,closed deals/active,0.00,3395.00,3395.00,279562.50,282957.50,0.00,282957.50,0.0,0.000000,0,0.000000,0.000000,187125,0.000000,140343.750000,0,0.0,142500.000000,30000,0.00,4.399688e+05,60000.00,0,7.829262e+05,,script fee $600K + fringe; optional polish $60K,NaN,Film,Unt Nicole Taylor_Film,2026-02-23 10:52:16.567168
3,10,American Spartan,closed deals/active,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.0,187125.000000,187125,0.000000,124750.000000,0,124750.000000,0.000000,0,0.0,0.000000,0,0.00,6.237500e+05,NaN,0,6.237500e+05,,$500K first draft + first rewrite,NaN,Film,American Spartan_Film,2026-02-23 10:52:16.567168
4,11,Unt James Sweeney,closed deals/active,NaN,NaN,0.00,190318.63,190318.63,0.00,190318.63,0.0,178733.625000,0,76600.125000,0.000000,0,76600.125000,0.000000,0,0.0,0.000000,0,48457.50,3.319339e+05,48457.50,0,5.707100e+05,,script fee $411K + fringe; optional polish $39K,NaN,Film,Unt James Sweeney_Film,2026-02-23 10:52:16.567168
5,12,Cuban Missile Crisis,closed deals/active,NaN,NaN,0.00,187925.00,187925.00,0.00,187925.00,0.0,126225.000000,0,0.000000,49900.000000,0,0.000000,0.000000,49900,0.0,0.000000,0,140000.00,2.260250e+05,140000.00,0,5.539500e+05,,option $40K; script $330K + fringe; $85K optio...,NaN,Film,Cuban Missile Crisis_Film,2026-02-23 10:52:16.567168
6,13,Unt Bennett Miller (fka Untitled Charlie Kaufm...,closed deals/active,0.00,463944.90,463944.90,-374781.25,89163.65,0.00,89163.65,0.0,0.000000,0,0.000000,0.000000,0,0.000000,0.000000,0,0.0,0.000000,0,454687.50,4.546875e+05,NaN,0,5.438512e+05,,delivery of first draft $375K + fringe; $20K r...,NaN,Film,Unt Bennett Miller (fka Untitled Charlie Kaufm...,2026-02-23 10:52:16.567168
7,14,Five Hitmen,closed deals/active,0.00,56192.50,56192.50,288582.51,344775.01,0.00,344775.01,0.0,37275.000000,0,0.000000,37275.000000,0,0.000000,0.000000,0,0.0,0.000000,0,102506.25,7.455000e+04,102506.25,0,5.218313e+05,,option $10K; remaining script fee $195K + frin...,NaN,Film,Five Hitmen_Film,2026-02-23 10:52:16.567168
8,15,Untitled Dolly Parton,closed deals/active,0.00,0.00,0.00,5300.00,5300.00,0.00,5300.00,0.0,0.000000,0,124750.000000,0.000000,0,124750.000000,0.000000,0,0.0,187125.000000,0,0.00,4.366250e+05,NaN,0,4.419250e+05,,script fee $350K + fringe (pending writing deal),NaN,Film,Untitled Dolly Parton_Film,2026-02-23 10:52:16.567168
9,16,Twelve Minutes (Anim/TV),closed deals/active,97049.73,10502.54,107552.27,234.39,107786.66,0.00,107786.66,0.0,18083.333333,0,8083.333333,41416.666667,33333.333333,41416.666667,33333.333333,41416.666667,0.0,41416.666667,62125,0.00,3.206250e+05,NaN,0,4.284117e+05,,script fee $250K + fringe; Option $10K,NaN,Film,Twelve Minutes (Anim/TV)_Film,2026-02-23 10:52:16.567168
10,17,Finding Gobi,closed deals/active,0.00,15462.50,15462.50,18130.00,33592.50,0.00,33592.50,0.0,0.000000,124250,0.000000,124250.000000,0,0.000000,62125.000000,0,0.0,0.000000,62125,0.00,3.727500e+05,NaN,0,4.063425e+05,,script fee $300K + fringe (pending writing deal),NaN,Film,Finding Gobi_Film,2026-02-23 10:52:16.567168
11,18,Syd,closed deals/active,0.00,0.00,0.00,260925.00,260925.00,0.00,260925.00,0.0,0.000000,0,0.000000,0.000000,0,0.000000,0.000000,0,0.0,0.000000,0,0.00,0.000000e+00,NaN,0,2.609250e+05,,script fee $300K + fringe,NaN,Film,Syd_Film,2026-02-23 10:52:16.567168
12,19,Norco 80,closed deals/active,0.00,0.00,0.00,202306.26,202306.26,0.00,202306.26,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0,0.00,0.000000e+00,NaN,0,2.023063e+05,,script $450K + fringe - will be split 50% with...,NaN,Film,Norco 80_Film,2026-02-23 10:52:16.567168
13,20,American Jewel,closed deals/active,NaN,NaN,NaN,32993.48,32993.48,0.00,32993.48,0.0,101272.320000,0,0.000000,0.000000,0,0.000000,0.000000,0,0.0,0.000000,0,0.00,1.012723e+05,NaN,0,1.342658e+05,,script rewrite $53K; EP deal $75K,NaN,Film,American Jewel_Film,2026-02-23 10:52:16.567168
14,21,"Untitled Lessovitz, Quesada, Zund",closed deals/active,80040.06,0.00,80040.06,0.00,80040.06,0.00,80040.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,0,8.004006e+04,,,NaN,Film,"Untitled Lessovitz, Quesada, Zund_Film",2026-02-23 10:52:16.567168
15,22,Chef,closed deals/active,0.00,1885.00,1885.00,2420.00,4305.00,0.00,4305.00,0.0,63332.955250,0,0.000000,0.000000,0,0.000000,0.000000,0,0.0,0.000000,0,0.00,6.333296e+04,NaN,0,6.763796e+04,,WGA scale + 15% $50K + fringe,NaN,Film,Chef_Film,2026-02-23 10:52:16.567168
16,23,The Lost Wild - Film,closed deals/active,NaN,NaN,0.00,1100.00,1100.00,0.00,1100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.100000e+03,,,NaN,Film,The Lost Wild - Film_Film,2026-02-23 10:52:16.567168
0,32,Eric Warren Singer,pending,NaN,NaN,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,4500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.500000e+06,NaN,0,4.500000e+06,,script deal $4.5M,NaN,Film,Eric Warren Singer_Film,2026-02-23 10:52:16.567168
1,33,Grind,pending,NaN,NaN,0.00,224550.00,224550.00,0.00,224550.00,0.0,0.000000,202275,0.000000,134850.000000,0,134850.000000,0.000000,0,0.0,0.000000,0,0.00,4.719750e+05,NaN,0,6.965250e+05,,script fee $600K + fringe,NaN,Film,Grind_Film,2026-02-23 10:52:16.567168
2,34,The Legend of Georgia McBride,pending,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.000000,0,0.000000,62375.000000,0,0.000000,62375.000000,0,0.0,0.000000,62375,62375.00,2.495000e+05,NaN,0,2.495000e+05,,script fee $200K + fringe,NaN,Film,The Legend of Georgia McBride_Film,2026-02-23 10:52:16.567168
3,35,Blankets,pending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,10000.000000,0,75000.000000,0.000000,0,62500.000000,0.000000,0,62500.0,0.000000,0,0.00,2.100000e+05,NaN,0,2.100000e+05,,script fee $200K and option $10K,NaN,Film,Blankets_Film,2026-02-23 10:52:16.567168
4,36,Belly of the Beast,pending,NaN,NaN,0.00,55104.86,55104.86,0.00,55104.86,0.0,37500.000000,64233.38,37500.000000,0.000000,0,0.000000,0.000000,0,0.0,0.000000,0,0.00,6.423338e+04,75000.00,0,1.943382e+05,,"option fee 37K; optional polish 75K, 32K budge...",NaN,Film,Belly of the Beast_Film,2026-02-23 10:52:16.567168
5,37,The Visit,pending,0.00,0.00,0.00,268.17,268.17,0.00,268.17,0.0,0.000000,52000,0.000000,0.000000,0,0.000000,0.000000,0,0.0,0.000000,0,0.00,5.200000e+04,NaN,0,5.226817e+04,,option $50K; $2K travel,NaN,Film,The Visit_Film,2026-02-23 10:52:16.567168
6,38,Women Clothed by the Sun,pending,NaN,NaN,0.00,30638.73,30638.73,0.00,30638.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.063873e+04,,,NaN,Film,Women Clothed by the Sun_Film,2026-02-23 10:52:16.567168
7,39,Unt Soap Opera Doc,pending,NaN,NaN,0.00,3135.00,3135.00,0.00,3135.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3.135000e+03,,,NaN,Film,Unt Soap Opera Doc_Film,2026-02-23 10:52:16.567168
8,40,Unt Brady Corbett Project,pending,NaN,NaN,0.00,1205.00,1205.00,0.00,1205.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.205000e+03,,,2025-10-14 00:00:00,Film,Unt Brady Corbett Project_Film,2026-02-23 10:52:16.567168
9,41,Monument Valley,pending,NaN,NaN,0.00,NaN,0.00,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.000000e+00,,,NaN,Film,Monument Valley_Film,2026-02-23 10:52:16.567168
10,42,Minds on Fire,pending,NaN,NaN,0.00,NaN,0.00,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.000000e+00,,,NaN,Film,Minds on Fire_Film,2026-02-23 10:52:16.567168
0,27,Stephen Feder fee,closed deals/active,0.00,176824.80,176824.80,426973.76,603798.56,0.00,603798.56,0.0,35581.000000,35581,0.000000,0.000000,0,0.000000,0.000000,0,0.0,0.000000,0,0.00,7.116200e+04,NaN,0,6.749606e+05,,3 months fee,NaN,Film,Stephen Feder fee_Film,2026-02-23 10:52:16.567168
1,28,Conner (Literary Research),closed deals/active,153450.00,34800.00,188250.00,34800.00,223050.00,2900.00,225950.00,0.0,2900.000000,2900,2900.000000,2900.000000,2900,2900.000000,2900.000000,2900,2900.0,2900.000000,2900,0.00,3.190000e+04,NaN,0,2.578500e+05,,$2.9K/mo,NaN,Film,Conner (Literary Research)_Film,2026-02-23 10:52:16.567168

In [54]:
from datetime import datetime

doc_list = []

for _, row in final_data.iterrows():
    #changes_val = row['changes']
    #changes_val = str(changes_val) if pd.notna(changes_val) else ""

    new_update = {
        'update_date': row['update_date'],
        'Status': row['Status'],
        'title': row['Title'],
        'ITD_2023': row['Inception To Date | 2023'],
        'ITD_2024': row['Inception To Date | 2024'],
        'ITD_2025': row['ITD TOTAL SPEND | 2025'],
        'ITD_2026': row['ITD TOTAL SPEND | 2026'],
        '2024_spend': row['Year To Date | 2024'],
        '2025_spend': row['Year To Date | 2025'],
        '2026_spend': row['Year To Date | 2026'],
        'Remaining_Committed': row['Committed '],
        'Remaining_Optional': row['Optional'],
        'Total_Cost_with_Committments': row['ITD w Commitments | 2026'],
        'Changes':row['Changes from Prior'],
        "Summary":row['SUMMARY']
    }

    doc = {
        '_id': row['_id'],
        #'date_added':row['DATE ADDED'],
        'title': row['Title'],
        'division': row['division'].lower(),
        'Status': row['Status'],
        'update_date': row['update_date'],
        'Total_Cost_with_Committments': new_update['Total_Cost_with_Committments'],
        'ITD_2026': new_update['ITD_2026'],
        'Remaining_Committed': new_update['Remaining_Committed'],
        'Remaining_Optional': new_update['Remaining_Optional'],
        'Changes': new_update['Changes'],
        # This will *append* to the history on upsert
        '$push': {'updates': new_update}
    }

    doc_list.append(doc)

In [55]:
## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [56]:
db = client['InDevelopment']

collection = db['development_tracker']

In [57]:
len(doc_list)

91

In [58]:
doc_list

[{'_id': 'Even the Losers/ Unt. Randy Lanier_Film',
  'title': 'Even the Losers/ Unt. Randy Lanier',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 4607503.5,
  'ITD_2026': 2094378.5,
  'Remaining_Committed': 1763125.0,
  'Remaining_Optional': 750000.0,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'closed deals/active',
    'title': 'Even the Losers/ Unt. Randy Lanier',
    'ITD_2023': nan,
    'ITD_2024': 0.0,
    'ITD_2025': 2094378.5,
    'ITD_2026': 2094378.5,
    '2024_spend': nan,
    '2025_spend': 2094378.5,
    '2026_spend': 0.0,
    'Remaining_Committed': 1763125.0,
    'Remaining_Optional': 750000.0,
    'Total_Cost_with_Committments': 4607503.5,
    'Changes': '',
    'Summary': 'script fee $4M; dev fee $1M; $30k option extension; $13K consulting fee; $750K optional rewrite and polish'}}},
 {'_id': 'The Silent Patient - Plan B_Film',
  'title': 'The Silent Patient - Plan B',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 2049739.3,
  'ITD_2026': 2003145.55,
  'Remaining_Committed': 31062.5,
  'Remaining_Optional': 15531.25,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'closed deals/active',
    'title': 'The Silent Patient - Plan B',
    'ITD_2023': 621510.95,
    'ITD_2024': 1797398.05,
    'ITD_2025': 1987551.8,
    'ITD_2026': 2003145.55,
    '2024_spend': 1175887.1,
    '2025_spend': 190153.75,
    '2026_spend': 15593.75,
    'Remaining_Committed': 31062.5,
    'Remaining_Optional': 15531.25,
    'Total_Cost_with_Committments': 2049739.3,
    'Changes': '',
    'Summary': 'polish and optional polish $100K; reflects the $925K option purchase'}}},
 {'_id': 'Unt Nicole Taylor_Film',
  'title': 'Unt Nicole Taylor',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 782926.25,
  'ITD_2026': 282957.5,
  'Remaining_Committed': 439968.75,
  'Remaining_Optional': 60000.0,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'closed deals/active',
    'title': 'Unt Nicole Taylor',
    'ITD_2023': 0.0,
    'ITD_2024': 3395.0,
    'ITD_2025': 282957.5,
    'ITD_2026': 282957.5,
    '2024_spend': 3395.0,
    '2025_spend': 279562.5,
    '2026_spend': 0.0,
    'Remaining_Committed': 439968.75,
    'Remaining_Optional': 60000.0,
    'Total_Cost_with_Committments': 782926.25,
    'Changes': '',
    'Summary': 'script fee $600K + fringe; optional polish $60K'}}},
 {'_id': 'American Spartan_Film',
  'title': 'American Spartan',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 623750.0,
  'ITD_2026': 0.0,
  'Remaining_Committed': 623750.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'closed deals/active',
    'title': 'American Spartan',
    'ITD_2023': nan,
    'ITD_2024': 0.0,
    'ITD_2025': 0.0,
    'ITD_2026': 0.0,
    '2024_spend': nan,
    '2025_spend': 0.0,
    '2026_spend': 0.0,
    'Remaining_Committed': 623750.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 623750.0,
    'Changes': '',
    'Summary': '$500K first draft + first rewrite'}}},
 {'_id': 'Unt James Sweeney_Film',
  'title': 'Unt James Sweeney',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 570710.005,
  'ITD_2026': 190318.63,
  'Remaining_Committed': 331933.875,
  'Remaining_Optional': 48457.5,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'closed deals/active',
    'title': 'Unt James Sweeney',
    'ITD_2023': nan,
    'ITD_2024': 0.0,
    'ITD_2025': 190318.63,
    'ITD_2026': 190318.63,
    '2024_spend': nan,
    '2025_spend': 190318.63,
    '2026_spend': 0.0,
    'Remaining_Committed': 331933.875,
    'Remaining_Optional': 48457.5,
    'Total_Cost_with_Committments': 570710.005,
    'Changes': '',
    'Summary': 'script fee $411K + fringe; optional polish $39K'}}},
 {'_id': 'Cuban Missile Crisis_Film',
  'title': 'Cuban Missile Crisis',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 553950.0,
  'ITD_2026': 187925.0,
  'Remaining_Committed': 226025.0,
  'Remaining_Optional': 140000.0,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'closed deals/active',
    'title': 'Cuban Missile Crisis',
    'ITD_2023': nan,
    'ITD_2024': 0.0,
    'ITD_2025': 187925.0,
    'ITD_2026': 187925.0,
    '2024_spend': nan,
    '2025_spend': 187925.0,
    '2026_spend': 0.0,
    'Remaining_Committed': 226025.0,
    'Remaining_Optional': 140000.0,
    'Total_Cost_with_Committments': 553950.0,
    'Changes': '',
    'Summary': 'option $40K; script $330K + fringe; $85K optional rewrite; $55K optional polish'}}},
 {'_id': 'Unt Bennett Miller (fka Untitled Charlie Kaufman Project)_Film',
  'title': 'Unt Bennett Miller (fka Untitled Charlie Kaufman Project)',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 543851.15,
  'ITD_2026': 89163.65000000002,
  'Remaining_Committed': 454687.5,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'closed deals/active',
    'title': 'Unt Bennett Miller (fka Untitled Charlie Kaufman Project)',
    'ITD_2023': 0.0,
    'ITD_2024': 463944.9,
    'ITD_2025': 89163.65000000002,
    'ITD_2026': 89163.65000000002,
    '2024_spend': 463944.9,
    '2025_spend': -374781.25,
    '2026_spend': 0.0,
    'Remaining_Committed': 454687.5,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 543851.15,
    'Changes': '',
    'Summary': 'delivery of first draft $375K + fringe; $20K research (pending writing deal) '}}},
 {'_id': 'Five Hitmen_Film',
  'title': 'Five Hitmen',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 521831.26,
  'ITD_2026': 344775.01,
  'Remaining_Committed': 74550.0,
  'Remaining_Optional': 102506.25,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'closed deals/active',
    'title': 'Five Hitmen',
    'ITD_2023': 0.0,
    'ITD_2024': 56192.5,
    'ITD_2025': 344775.01,
    'ITD_2026': 344775.01,
    '2024_spend': 56192.5,
    '2025_spend': 288582.51,
    '2026_spend': 0.0,
    'Remaining_Committed': 74550.0,
    'Remaining_Optional': 102506.25,
    'Total_Cost_with_Committments': 521831.26,
    'Changes': '',
    'Summary': 'option $10K; remaining script fee $195K + fringe; optional rewrite and polish $82.5K'}}},
 {'_id': 'Untitled Dolly Parton_Film',
  'title': 'Untitled Dolly Parton',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 441925.0,
  'ITD_2026': 5300.0,
  'Remaining_Committed': 436625.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'closed deals/active',
    'title': 'Untitled Dolly Parton',
    'ITD_2023': 0.0,
    'ITD_2024': 0.0,
    'ITD_2025': 5300.0,
    'ITD_2026': 5300.0,
    '2024_spend': 0.0,
    '2025_spend': 5300.0,
    '2026_spend': 0.0,
    'Remaining_Committed': 436625.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 441925.0,
    'Changes': '',
    'Summary': 'script fee $350K + fringe (pending writing deal)'}}},
 {'_id': 'Twelve Minutes (Anim/TV)_Film',
  'title': 'Twelve Minutes (Anim/TV)',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 428411.66,
  'ITD_2026': 107786.65999999999,
  'Remaining_Committed': 320625.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'closed deals/active',
    'title': 'Twelve Minutes (Anim/TV)',
    'ITD_2023': 97049.73,
    'ITD_2024': 107552.26999999999,
    'ITD_2025': 107786.65999999999,
    'ITD_2026': 107786.65999999999,
    '2024_spend': 10502.54,
    '2025_spend': 234.39,
    '2026_spend': 0.0,
    'Remaining_Committed': 320625.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 428411.66,
    'Changes': '',
    'Summary': 'script fee $250K + fringe; Option $10K'}}},
 {'_id': 'Finding Gobi_Film',
  'title': 'Finding Gobi',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 406342.5,
  'ITD_2026': 33592.5,
  'Remaining_Committed': 372750.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'closed deals/active',
    'title': 'Finding Gobi',
    'ITD_2023': 0.0,
    'ITD_2024': 15462.5,
    'ITD_2025': 33592.5,
    'ITD_2026': 33592.5,
    '2024_spend': 15462.5,
    '2025_spend': 18130.0,
    '2026_spend': 0.0,
    'Remaining_Committed': 372750.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 406342.5,
    'Changes': '',
    'Summary': 'script fee $300K + fringe (pending writing deal)'}}},
 {'_id': 'Syd_Film',
  'title': 'Syd',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 260925.0,
  'ITD_2026': 260925.0,
  'Remaining_Committed': 0.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'closed deals/active',
    'title': 'Syd',
    'ITD_2023': 0.0,
    'ITD_2024': 0.0,
    'ITD_2025': 260925.0,
    'ITD_2026': 260925.0,
    '2024_spend': 0.0,
    '2025_spend': 260925.0,
    '2026_spend': 0.0,
    'Remaining_Committed': 0.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 260925.0,
    'Changes': '',
    'Summary': 'script fee $300K + fringe'}}},
 {'_id': 'Norco 80_Film',
  'title': 'Norco 80',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 202306.26,
  'ITD_2026': 202306.26,
  'Remaining_Committed': 0.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'closed deals/active',
    'title': 'Norco 80',
    'ITD_2023': 0.0,
    'ITD_2024': 0.0,
    'ITD_2025': 202306.26,
    'ITD_2026': 202306.26,
    '2024_spend': 0.0,
    '2025_spend': 202306.26,
    '2026_spend': 0.0,
    'Remaining_Committed': 0.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 202306.26,
    'Changes': '',
    'Summary': 'script $450K + fringe - will be split 50% with Fifth Season'}}},
 {'_id': 'American Jewel_Film',
  'title': 'American Jewel',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 134265.80000000002,
  'ITD_2026': 32993.48,
  'Remaining_Committed': 101272.32,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'closed deals/active',
    'title': 'American Jewel',
    'ITD_2023': nan,
    'ITD_2024': nan,
    'ITD_2025': 32993.48,
    'ITD_2026': 32993.48,
    '2024_spend': nan,
    '2025_spend': 32993.48,
    '2026_spend': 0.0,
    'Remaining_Committed': 101272.32,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 134265.80000000002,
    'Changes': '',
    'Summary': 'script rewrite $53K; EP deal $75K'}}},
 {'_id': 'Untitled Lessovitz, Quesada, Zund_Film',
  'title': 'Untitled Lessovitz, Quesada, Zund',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 80040.06,
  'ITD_2026': 80040.06,
  'Remaining_Committed': 0.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'closed deals/active',
    'title': 'Untitled Lessovitz, Quesada, Zund',
    'ITD_2023': 80040.06,
    'ITD_2024': 80040.06,
    'ITD_2025': 80040.06,
    'ITD_2026': 80040.06,
    '2024_spend': 0.0,
    '2025_spend': 0.0,
    '2026_spend': 0.0,
    'Remaining_Committed': 0.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 80040.06,
    'Changes': '',
    'Summary': ''}}},
 {'_id': 'Chef_Film',
  'title': 'Chef',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 67637.95525,
  'ITD_2026': 4305.0,
  'Remaining_Committed': 63332.95524999999,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'closed deals/active',
    'title': 'Chef',
    'ITD_2023': 0.0,
    'ITD_2024': 1885.0,
    'ITD_2025': 4305.0,
    'ITD_2026': 4305.0,
    '2024_spend': 1885.0,
    '2025_spend': 2420.0,
    '2026_spend': 0.0,
    'Remaining_Committed': 63332.95524999999,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 67637.95525,
    'Changes': '',
    'Summary': 'WGA scale + 15% $50K + fringe'}}},
 {'_id': 'The Lost Wild - Film_Film',
  'title': 'The Lost Wild - Film',
  'division': 'film',
  'Status': 'closed deals/active',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 1100.0,
  'ITD_2026': 1100.0,
  'Remaining_Committed': nan,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'closed deals/active',
    'title': 'The Lost Wild - Film',
    'ITD_2023': nan,
    'ITD_2024': 0.0,
    'ITD_2025': 1100.0,
    'ITD_2026': 1100.0,
    '2024_spend': nan,
    '2025_spend': 1100.0,
    '2026_spend': 0.0,
    'Remaining_Committed': nan,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 1100.0,
    'Changes': '',
    'Summary': ''}}},
 {'_id': 'Eric Warren Singer_Film',
  'title': 'Eric Warren Singer',
  'division': 'film',
  'Status': 'pending',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 4500000.0,
  'ITD_2026': 0.0,
  'Remaining_Committed': 4500000.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'pending',
    'title': 'Eric Warren Singer',
    'ITD_2023': nan,
    'ITD_2024': 0.0,
    'ITD_2025': 0.0,
    'ITD_2026': 0.0,
    '2024_spend': nan,
    '2025_spend': 0.0,
    '2026_spend': 0.0,
    'Remaining_Committed': 4500000.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 4500000.0,
    'Changes': '',
    'Summary': 'script deal $4.5M'}}},
 {'_id': 'Grind_Film',
  'title': 'Grind',
  'division': 'film',
  'Status': 'pending',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 696525.0,
  'ITD_2026': 224550.0,
  'Remaining_Committed': 471975.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'pending',
    'title': 'Grind',
    'ITD_2023': nan,
    'ITD_2024': 0.0,
    'ITD_2025': 224550.0,
    'ITD_2026': 224550.0,
    '2024_spend': nan,
    '2025_spend': 224550.0,
    '2026_spend': 0.0,
    'Remaining_Committed': 471975.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 696525.0,
    'Changes': '',
    'Summary': 'script fee $600K + fringe'}}},
 {'_id': 'The Legend of Georgia McBride_Film',
  'title': 'The Legend of Georgia McBride',
  'division': 'film',
  'Status': 'pending',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 249500.0,
  'ITD_2026': 0.0,
  'Remaining_Committed': 249500.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'pending',
    'title': 'The Legend of Georgia McBride',
    'ITD_2023': 0.0,
    'ITD_2024': 0.0,
    'ITD_2025': 0.0,
    'ITD_2026': 0.0,
    '2024_spend': 0.0,
    '2025_spend': 0.0,
    '2026_spend': 0.0,
    'Remaining_Committed': 249500.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 249500.0,
    'Changes': '',
    'Summary': 'script fee $200K + fringe'}}},
 {'_id': 'Blankets_Film',
  'title': 'Blankets',
  'division': 'film',
  'Status': 'pending',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 210000.0,
  'ITD_2026': nan,
  'Remaining_Committed': 210000.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'pending',
    'title': 'Blankets',
    'ITD_2023': nan,
    'ITD_2024': nan,
    'ITD_2025': nan,
    'ITD_2026': nan,
    '2024_spend': nan,
    '2025_spend': nan,
    '2026_spend': nan,
    'Remaining_Committed': 210000.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 210000.0,
    'Changes': '',
    'Summary': 'script fee $200K and option $10K'}}},
 {'_id': 'Belly of the Beast_Film',
  'title': 'Belly of the Beast',
  'division': 'film',
  'Status': 'pending',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 194338.24,
  'ITD_2026': 55104.86,
  'Remaining_Committed': 64233.380000000005,
  'Remaining_Optional': 75000.0,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'pending',
    'title': 'Belly of the Beast',
    'ITD_2023': nan,
    'ITD_2024': 0.0,
    'ITD_2025': 55104.86,
    'ITD_2026': 55104.86,
    '2024_spend': nan,
    '2025_spend': 55104.86,
    '2026_spend': 0.0,
    'Remaining_Committed': 64233.380000000005,
    'Remaining_Optional': 75000.0,
    'Total_Cost_with_Committments': 194338.24,
    'Changes': '',
    'Summary': 'option fee 37K; optional polish 75K, 32K budgeting and scouting'}}},
 {'_id': 'The Visit_Film',
  'title': 'The Visit',
  'division': 'film',
  'Status': 'pending',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 52268.17,
  'ITD_2026': 268.17,
  'Remaining_Committed': 52000.0,
  'Remaining_Optional': nan,
  'Changes': '',
  '$push': {'updates': {'update_date': Timestamp('2026-02-23 10:52:16.567168'),
    'Status': 'pending',
    'title': 'The Visit',
    'ITD_2023': 0.0,
    'ITD_2024': 0.0,
    'ITD_2025': 268.17,
    'ITD_2026': 268.17,
    '2024_spend': 0.0,
    '2025_spend': 268.17,
    '2026_spend': 0.0,
    'Remaining_Committed': 52000.0,
    'Remaining_Optional': nan,
    'Total_Cost_with_Committments': 52268.17,
    'Changes': '',
    'Summary': 'option $50K; $2K travel'}}},
 {'_id': 'Women Clothed by the Sun_Film',
  'title': 'Women Clothed by the Sun',
  'division': 'film',
  'Status': 'pending',
  'update_date': Timestamp('2026-02-23 10:52:16.567168'),
  'Total_Cost_with_Committments': 30638.73,
  'ITD_2026': 30638.73,
  'Remaining_Committed': nan,
  'Remaining_Optional': nan,
  'Changes': '',

In [59]:
stop

NameError: name 'stop' is not defined

collection.delete_many({})

In [60]:
from pymongo import UpdateOne

operations = []

for doc in doc_list:
    # Split update payloads
    base_fields = {
        'title': doc['title'],
        'division': doc['division'],
        'status':doc['Status'],
        'update_date': doc['update_date'],
        'Total_Cost_with_Committments': doc['Total_Cost_with_Committments'],
        'ITD_current_year': doc['ITD_2026'],
        'Remaining_Committed': doc['Remaining_Committed'],
        'Remaining_Optional': doc['Remaining_Optional'],
    }

    new_update = doc['$push']['updates']  # from your earlier construction

    operations.append(
        UpdateOne(
            {"_id": doc["_id"]},
            {
                "$set": base_fields,
                "$push": {"updates": new_update}
            },
            upsert=True
        )
    )

result = collection.bulk_write(operations)
print(f"Matched: {result.matched_count}, Upserted: {len(result.upserted_ids)}, Modified: {result.modified_count}")

Matched: 91, Upserted: 0, Modified: 91

In [61]:
docs = collection.find({})

In [62]:
df = pd.DataFrame(docs)

In [63]:
df.sort_values(by='Total_Cost_with_Committments',ascending=False)

,_id,ITD_current_year,Remaining_Committed,Remaining_Optional,Total_Cost_with_Committments,division,status,title,update_date,updates
0,Even the Losers/ Unt. Randy Lanier_Film,2094378.50,1763125.0,750000.00,4607503.50,film,closed deals/active,Even the Losers/ Unt. Randy Lanier,2026-02-23 10:52:16.567,"[{'update_date': 2026-02-17 14:57:00.405000, '..."
17,Eric Warren Singer_Film,0.00,4500000.0,NaN,4500000.00,film,pending,Eric Warren Singer,2026-02-23 10:52:16.567,"[{'update_date': 2026-02-17 14:57:00.405000, '..."
65,Stray - Animation_Animation_Film,1103402.37,1595209.0,NaN,2698611.37,animation_film,,Stray - Animation,2026-02-23 10:52:16.567,"[{'update_date': 2026-02-17 14:57:00.405000, '..."
66,Mantooth_Animation_Film,2448846.95,120000.0,NaN,2568846.95,animation_film,,Mantooth,2026-02-23 10:52:16.567,"[{'update_date': 2026-02-17 14:57:00.405000, '..."
1,The Silent Patient - Plan B_Film,2003145.55,31062.5,15531.25,2049739.30,film,closed deals/active,The Silent Patient - Plan B,2026-02-23 10:52:16.567,"[{'update_date': 2026-02-17 14:57:00.405000, '..."
...,...,...,...,...,...,...,...,...,...,...
48,Unt. Shi Yang_TV,0.00,0.0,NaN,0.00,tv,closed deals/active,Unt. Shi Yang,2026-02-23 10:52:16.567,"[{'update_date': 2026-02-17 14:57:00.405000, '..."
27,Minds on Fire_Film,0.00,NaN,NaN,0.00,film,pending,Minds on Fire,2026-02-23 10:52:16.567,"[{'update_date': 2026-02-17 14:57:00.405000, '..."
26,Monument Valley_Film,0.00,NaN,NaN,0.00,film,pending,Monument Valley,2026-02-23 10:52:16.567,"[{'update_date': 2026-02-17 14:57:00.405000, '..."
90,This Perfect Day_Intl_TV,0.00,0.0,NaN,0.00,intl_tv,pending,This Perfect Day,2026-02-23 10:52:16.567,"[{'update_date': 2026-02-23 10:33:43.615000, '..."
91,A Lie for a Life_Intl_TV,0.00,NaN,NaN,0.00,intl_tv,pending,A Lie for a Life,2026-02-23 10:52:16.567,"[{'update_date': 2026-02-23 10:33:43.615000, '..."

In [64]:
client.close()

In [65]:
df.groupby('division')['Total_Cost_with_Committments'].sum()/1_000_000

division
animation_film     8.073111
animation_tv       1.337186
corporate          0.134479
film              19.147636
intl_tv            0.185869
theatre            0.440000
tv                 5.664997
Name: Total_Cost_with_Committments, dtype: float64

In [66]:
df.query("division =='corporate'")

,_id,ITD_current_year,Remaining_Committed,Remaining_Optional,Total_Cost_with_Committments,division,status,title,update_date,updates
62,Calliope_corporate,44424.64,33900.0,NaN,78324.64,corporate,closed deals/active,Calliope,2026-02-23 10:52:16.567,"[{'update_date': 2026-02-17 14:57:00.405000, '..."
63,Grant & Sherman_corporate,10000.00,0.0,NaN,10000.00,corporate,closed deals/active,Grant & Sherman,2026-02-23 10:52:16.567,"[{'update_date': 2026-02-17 14:57:00.405000, '..."
64,England Expects (Film)_corporate,46154.00,NaN,NaN,46154.00,corporate,pending,England Expects (Film),2026-02-23 10:52:16.567,"[{'update_date': 2026-02-17 14:57:00.405000, '..."

In [67]:
df[['_id']].to_clipboard()