In [1]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# Step 1: Define the scope
scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]

# Step 2: Load credentials
creds = ServiceAccountCredentials.from_json_keyfile_name("ultra-sound-463216-c2-0e076e5f88fe.json", scope)

# Step 3: Authorize and connect
client = gspread.authorize(creds)

# Step 4: Open sheet by URL
sheet_url = "https://docs.google.com/spreadsheets/d/1VkL-CuVPIRVJ6gkAkoPdHuDxBXZ-Cx6WgjvqRaiOsjA/edit?gid=0#gid=0"
spreadsheet = client.open_by_url(sheet_url)

# Optional: Access specific sheet/tab
sheet = spreadsheet.worksheet("slate")  # or spreadsheet.worksheet("SheetName")

# Example: Read data
data = sheet.get_all_records(head=1)

In [2]:
import pandas as pd

df = pd.DataFrame(data)

In [3]:
df

,_id,Status
0,American Jewel,ADVANCED DEVELOPMENT
1,Belly of The Beast,ADVANCED DEVELOPMENT
2,Even the Losers,ADVANCED DEVELOPMENT
3,Minds on Fire,ADVANCED DEVELOPMENT
4,Origin of the World fka Unt. Brady Corbet & Mo...,ADVANCED DEVELOPMENT
5,The Silent Patient,ADVANCED DEVELOPMENT
6,12 Minutes,INTERNAL DEVELOPMENT
7,American Spartan,INTERNAL DEVELOPMENT
8,Unt. Bennett Miller,INTERNAL DEVELOPMENT
9,Chef,INTERNAL DEVELOPMENT
10,Cuban Missile Crisis,INTERNAL DEVELOPMENT
11,Dolly,INTERNAL DEVELOPMENT
12,Evie Mcbrayne fka Unt. Nicole Taylor,INTERNAL DEVELOPMENT
13,Finding Gobi,INTERNAL DEVELOPMENT
14,Five Hitmen,INTERNAL DEVELOPMENT
15,Unt. James Sweeney,INTERNAL DEVELOPMENT
16,Into the Glory whole,INTERNAL DEVELOPMENT
17,The Legend of Georgia McBride,INTERNAL DEVELOPMENT
18,The Lost Wild,INTERNAL DEVELOPMENT
19,Norco 80,INTERNAL DEVELOPMENT
20,Syd,INTERNAL DEVELOPMENT
21,Unt. Ted Schipper,INTERNAL DEVELOPMENT
22,Unt. Beast Fiction Project,PENDING DEALS
23,Clair Obscur: Expedition 33,PENDING DEALS
24,Unt. Eric Singer,PENDING DEALS
25,Grind,PENDING DEALS
26,The Invite,POST // AWAITING RELEASE
27,The Testament of Ann Lee,POST // AWAITING RELEASE

In [4]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# Step 1: Define the scope
scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]

# Step 2: Load credentials
creds = ServiceAccountCredentials.from_json_keyfile_name("ultra-sound-463216-c2-0e076e5f88fe.json", scope)

# Step 3: Authorize and connect
client = gspread.authorize(creds)

# Step 4: Open sheet by URL
sheet_url = "https://docs.google.com/spreadsheets/d/1VkL-CuVPIRVJ6gkAkoPdHuDxBXZ-Cx6WgjvqRaiOsjA/edit?gid=0#gid=0"
spreadsheet = client.open_by_url(sheet_url)

# Optional: Access specific sheet/tab
sheet = spreadsheet.worksheet("submissions")  # or spreadsheet.worksheet("SheetName")

# Example: Read data
data2 = sheet.get_all_records(head=1)

In [5]:
import pandas as pd

df2 = pd.DataFrame(data2)

cancelled_idx = df2.query("Project =='Cancelled Games'").index[0]

df['status'] = 'active'
df2['status'] = 'released'

df2.loc[cancelled_idx:, 'status'] = 'cancelled'

df2 = df2.drop(cancelled_idx)

df2.head()

df2 = df2.drop(df2.query("Project ==''").index.values)

In [6]:
df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(r"\s+", "_", regex=True)   # spaces -> underscore
      .str.replace(r"[^0-9a-zA-Z_]", "", regex=True)  # optional: remove weird chars
      + "_pt"
)

In [7]:
df2.columns = (
    df2.columns
      .str.lower()
      .str.strip()
      .str.replace(r"\s+", "_", regex=True)   # spaces -> underscore
      .str.replace(r"[^0-9a-zA-Z_]", "", regex=True)  # optional: remove weird chars
      + "_sub"
)

In [31]:
df2 = df2.rename({"_id_sub":"_id"}, axis=1)
df = df.rename({"_id_pt":"_id"}, axis=1)

In [32]:
df2

,_id,date_sub,elements_sub,loglineinfo_sub,materials_sub,reviewer_comments_sub,reviewing_sub,status_sub,submitted_by_sub
0,NO LONGER WITH US,11/3/25,W: Tamara Jenkins\n D: Tamara Jenkins\n P: Mar...,,Submissions/NoLongerWith7_10_25.pdf,very small slice of life. I don’t think makes ...,Katelin Mora,Passed,Stephen Feder
1,TOPDOG/UNDERDOG,10/24/25,Suzan-Lori Parks,,,,Katelin Mora,Passed,Steven Farneth @ Cinetic Media
2,THE FOLLY,10/31/25,Ezra Woods,LOGLINE: As a displaced French noble family st...,Submissions/THE_FOLLY_10.7.25_Wengrod.pdf,,"Chelsea Barnard, Katelin Mora",In progress,Trent Hubbard @ Linden Entertainment
3,THE BURN,11/5/25,,,,,Katelin Mora,Not started,Shelby G
4,THE PROJECT,11/6/25,W: Jamie Carragher,Logline: After being promised the chance to fu...,,,"Peryn Reeves-Darby, Jenna Go",In progress,Ben Neumann (Kaplan Perrone)
5,ADRENALINE,11/6/25,W: Jos Howard Demme,Logline: When two queer men in 80s Los Angeles...,,,"Peryn Reeves-Darby, Jenna Go",In progress,Ben Neumann (Kaplan Perrone)
6,DEEP SLEEP,11/5/25,W: Regina Kim,Logline: When a grief-stricken air-traffic con...,,,Peryn Reeves-Darby,In progress,Joe Cavalier (Heroes & Villians)
7,INDIGO,10/29/25,W: Ola Shokunbi,Art heist,,,Peryn Reeves-Darby,In progress,Ola Shokunbi
8,DEMON LOVER,11/14/25,W: Nathan Elston and Natalia Leite,"based on the short story ""I Can See Right Thro...",,,Jenna Go,In progress,Eni Akintade (UTA)
9,THE TOMATO CAN,11/24/25,D: Dee Rees\n W: Michael Brandt\n Story by: Ja...,Logline: THE TOMATO CAN follows an aging boxer...,,,,Not started,
10,TOXIC,11/17/25,D: Stephanie Laing\n W: Bill Gullo\n P: Chris ...,Logline: When a patient woman loses her patien...,,,,In progress,Jenn Semmler
11,PINEHURST,11/20/25,D: Joshua Rofé\n W: Joshua Rofé & Steven J Berger,Logline: PINEHURST follows an aspiring actress...,,,,Not started,Joshua Rofé
12,FIRST LADY,12/1/25,W: Mike Demski,FIRST LADY is a contained action thriller with...,,,,Not started,Lars Theriot
13,TIS THE SEASON,12/1/25,W: Craig Coyne\n P: Industry Entertainment & M...,Logline: When a divorced American couple’s pac...,,,,Not started,Lars Theriot
14,IKEAVILLE,12/1/25,"W/D: Mike Vukadinovich\n C: Kit Harington, May...",,,,,Not started,Lars Theriot
15,ENDINGS ARE A BITCH,11/5/25,W Tommy Wallach,based on his novel Thanks for The Trouble. The...,,,Katelin Mora,Not started,Frank Wuliger
16,NEVER EVENT,12/4/25,w/d. Harry Wootliff,"Thriller-horror, set in the world of high-end ...",,Looking for script finance,Skye Optican,Not started,Katie Sinclair (Riff Raff)

In [33]:
df.head()

                                                 _id             status_pt
0                                     American Jewel  ADVANCED DEVELOPMENT
1                                 Belly of The Beast  ADVANCED DEVELOPMENT
2                                    Even the Losers  ADVANCED DEVELOPMENT
3                                      Minds on Fire  ADVANCED DEVELOPMENT
4  Origin of the World fka Unt. Brady Corbet & Mo...  ADVANCED DEVELOPMENT

In [34]:
data = df.to_dict(orient='records')

In [35]:
sub_data = df2.to_dict(orient='records')

In [36]:
stop

NameError: name 'stop' is not defined

In [39]:
## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [40]:
db = client['InDevelopment']

collection = db['house_submissions']
collection_projects = db['projects']

collection.delete_many({})

collection_projects.delete_many({})

In [41]:
def batchify(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]

In [42]:
from pymongo import UpdateOne


#####
for batch in batchify(data, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection_projects.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 28, Inserted: 0, Modified: 0

In [43]:
from pymongo import UpdateOne


#####
for batch in batchify(sub_data, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 0, Inserted: 17, Modified: 0

In [44]:
from datetime import datetime


datetime.today()

datetime.datetime(2025, 12, 10, 10, 49, 51, 76520)

In [45]:
client.close()