In [1]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# Step 1: Define the scope
scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]

# Step 2: Load credentials
creds = ServiceAccountCredentials.from_json_keyfile_name("ultra-sound-463216-c2-0e076e5f88fe.json", scope)

# Step 3: Authorize and connect
client = gspread.authorize(creds)

# Step 4: Open sheet by URL
sheet_url = "https://docs.google.com/spreadsheets/d/1CVrRk4--uOQx5iEtAUd798LeJM8g_jxA3qr634guj18/edit?gid=748703564#gid=748703564"
spreadsheet = client.open_by_url(sheet_url)

# Optional: Access specific sheet/tab
sheet = spreadsheet.worksheet("Film")  # or spreadsheet.worksheet("SheetName")

# Example: Read data
data = sheet.get_all_records(head=1)

In [2]:
import pandas as pd

df = pd.DataFrame(data)

In [3]:
df["Title"] = df["Title"].str.title()

In [4]:
df

,Title,AP DIVISION,Project Stage,AP Lead,AP Jr.,AP Dev,BA Status,Creative Status,Next Milestone,Key Timing,...,Producer 2,Cast 1,Cast 2,Cast 3,Cast 4,BA Update Time,Creative Status Update Time,Key Timing Update Time,slack_channel_id,links
0,I Love Boosters,Film,1. GTM,"Megan, Pat",,,OPA with Neon is fully signed. No pending deals.,CB and PC discussing cut with Swett. Boots is ...,,● Option Expiration: Neon purchased the rights...,...,,LaKeith Stanfield,Demi Moore,Taylour Page,,5/28/2025 22:24:59,8/25/2025 6:23:09,,C07E54SLMA7,
1,The Invite,Film,1. GTM,"Megan, Pat",Alex,,Finance agreement and related agreements close...,Expecting Director’s Cut end of next week.,,● Option Expiration: N/A\n● Next Draft Expecte...,...,,Olivia Wilde,Seth Rogen,Edward Norton,,5/28/2025 22:24:59,8/25/2025 6:21:43,10/7/2025 19:34:38,C08C6HA4GG2,
2,12 Minutes (Film),"Film, Interactive",3. Internal Development,"Megan, Hector, Pat, Katelin",,,Underlying rights agreement is fully executed....,Bo and Jantje currently showrunning and are wa...,,● Option Expiration: 2.17.26. No further exten...,...,,,,,,5/27/2025 7:06:10,8/25/2025 6:24:26,5/27/2025 7:06:14,C07CHMLR64W,
3,American Jewel,Film,3. Internal Development,"Pat, Megan, Zelda, Josh",Jenna,Josh,"Closed deal terms with Chernin 6.2.25, AP to r...",Setting kick-off for the group. ME and Yngvild...,New draft delivered 6/27,● Option Expiration: N/A\n● Next Draft Expecte...,...,,Rachel Sennott,,,,8/25/2025 6:24:56,8/25/2025 6:25:19,7/3/2025 5:39:38,C090BQFAJ8Y,
4,American Spartan,Film,3. Internal Development,"Megan, Pat",,,Mark Boal deal terms closed. JT sent revised ...,PC checked in with Boal. He’s working away.,,● Option Expiration: N/A\n● Next Draft Expecte...,...,,,,,,7/3/2025 5:40:17,7/14/2025 6:49:30,,C09CHCG0080,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,Vice,Film,8. Library,,,,,,,,...,,,,,,,,,,
72,Where’D You Go Bernadette,Film,8. Library,,,,,,,,...,,,,,,,,,,
73,Wiener-Dog,Film,8. Library,,,,,,,,...,,,,,,,,,,
74,Wounds,Film,8. Library,,,,,,,,...,,,,,,,,,,
75,Zero Dark Thirty,Film,8. Library,,,,,,,,...,,,,,,,,,,

In [5]:
df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(r"\s+", "_", regex=True)   # spaces -> underscore
      .str.replace(r"[^0-9a-zA-Z_]", "", regex=True)  # optional: remove weird chars
      + "_film_pt"
)

In [6]:
df = df.rename({"title_film_pt":"_id"}, axis=1)

In [7]:
cols = [
    '_id', 
        'ap_division_film_pt', 
        'project_stage_film_pt',
       'ap_lead_film_pt', 
        'ap_jr_film_pt', 
        'ap_dev_film_pt',
       'ba_status_film_pt', 
        'creative_status_film_pt',
       'next_milestone_film_pt', 
        'key_timing_film_pt',
       'option_expiration_film_pt', 
        'key_timing_date_film_pt',
       'underlying_ip_film_pt', 
        'logline_film_pt',
       'platform__distribution_film_pt', 
        'deal_type_film_pt',
       'partners_and_vendors_film_pt', 
        'creators_film_pt', 
        'director_film_pt',
       'writers_film_pt', 
        'producer_1_film_pt', 
        'producer_2_film_pt',
       'cast_1_film_pt', 
        'cast_2_film_pt', 
        'cast_3_film_pt', 
        'cast_4_film_pt',
       ]

In [8]:
#df["project_stage_film_pt"] = df["project_stage_film_pt"].str.split(",").apply(lambda x: [i.strip() for i in x])
df["ap_lead_film_pt"] = df["ap_lead_film_pt"].str.split(",").apply(lambda x: [i.strip() for i in x])
df["ap_jr_film_pt"] = df["ap_jr_film_pt"].str.split(",").apply(lambda x: [i.strip() for i in x])
df["ap_division_film_pt"] = df["ap_division_film_pt"].str.split(",").apply(lambda x: [i.strip() for i in x])

In [9]:
df[cols]

,_id,ap_division_film_pt,project_stage_film_pt,ap_lead_film_pt,ap_jr_film_pt,ap_dev_film_pt,ba_status_film_pt,creative_status_film_pt,next_milestone_film_pt,key_timing_film_pt,...,partners_and_vendors_film_pt,creators_film_pt,director_film_pt,writers_film_pt,producer_1_film_pt,producer_2_film_pt,cast_1_film_pt,cast_2_film_pt,cast_3_film_pt,cast_4_film_pt
0,I Love Boosters,[Film],1. GTM,"[Megan, Pat]",[],,OPA with Neon is fully signed. No pending deals.,CB and PC discussing cut with Swett. Boots is ...,,● Option Expiration: Neon purchased the rights...,...,Ryder Picture Co.,,Boots Riley,Boots Riley,Aaron Ryder,,LaKeith Stanfield,Demi Moore,Taylour Page,
1,The Invite,[Film],1. GTM,"[Megan, Pat]",[Alex],,Finance agreement and related agreements close...,Expecting Director’s Cut end of next week.,,● Option Expiration: N/A\n● Next Draft Expecte...,...,Filmnation,,Olivia Wilde,Will McCormack & Rashida Jones,David Permut,,Olivia Wilde,Seth Rogen,Edward Norton,
2,12 Minutes (Film),"[Film, Interactive]",3. Internal Development,"[Megan, Hector, Pat, Katelin]",[],,Underlying rights agreement is fully executed....,Bo and Jantje currently showrunning and are wa...,,● Option Expiration: 2.17.26. No further exten...,...,Netflix,,,OWA,,,,,,
3,American Jewel,[Film],3. Internal Development,"[Pat, Megan, Zelda, Josh]",[Jenna],Josh,"Closed deal terms with Chernin 6.2.25, AP to r...",Setting kick-off for the group. ME and Yngvild...,New draft delivered 6/27,● Option Expiration: N/A\n● Next Draft Expecte...,...,Chernin,,Yngvild Sve Flikke,Jia Tolentino,Kori Adelson,,Rachel Sennott,,,
4,American Spartan,[Film],3. Internal Development,"[Megan, Pat]",[],,Mark Boal deal terms closed. JT sent revised ...,PC checked in with Boal. He’s working away.,,● Option Expiration: N/A\n● Next Draft Expecte...,...,,,Mark Boal,Mark Boal,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,Vice,[Film],8. Library,[],[],,,,,,...,,,,,,,,,,
72,Where’D You Go Bernadette,[Film],8. Library,[],[],,,,,,...,,,,,,,,,,
73,Wiener-Dog,[Film],8. Library,[],[],,,,,,...,,,,,,,,,,
74,Wounds,[Film],8. Library,[],[],,,,,,...,,,,,,,,,,
75,Zero Dark Thirty,[Film],8. Library,[],[],,,,,,...,,,,,,,,,,

In [10]:
title_map = {
    "Even The Losers (Fka Need For Weed)": "Even the Losers",
    "Belly Of The Beast": "Belly of The Beast",
    'Brady Corbet / Mona Fastvold Project (Unt.)': "Origin of the World fka Unt. Brady Corbet & Mona Fastvold Project",

    'Silent Patient, The ': "The Silent Patient",
    '12 Minutes (Film)': "12 Minutes",
    'Bennett Miller (Unt.) ':"Unt. Bennett Miller",
    
    'Nicole Taylor Idea (Unt.)':"Evie Mcbrayne fka Unt. Nicole Taylor",
    'James Sweeney (Unt.)':"Unt. James Sweeney",
    'Into The Glory Whole':"Into the Glory whole",
    'Legend Of Georgia Mcbride, The ':"The Legend of Georgia McBride",

        'Lost Wild, The ':"The Lost Wild",


        'Beast Fiction Project (Unt.)':"Unt. Beast Fiction Project",

            'Ann Lee (Fka The Woman Clothed By The Sun) ':"The Testament of Ann Lee",



    # add more…
}

df['_id'] = df['_id'].replace(title_map)

In [11]:
df.query("_id=='The Invite'")

,_id,ap_division_film_pt,project_stage_film_pt,ap_lead_film_pt,ap_jr_film_pt,ap_dev_film_pt,ba_status_film_pt,creative_status_film_pt,next_milestone_film_pt,key_timing_film_pt,...,producer_2_film_pt,cast_1_film_pt,cast_2_film_pt,cast_3_film_pt,cast_4_film_pt,ba_update_time_film_pt,creative_status_update_time_film_pt,key_timing_update_time_film_pt,slack_channel_id_film_pt,links_film_pt
1,The Invite,[Film],1. GTM,"[Megan, Pat]",[Alex],,Finance agreement and related agreements close...,Expecting Director’s Cut end of next week.,,● Option Expiration: N/A\n● Next Draft Expecte...,...,,Olivia Wilde,Seth Rogen,Edward Norton,,5/28/2025 22:24:59,8/25/2025 6:21:43,10/7/2025 19:34:38,C08C6HA4GG2,

In [12]:
df.head().columns

Index(['_id', 'ap_division_film_pt', 'project_stage_film_pt',
       'ap_lead_film_pt', 'ap_jr_film_pt', 'ap_dev_film_pt',
       'ba_status_film_pt', 'creative_status_film_pt',
       'next_milestone_film_pt', 'key_timing_film_pt',
       'option_expiration_film_pt', 'key_timing_date_film_pt',
       'underlying_ip_film_pt', 'logline_film_pt',
       'platform__distribution_film_pt', 'deal_type_film_pt',
       'partners_and_vendors_film_pt', 'creators_film_pt', 'director_film_pt',
       'writers_film_pt', 'producer_1_film_pt', 'producer_2_film_pt',
       'cast_1_film_pt', 'cast_2_film_pt', 'cast_3_film_pt', 'cast_4_film_pt',
       'ba_update_time_film_pt', 'creative_status_update_time_film_pt',
       'key_timing_update_time_film_pt', 'slack_channel_id_film_pt',
       'links_film_pt'],
      dtype='object')

In [13]:
data = df.to_dict(orient='records')

In [14]:
stop

NameError: name 'stop' is not defined

In [15]:
## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [16]:
db = client['InDevelopment']

collection = db['projects']

In [17]:
def batchify(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]

collection.delete_many({})

In [18]:
from pymongo import UpdateOne


#####
for batch in batchify(data, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 76, Inserted: 0, Modified: 0

In [19]:
from datetime import datetime


datetime.today()

datetime.datetime(2025, 12, 16, 6, 27, 32, 201869)

In [20]:
client.close()