In [1]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# Step 1: Define the scope
scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]

# Step 2: Load credentials
creds = ServiceAccountCredentials.from_json_keyfile_name("ultra-sound-463216-c2-0e076e5f88fe.json", scope)

# Step 3: Authorize and connect
client = gspread.authorize(creds)

# Step 4: Open sheet by URL
sheet_url = "https://docs.google.com/spreadsheets/d/1JVNtgSJFswHEH6iHz-XP1qUzdyxQXa5Q-WGI86CqGmE/edit?gid=1534679013#gid=1534679013"
spreadsheet = client.open_by_url(sheet_url)

# Optional: Access specific sheet/tab
sheet = spreadsheet.worksheet("film_long")  # or spreadsheet.worksheet("SheetName")

# Example: Read data
data = sheet.get_all_records(head=1)

In [2]:
import pandas as pd

df = pd.DataFrame(data)

In [3]:
df.columns

Index(['id', 'title', 'phase', 'start', 'end'], dtype='object')

In [4]:
date_cols = ['start', 'end']

In [5]:
df[date_cols] = df[date_cols].apply(pd.to_datetime, errors="coerce")

df = df.replace({pd.NaT: None})

In [6]:
df

,id,title,phase,start,end
0,857713278,American Jewel,writing,2026-01-01,2026-09-01
1,857711298,Even The Losers,writing,2026-01-01,2026-08-15
2,905512660,Unt. Nicole Taylor (bud target: ),writing,2026-01-01,2027-12-31
3,905507328,Silent Patient (bud target: net 25M),writing,2026-01-01,2026-09-01
4,905509963,Norco 80 (bud target: net 40-50M),writing,2026-01-01,2026-07-31
5,905500587,SOAPS (budget: 2M),post,2026-03-01,2026-07-31
6,828769775,The Invite,release,2026-06-26,2026-07-24
7,905509963,Norco 80 (bud target: net 40-50M),prep,2026-08-01,2026-09-30
8,905500587,SOAPS (budget: 2M),delivery,2026-08-01,2026-09-01
9,857711298,Even The Losers,prep,2026-08-15,2026-11-01
10,857713278,American Jewel,prep,2026-09-01,2026-11-01
11,905507328,Silent Patient (bud target: net 25M),prep,2026-09-01,2026-10-31
12,905509963,Norco 80 (bud target: net 40-50M),shoot,2026-10-01,2026-11-30
13,905507328,Silent Patient (bud target: net 25M),shoot,2026-10-31,2026-12-31
14,857713278,American Jewel,shoot,2026-11-01,2027-01-01
15,857711298,Even The Losers,shoot,2026-11-01,2027-03-01
16,905509963,Norco 80 (bud target: net 40-50M),post,2026-12-01,2027-07-01
17,857713278,American Jewel,post,2027-01-01,2027-07-01
18,905507328,Silent Patient (bud target: net 25M),post,2027-01-01,2027-06-30
19,857711298,Even The Losers,post,2027-03-01,2027-10-01
20,857713278,American Jewel,delivery,2027-07-01,2027-07-29
21,905507328,Silent Patient (bud target: net 25M),delivery,2027-07-01,2027-07-31
22,905509963,Norco 80 (bud target: net 40-50M),delivery,2027-07-01,2027-07-31
23,857711298,Even The Losers,delivery,2027-10-01,2027-10-29

In [7]:
df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(r"\s+", "_", regex=True)   # spaces -> underscore
      .str.replace(r"[^0-9a-zA-Z_]", "", regex=True)  # optional: remove weird chars
   #   + "_film_milestone_tracker"
)

In [8]:
df

,id,title,phase,start,end
0,857713278,American Jewel,writing,2026-01-01,2026-09-01
1,857711298,Even The Losers,writing,2026-01-01,2026-08-15
2,905512660,Unt. Nicole Taylor (bud target: ),writing,2026-01-01,2027-12-31
3,905507328,Silent Patient (bud target: net 25M),writing,2026-01-01,2026-09-01
4,905509963,Norco 80 (bud target: net 40-50M),writing,2026-01-01,2026-07-31
5,905500587,SOAPS (budget: 2M),post,2026-03-01,2026-07-31
6,828769775,The Invite,release,2026-06-26,2026-07-24
7,905509963,Norco 80 (bud target: net 40-50M),prep,2026-08-01,2026-09-30
8,905500587,SOAPS (budget: 2M),delivery,2026-08-01,2026-09-01
9,857711298,Even The Losers,prep,2026-08-15,2026-11-01
10,857713278,American Jewel,prep,2026-09-01,2026-11-01
11,905507328,Silent Patient (bud target: net 25M),prep,2026-09-01,2026-10-31
12,905509963,Norco 80 (bud target: net 40-50M),shoot,2026-10-01,2026-11-30
13,905507328,Silent Patient (bud target: net 25M),shoot,2026-10-31,2026-12-31
14,857713278,American Jewel,shoot,2026-11-01,2027-01-01
15,857711298,Even The Losers,shoot,2026-11-01,2027-03-01
16,905509963,Norco 80 (bud target: net 40-50M),post,2026-12-01,2027-07-01
17,857713278,American Jewel,post,2027-01-01,2027-07-01
18,905507328,Silent Patient (bud target: net 25M),post,2027-01-01,2027-06-30
19,857711298,Even The Losers,post,2027-03-01,2027-10-01
20,857713278,American Jewel,delivery,2027-07-01,2027-07-29
21,905507328,Silent Patient (bud target: net 25M),delivery,2027-07-01,2027-07-31
22,905509963,Norco 80 (bud target: net 40-50M),delivery,2027-07-01,2027-07-31
23,857711298,Even The Losers,delivery,2027-10-01,2027-10-29

In [9]:
import pandas as pd
from datetime import datetime, timezone
from pymongo import UpdateOne

def gantt_long_to_project_docs(df: pd.DataFrame) -> list[dict]:
    d = df.copy()

    # normalize + ensure types Mongo likes
    d = d.rename(columns={"id": "hub_id"})
    d["phase"] = d["phase"].astype(str).str.strip().str.lower()

    d["start"] = pd.to_datetime(d["start"], errors="coerce")
    d["end"] = pd.to_datetime(d["end"], errors="coerce")

    # drop bad rows
    d = d[d["hub_id"].notna() & d["start"].notna() & d["end"].notna()].copy()

    now = datetime.now(timezone.utc)

    docs = []
    for hub_id, g in d.groupby("hub_id", dropna=False):
        g = g.sort_values(["start", "end", "phase"])
        title = g["title"].dropna().iloc[0] if g["title"].notna().any() else None

        phases = [
            {
                "phase": r.phase,
                "start": r.start.to_pydatetime(),
                "end": r.end.to_pydatetime(),
            }
            for r in g.itertuples(index=False)
        ]

        docs.append({
            "hub_id": int(hub_id),
            "title": title,
            "schedule": {
                "source": "gantt_long",
                "updated_at": now,
                "phases": phases,
            }
        })

    return docs

def upsert_project_schedules(collection, df: pd.DataFrame):
    docs = gantt_long_to_project_docs(df)

    ops = [
        UpdateOne(
            {"hub_id": doc["hub_id"]},
            {"$set": doc},
            upsert=True
        )
        for doc in docs
    ]

    return collection.bulk_write(ops)

In [10]:
stop

NameError: name 'stop' is not defined

In [22]:
## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [23]:
db = client['InDevelopment']

collection = db['milestone_tracker']

collection.delete_many({})

In [24]:
# usage:
result = upsert_project_schedules(collection, df)
print(result.bulk_api_result)

{'writeErrors': [], 'writeConcernErrors': [], 'nInserted': 0, 'nUpserted': 4, 'nMatched': 3, 'nModified': 3, 'nRemoved': 0, 'upserted': [{'index': 3, '_id': ObjectId('69af2b60ec34f6d7119b08b6')}, {'index': 4, '_id': ObjectId('69af2b60ec34f6d7119b08b7')}, {'index': 5, '_id': ObjectId('69af2b60ec34f6d7119b08b8')}, {'index': 6, '_id': ObjectId('69af2b60ec34f6d7119b08b9')}]}

def batchify(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]

from pymongo import UpdateOne


#####
for batch in batchify(data, 4000):
    operations = [
        UpdateOne(
            {"hub_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

In [25]:
from datetime import datetime


datetime.today()

datetime.datetime(2026, 3, 9, 13, 19, 44, 869897)

In [26]:

db = client['InDevelopment']
collection = db['milestone_tracker']
query = {"hub_id": 857711298}

mt_query_docs = collection.find(query)
df = pd.DataFrame(mt_query_docs)

df

,_id,hub_id,schedule,title
0,69a8a261ec34f6d7119b08b4,857711298,"{'source': 'gantt_long', 'updated_at': 2026-03...",Even The Losers

In [27]:
import pandas as pd

pipeline = [
    {"$match": {"schedule.phases": {"$exists": True, "$ne": []}}},
    {"$unwind": "$schedule.phases"},
    {"$project": {
        "_id": 0,
        "id": "$hub_id",
        "title": "$title",
        "phase": "$schedule.phases.phase",
        "start": "$schedule.phases.start",
        "end": "$schedule.phases.end",
    }},
    {"$sort": {"id": 1, "start": 1}},
]

rows = list(collection.aggregate(pipeline))
gantt_df = pd.DataFrame(rows)

# (optional) ensure datetime dtype
gantt_df["start"] = pd.to_datetime(gantt_df["start"], errors="coerce")
gantt_df["end"] = pd.to_datetime(gantt_df["end"], errors="coerce")

In [28]:
gantt_df

,id,title,phase,start,end
0,828769775,The Invite,release,2026-06-26,2026-07-24
1,857711298,Even The Losers,writing,2026-01-01,2026-08-15
2,857711298,Even The Losers,prep,2026-08-15,2026-11-01
3,857711298,Even The Losers,shoot,2026-11-01,2027-03-01
4,857711298,Even The Losers,post,2027-03-01,2027-10-01
5,857711298,Even The Losers,delivery,2027-10-01,2027-10-29
6,857713278,American Jewel,writing,2026-01-01,2026-09-01
7,857713278,American Jewel,prep,2026-09-01,2026-11-01
8,857713278,American Jewel,shoot,2026-11-01,2027-01-01
9,857713278,American Jewel,post,2027-01-01,2027-07-01
10,857713278,American Jewel,delivery,2027-07-01,2027-07-29
11,905500587,SOAPS (budget: 2M),post,2026-03-01,2026-07-31
12,905500587,SOAPS (budget: 2M),delivery,2026-08-01,2026-09-01
13,905507328,Silent Patient (bud target: net 25M),writing,2026-01-01,2026-09-01
14,905507328,Silent Patient (bud target: net 25M),prep,2026-09-01,2026-10-31
15,905507328,Silent Patient (bud target: net 25M),shoot,2026-10-31,2026-12-31
16,905507328,Silent Patient (bud target: net 25M),post,2027-01-01,2027-06-30
17,905507328,Silent Patient (bud target: net 25M),delivery,2027-07-01,2027-07-31
18,905509963,Norco 80 (bud target: net 40-50M),writing,2026-01-01,2026-07-31
19,905509963,Norco 80 (bud target: net 40-50M),prep,2026-08-01,2026-09-30
20,905509963,Norco 80 (bud target: net 40-50M),shoot,2026-10-01,2026-11-30
21,905509963,Norco 80 (bud target: net 40-50M),post,2026-12-01,2027-07-01
22,905509963,Norco 80 (bud target: net 40-50M),delivery,2027-07-01,2027-07-31
23,905512660,Unt. Nicole Taylor (bud target: ),writing,2026-01-01,2027-12-31

In [29]:
client.close()

In [30]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# Step 1: Define the scope
scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]

# Step 2: Load credentials
creds = ServiceAccountCredentials.from_json_keyfile_name("ultra-sound-463216-c2-0e076e5f88fe.json", scope)

# Step 3: Authorize and connect
client = gspread.authorize(creds)

# Step 4: Open sheet by URL
sheet_url = "https://docs.google.com/spreadsheets/d/1PaAQEAJcTupLNgvTLaawyWPKOfIrUFAQf-WiUnZMbxY/edit?gid=25505532#gid=25505532"
spreadsheet = client.open_by_url(sheet_url)

# Optional: Access specific sheet/tab
sheet = spreadsheet.worksheet("milestone_tracker")  # or spreadsheet.worksheet("SheetName")

In [31]:
# Example: Read data
sheet.clear()

{'spreadsheetId': '1PaAQEAJcTupLNgvTLaawyWPKOfIrUFAQf-WiUnZMbxY',
 'clearedRange': 'milestone_tracker!A1:Z1000'}

In [32]:
g_sheet = gantt_df.copy()

In [33]:
g_sheet[date_cols] = g_sheet[date_cols].apply(
    lambda col: pd.to_datetime(col, errors="coerce").dt.strftime("%Y-%m-%d")
)

In [34]:
data_export = [g_sheet.columns.tolist()] + g_sheet.values.tolist()
data_export

[['id', 'title', 'phase', 'start', 'end'],
 [828769775, 'The Invite', 'release', '2026-06-26', '2026-07-24'],
 [857711298, 'Even The Losers', 'writing', '2026-01-01', '2026-08-15'],
 [857711298, 'Even The Losers', 'prep', '2026-08-15', '2026-11-01'],
 [857711298, 'Even The Losers', 'shoot', '2026-11-01', '2027-03-01'],
 [857711298, 'Even The Losers', 'post', '2027-03-01', '2027-10-01'],
 [857711298, 'Even The Losers', 'delivery', '2027-10-01', '2027-10-29'],
 [857713278, 'American Jewel', 'writing', '2026-01-01', '2026-09-01'],
 [857713278, 'American Jewel', 'prep', '2026-09-01', '2026-11-01'],
 [857713278, 'American Jewel', 'shoot', '2026-11-01', '2027-01-01'],
 [857713278, 'American Jewel', 'post', '2027-01-01', '2027-07-01'],
 [857713278, 'American Jewel', 'delivery', '2027-07-01', '2027-07-29'],
 [905500587, 'SOAPS (budget: 2M)', 'post', '2026-03-01', '2026-07-31'],
 [905500587, 'SOAPS (budget: 2M)', 'delivery', '2026-08-01', '2026-09-01'],
 [905507328,
  'Silent Patient (bud target: net 25M)',
  'writing',
  '2026-01-01',
  '2026-09-01'],
 [905507328,
  'Silent Patient (bud target: net 25M)',
  'prep',
  '2026-09-01',
  '2026-10-31'],
 [905507328,
  'Silent Patient (bud target: net 25M)',
  'shoot',
  '2026-10-31',
  '2026-12-31'],
 [905507328,
  'Silent Patient (bud target: net 25M)',
  'post',
  '2027-01-01',
  '2027-06-30'],
 [905507328,
  'Silent Patient (bud target: net 25M)',
  'delivery',
  '2027-07-01',
  '2027-07-31'],
 [905509963,
  'Norco 80 (bud target: net 40-50M)',
  'writing',
  '2026-01-01',
  '2026-07-31'],
 [905509963,
  'Norco 80 (bud target: net 40-50M)',
  'prep',
  '2026-08-01',
  '2026-09-30'],
 [905509963,
  'Norco 80 (bud target: net 40-50M)',
  'shoot',
  '2026-10-01',
  '2026-11-30'],
 [905509963,
  'Norco 80 (bud target: net 40-50M)',
  'post',
  '2026-12-01',
  '2027-07-01'],
 [905509963,
  'Norco 80 (bud target: net 40-50M)',
  'delivery',
  '2027-07-01',
  '2027-07-31'],
 [905512660,
  'Unt. Nicole Taylor (bud target: )',
  'writing',
  '2026-01-01',
  '2027-12-31']]

In [35]:
sheet.update(data_export)

{'spreadsheetId': '1PaAQEAJcTupLNgvTLaawyWPKOfIrUFAQf-WiUnZMbxY',
 'updatedRange': 'milestone_tracker!A1:E25',
 'updatedRows': 25,
 'updatedColumns': 5,
 'updatedCells': 125}