In [1]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# Step 1: Define the scope
scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]

# Step 2: Load credentials
creds = ServiceAccountCredentials.from_json_keyfile_name("ultra-sound-463216-c2-0e076e5f88fe.json", scope)

# Step 3: Authorize and connect
client = gspread.authorize(creds)

# Step 4: Open sheet by URL
sheet_url = "https://docs.google.com/spreadsheets/d/1JVNtgSJFswHEH6iHz-XP1qUzdyxQXa5Q-WGI86CqGmE/edit?gid=1534679013#gid=1534679013"
spreadsheet = client.open_by_url(sheet_url)

# Optional: Access specific sheet/tab
sheet = spreadsheet.worksheet("Data")  # or spreadsheet.worksheet("SheetName")

# Example: Read data
data = sheet.get_all_records(head=1)

In [2]:
import pandas as pd

df = pd.DataFrame(data)

In [3]:
df.columns

Index(['hub_id', 'Title', 'writing_start', 'writing_end', 'prep_start',
       'Prep_end', 'shoot_start', 'shoot_end', 'post_start', 'post_end',
       'delivery', 'est_release_date'],
      dtype='object')

df["Title"] = df["Project"].str.title()

In [4]:
date_cols = ['writing_start', 'writing_end', 'prep_start',
       'Prep_end', 'shoot_start', 'shoot_end', 'post_start', 'post_end',
       'delivery', 'est_release_date']

In [5]:
df[date_cols] = df[date_cols].apply(pd.to_datetime, errors="coerce")

df = df.replace({pd.NaT: None})

In [6]:
df

,hub_id,Title,writing_start,writing_end,prep_start,Prep_end,shoot_start,shoot_end,post_start,post_end,delivery,est_release_date
0,,I Love Boosters,None,None,None,None,None,None,None,None,None,2025-05-22 00:00:00
1,828769775,The Invite,None,None,None,None,None,None,None,None,None,2026-06-26 00:00:00
2,,Soaps,None,None,None,None,None,None,2026-01-01 00:00:00,2026-08-01 00:00:00,2026-08-01 00:00:00,None
3,,Belly of the Beast,2026-01-01 00:00:00,2026-04-01 00:00:00,2026-04-01 00:00:00,2026-06-01 00:00:00,2026-06-01 00:00:00,2026-08-15 00:00:00,2026-08-15 00:00:00,2027-02-01 00:00:00,2027-02-01 00:00:00,None
4,,25 Scenes,2026-01-01 00:00:00,2026-04-01 00:00:00,2026-04-01 00:00:00,2026-06-01 00:00:00,2026-06-01 00:00:00,2026-08-15 00:00:00,2026-08-15 00:00:00,2027-02-01 00:00:00,2027-02-01 00:00:00,None
5,,Unt. Brady Corbet (est. budget: net 20M),2026-01-01 00:00:00,2026-06-01 00:00:00,2026-06-01 00:00:00,2026-08-01 00:00:00,2026-08-01 00:00:00,2026-10-01 00:00:00,2026-10-01 00:00:00,2027-04-01 00:00:00,2027-04-01 00:00:00,None
6,,Norco 80 (bud target: net 40-50M),2026-01-01 00:00:00,2026-08-01 00:00:00,2026-08-01 00:00:00,2026-10-01 00:00:00,2026-10-01 00:00:00,2026-12-01 00:00:00,2026-12-01 00:00:00,2027-07-01 00:00:00,2027-07-01 00:00:00,None
7,857713278,American Jewel (bud target: net 8-15M),2026-01-01 00:00:00,2026-09-01 00:00:00,2026-09-01 00:00:00,2026-11-01 00:00:00,2026-11-01 00:00:00,2027-01-01 00:00:00,2027-01-01 00:00:00,2027-07-01 00:00:00,2027-07-01 00:00:00,None
8,,Silent Patient (bud target: net 25M),2026-01-01 00:00:00,2026-09-01 00:00:00,2026-09-01 00:00:00,2026-11-01 00:00:00,2026-11-01 00:00:00,2027-01-01 00:00:00,2027-01-01 00:00:00,2027-07-01 00:00:00,2027-07-01 00:00:00,None
9,857711298,Even The Losers (bud target: net 80M),2026-01-01 00:00:00,2026-08-15 00:00:00,2026-08-15 00:00:00,2026-11-01 00:00:00,2026-11-01 00:00:00,2027-03-01 00:00:00,2027-03-01 00:00:00,2027-10-01 00:00:00,2027-10-01 00:00:00,None
10,,Chef (bud target: net 20M),2026-01-01 00:00:00,2027-04-01 00:00:00,2027-04-01 00:00:00,2027-06-01 00:00:00,2027-06-01 00:00:00,2027-08-01 00:00:00,2027-08-01 00:00:00,2027-12-31 00:00:00,None,None
11,,Five Hitmen (bud target: net 30-40M),2026-01-01 00:00:00,2027-05-01 00:00:00,2027-05-01 00:00:00,2027-07-01 00:00:00,2027-07-01 00:00:00,2027-09-01 00:00:00,2027-09-01 00:00:00,2027-12-31 00:00:00,None,None
12,,Unt. James Sweeney (bud target: ),2026-01-01 00:00:00,2027-12-31 00:00:00,None,None,None,None,None,None,None,None
13,,Unt. Nicole Taylor (bud target: ),2026-01-01 00:00:00,2027-12-31 00:00:00,None,None,None,None,None,None,None,None

In [7]:
df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(r"\s+", "_", regex=True)   # spaces -> underscore
      .str.replace(r"[^0-9a-zA-Z_]", "", regex=True)  # optional: remove weird chars
      + "_film_milestone_tracker"
)

In [8]:
df

,hub_id_film_milestone_tracker,title_film_milestone_tracker,writing_start_film_milestone_tracker,writing_end_film_milestone_tracker,prep_start_film_milestone_tracker,prep_end_film_milestone_tracker,shoot_start_film_milestone_tracker,shoot_end_film_milestone_tracker,post_start_film_milestone_tracker,post_end_film_milestone_tracker,delivery_film_milestone_tracker,est_release_date_film_milestone_tracker
0,,I Love Boosters,None,None,None,None,None,None,None,None,None,2025-05-22 00:00:00
1,828769775,The Invite,None,None,None,None,None,None,None,None,None,2026-06-26 00:00:00
2,,Soaps,None,None,None,None,None,None,2026-01-01 00:00:00,2026-08-01 00:00:00,2026-08-01 00:00:00,None
3,,Belly of the Beast,2026-01-01 00:00:00,2026-04-01 00:00:00,2026-04-01 00:00:00,2026-06-01 00:00:00,2026-06-01 00:00:00,2026-08-15 00:00:00,2026-08-15 00:00:00,2027-02-01 00:00:00,2027-02-01 00:00:00,None
4,,25 Scenes,2026-01-01 00:00:00,2026-04-01 00:00:00,2026-04-01 00:00:00,2026-06-01 00:00:00,2026-06-01 00:00:00,2026-08-15 00:00:00,2026-08-15 00:00:00,2027-02-01 00:00:00,2027-02-01 00:00:00,None
5,,Unt. Brady Corbet (est. budget: net 20M),2026-01-01 00:00:00,2026-06-01 00:00:00,2026-06-01 00:00:00,2026-08-01 00:00:00,2026-08-01 00:00:00,2026-10-01 00:00:00,2026-10-01 00:00:00,2027-04-01 00:00:00,2027-04-01 00:00:00,None
6,,Norco 80 (bud target: net 40-50M),2026-01-01 00:00:00,2026-08-01 00:00:00,2026-08-01 00:00:00,2026-10-01 00:00:00,2026-10-01 00:00:00,2026-12-01 00:00:00,2026-12-01 00:00:00,2027-07-01 00:00:00,2027-07-01 00:00:00,None
7,857713278,American Jewel (bud target: net 8-15M),2026-01-01 00:00:00,2026-09-01 00:00:00,2026-09-01 00:00:00,2026-11-01 00:00:00,2026-11-01 00:00:00,2027-01-01 00:00:00,2027-01-01 00:00:00,2027-07-01 00:00:00,2027-07-01 00:00:00,None
8,,Silent Patient (bud target: net 25M),2026-01-01 00:00:00,2026-09-01 00:00:00,2026-09-01 00:00:00,2026-11-01 00:00:00,2026-11-01 00:00:00,2027-01-01 00:00:00,2027-01-01 00:00:00,2027-07-01 00:00:00,2027-07-01 00:00:00,None
9,857711298,Even The Losers (bud target: net 80M),2026-01-01 00:00:00,2026-08-15 00:00:00,2026-08-15 00:00:00,2026-11-01 00:00:00,2026-11-01 00:00:00,2027-03-01 00:00:00,2027-03-01 00:00:00,2027-10-01 00:00:00,2027-10-01 00:00:00,None
10,,Chef (bud target: net 20M),2026-01-01 00:00:00,2027-04-01 00:00:00,2027-04-01 00:00:00,2027-06-01 00:00:00,2027-06-01 00:00:00,2027-08-01 00:00:00,2027-08-01 00:00:00,2027-12-31 00:00:00,None,None
11,,Five Hitmen (bud target: net 30-40M),2026-01-01 00:00:00,2027-05-01 00:00:00,2027-05-01 00:00:00,2027-07-01 00:00:00,2027-07-01 00:00:00,2027-09-01 00:00:00,2027-09-01 00:00:00,2027-12-31 00:00:00,None,None
12,,Unt. James Sweeney (bud target: ),2026-01-01 00:00:00,2027-12-31 00:00:00,None,None,None,None,None,None,None,None
13,,Unt. Nicole Taylor (bud target: ),2026-01-01 00:00:00,2027-12-31 00:00:00,None,None,None,None,None,None,None,None

In [9]:
mongo_cols = ['_id', 'title_film_milestone_tracker',
       'writing_start_film_milestone_tracker',
       'writing_end_film_milestone_tracker',
       'prep_start_film_milestone_tracker', 'prep_end_film_milestone_tracker',
       'shoot_start_film_milestone_tracker',
       'shoot_end_film_milestone_tracker', 'post_start_film_milestone_tracker',
       'post_end_film_milestone_tracker', 'delivery_film_milestone_tracker',
       'est_release_date_film_milestone_tracker']

In [10]:
df["_id"] = df['hub_id_film_milestone_tracker']
df=df[mongo_cols]

In [11]:
df.head().columns

Index(['_id', 'title_film_milestone_tracker',
       'writing_start_film_milestone_tracker',
       'writing_end_film_milestone_tracker',
       'prep_start_film_milestone_tracker', 'prep_end_film_milestone_tracker',
       'shoot_start_film_milestone_tracker',
       'shoot_end_film_milestone_tracker', 'post_start_film_milestone_tracker',
       'post_end_film_milestone_tracker', 'delivery_film_milestone_tracker',
       'est_release_date_film_milestone_tracker'],
      dtype='object')

In [12]:
df

,_id,title_film_milestone_tracker,writing_start_film_milestone_tracker,writing_end_film_milestone_tracker,prep_start_film_milestone_tracker,prep_end_film_milestone_tracker,shoot_start_film_milestone_tracker,shoot_end_film_milestone_tracker,post_start_film_milestone_tracker,post_end_film_milestone_tracker,delivery_film_milestone_tracker,est_release_date_film_milestone_tracker
0,,I Love Boosters,None,None,None,None,None,None,None,None,None,2025-05-22 00:00:00
1,828769775,The Invite,None,None,None,None,None,None,None,None,None,2026-06-26 00:00:00
2,,Soaps,None,None,None,None,None,None,2026-01-01 00:00:00,2026-08-01 00:00:00,2026-08-01 00:00:00,None
3,,Belly of the Beast,2026-01-01 00:00:00,2026-04-01 00:00:00,2026-04-01 00:00:00,2026-06-01 00:00:00,2026-06-01 00:00:00,2026-08-15 00:00:00,2026-08-15 00:00:00,2027-02-01 00:00:00,2027-02-01 00:00:00,None
4,,25 Scenes,2026-01-01 00:00:00,2026-04-01 00:00:00,2026-04-01 00:00:00,2026-06-01 00:00:00,2026-06-01 00:00:00,2026-08-15 00:00:00,2026-08-15 00:00:00,2027-02-01 00:00:00,2027-02-01 00:00:00,None
5,,Unt. Brady Corbet (est. budget: net 20M),2026-01-01 00:00:00,2026-06-01 00:00:00,2026-06-01 00:00:00,2026-08-01 00:00:00,2026-08-01 00:00:00,2026-10-01 00:00:00,2026-10-01 00:00:00,2027-04-01 00:00:00,2027-04-01 00:00:00,None
6,,Norco 80 (bud target: net 40-50M),2026-01-01 00:00:00,2026-08-01 00:00:00,2026-08-01 00:00:00,2026-10-01 00:00:00,2026-10-01 00:00:00,2026-12-01 00:00:00,2026-12-01 00:00:00,2027-07-01 00:00:00,2027-07-01 00:00:00,None
7,857713278,American Jewel (bud target: net 8-15M),2026-01-01 00:00:00,2026-09-01 00:00:00,2026-09-01 00:00:00,2026-11-01 00:00:00,2026-11-01 00:00:00,2027-01-01 00:00:00,2027-01-01 00:00:00,2027-07-01 00:00:00,2027-07-01 00:00:00,None
8,,Silent Patient (bud target: net 25M),2026-01-01 00:00:00,2026-09-01 00:00:00,2026-09-01 00:00:00,2026-11-01 00:00:00,2026-11-01 00:00:00,2027-01-01 00:00:00,2027-01-01 00:00:00,2027-07-01 00:00:00,2027-07-01 00:00:00,None
9,857711298,Even The Losers (bud target: net 80M),2026-01-01 00:00:00,2026-08-15 00:00:00,2026-08-15 00:00:00,2026-11-01 00:00:00,2026-11-01 00:00:00,2027-03-01 00:00:00,2027-03-01 00:00:00,2027-10-01 00:00:00,2027-10-01 00:00:00,None
10,,Chef (bud target: net 20M),2026-01-01 00:00:00,2027-04-01 00:00:00,2027-04-01 00:00:00,2027-06-01 00:00:00,2027-06-01 00:00:00,2027-08-01 00:00:00,2027-08-01 00:00:00,2027-12-31 00:00:00,None,None
11,,Five Hitmen (bud target: net 30-40M),2026-01-01 00:00:00,2027-05-01 00:00:00,2027-05-01 00:00:00,2027-07-01 00:00:00,2027-07-01 00:00:00,2027-09-01 00:00:00,2027-09-01 00:00:00,2027-12-31 00:00:00,None,None
12,,Unt. James Sweeney (bud target: ),2026-01-01 00:00:00,2027-12-31 00:00:00,None,None,None,None,None,None,None,None
13,,Unt. Nicole Taylor (bud target: ),2026-01-01 00:00:00,2027-12-31 00:00:00,None,None,None,None,None,None,None,None

In [13]:
df = df[df["_id"] != ""]
#df['_id'] = df['_id'].astype('str')

In [14]:
df

,_id,title_film_milestone_tracker,writing_start_film_milestone_tracker,writing_end_film_milestone_tracker,prep_start_film_milestone_tracker,prep_end_film_milestone_tracker,shoot_start_film_milestone_tracker,shoot_end_film_milestone_tracker,post_start_film_milestone_tracker,post_end_film_milestone_tracker,delivery_film_milestone_tracker,est_release_date_film_milestone_tracker
1,828769775,The Invite,None,None,None,None,None,None,None,None,None,2026-06-26 00:00:00
7,857713278,American Jewel (bud target: net 8-15M),2026-01-01 00:00:00,2026-09-01 00:00:00,2026-09-01 00:00:00,2026-11-01 00:00:00,2026-11-01 00:00:00,2027-01-01 00:00:00,2027-01-01 00:00:00,2027-07-01 00:00:00,2027-07-01 00:00:00,None
9,857711298,Even The Losers (bud target: net 80M),2026-01-01 00:00:00,2026-08-15 00:00:00,2026-08-15 00:00:00,2026-11-01 00:00:00,2026-11-01 00:00:00,2027-03-01 00:00:00,2027-03-01 00:00:00,2027-10-01 00:00:00,2027-10-01 00:00:00,None

In [15]:
data = df.to_dict(orient='records')

In [16]:
data

[{'_id': 828769775,
  'title_film_milestone_tracker': 'The Invite',
  'writing_start_film_milestone_tracker': None,
  'writing_end_film_milestone_tracker': None,
  'prep_start_film_milestone_tracker': None,
  'prep_end_film_milestone_tracker': None,
  'shoot_start_film_milestone_tracker': None,
  'shoot_end_film_milestone_tracker': None,
  'post_start_film_milestone_tracker': None,
  'post_end_film_milestone_tracker': None,
  'delivery_film_milestone_tracker': None,
  'est_release_date_film_milestone_tracker': Timestamp('2026-06-26 00:00:00')},
 {'_id': 857713278,
  'title_film_milestone_tracker': 'American Jewel (bud target: net 8-15M)',
  'writing_start_film_milestone_tracker': Timestamp('2026-01-01 00:00:00'),
  'writing_end_film_milestone_tracker': Timestamp('2026-09-01 00:00:00'),
  'prep_start_film_milestone_tracker': Timestamp('2026-09-01 00:00:00'),
  'prep_end_film_milestone_tracker': Timestamp('2026-11-01 00:00:00'),
  'shoot_start_film_milestone_tracker': Timestamp('2026-11-01 00:00:00'),
  'shoot_end_film_milestone_tracker': Timestamp('2027-01-01 00:00:00'),
  'post_start_film_milestone_tracker': Timestamp('2027-01-01 00:00:00'),
  'post_end_film_milestone_tracker': Timestamp('2027-07-01 00:00:00'),
  'delivery_film_milestone_tracker': Timestamp('2027-07-01 00:00:00'),
  'est_release_date_film_milestone_tracker': None},
 {'_id': 857711298,
  'title_film_milestone_tracker': 'Even The Losers (bud target: net 80M)',
  'writing_start_film_milestone_tracker': Timestamp('2026-01-01 00:00:00'),
  'writing_end_film_milestone_tracker': Timestamp('2026-08-15 00:00:00'),
  'prep_start_film_milestone_tracker': Timestamp('2026-08-15 00:00:00'),
  'prep_end_film_milestone_tracker': Timestamp('2026-11-01 00:00:00'),
  'shoot_start_film_milestone_tracker': Timestamp('2026-11-01 00:00:00'),
  'shoot_end_film_milestone_tracker': Timestamp('2027-03-01 00:00:00'),
  'post_start_film_milestone_tracker': Timestamp('2027-03-01 00:00:00'),
  'post_end_film_milestone_tracker': Timestamp('2027-10-01 00:00:00'),
  'delivery_film_milestone_tracker': Timestamp('2027-10-01 00:00:00'),
  'est_release_date_film_milestone_tracker': None}]

In [17]:
stop

NameError: name 'stop' is not defined

In [30]:
## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [31]:
db = client['InDevelopment']

collection = db['milestone_tracker']

In [20]:
def batchify(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]

collection.delete_many({})

In [24]:
from pymongo import UpdateOne


#####
for batch in batchify(data, 4000):
    operations = [
        UpdateOne(
            {"hub_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 0, Inserted: 3, Modified: 0

In [26]:
from datetime import datetime


datetime.today()

datetime.datetime(2026, 3, 4, 10, 48, 2, 354042)

client.close()

In [34]:

db = client['InDevelopment']
collection = db['milestone_tracker']
query = {"hub_id": 857713278}

mt_query_docs = collection.find(query)
df = pd.DataFrame(mt_query_docs)

df

,_id,hub_id,delivery_film_milestone_tracker,est_release_date_film_milestone_tracker,post_end_film_milestone_tracker,post_start_film_milestone_tracker,prep_end_film_milestone_tracker,prep_start_film_milestone_tracker,shoot_end_film_milestone_tracker,shoot_start_film_milestone_tracker,title_film_milestone_tracker,writing_end_film_milestone_tracker,writing_start_film_milestone_tracker
0,857713278,857713278,2027-07-01,None,2027-07-01,2027-01-01,2026-11-01,2026-09-01,2027-01-01,2026-11-01,American Jewel (bud target: net 8-15M),2026-09-01,2026-01-01

In [38]:
df.T

                                                                              0
_id                                                                   857713278
hub_id                                                                857713278
delivery_film_milestone_tracker                             2027-07-01 00:00:00
est_release_date_film_milestone_tracker                                    None
post_end_film_milestone_tracker                             2027-07-01 00:00:00
post_start_film_milestone_tracker                           2027-01-01 00:00:00
prep_end_film_milestone_tracker                             2026-11-01 00:00:00
prep_start_film_milestone_tracker                           2026-09-01 00:00:00
shoot_end_film_milestone_tracker                            2027-01-01 00:00:00
shoot_start_film_milestone_tracker                          2026-11-01 00:00:00
title_film_milestone_tracker             American Jewel (bud target: net 8-15M)
writing_end_film_milestone_tracker                          2026-09-01 00:00:00
writing_start_film_milestone_tracker                        2026-01-01 00:00:00