In [1]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# Step 1: Define the scope
scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]

# Step 2: Load credentials
creds = ServiceAccountCredentials.from_json_keyfile_name("ultra-sound-463216-c2-0e076e5f88fe.json", scope)

# Step 3: Authorize and connect
client = gspread.authorize(creds)

# Step 4: Open sheet by URL
sheet_url = "https://docs.google.com/spreadsheets/d/1Et8ufbD8I4wt96CjzkteDN7IPN27S3kdDGAZ7d74fco/edit?gid=1939998625#gid=1939998625"
spreadsheet = client.open_by_url(sheet_url)

# Optional: Access specific sheet/tab
sheet = spreadsheet.worksheet("Film_and_TV_Options_Tracker")  # or spreadsheet.worksheet("SheetName")

# Example: Read data
data = sheet.get_all_records(head=1)

In [2]:
import pandas as pd

df = pd.DataFrame(data)

df["Title"] = df["Project"].str.title()

In [3]:
df

,Dept,﻿Project,Rights Holder,Type,Option Status,Initial Option Start Date,Current Option Term Expiration Date,Current Status,Deal-specific notes,Initial Option,Extension(s),Purchase Price,Reversion
0,TV,Amberville,,,Lapsed,,7/28/2024,,,,,,
1,TV,Animal Husbandry,Noah Prestwich,Spec Script,Lapsed,5/18/2022,8/18/2022,We have pro-rata monthly extensions remaining.,,,,,
2,Film,Antarctica,Don Hertzfeldt,Screenplay,Initial Option,4/17/2025,10/17/2026,REMAINING: Extended Option Period. $15k for an...,,,,,
3,TV,Artful Escape (Attachment),,,Lapsed,2/8/2023,2/7/2024,,"Pitch Bible delivered April 17, 2023 - checkin...",,,,
4,Film,Assassination of B.W Spurge,Yelchin and Anderson,Literary Material (Book),Lapsed,8/4/2021,8/4/2022,We have no more options left.,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,TV,What Remains of Edith Finch,Annapurna Interactive,Video Game,,10/30/2019,10/29/2021,We have an option extension for 18 months for ...,Lapsed/Letting Go.,,,,
82,TV,Who is Maud Dixon,Alexandra Andrews Beha,Book,Initial Option,6/12/2024,12/11/2025,,- we have an extension at $125K for an addtl 1...,,,,
83,TV,Who is Maud Dixon (First Position),Boo Killebrew,Screenplay,Initial Term,3/28/2025,10/16/2025,,This is when the writer Boo Killebrew is in fi...,,,,
84,TV,Who Killed Tulum?,NY Mag,Article,Lapsed,9/16/2021,9/16/2022,Amazon took over and negotiated this second op...,Lapsed/Letting Go.,,,,
85,TV,Zankou Chicken Murders,Wondery,Podcast,Lapsed,12/9/2021,12/9/2022,No extensions left. (With Starz),Lapsed/Letting Go.,,,,

In [4]:
df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(r"\s+", "_", regex=True)   # spaces -> underscore
      .str.replace(r"[^0-9a-zA-Z_]", "", regex=True)  # optional: remove weird chars
      + "_film_ot"
)

In [5]:
df

,dept_film_ot,project_film_ot,rights_holder_film_ot,type_film_ot,option_status_film_ot,initial_option_start_date_film_ot,current_option_term_expiration_date_film_ot,current_status_film_ot,dealspecific_notes_film_ot,initial_option_film_ot,extensions_film_ot,purchase_price_film_ot,reversion_film_ot
0,TV,Amberville,,,Lapsed,,7/28/2024,,,,,,
1,TV,Animal Husbandry,Noah Prestwich,Spec Script,Lapsed,5/18/2022,8/18/2022,We have pro-rata monthly extensions remaining.,,,,,
2,Film,Antarctica,Don Hertzfeldt,Screenplay,Initial Option,4/17/2025,10/17/2026,REMAINING: Extended Option Period. $15k for an...,,,,,
3,TV,Artful Escape (Attachment),,,Lapsed,2/8/2023,2/7/2024,,"Pitch Bible delivered April 17, 2023 - checkin...",,,,
4,Film,Assassination of B.W Spurge,Yelchin and Anderson,Literary Material (Book),Lapsed,8/4/2021,8/4/2022,We have no more options left.,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,TV,What Remains of Edith Finch,Annapurna Interactive,Video Game,,10/30/2019,10/29/2021,We have an option extension for 18 months for ...,Lapsed/Letting Go.,,,,
82,TV,Who is Maud Dixon,Alexandra Andrews Beha,Book,Initial Option,6/12/2024,12/11/2025,,- we have an extension at $125K for an addtl 1...,,,,
83,TV,Who is Maud Dixon (First Position),Boo Killebrew,Screenplay,Initial Term,3/28/2025,10/16/2025,,This is when the writer Boo Killebrew is in fi...,,,,
84,TV,Who Killed Tulum?,NY Mag,Article,Lapsed,9/16/2021,9/16/2022,Amazon took over and negotiated this second op...,Lapsed/Letting Go.,,,,
85,TV,Zankou Chicken Murders,Wondery,Podcast,Lapsed,12/9/2021,12/9/2022,No extensions left. (With Starz),Lapsed/Letting Go.,,,,

In [6]:
df["_id"] = df['project_film_ot'] + "_"+ df['dept_film_ot']+ "_"+ df['rights_holder_film_ot']

df = df.rename({"project_film_ot":"_id"}, axis=1)

cols = [
    '_id', 
        'ap_division_film_pt', 
        'project_stage_film_pt',
       'ap_lead_film_pt', 
        'ap_jr_film_pt', 
        'ap_dev_film_pt',
       'ba_status_film_pt', 
        'creative_status_film_pt',
       'next_milestone_film_pt', 
        'key_timing_film_pt',
       'option_expiration_film_pt', 
        'key_timing_date_film_pt',
       'underlying_ip_film_pt', 
        'logline_film_pt',
       'platform__distribution_film_pt', 
        'deal_type_film_pt',
       'partners_and_vendors_film_pt', 
        'creators_film_pt', 
        'director_film_pt',
       'writers_film_pt', 
        'producer_1_film_pt', 
        'producer_2_film_pt',
       'cast_1_film_pt', 
        'cast_2_film_pt', 
        'cast_3_film_pt', 
        'cast_4_film_pt',
       ]

#df["project_stage_film_pt"] = df["project_stage_film_pt"].str.split(",").apply(lambda x: [i.strip() for i in x])
df["ap_lead_film_pt"] = df["ap_lead_film_pt"].str.split(",").apply(lambda x: [i.strip() for i in x])
df["ap_jr_film_pt"] = df["ap_jr_film_pt"].str.split(",").apply(lambda x: [i.strip() for i in x])

df

df[cols]

title_map = {
    "Even The Losers (Fka Need For Weed)": "Even the Losers",
    "Belly Of The Beast": "Belly of The Beast",
    'Brady Corbet / Mona Fastvold Project (Unt.)': "Origin of the World fka Unt. Brady Corbet & Mona Fastvold Project",

    'Silent Patient, The ': "The Silent Patient",
    '12 Minutes (Film)': "12 Minutes",
    'Bennett Miller (Unt.) ':"Unt. Bennett Miller",
    
    'Nicole Taylor Idea (Unt.)':"Evie Mcbrayne fka Unt. Nicole Taylor",
    'James Sweeney (Unt.)':"Unt. James Sweeney",
    'Into The Glory Whole':"Into the Glory whole",
    'Legend Of Georgia Mcbride, The ':"The Legend of Georgia McBride",

        'Lost Wild, The ':"The Lost Wild",


        'Beast Fiction Project (Unt.)':"Unt. Beast Fiction Project",

            'Ann Lee (Fka The Woman Clothed By The Sun) ':"The Testament of Ann Lee",



    # add more…
}

df['_id'] = df['_id'].replace(title_map)

In [7]:
df.head().columns

Index(['dept_film_ot', 'project_film_ot', 'rights_holder_film_ot',
       'type_film_ot', 'option_status_film_ot',
       'initial_option_start_date_film_ot',
       'current_option_term_expiration_date_film_ot', 'current_status_film_ot',
       'dealspecific_notes_film_ot', 'initial_option_film_ot',
       'extensions_film_ot', 'purchase_price_film_ot', 'reversion_film_ot',
       '_id'],
      dtype='object')

In [8]:
df

,dept_film_ot,project_film_ot,rights_holder_film_ot,type_film_ot,option_status_film_ot,initial_option_start_date_film_ot,current_option_term_expiration_date_film_ot,current_status_film_ot,dealspecific_notes_film_ot,initial_option_film_ot,extensions_film_ot,purchase_price_film_ot,reversion_film_ot,_id
0,TV,Amberville,,,Lapsed,,7/28/2024,,,,,,,Amberville_TV_
1,TV,Animal Husbandry,Noah Prestwich,Spec Script,Lapsed,5/18/2022,8/18/2022,We have pro-rata monthly extensions remaining.,,,,,,Animal Husbandry_TV_Noah Prestwich
2,Film,Antarctica,Don Hertzfeldt,Screenplay,Initial Option,4/17/2025,10/17/2026,REMAINING: Extended Option Period. $15k for an...,,,,,,Antarctica_Film_Don Hertzfeldt
3,TV,Artful Escape (Attachment),,,Lapsed,2/8/2023,2/7/2024,,"Pitch Bible delivered April 17, 2023 - checkin...",,,,,Artful Escape (Attachment)_TV_
4,Film,Assassination of B.W Spurge,Yelchin and Anderson,Literary Material (Book),Lapsed,8/4/2021,8/4/2022,We have no more options left.,,,,,,Assassination of B.W Spurge_Film_Yelchin and A...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,TV,What Remains of Edith Finch,Annapurna Interactive,Video Game,,10/30/2019,10/29/2021,We have an option extension for 18 months for ...,Lapsed/Letting Go.,,,,,What Remains of Edith Finch_TV_Annapurna Inter...
82,TV,Who is Maud Dixon,Alexandra Andrews Beha,Book,Initial Option,6/12/2024,12/11/2025,,- we have an extension at $125K for an addtl 1...,,,,,Who is Maud Dixon_TV_Alexandra Andrews Beha
83,TV,Who is Maud Dixon (First Position),Boo Killebrew,Screenplay,Initial Term,3/28/2025,10/16/2025,,This is when the writer Boo Killebrew is in fi...,,,,,Who is Maud Dixon (First Position)_TV_Boo Kill...
84,TV,Who Killed Tulum?,NY Mag,Article,Lapsed,9/16/2021,9/16/2022,Amazon took over and negotiated this second op...,Lapsed/Letting Go.,,,,,Who Killed Tulum?_TV_NY Mag
85,TV,Zankou Chicken Murders,Wondery,Podcast,Lapsed,12/9/2021,12/9/2022,No extensions left. (With Starz),Lapsed/Letting Go.,,,,,Zankou Chicken Murders_TV_Wondery

In [9]:
data = df.to_dict(orient='records')

In [10]:
stop

NameError: name 'stop' is not defined

In [16]:
## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [17]:
db = client['InDevelopment']

collection = db['options_tracker']

In [18]:
def batchify(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]

In [19]:
collection.delete_many({})

DeleteResult({'n': 86, 'electionId': ObjectId('7fffffff0000000000000007'), 'opTime': {'ts': Timestamp(1765835060, 9), 't': 7}, 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1765835060, 9), 'signature': {'hash': b'\t\x92V\xeb{U.R\xca\xfe\\\x06\xf4<\xe2\xf7\xb8\xcf\xbe\xa7', 'keyId': 7570007239340064773}}, 'operationTime': Timestamp(1765835060, 9)}, acknowledged=True)

In [20]:
from pymongo import UpdateOne


#####
for batch in batchify(data, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 0, Inserted: 86, Modified: 0

In [21]:
from datetime import datetime


datetime.today()

datetime.datetime(2025, 12, 15, 13, 44, 20, 290892)

In [22]:
client.close()