In [ ]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# Step 1: Define the scope
scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]

# Step 2: Load credentials
creds = ServiceAccountCredentials.from_json_keyfile_name("ultra-sound-463216-c2-0e076e5f88fe.json", scope)

# Step 3: Authorize and connect
client = gspread.authorize(creds)

# Step 4: Open sheet by URL
sheet_url = "https://docs.google.com/spreadsheets/d/1Et8ufbD8I4wt96CjzkteDN7IPN27S3kdDGAZ7d74fco/edit?gid=1939998625#gid=1939998625"
spreadsheet = client.open_by_url(sheet_url)

# Optional: Access specific sheet/tab
sheet = spreadsheet.worksheet("Film_and_TV_Options_Tracker")  # or spreadsheet.worksheet("SheetName")

# Example: Read data
data = sheet.get_all_records(head=1)

In [2]:
import pandas as pd

df = pd.DataFrame(data)

df["Title"] = df["Project"].str.title()

In [3]:
df

,Dept,﻿Project,Rights Holder,Type,Option Status,Initial Option Start Date,Current Option Term Expiration Date,Current Status,Deal-specific notes,Initial Option $,Extension(s) $,Purchase Price $,Reversion
0,TV,Nick Weidenfeld,First Look Deal across TV/FILM/AN,First Look Deal,Initial Term,2/1/2025,3/1/2027,Extended Term available for 12 months and $575k,,,,,
1,TV,Planet of Exile (Book Rights),Theodore Downes-LeGuin,Book,Additional Extension,5/4/2023,2/15/2027,"We are on the third option extension, negotiat...",• Expiration of the Second Extension Period fo...,,,,
2,Film,FOO Rights Purchase (TA),Disney,Concept IP,2nd Extension,6/1/2025,12/31/2026,"In June 2025, AP paid 380K for 18 month extens...",,,,,
3,TV,Strangers,Isaac Siegmund-Broka,Spec Script,Initial Option,5/22/2025,11/22/2026,Studio shall have the right to extend the ini...,,,,,
4,TV,The Hot Kid; Up In Honey’s Room,Peter Leonard/ Elmore Leonard,Book,Initial Option,4/13/2023,10/22/2026,We have a Second Option Period: $50k for addit...,CP’s satisfied 4/13/23. Initial Option Period ...,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,Film,Not Fade Away*,Annapurna,Script,Lapsed,,5/31/2022,This is Netflix's initial option of the screen...,,,,,
82,Film,Edge of Identity,Barbara Bellus,Life Story Rights,Lapsed,11/13/2020,5/12/2022,No extensions left.,,,,,
83,Film,Edge of Identity,Aviv / New Yorker,Literary Material (Article),Lapsed,11/13/2020,5/12/2022,No extensions left.,,,,,
84,Film,True American,Rais Bhuiyan,,Purchased,,5/11/2022,Rough date. Assumes 4 months of force majeure ...,,"$X for XX Months, Appliable vs. non-applicable","$X for XX Months, Appliable vs. non-applicable",$XXX,
85,TV,What Remains of Edith Finch,Annapurna Interactive,Video Game,,10/30/2019,10/29/2021,We have an option extension for 18 months for ...,Lapsed/Letting Go.,,,,

In [4]:
df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(r"\s+", "_", regex=True)   # spaces -> underscore
      .str.replace(r"[^0-9a-zA-Z_]", "", regex=True)  # optional: remove weird chars
      + "_film_ot"
)

In [5]:
df

,dept_film_ot,project_film_ot,rights_holder_film_ot,type_film_ot,option_status_film_ot,initial_option_start_date_film_ot,current_option_term_expiration_date_film_ot,current_status_film_ot,dealspecific_notes_film_ot,initial_option__film_ot,extensions__film_ot,purchase_price__film_ot,reversion_film_ot
0,TV,Nick Weidenfeld,First Look Deal across TV/FILM/AN,First Look Deal,Initial Term,2/1/2025,3/1/2027,Extended Term available for 12 months and $575k,,,,,
1,TV,Planet of Exile (Book Rights),Theodore Downes-LeGuin,Book,Additional Extension,5/4/2023,2/15/2027,"We are on the third option extension, negotiat...",• Expiration of the Second Extension Period fo...,,,,
2,Film,FOO Rights Purchase (TA),Disney,Concept IP,2nd Extension,6/1/2025,12/31/2026,"In June 2025, AP paid 380K for 18 month extens...",,,,,
3,TV,Strangers,Isaac Siegmund-Broka,Spec Script,Initial Option,5/22/2025,11/22/2026,Studio shall have the right to extend the ini...,,,,,
4,TV,The Hot Kid; Up In Honey’s Room,Peter Leonard/ Elmore Leonard,Book,Initial Option,4/13/2023,10/22/2026,We have a Second Option Period: $50k for addit...,CP’s satisfied 4/13/23. Initial Option Period ...,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,Film,Not Fade Away*,Annapurna,Script,Lapsed,,5/31/2022,This is Netflix's initial option of the screen...,,,,,
82,Film,Edge of Identity,Barbara Bellus,Life Story Rights,Lapsed,11/13/2020,5/12/2022,No extensions left.,,,,,
83,Film,Edge of Identity,Aviv / New Yorker,Literary Material (Article),Lapsed,11/13/2020,5/12/2022,No extensions left.,,,,,
84,Film,True American,Rais Bhuiyan,,Purchased,,5/11/2022,Rough date. Assumes 4 months of force majeure ...,,"$X for XX Months, Appliable vs. non-applicable","$X for XX Months, Appliable vs. non-applicable",$XXX,
85,TV,What Remains of Edith Finch,Annapurna Interactive,Video Game,,10/30/2019,10/29/2021,We have an option extension for 18 months for ...,Lapsed/Letting Go.,,,,

In [6]:
df["_id"] = df['project_film_ot'] + "_"+ df['dept_film_ot']+ "_"+ df['rights_holder_film_ot']
df["dev_id_map"] = df['project_film_ot'] + "_"+ df['dept_film_ot']

df = df.rename({"project_film_ot":"_id"}, axis=1)

cols = [
    '_id', 
        'ap_division_film_pt', 
        'project_stage_film_pt',
       'ap_lead_film_pt', 
        'ap_jr_film_pt', 
        'ap_dev_film_pt',
       'ba_status_film_pt', 
        'creative_status_film_pt',
       'next_milestone_film_pt', 
        'key_timing_film_pt',
       'option_expiration_film_pt', 
        'key_timing_date_film_pt',
       'underlying_ip_film_pt', 
        'logline_film_pt',
       'platform__distribution_film_pt', 
        'deal_type_film_pt',
       'partners_and_vendors_film_pt', 
        'creators_film_pt', 
        'director_film_pt',
       'writers_film_pt', 
        'producer_1_film_pt', 
        'producer_2_film_pt',
       'cast_1_film_pt', 
        'cast_2_film_pt', 
        'cast_3_film_pt', 
        'cast_4_film_pt',
       ]

#df["project_stage_film_pt"] = df["project_stage_film_pt"].str.split(",").apply(lambda x: [i.strip() for i in x])
df["ap_lead_film_pt"] = df["ap_lead_film_pt"].str.split(",").apply(lambda x: [i.strip() for i in x])
df["ap_jr_film_pt"] = df["ap_jr_film_pt"].str.split(",").apply(lambda x: [i.strip() for i in x])

df

df[cols]

title_map = {
    "Even The Losers (Fka Need For Weed)": "Even the Losers",
    "Belly Of The Beast": "Belly of The Beast",
    'Brady Corbet / Mona Fastvold Project (Unt.)': "Origin of the World fka Unt. Brady Corbet & Mona Fastvold Project",

    'Silent Patient, The ': "The Silent Patient",
    '12 Minutes (Film)': "12 Minutes",
    'Bennett Miller (Unt.) ':"Unt. Bennett Miller",
    
    'Nicole Taylor Idea (Unt.)':"Evie Mcbrayne fka Unt. Nicole Taylor",
    'James Sweeney (Unt.)':"Unt. James Sweeney",
    'Into The Glory Whole':"Into the Glory whole",
    'Legend Of Georgia Mcbride, The ':"The Legend of Georgia McBride",

        'Lost Wild, The ':"The Lost Wild",


        'Beast Fiction Project (Unt.)':"Unt. Beast Fiction Project",

            'Ann Lee (Fka The Woman Clothed By The Sun) ':"The Testament of Ann Lee",



    # add more…
}

df['_id'] = df['_id'].replace(title_map)

In [7]:
df.head().columns

Index(['dept_film_ot', 'project_film_ot', 'rights_holder_film_ot',
       'type_film_ot', 'option_status_film_ot',
       'initial_option_start_date_film_ot',
       'current_option_term_expiration_date_film_ot', 'current_status_film_ot',
       'dealspecific_notes_film_ot', 'initial_option__film_ot',
       'extensions__film_ot', 'purchase_price__film_ot', 'reversion_film_ot',
       '_id', 'dev_id_map'],
      dtype='object')

In [8]:
df

,dept_film_ot,project_film_ot,rights_holder_film_ot,type_film_ot,option_status_film_ot,initial_option_start_date_film_ot,current_option_term_expiration_date_film_ot,current_status_film_ot,dealspecific_notes_film_ot,initial_option__film_ot,extensions__film_ot,purchase_price__film_ot,reversion_film_ot,_id,dev_id_map
0,TV,Nick Weidenfeld,First Look Deal across TV/FILM/AN,First Look Deal,Initial Term,2/1/2025,3/1/2027,Extended Term available for 12 months and $575k,,,,,,Nick Weidenfeld_TV_First Look Deal across TV/F...,Nick Weidenfeld_TV
1,TV,Planet of Exile (Book Rights),Theodore Downes-LeGuin,Book,Additional Extension,5/4/2023,2/15/2027,"We are on the third option extension, negotiat...",• Expiration of the Second Extension Period fo...,,,,,Planet of Exile (Book Rights)_TV_Theodore Down...,Planet of Exile (Book Rights)_TV
2,Film,FOO Rights Purchase (TA),Disney,Concept IP,2nd Extension,6/1/2025,12/31/2026,"In June 2025, AP paid 380K for 18 month extens...",,,,,,FOO Rights Purchase (TA)_Film_Disney,FOO Rights Purchase (TA)_Film
3,TV,Strangers,Isaac Siegmund-Broka,Spec Script,Initial Option,5/22/2025,11/22/2026,Studio shall have the right to extend the ini...,,,,,,Strangers_TV_Isaac Siegmund-Broka,Strangers_TV
4,TV,The Hot Kid; Up In Honey’s Room,Peter Leonard/ Elmore Leonard,Book,Initial Option,4/13/2023,10/22/2026,We have a Second Option Period: $50k for addit...,CP’s satisfied 4/13/23. Initial Option Period ...,,,,,The Hot Kid; Up In Honey’s Room_TV_Peter Leona...,The Hot Kid; Up In Honey’s Room_TV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,Film,Not Fade Away*,Annapurna,Script,Lapsed,,5/31/2022,This is Netflix's initial option of the screen...,,,,,,Not Fade Away*_Film_Annapurna,Not Fade Away*_Film
82,Film,Edge of Identity,Barbara Bellus,Life Story Rights,Lapsed,11/13/2020,5/12/2022,No extensions left.,,,,,,Edge of Identity_Film_Barbara Bellus,Edge of Identity_Film
83,Film,Edge of Identity,Aviv / New Yorker,Literary Material (Article),Lapsed,11/13/2020,5/12/2022,No extensions left.,,,,,,Edge of Identity_Film_Aviv / New Yorker,Edge of Identity_Film
84,Film,True American,Rais Bhuiyan,,Purchased,,5/11/2022,Rough date. Assumes 4 months of force majeure ...,,"$X for XX Months, Appliable vs. non-applicable","$X for XX Months, Appliable vs. non-applicable",$XXX,,True American _Film_Rais Bhuiyan,True American _Film
85,TV,What Remains of Edith Finch,Annapurna Interactive,Video Game,,10/30/2019,10/29/2021,We have an option extension for 18 months for ...,Lapsed/Letting Go.,,,,,What Remains of Edith Finch_TV_Annapurna Inter...,What Remains of Edith Finch_TV

In [9]:
data = df.to_dict(orient='records')

In [10]:
stop

NameError: name 'stop' is not defined

In [18]:
## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [19]:
db = client['InDevelopment']

collection = db['options_tracker']

In [20]:
def batchify(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]

In [21]:
collection.delete_many({})

DeleteResult({'n': 86, 'electionId': ObjectId('7fffffff000000000000000e'), 'opTime': {'ts': Timestamp(1771596624, 9), 't': 14}, 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1771596624, 9), 'signature': {'hash': b'\xf8\xa5/@\xa7m\x13\xbd\x89\xbc$\x91~\xc1\x10\xbf+d?t', 'keyId': 7570007239340064774}}, 'operationTime': Timestamp(1771596624, 9)}, acknowledged=True)

In [22]:
from pymongo import UpdateOne


#####
for batch in batchify(data, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 0, Inserted: 86, Modified: 0

In [23]:
from datetime import datetime


datetime.today()

datetime.datetime(2026, 2, 20, 6, 10, 25, 105973)

In [24]:
client.close()