https://docs.google.com/spreadsheets/d/1PaAQEAJcTupLNgvTLaawyWPKOfIrUFAQf-WiUnZMbxY/edit?gid=25505532#gid=25505532

In [1]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# Step 1: Define the scope
scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]

# Step 2: Load credentials
creds = ServiceAccountCredentials.from_json_keyfile_name("ultra-sound-463216-c2-0e076e5f88fe.json", scope)

# Step 3: Authorize and connect
client = gspread.authorize(creds)

# Step 4: Open sheet by URL
sheet_url = "https://docs.google.com/spreadsheets/d/1PaAQEAJcTupLNgvTLaawyWPKOfIrUFAQf-WiUnZMbxY/edit?gid=25505532#gid=25505532"
spreadsheet = client.open_by_url(sheet_url)

# Optional: Access specific sheet/tab
sheet = spreadsheet.worksheet("Linear Project List")  # or spreadsheet.worksheet("SheetName")

# Example: Read data
data = sheet.get_all_records(head=1)

In [2]:
import pandas as pd

df = pd.DataFrame(data)

import pandas as pd

df = pd.read_csv("Project Directory - Project List.csv") ## Temporary

In [3]:
df

,Title,Project ID,Underlying IP,Logline,AP DIVISION,priority_title,Project Stage,AP Lead,AP Producer,AP Jr.,...,Release Date,Dev_tracker_ID,Remaining_Committed,Total_Cost_with_Committments,ITD_current_year,options_tracker_id,initial_option_start_date_film_ot,option_status_film_ot,current_option_term_expiration_date_film_ot,current_status_film_ot
0,ANTARCTICA,,,"A darkly funny, horrific, and surreal feature-...","Animation, Film",FALSE,3. Internal Development,"Andrew, Rob",,,...,,Antarctica_Animation_Film,$0.00,"$86,000.00","$86,000.00",Antarctica_Film_Don Hertzfeldt,4/17/2025,Initial Option,10/17/2026,REMAINING: Extended Option Period. $15k for an...
1,FOO,814974530,,A feature-length animation film that follows F...,"Animation, Film",FALSE,3. Internal Development,"Andrew, Rob",,,...,,FOO (Animation)_Animation_Film,$0.00,"$266,996.26","$266,996.26",FOO Rights Purchase (TA)_Film_Disney,6/1/2025,2nd Extension,12/31/2026,"In June 2025, AP paid 380K for 18 month extens..."
2,MOOMINS,,The world and characters of the Moomin franchise,Animated adaptation of the books by Tove Jansson.,"Animation, Film",TRUE,3. Internal Development,"Andrew, Rob, Hector, Megan",,,...,,Moomins_Animation_Film,"$479,220.00","$1,115,549.58","$636,329.58",,,,,
3,SOME ASSEMBLY REQUIRED,,,"Jack, an orphan from the streets of London, ha...","Animation, Film",FALSE,3. Internal Development,"Andrew, Rob",,,...,,Some Assembly Required_Animation_Film,"$298,056.00","$655,473.43","$357,417.43",,,,,
4,THE BROBARIANS (FKA MANTOOTH),,,"To protect his tribe, stop a war, and save a l...","Animation, Film",FALSE,3. Internal Development,"Andrew, Rob",,,...,,Mantooth_Animation_Film,"$120,000.00","$2,568,846.95","$2,448,846.95",,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
961,,,,,,FALSE,,,,,...,,,,,,,,,,
962,,,,,,FALSE,,,,,...,,,,,,,,,,
963,,,,,,FALSE,,,,,...,,,,,,,,,,
964,,,,,,FALSE,,,,,...,,,,,,,,,,
965,,,,,,FALSE,,,,,...,,,,,,,,,,

In [4]:
df['Title'] = df['Title'].astype(str).str.strip()

In [5]:
df = df[df['Title'] != ""]

In [6]:
df

,Title,Project ID,Underlying IP,Logline,AP DIVISION,priority_title,Project Stage,AP Lead,AP Producer,AP Jr.,...,Release Date,Dev_tracker_ID,Remaining_Committed,Total_Cost_with_Committments,ITD_current_year,options_tracker_id,initial_option_start_date_film_ot,option_status_film_ot,current_option_term_expiration_date_film_ot,current_status_film_ot
0,ANTARCTICA,,,"A darkly funny, horrific, and surreal feature-...","Animation, Film",FALSE,3. Internal Development,"Andrew, Rob",,,...,,Antarctica_Animation_Film,$0.00,"$86,000.00","$86,000.00",Antarctica_Film_Don Hertzfeldt,4/17/2025,Initial Option,10/17/2026,REMAINING: Extended Option Period. $15k for an...
1,FOO,814974530,,A feature-length animation film that follows F...,"Animation, Film",FALSE,3. Internal Development,"Andrew, Rob",,,...,,FOO (Animation)_Animation_Film,$0.00,"$266,996.26","$266,996.26",FOO Rights Purchase (TA)_Film_Disney,6/1/2025,2nd Extension,12/31/2026,"In June 2025, AP paid 380K for 18 month extens..."
2,MOOMINS,,The world and characters of the Moomin franchise,Animated adaptation of the books by Tove Jansson.,"Animation, Film",TRUE,3. Internal Development,"Andrew, Rob, Hector, Megan",,,...,,Moomins_Animation_Film,"$479,220.00","$1,115,549.58","$636,329.58",,,,,
3,SOME ASSEMBLY REQUIRED,,,"Jack, an orphan from the streets of London, ha...","Animation, Film",FALSE,3. Internal Development,"Andrew, Rob",,,...,,Some Assembly Required_Animation_Film,"$298,056.00","$655,473.43","$357,417.43",,,,,
4,THE BROBARIANS (FKA MANTOOTH),,,"To protect his tribe, stop a war, and save a l...","Animation, Film",FALSE,3. Internal Development,"Andrew, Rob",,,...,,Mantooth_Animation_Film,"$120,000.00","$2,568,846.95","$2,448,846.95",,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,THE STAIRCASE,,,"Inspired by a true story, The Staircase explor...",TV,FALSE,8. Library,,,,...,5/5/2022,,$0.00,$0.00,$0.00,,,,,
210,THE BALLARD OF BUSTER SCRUGGS,,,"Ranging from absurd to profound, these Western...","TV, Film",FALSE,8. Library,,,,...,11/16/2018,,$0.00,$0.00,$0.00,,,,,
211,ALAN WAKE,905490123,,When bestselling novelist Alan Wake’s wife van...,"TV, Interactive",FALSE,3. Internal Development,"Hector, Megan",,"Zelda, Katelin",...,,Alan Wake_TV,"$150,000.00","$150,000.00",$0.00,,,,,
212,CONTROL,857708672,,After a supernatural force takes over a secret...,"TV, Interactive",FALSE,3. Internal Development,"Megan, Hector, Katelin, Zelda",,,...,,Control_TV,"$763,465.00","$763,465.00",$0.00,,,,,
213,EDITH FINCH (WHAT REMAINS OF),,,What Remains of Edith Finch is a haunting jour...,"TV, Interactive",FALSE,3. Internal Development,"Megan, Hector, Katelin",,,...,,,$0.00,$0.00,$0.00,What Remains of Edith Finch_TV_Annapurna Inter...,10/30/2019,,10/29/2021,We have an option extension for 18 months for ...

In [7]:
df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(r"\s+", "_", regex=True)   # spaces -> underscore
      .str.replace(r"[^0-9a-zA-Z_]", "", regex=True)  # optional: remove weird chars
      + "_directory"
)

In [8]:
df = df.rename({"title_directory":"_id"}, axis=1)

In [9]:
df.columns.to_list()

['_id',
 'project_id_directory',
 'underlying_ip_directory',
 'logline_directory',
 'ap_division_directory',
 'priority_title_directory',
 'project_stage_directory',
 'ap_lead_directory',
 'ap_producer_directory',
 'ap_jr_directory',
 'ap_dev_directory',
 'ap_admin_directory',
 'slack_channel_directory',
 'creator_id_directory',
 'creator_name_directory',
 'lead_creative_directorshowrunnerdeveloper_attached_directory',
 'talent_attached_directory',
 'start_of_development_directory',
 'release_date_directory',
 'dev_tracker_id_directory',
 'remaining_committed_directory',
 'total_cost_with_committments_directory',
 'itd_current_year_directory',
 'options_tracker_id_directory',
 'initial_option_start_date_film_ot_directory',
 'option_status_film_ot_directory',
 'current_option_term_expiration_date_film_ot_directory',
 'current_status_film_ot_directory']

In [10]:
cols = [
    '_id',
 'project_id_directory',
    'priority_title_directory',
 'underlying_ip_directory',
 'logline_directory',
 'ap_division_directory',
 'project_stage_directory',
 'ap_lead_directory',
 'ap_producer_directory',
 'ap_jr_directory',
 'ap_dev_directory',
 'ap_admin_directory',
 'slack_channel_directory',
 'creator_id_directory',
 'creator_name_directory',
 'lead_creative_directorshowrunnerdeveloper_attached_directory',
 'talent_attached_directory',
 'start_of_development_directory',
 'release_date_directory',

    'dev_tracker_id_directory',
 'remaining_committed_directory',
 'total_cost_with_committments_directory',
 'itd_current_year_directory',
 'options_tracker_id_directory',
# 'initial_option_start_date_film_ot_directory',
 'option_status_film_ot_directory',
 #'current_option_term_expiration_date_film_ot_directory',
 'current_status_film_ot_directory'
       ]

In [11]:
float_cols = [
    "remaining_committed_directory",
    "total_cost_with_committments_directory",
    "itd_current_year_directory",
]

df[float_cols] = (
    df[float_cols]
    .replace(r"[\$,]", "", regex=True)
    .replace("", None)
    .astype(float)
)

In [12]:
df["initial_option_start_date_film_ot_directory"] = pd.to_datetime(df["initial_option_start_date_film_ot_directory"])
df["current_option_term_expiration_date_film_ot_directory"] = pd.to_datetime(df["current_option_term_expiration_date_film_ot_directory"])

In [13]:
df["ap_lead_directory"] = df["ap_lead_directory"].fillna("")
df["ap_jr_directory"] = df["ap_jr_directory"].fillna("")
df["ap_dev_directory"] = df["ap_dev_directory"].fillna("")
df["ap_admin_directory"] = df["ap_admin_directory"].fillna("")
df["ap_division_directory"] = df["ap_division_directory"].fillna("")

In [14]:
#df["project_stage_film_pt"] = df["project_stage_film_pt"].str.split(",").apply(lambda x: [i.strip() for i in x])
df["ap_lead_directory"] = df["ap_lead_directory"].str.split(",").apply(lambda x: [i.strip() for i in x])
df["ap_jr_directory"] = df["ap_jr_directory"].str.split(",").apply(lambda x: [i.strip() for i in x])
df["ap_dev_directory"] = df["ap_dev_directory"].str.split(",").apply(lambda x: [i.strip() for i in x])
df["ap_admin_directory"] = df["ap_admin_directory"].str.split(",").apply(lambda x: [i.strip() for i in x])
df["ap_division_directory"] = df["ap_division_directory"].str.split(",").apply(lambda x: [i.strip() for i in x])

In [15]:
title_map = {
    "Even The Losers (Fka Need For Weed)": "Even the Losers",
    "Belly Of The Beast": "Belly of The Beast",
    'Brady Corbet / Mona Fastvold Project (Unt.)': "Origin of the World fka Unt. Brady Corbet & Mona Fastvold Project",

    'Silent Patient, The ': "The Silent Patient",
    '12 Minutes (Film)': "12 Minutes",
    'Bennett Miller (Unt.) ':"Unt. Bennett Miller",
    
    'Nicole Taylor Idea (Unt.)':"Evie Mcbrayne fka Unt. Nicole Taylor",
    'James Sweeney (Unt.)':"Unt. James Sweeney",
    'Into The Glory Whole':"Into the Glory whole",
    'Legend Of Georgia Mcbride, The ':"The Legend of Georgia McBride",

        'Lost Wild, The ':"The Lost Wild",


        'Beast Fiction Project (Unt.)':"Unt. Beast Fiction Project",

            'Ann Lee (Fka The Woman Clothed By The Sun) ':"The Testament of Ann Lee",



    # add more…
}

df['_id'] = df['_id'].replace(title_map)

In [16]:
df['_id'] = df["_id"].str.title()

In [17]:
df.query("_id=='The Invite'")

,_id,project_id_directory,underlying_ip_directory,logline_directory,ap_division_directory,priority_title_directory,project_stage_directory,ap_lead_directory,ap_producer_directory,ap_jr_directory,...,release_date_directory,dev_tracker_id_directory,remaining_committed_directory,total_cost_with_committments_directory,itd_current_year_directory,options_tracker_id_directory,initial_option_start_date_film_ot_directory,option_status_film_ot_directory,current_option_term_expiration_date_film_ot_directory,current_status_film_ot_directory
23,The Invite,828769775,,A wild night ensues when one couple invites th...,[Film],FALSE,"1. Post, 1. GTM","[Megan, Chelsea]",,[Alex],...,6/26/2026,,0.0,0.0,0.0,,NaT,,NaT,

In [18]:
df.head().columns

Index(['_id', 'project_id_directory', 'underlying_ip_directory',
       'logline_directory', 'ap_division_directory',
       'priority_title_directory', 'project_stage_directory',
       'ap_lead_directory', 'ap_producer_directory', 'ap_jr_directory',
       'ap_dev_directory', 'ap_admin_directory', 'slack_channel_directory',
       'creator_id_directory', 'creator_name_directory',
       'lead_creative_directorshowrunnerdeveloper_attached_directory',
       'talent_attached_directory', 'start_of_development_directory',
       'release_date_directory', 'dev_tracker_id_directory',
       'remaining_committed_directory',
       'total_cost_with_committments_directory', 'itd_current_year_directory',
       'options_tracker_id_directory',
       'initial_option_start_date_film_ot_directory',
       'option_status_film_ot_directory',
       'current_option_term_expiration_date_film_ot_directory',
       'current_status_film_ot_directory'],
      dtype='object')

In [19]:
df.tail().to_clipboard()

alias_cols = ['imdb_id', 'tmdb_id', 'igdb_id',
       'steam_id', 'dev_tracker_id', 'indie_bi_product_name']

df[alias_cols] = pd.NA

df["aliases"] = df[alias_cols].to_dict(orient="records")

df = df.drop(alias_cols, axis=1)

In [20]:
date_df = df[['_id', 'initial_option_start_date_film_ot_directory', 'current_option_term_expiration_date_film_ot_directory']].dropna()

In [21]:
df = df[cols]

In [22]:
df.columns

Index(['_id', 'project_id_directory', 'priority_title_directory',
       'underlying_ip_directory', 'logline_directory', 'ap_division_directory',
       'project_stage_directory', 'ap_lead_directory', 'ap_producer_directory',
       'ap_jr_directory', 'ap_dev_directory', 'ap_admin_directory',
       'slack_channel_directory', 'creator_id_directory',
       'creator_name_directory',
       'lead_creative_directorshowrunnerdeveloper_attached_directory',
       'talent_attached_directory', 'start_of_development_directory',
       'release_date_directory', 'dev_tracker_id_directory',
       'remaining_committed_directory',
       'total_cost_with_committments_directory', 'itd_current_year_directory',
       'options_tracker_id_directory', 'option_status_film_ot_directory',
       'current_status_film_ot_directory'],
      dtype='object')

In [23]:
from datetime import datetime

df['update_date'] = datetime.today()

In [24]:
data = df.to_dict(orient='records')

In [25]:
date_data = date_df.to_dict(orient='records')

In [26]:
date_data

[{'_id': 'Antarctica',
  'initial_option_start_date_film_ot_directory': Timestamp('2025-04-17 00:00:00'),
  'current_option_term_expiration_date_film_ot_directory': Timestamp('2026-10-17 00:00:00')},
 {'_id': 'Foo',
  'initial_option_start_date_film_ot_directory': Timestamp('2025-06-01 00:00:00'),
  'current_option_term_expiration_date_film_ot_directory': Timestamp('2026-12-31 00:00:00')},
 {'_id': 'Belly Of The Beast',
  'initial_option_start_date_film_ot_directory': Timestamp('2025-03-01 00:00:00'),
  'current_option_term_expiration_date_film_ot_directory': Timestamp('2026-03-01 00:00:00')},
 {'_id': 'Even The Losers (Fka Need For Weed)',
  'initial_option_start_date_film_ot_directory': Timestamp('2025-06-29 00:00:00'),
  'current_option_term_expiration_date_film_ot_directory': Timestamp('2026-07-28 00:00:00')},
 {'_id': 'Legend Of Georgia Mcbride, The',
  'initial_option_start_date_film_ot_directory': Timestamp('2025-04-01 00:00:00'),
  'current_option_term_expiration_date_film_ot_directory': Timestamp('2025-10-01 00:00:00')},
 {'_id': 'Silent Patient, The',
  'initial_option_start_date_film_ot_directory': Timestamp('2022-03-14 00:00:00'),
  'current_option_term_expiration_date_film_ot_directory': Timestamp('2024-12-20 00:00:00')},
 {'_id': '12 Minutes (Film)',
  'initial_option_start_date_film_ot_directory': Timestamp('2022-08-08 00:00:00'),
  'current_option_term_expiration_date_film_ot_directory': Timestamp('2026-02-17 00:00:00')},
 {'_id': 'Aztec',
  'initial_option_start_date_film_ot_directory': Timestamp('2025-01-22 00:00:00'),
  'current_option_term_expiration_date_film_ot_directory': Timestamp('2026-07-22 00:00:00')},
 {'_id': 'Felt (Fka Unt. Dan Mallory)',
  'initial_option_start_date_film_ot_directory': Timestamp('2021-01-05 00:00:00'),
  'current_option_term_expiration_date_film_ot_directory': Timestamp('2026-01-12 00:00:00')},
 {'_id': 'Hot Kid, The',
  'initial_option_start_date_film_ot_directory': Timestamp('2023-04-13 00:00:00'),
  'current_option_term_expiration_date_film_ot_directory': Timestamp('2026-10-22 00:00:00')},
 {'_id': 'Planet Of Exile',
  'initial_option_start_date_film_ot_directory': Timestamp('2023-04-24 00:00:00'),
  'current_option_term_expiration_date_film_ot_directory': Timestamp('2025-08-23 00:00:00')},
 {'_id': 'Who Is Maud Dixon',
  'initial_option_start_date_film_ot_directory': Timestamp('2024-06-12 00:00:00'),
  'current_option_term_expiration_date_film_ot_directory': Timestamp('2025-12-11 00:00:00')},
 {'_id': 'Edith Finch (What Remains Of)',
  'initial_option_start_date_film_ot_directory': Timestamp('2019-10-30 00:00:00'),
  'current_option_term_expiration_date_film_ot_directory': Timestamp('2021-10-29 00:00:00')}]

In [27]:
stop

NameError: name 'stop' is not defined

In [28]:
## Establish connection to Account
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://dougsack:Ocana2421@cluster1.zdl0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [29]:
db = client['InDevelopment']

collection = db['project_directory']

In [30]:
def batchify(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]

collection.delete_many({})

In [31]:
from pymongo import UpdateOne


#####
for batch in batchify(data, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 214, Inserted: 0, Modified: 214

In [32]:
from pymongo import UpdateOne


#####
for batch in batchify(date_data, 4000):
    operations = [
        UpdateOne(
            {"_id": doc["_id"]},
            {"$set": doc},
            upsert=True
        ) for doc in batch
    ]
    
    result = collection.bulk_write(operations)
    print(f"Matched: {result.matched_count}, Inserted: {result.upserted_count}, Modified: {result.modified_count}")

Matched: 13, Inserted: 0, Modified: 0

In [33]:
from datetime import datetime


datetime.today()

datetime.datetime(2026, 3, 9, 13, 5, 36, 606814)

In [34]:
client.close()